CREATE TABLE qrtz_job_details
  (
    JOB_NAME  VARCHAR(80) NOT NULL,
    JOB_GROUP VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(120) ,
    JOB_CLASS_NAME   VARCHAR(128) NOT NULL, 
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_VOLATILE VARCHAR(1) NOT NULL,
    IS_STATEFUL VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB ,
    PRIMARY KEY (JOB_NAME,JOB_GROUP)
)
go
CREATE TABLE qrtz_job_listeners
  (
    JOB_NAME  VARCHAR(80) NOT NULL, 
    JOB_GROUP VARCHAR(80) NOT NULL,
    JOB_LISTENER VARCHAR(80) NOT NULL,
    PRIMARY KEY (JOB_NAME,JOB_GROUP,JOB_LISTENER),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
	REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP)
)
go
CREATE TABLE qrtz_triggers
  (
    TRIGGER_NAME VARCHAR(80) NOT NULL,
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    JOB_NAME  VARCHAR(80) NOT NULL, 
    JOB_GROUP VARCHAR(80) NOT NULL,
    IS_VOLATILE VARCHAR(1) NOT NULL,
    DESCRIPTION VARCHAR(120) ,
    NEXT_FIRE_TIME decimal(13) ,
    PREV_FIRE_TIME decimal(13) ,
    PRIORITY decimal(13) ,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME decimal(13) NOT NULL,
    END_TIME decimal(13) ,
    CALENDAR_NAME VARCHAR(80) ,
    MISFIRE_INSTR decimal(2) ,
    JOB_DATA BLOB ,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
	REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP) 
)
go
CREATE TABLE qrtz_simple_triggers
  (
    TRIGGER_NAME VARCHAR(80) NOT NULL,
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    REPEAT_COUNT decimal(7) NOT NULL,
    REPEAT_INTERVAL decimal(12) NOT NULL,
    TIMES_TRIGGERED decimal(7) NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)
go
CREATE TABLE qrtz_cron_triggers
  (
    TRIGGER_NAME VARCHAR(80) NOT NULL,
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    CRON_EXPRESSION VARCHAR(80) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)
go
CREATE TABLE qrtz_blob_triggers
  (
    TRIGGER_NAME VARCHAR(80) NOT NULL,
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    BLOB_DATA BLOB ,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
        REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)
go
CREATE TABLE qrtz_trigger_listeners
  (
    TRIGGER_NAME  VARCHAR(80) NOT NULL, 
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    TRIGGER_LISTENER VARCHAR(80) NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_LISTENER),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)
go
CREATE TABLE qrtz_calendars
  (
    CALENDAR_NAME  VARCHAR(80) NOT NULL, 
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (CALENDAR_NAME)
)
go
CREATE TABLE qrtz_paused_trigger_grps
  (
    TRIGGER_GROUP  VARCHAR(80) NOT NULL, 
    PRIMARY KEY (TRIGGER_GROUP)
)
go
CREATE TABLE qrtz_fired_triggers 
  (
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(80) NOT NULL,
    TRIGGER_GROUP VARCHAR(80) NOT NULL,
    IS_VOLATILE VARCHAR(1) NOT NULL,
    INSTANCE_NAME VARCHAR(80) NOT NULL,
    FIRED_TIME decimal(13) NOT NULL,
    PRIORITY decimal(13) NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(80) ,
    JOB_GROUP VARCHAR(80) ,
    IS_STATEFUL VARCHAR(1) ,
    REQUESTS_RECOVERY VARCHAR(1),
    PRIMARY KEY (ENTRY_ID)
)
go
CREATE TABLE qrtz_scheduler_state 
  (
    INSTANCE_NAME VARCHAR(80) NOT NULL,
    LAST_CHECKIN_TIME decimal(13) NOT NULL,
    CHECKIN_INTERVAL decimal(13) NOT NULL,
    PRIMARY KEY (INSTANCE_NAME)
)
go
CREATE TABLE qrtz_locks
  (
    LOCK_NAME  VARCHAR(40) NOT NULL, 
    PRIMARY KEY (LOCK_NAME)
)
go
INSERT INTO qrtz_locks values('TRIGGER_ACCESS')
go
INSERT INTO qrtz_locks values('JOB_ACCESS')
go
INSERT INTO qrtz_locks values('CALENDAR_ACCESS')
go
INSERT INTO qrtz_locks values('STATE_ACCESS')
go
INSERT INTO qrtz_locks values('MISFIRE_ACCESS')
go

CREATE INDEX idx_qrtz_j_req_recovery on qrtz_job_details(REQUESTS_RECOVERY)
go
CREATE INDEX idx_qrtz_t_next_fire_time on qrtz_triggers(NEXT_FIRE_TIME)
go
CREATE INDEX idx_qrtz_t_state on qrtz_triggers(TRIGGER_STATE)
go
CREATE INDEX idx_qrtz_t_nft_st on qrtz_triggers(NEXT_FIRE_TIME,TRIGGER_STATE)
go
CREATE INDEX idx_qrtz_t_volatile on qrtz_triggers(IS_VOLATILE)
go
CREATE INDEX idx_qrtz_ft_trig_name on qrtz_fired_triggers(TRIGGER_NAME)
go
CREATE INDEX idx_qrtz_ft_trig_group on qrtz_fired_triggers(TRIGGER_GROUP)
go
CREATE INDEX idx_qrtz_ft_trig_nm_gp on qrtz_fired_triggers(TRIGGER_NAME,TRIGGER_GROUP)
go
CREATE INDEX idx_qrtz_ft_trig_volatile on qrtz_fired_triggers(IS_VOLATILE)
go
CREATE INDEX idx_qrtz_ft_trig_inst_name on qrtz_fired_triggers(INSTANCE_NAME)
go
CREATE INDEX idx_qrtz_ft_job_name on qrtz_fired_triggers(JOB_NAME)
go
CREATE INDEX idx_qrtz_ft_job_group on qrtz_fired_triggers(JOB_GROUP)
go
CREATE INDEX idx_qrtz_ft_job_stateful on qrtz_fired_triggers(IS_STATEFUL)
go
CREATE INDEX idx_qrtz_ft_job_req_recovery on qrtz_fired_triggers(REQUESTS_RECOVERY)
go
