whenever sqlerror exit sql.sqlcode;
SET SERVEROUTPUT on;

DECLARE
  V_COUNT NUMBER(16);
  V_ESQUEMA VARCHAR2(25 CHAR):= 'BANK01'; -- Configuracion Esquemas

BEGIN
  SELECT count(1) INTO V_COUNT FROM SYS.ALL_INDEXES WHERE INDEX_NAME='IDX_ARP_ID_ARQ_DATE' AND TABLE_OWNER=V_ESQUEMA;
  IF V_COUNT = 0 THEN 
    EXECUTE IMMEDIATE 'CREATE INDEX '||V_ESQUEMA||'.IDX_ARP_ID_ARQ_DATE ON BANK01.ARP_ARQ_RECOBRO_PERSONA (PER_ID, ARQ_DATE DESC)';
    DBMS_OUTPUT.PUT_LINE('Indice Creado: '||V_ESQUEMA||'.IDX_ARP_ID_ARQ_DATE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Indice: '||V_ESQUEMA||'.IDX_ARP_ID_ARQ_DATE ya existía, no creado');
  END IF;
  SELECT count(1) INTO V_COUNT FROM SYS.ALL_INDEXES WHERE INDEX_NAME='IDX_ARP_ID_ARQ_DATE_SI' AND TABLE_OWNER=V_ESQUEMA;
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX '||V_ESQUEMA||'.IDX_ARP_ID_ARQ_DATE_SI ON BANK01.ARP_ARQ_RECOBRO_PERSONA_SIM (PER_ID, ARQ_DATE DESC)';
    DBMS_OUTPUT.PUT_LINE('Indice Creado: '||V_ESQUEMA||'.IDX_ARP_ID_ARQ_DATE_SI');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Indice: BANK01.IDX_ARP_ID_ARQ_DATE_SI ya existía, no creado');
  END IF;
END;
/
EXIT