OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_2802
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	COD_PROMOCION					NULLIF(COD_PROMOCION=BLANKS)			"TRIM(:COD_PROMOCION)",
	ACT_PRINEX					NULLIF(ACT_PRINEX=BLANKS)			"TRIM(:ACT_PRINEX)",
	ACT_HAYA					NULLIF(ACT_HAYA=BLANKS)				"TRIM(:ACT_HAYA)"
	
)
