--/*
--#########################################
--## AUTOR=Viorel Remus Ovidiu
--## FECHA_CREACION=20200221
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=REMVIP-6357
--## PRODUCTO=NO
--##
--## Finalidad: Creación de tabla de migración MIG2_PVC_PROVEEDOR_CONTACTO
--##
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

TABLE_COUNT NUMBER(1,0) := 0;
V_ESQUEMA_1 VARCHAR2(20 CHAR) := 'REM01';
V_ESQUEMA_2 VARCHAR2(20 CHAR) := 'REMMASTER'; --SE CREA UNA SEGUNDA VARIABLE DE ESQUEMA POR SI EN ALGÚN MOMENTO QUEREMOS CREAR LA TABLA EN UN ESQUEMA DIFERENTE AL DEL USUARIO QUE LA ACCEDE O VICEVERSA
V_ESQUEMA_3 VARCHAR2(20 CHAR) := 'REM_QUERY';
V_ESQUEMA_4 VARCHAR2(20 CHAR) := 'PFSREM';
V_TABLESPACE_IDX VARCHAR2(30 CHAR) := 'REM_IDX';
V_TABLA VARCHAR2(40 CHAR) := 'MIG2_PVC_PROVEEDOR_CONTACTO';

BEGIN

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA||'' AND OWNER= ''||V_ESQUEMA_1||'';

IF TABLE_COUNT > 0 THEN

    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'';
    
END IF;

EXECUTE IMMEDIATE '
CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'
(
		PVC_DOCUMENTO           VARCHAR2(20 CHAR),     
		PVC_TIPO_DOCUMENTO      VARCHAR2(20 CHAR),
		PVE_COD_ORIGEN          VARCHAR2(20 CHAR),
		PVC_NOMBRE              VARCHAR2(250 CHAR),
		PVC_APELLIDO1           VARCHAR2(100 CHAR), 
		PVC_APELLIDO2           VARCHAR2(100 CHAR),
		PVC_PROVINCIA           VARCHAR2(20 CHAR),
		PVC_CP                  NUMBER(8,0),
		PVC_DIRECCION           VARCHAR2(250 CHAR),
		PVC_TELF1               VARCHAR2(20 CHAR),
		PVC_TELF2               VARCHAR2(20 CHAR),
		PVC_FAX                 VARCHAR2(20 CHAR),
		PVC_EMAIL               VARCHAR2(50 CHAR),
		PVC_IND_PRINCIPAL       NUMBER(1,0),
		PVC_COD_CARGO           VARCHAR2(20 CHAR),
		PVC_CARGO               VARCHAR2(50 CHAR),
		PVC_FECHA_ALTA          DATE,
		PVC_FECHA_BAJA          DATE,
		PVC_OBSERVACIONES       VARCHAR2(200 CHAR),
		PVC_COD_DIRECCION       NUMBER(16,0),
		PVC_COD_USUARIO         VARCHAR2(20 CHAR),    
		VALIDACION NUMBER(1) DEFAULT 0 NOT NULL 
)'
;


DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA||' CREADA');  

IF V_ESQUEMA_2 != V_ESQUEMA_1 THEN

	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' OTORGADOS A '||V_ESQUEMA_2||''); 

END IF;

IF V_ESQUEMA_3 != V_ESQUEMA_1 THEN

	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA||'" TO "'||V_ESQUEMA_3||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' OTORGADOS A '||V_ESQUEMA_3||''); 

END IF;

IF V_ESQUEMA_4 != V_ESQUEMA_1 THEN
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA||'" TO "'||V_ESQUEMA_4||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' OTORGADOS A '||V_ESQUEMA_4||''); 

END IF;

EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_DOCUMENTO IS ''Número de documento identificativo del proveedor.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_TIPO_DOCUMENTO IS ''Tipo documento contacto . (código según dicc. datos)''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVE_COD_ORIGEN IS ''Código identificador único del proveedor del contacto''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_NOMBRE IS ''Nombre contacto proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_APELLIDO1 IS ''Apellido 1 del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_APELLIDO2 IS ''Apellido 2 del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_PROVINCIA IS ''Provincia del contacto del proveedor (Código según Dic. Datos).''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_CP IS ''Codigo postal del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_DIRECCION IS ''Dirección del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_TELF1 IS ''Número de teléfono 1 del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_TELF2 IS ''Número de teléfono 2 del contacto del proveedor''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_FAX IS ''Fax del contacto del proveedor.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_EMAIL IS ''Email del contacto del proveedor.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_IND_PRINCIPAL IS ''Indicador de si es el proveedor contacto principal o no.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_COD_CARGO IS ''Código identificador del Cargo del Contacto del Proveedor (Código según Dic. Datos).''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_CARGO IS ''Cargo del proveedor contacto (Administración y proveedor).''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_FECHA_ALTA IS ''Fecha de Alta del Contacto''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_FECHA_BAJA IS ''Fecha de Baja del Contacto''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_OBSERVACIONES IS ''Observaciones del Contacto.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_COD_DIRECCION IS ''Código identificador de la Dirección del Contacto del Proveedor.''';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_PVC_PROVEEDOR_CONTACTO.PVC_COD_USUARIO IS ''USERNAME en REM del Usuario (Código según Dic. Datos).''';

COMMIT;
EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

EXIT;

