--/*
--#########################################
--## AUTOR=Viorel Remus Ovidiu
--## FECHA_CREACION=20191220
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-5874
--## PRODUCTO=NO
--## 
--## Finalidad: Creación de tablas backup 
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar  
TABLE_COUNT NUMBER(1,0) := 0;
V_ESQUEMA_1 VARCHAR2(20 CHAR) := 'REM01';
V_ESQUEMA_2 VARCHAR2(20 CHAR) := 'REMMASTER'; --SE CREA UNA SEGUNDA VARIABLE DE ESQUEMA POR SI EN ALGÚN MOMENTO QUEREMOS CREAR LA TABLA EN UN ESQUEMA DIFERENTE AL DEL USUARIO QUE LA ACCEDE O VICEVERSA
V_ESQUEMA_3 VARCHAR2(20 CHAR) := 'REM_QUERY';
V_ESQUEMA_4 VARCHAR2(20 CHAR) := 'PFSREM';
V_TABLESPACE_IDX VARCHAR2(30 CHAR) := 'REM_IDX';
V_TABLA1 VARCHAR2(40 CHAR) := 'AUX_TBJ_EXCEL_REMVIP_5874';
V_TABLA2 VARCHAR2(40 CHAR) := 'AUX_TBJ_NO_EXCEL_5874';
V_TABLA3 VARCHAR2(40 CHAR) := 'AUX_TAR_EXCEL_REMVIP_5874';
V_TABLA4 VARCHAR2(40 CHAR) := 'AUX_TAR_NO_EXCEL_REMVIP_5874';

BEGIN

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA1||'' AND OWNER= ''||V_ESQUEMA_1||'';
IF TABLE_COUNT > 0 THEN
    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA1||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA1||'';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA1||' AS 
  ( select tbj_num_trabajo, TBJ_GESTOR_ACTIVO_RESPONSABLE from REM01.act_tbj_trabajo tbj
    inner join REM01.AUX_REMVIP_5874 aux on aux.num_trabajo = tbj.tbj_num_trabajo
  ) ';

DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA1||' CREADA');  

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA2||'' AND OWNER= ''||V_ESQUEMA_1||'';
IF TABLE_COUNT > 0 THEN
    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA2||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA2||'';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA2||' AS 
  ( 	SELECT 
	GEE_GACT.GEE_ID,
	USU_GACT.USU_ID AS USU_ID_GESTOR_MANT_ACT,
	ACT.ACT_NUM_ACTIVO, 
	USU_GACT.USU_USERNAME, 
	USU_GACT.USU_NOMBRE, 
	TBJ.TBJ_NUM_TRABAJO, 
	TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE
	FROM REM01.ACT_ACTIVO ACT
	INNER JOIN REM01.GAC_GESTOR_ADD_ACTIVO GAC ON GAC.ACT_ID = ACT.ACT_ID
	INNER JOIN REM01.GEE_GESTOR_ENTIDAD GEE_GACT ON REM01.GEE_GACT.GEE_ID = GAC.GEE_ID
	INNER JOIN REMMASTER.USU_USUARIOS USU_GACT ON GEE_GACT.USU_ID = USU_GACT.USU_ID
	INNER JOIN REM01.ACT_TBJ ACTTBJ ON ACTTBJ.ACT_ID = ACT.ACT_ID
	INNER JOIN REM01.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ACTTBJ.TBJ_ID 
	WHERE GEE_GACT.DD_TGE_ID  = 362 
	AND ACT.DD_CRA_ID IN (21,43) 
	AND ACT.BORRADO = 0 
	AND GEE_GACT.BORRADO = 0 
	AND EXISTS ( 
	SELECT 1 FROM
	REM01.GAC_GESTOR_ADD_ACTIVO GAC 
	JOIN REM01.GEE_GESTOR_ENTIDAD GEE ON REM01.GEE.GEE_ID = GAC.GEE_ID
	JOIN REMMASTER.USU_USUARIOS USU ON GEE.USU_ID = USU.USU_ID
	WHERE GAC.ACT_ID = ACT.ACT_ID
	AND GEE.DD_TGE_ID IN  (362,/* MANTENIMIENTO*/541 /*ALQUILER*/,543 /*EDIFICACION*/,545 /*SUELOS*/) 
	AND USU.USU_ID = USU_GACT.USU_ID 
	AND USU.USU_ID = TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE 
	and TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE <> 50479)

  ) ';

DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA2||' CREADA');  

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA3||'' AND OWNER= ''||V_ESQUEMA_1||'';
IF TABLE_COUNT > 0 THEN
    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA3||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA3||'';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA3||' AS 
  (  SELECT DISTINCT TAR.TAR_ID,
	TAC.TRA_ID, 
	TAR.BORRADO, 
	TAP.TAP_CODIGO,
	TBJ.TBJ_NUM_TRABAJO,
	TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE,
	TBJ.TBJ_RESPONSABLE_TRABAJO,
    	TAC.USUARIOMODIFICAR, 
	ACT.ACT_NUM_ACTIVO, 
	TBJ.ACT_ID, 
	TBJ.AGR_ID
			FROM REM01.TAC_TAREAS_ACTIVOS TAC
			INNER JOIN REM01.TAR_TAREAS_NOTIFICACIONES TAR ON TAC.TAR_ID = TAR.TAR_ID 
			INNER JOIN REM01.ACT_TRA_TRAMITE TRA ON TRA.TRA_ID = TAC.TRA_ID
			INNER JOIN REM01.ACT_ACTIVO ACT ON ACT.ACT_ID = TAC.ACT_ID 
			INNER JOIN REM01.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAC.TAR_ID
			INNER JOIN REM01.TAP_TAREA_PROCEDIMIENTO TAP ON TAP.TAP_ID = TEX.TAP_ID
			INNER JOIN REMMASTER.USU_USUARIOS USU ON TAC.USU_ID = USU.USU_ID
			INNER JOIN REM01.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = TRA.TBJ_ID
			INNER JOIN REM01.AUX_REMVIP_5874 AUX ON TBJ.TBJ_NUM_TRABAJO = AUX.NUM_TRABAJO
			WHERE TRA.DD_EPR_ID = 30 
			AND (ACT.DD_CRA_ID = 21 OR ACT.DD_CRA_ID = 43) 
			AND TAP.DD_TGE_ID = 362 
			AND TAR.BORRADO = 0
			AND USU.USU_USERNAME <> ''usugruhpm'' 
			AND TAP.TAP_CODIGO NOT LIKE ''%Result%'' 
			AND (TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE <> 50479 OR TBJ.TBJ_RESPONSABLE_TRABAJO <> 50479)
  ) ';
DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA3||' CREADA');  

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA4||'' AND OWNER= ''||V_ESQUEMA_1||'';
IF TABLE_COUNT > 0 THEN
    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA4||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA4||'';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA4||' AS 
  ( SELECT DISTINCT TAR.TAR_ID,
	TAC.TRA_ID, 
	TAR.BORRADO, 
	TAP.TAP_CODIGO,
	TBJ.TBJ_NUM_TRABAJO,
	TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE,
	TBJ.TBJ_RESPONSABLE_TRABAJO,
	GEE.USU_ID, TAC.USUARIOMODIFICAR, 
	ACT.ACT_NUM_ACTIVO, 
	TBJ.ACT_ID, 
	TBJ.AGR_ID,
	GEE.USU_ID as USU_ID_GESTOR
			FROM  REM01.TAC_TAREAS_ACTIVOS TAC
			INNER JOIN REM01.TAR_TAREAS_NOTIFICACIONES TAR ON TAC.TAR_ID = TAR.TAR_ID 
			INNER JOIN REM01.ACT_TRA_TRAMITE TRA ON TRA.TRA_ID = TAC.TRA_ID
			INNER JOIN REM01.ACT_ACTIVO ACT ON ACT.ACT_ID = TAC.ACT_ID 
			INNER JOIN REM01.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAC.TAR_ID
			INNER JOIN REM01.TAP_TAREA_PROCEDIMIENTO TAP ON TAP.TAP_ID = TEX.TAP_ID
			INNER JOIN REMMASTER.USU_USUARIOS USU ON TAC.USU_ID = USU.USU_ID
			INNER JOIN REM01.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = TRA.TBJ_ID 
			INNER JOIN REM01.GAC_GESTOR_ADD_ACTIVO GAC ON ACT.ACT_ID = GAC.ACT_ID 
			INNER JOIN REM01.GEE_GESTOR_ENTIDAD GEE ON GEE.GEE_ID = GAC.GEE_ID AND GEE.DD_TGE_ID = 362
			WHERE TRA.DD_EPR_ID = 30 
			AND (ACT.DD_CRA_ID = 21 OR ACT.DD_CRA_ID = 43) 
			AND TAP.DD_TGE_ID = 362 
			AND TAR.BORRADO = 0
			AND USU.USU_USERNAME <> ''usugruhpm'' 
			AND TAP.TAP_CODIGO NOT LIKE ''%Result%'' 
			AND ((TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE <> 50479 OR TBJ.TBJ_RESPONSABLE_TRABAJO <> 50479) OR TBJ.TBJ_GESTOR_ACTIVO_RESPONSABLE IS NULL)
			AND (TAC.USUARIOMODIFICAR <> ''REMVIP-5874'' OR TAC.USUARIOMODIFICAR IS NULL) 
			AND (TBJ.ACT_ID IS NOT NULL AND TBJ.AGR_ID IS NULL) 
			AND GEE.USU_ID = (SELECT USU_ID FROM REMMASTER.USU_USUARIOS WHERE USU_USERNAME = ''grupgact'')
  ) ';
DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA4||' CREADA');  


IF V_ESQUEMA_2 != V_ESQUEMA_1 THEN

	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA1||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA1||' OTORGADOS A '||V_ESQUEMA_2||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA2||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA2||' OTORGADOS A '||V_ESQUEMA_2||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA3||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA3||' OTORGADOS A '||V_ESQUEMA_2||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA4||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA4||' OTORGADOS A '||V_ESQUEMA_2||''); 

END IF;


IF V_ESQUEMA_4 != V_ESQUEMA_1 THEN
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA1||'" TO "'||V_ESQUEMA_4||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA1||' OTORGADOS A '||V_ESQUEMA_4||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA2||'" TO "'||V_ESQUEMA_4||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA2||' OTORGADOS A '||V_ESQUEMA_4||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA3||'" TO "'||V_ESQUEMA_4||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA3||' OTORGADOS A '||V_ESQUEMA_4||''); 
	
	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA4||'" TO "'||V_ESQUEMA_4||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA4||' OTORGADOS A '||V_ESQUEMA_4||''); 

END IF;

	V_MSQL := 'CREATE INDEX IDX_AUX_GEE_GEE_ID_5874 ON '||V_ESQUEMA_1||'.AUX_GEE_REMVIP_5874(GEE_ID)';
	EXECUTE IMMEDIATE V_MSQL;
	DBMS_OUTPUT.PUT_LINE('[INFO] CREADO INDICE PARA AUX_GEE_REMVIP_5874'); 

	V_MSQL := 'CREATE INDEX IDX_AUX_GAC_GAC_ID_5874 ON '||V_ESQUEMA_1||'.AUX_GAC_REMVIP_5874(GEE_ID)';
	EXECUTE IMMEDIATE V_MSQL;
	DBMS_OUTPUT.PUT_LINE('[INFO] CREADO INDICE PARA AUX_GAC_REMVIP_5874'); 

	V_MSQL := 'CREATE INDEX IDX_AUX_GEH_GEH_ID_5874 ON '||V_ESQUEMA_1||'.AUX_GEH_REMVIP_5874(GEH_ID)';
	EXECUTE IMMEDIATE V_MSQL;
	DBMS_OUTPUT.PUT_LINE('[INFO] CREADO INDICE PARA AUX_GEH_REMVIP_5874'); 

	V_MSQL := 'CREATE INDEX IDX_AUX_GAH_GAH_ID_5874 ON '||V_ESQUEMA_1||'.AUX_GAH_REMVIP_5874(GEH_ID)';
	EXECUTE IMMEDIATE V_MSQL;
	DBMS_OUTPUT.PUT_LINE('[INFO] CREADO INDICE PARA AUX_GAH_REMVIP_5874'); 

	COMMIT;

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

EXIT;
