--/*
--##########################################
--## AUTOR=IVAN REPISO
--## FECHA_CREACION=20201102
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-8288
--## PRODUCTO=NO
--##
--## Finalidad: Script que modifica partidas presupuestarias y cuentas contables
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Ver1ón inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_NUM_TABLAS NUMBER(25);
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-8288'; -- USUARIO CREAR/MODIFICAR

    V_CARTERA VARCHAR2(50 CHAR) := '07'; --COD CERBERUS
    V_SUBCARTERA VARCHAR2(100 CHAR) := '138'; -- COD Apple - Inmobiliario
    V_TIPO_GASTO VARCHAR2(100 CHAR) := '02'; -- COD Tasa
    V_SUBTIPO_GASTO VARCHAR2(100 CHAR) := '16'; -- COD Judicial
    
BEGIN	
	
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');

    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA CPP_CONFIG_PTDAS_PREP');

	--Comprobamos el dato a insertar par registros sin arrendamiento
	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP CPP
                INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CPP.EJE_ID AND EJE.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CPP.DD_SCR_ID AND SCR.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CPP.DD_STG_ID AND STG.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                WHERE CPP.BORRADO = 0 AND CPP.CPP_PARTIDA_PRESUPUESTARIA = ''PP054''
                AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                AND CPP.CPP_ARRENDAMIENTO = 0';
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
			
	--Si NO existe lo insertamos
	IF V_NUM_TABLAS = 0 THEN				
			  
		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP (CPP_ID, EJE_ID, DD_STG_ID, DD_CRA_ID, DD_SCR_ID,
                    CPP_PARTIDA_PRESUPUESTARIA, USUARIOCREAR, FECHACREAR, CPP_ARRENDAMIENTO) 
                    SELECT '||V_ESQUEMA||'.S_CPP_CONFIG_PTDAS_PREP.NEXTVAL, (SELECT EJE_ID FROM '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE WHERE EJE.EJE_ANYO = ''2020'' AND BORRADO = 0),
                    (SELECT DD_STG_ID FROM '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG WHERE STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||'''
                    AND STG.DD_TGA_ID = (SELECT DD_TGA_ID FROM '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA WHERE TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||''' AND BORRADO = 0) AND BORRADO = 0),
                    (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = '''||V_CARTERA||''' AND BORRADO = 0), 
                    (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND BORRADO = 0),
                    ''PP071'','''||V_USUARIO||''',SYSDATE,0 FROM DUAL';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO]: INSERTADA PARTIDA PP071 SIN ARRENDAMIENTO ');

	ELSE	

		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP T1 USING 
			            (SELECT CPP_ID FROM '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP CPP
                            INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CPP.EJE_ID  AND CPP.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CPP.DD_SCR_ID AND SCR.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CPP.DD_STG_ID AND STG.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                            WHERE CPP.BORRADO = 0 AND CPP.CPP_PARTIDA_PRESUPUESTARIA = ''PP054''
                            AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                            AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                            AND CPP.CPP_ARRENDAMIENTO = 0) T2
                        ON ( T1.CPP_ID = T2.CPP_ID )
                        WHEN MATCHED THEN UPDATE SET 
                        T1.CPP_PARTIDA_PRESUPUESTARIA = ''PP071'',
                        T1.USUARIOMODIFICAR = '''||V_USUARIO||''',
                        T1.FECHAMODIFICAR = SYSDATE';
		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO]: YA EXISTE PARTIDA Y SE MODIFICA ');        
	END IF;

	--Comprobamos el dato a insertar par registros con arrendamiento
	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP CPP
                INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CPP.EJE_ID AND EJE.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CPP.DD_SCR_ID AND SCR.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CPP.DD_STG_ID AND STG.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                WHERE CPP.BORRADO = 0 AND CPP.CPP_PARTIDA_PRESUPUESTARIA = ''PP054''
                AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                AND CPP.CPP_ARRENDAMIENTO = 1';
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
			
	--Si NO existe lo insertamos
	IF V_NUM_TABLAS = 0 THEN				
			  
		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP (CPP_ID, EJE_ID, DD_STG_ID, DD_CRA_ID, DD_SCR_ID,
                    CPP_PARTIDA_PRESUPUESTARIA, USUARIOCREAR, FECHACREAR, CPP_ARRENDAMIENTO) 
                    SELECT '||V_ESQUEMA||'.S_CPP_CONFIG_PTDAS_PREP.NEXTVAL, (SELECT EJE_ID FROM '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE WHERE EJE.EJE_ANYO = ''2020'' AND BORRADO = 0),
                    (SELECT DD_STG_ID FROM '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG WHERE STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||'''
                    AND STG.DD_TGA_ID = (SELECT DD_TGA_ID FROM '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA WHERE TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||''' AND BORRADO = 0) AND BORRADO = 0),
                    (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = '''||V_CARTERA||''' AND BORRADO = 0), 
                    (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND BORRADO = 0),
                    ''PP071'','''||V_USUARIO||''',SYSDATE,1 FROM DUAL';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO]: INSERTADA PARTIDA PP071 CON ARRENDAMIENTO ');
		     
	ELSE	

		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP T1 USING 
			            (SELECT CPP_ID FROM '||V_ESQUEMA||'.CPP_CONFIG_PTDAS_PREP CPP
                            INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CPP.EJE_ID  AND CPP.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CPP.DD_SCR_ID AND SCR.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CPP.DD_STG_ID AND STG.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                            WHERE CPP.BORRADO = 0 AND CPP.CPP_PARTIDA_PRESUPUESTARIA = ''PP054''
                            AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                            AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                            AND CPP.CPP_ARRENDAMIENTO = 1) T2
                        ON ( T1.CPP_ID = T2.CPP_ID )
                        WHEN MATCHED THEN UPDATE SET 
                        T1.CPP_PARTIDA_PRESUPUESTARIA = ''PP071'',
                        T1.USUARIOMODIFICAR = '''||V_USUARIO||''',
                        T1.FECHAMODIFICAR = SYSDATE';
		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO]: YA EXISTE PARTIDA Y SE MODIFICA ');        
	END IF;

    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA CCC_CONFIG_CTAS_CONTABLES');

    --Comprobamos el dato a insertar par registros sin arrendamiento
	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES CCC
                INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CCC.EJE_ID AND EJE.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CCC.DD_SCR_ID AND SCR.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CCC.DD_STG_ID AND STG.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                WHERE CCC.BORRADO = 0 AND CCC.CCC_CUENTA_CONTABLE = ''6310000110''
                AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                AND CCC.CCC_ARRENDAMIENTO = 0';
		
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
			
	--Si NO existe lo insertamos
	IF V_NUM_TABLAS = 0 THEN				
			  
		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES (CCC_ID, EJE_ID, DD_STG_ID, DD_CRA_ID, DD_SCR_ID,
                    CCC_CUENTA_CONTABLE, USUARIOCREAR, FECHACREAR, CCC_ARRENDAMIENTO) 
                    SELECT '||V_ESQUEMA||'.S_CCC_CONFIG_PTDAS_PREP.NEXTVAL, (SELECT EJE_ID FROM '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE WHERE EJE.EJE_ANYO = ''2020'' AND BORRADO = 0),
                    (SELECT DD_STG_ID FROM '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG WHERE STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||'''
                    AND STG.DD_TGA_ID = (SELECT DD_TGA_ID FROM '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA WHERE TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||''' AND BORRADO = 0) AND BORRADO = 0),
                    (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = '''||V_CARTERA||''' AND BORRADO = 0), 
                    (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND BORRADO = 0),
                    ''6310000090'','''||V_USUARIO||''',SYSDATE,0 FROM DUAL';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO]: INSERTADA CC 6222000050 SIN ARRENDAMIENTO ');
			  
	ELSE

		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES T1 USING 
			            (SELECT CCC_ID FROM '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES CCC
                            INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CCC.EJE_ID  AND CCC.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = CCC.DD_CRA_ID  AND CRA.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CCC.DD_SCR_ID AND SCR.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CCC.DD_STG_ID AND STG.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                            WHERE CCC.BORRADO = 0 AND CCC.CCC_CUENTA_CONTABLE = ''6310000110''
                            AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                            AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                            AND CCC.CCC_ARRENDAMIENTO = 0) T2
                        ON ( T1.CCC_ID = T2.CCC_ID )
                        WHEN MATCHED THEN UPDATE SET 
                        T1.CCC_CUENTA_CONTABLE = ''6310000090'',
                        T1.USUARIOMODIFICAR = '''||V_USUARIO||''',
                        T1.FECHAMODIFICAR = SYSDATE';

		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO]: YA EXISTE PARTIDA Y SE MODIFICA ');        
	END IF;


	--------------------------------------------------------------------------------------------------------------------------------------------------------------------
	--Comprobamos el dato a insertar par registros con arrendamiento
	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES CCC
                INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CCC.EJE_ID AND EJE.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CCC.DD_SCR_ID AND SCR.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CCC.DD_STG_ID AND STG.BORRADO = 0
                INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                WHERE CCC.BORRADO = 0 AND CCC.CCC_CUENTA_CONTABLE = ''6310000110''
                AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                AND CCC.CCC_ARRENDAMIENTO = 1';
		
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
			
	--Si NO existe lo insertamos
	IF V_NUM_TABLAS = 0 THEN				
			  
		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES (CCC_ID, EJE_ID, DD_STG_ID, DD_CRA_ID, DD_SCR_ID,
                    CCC_CUENTA_CONTABLE, USUARIOCREAR, FECHACREAR, CCC_ARRENDAMIENTO) 
                    SELECT '||V_ESQUEMA||'.S_CCC_CONFIG_PTDAS_PREP.NEXTVAL, (SELECT EJE_ID FROM '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE WHERE EJE.EJE_ANYO = ''2020'' AND BORRADO = 0),
                    (SELECT DD_STG_ID FROM '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG WHERE STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||'''
                    AND STG.DD_TGA_ID = (SELECT DD_TGA_ID FROM '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA WHERE TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||''' AND BORRADO = 0) AND BORRADO = 0),
                    (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = '''||V_CARTERA||''' AND BORRADO = 0), 
                    (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND BORRADO = 0),
                    ''6310000090'','''||V_USUARIO||''',SYSDATE,1 FROM DUAL';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO]: INSERTADA CC 6222000050 CON ARRENDAMIENTO ');
			       
	ELSE	

		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES T1 USING 
			            (SELECT CCC_ID FROM '||V_ESQUEMA||'.CCC_CONFIG_CTAS_CONTABLES CCC
                            INNER JOIN '||V_ESQUEMA||'.ACT_EJE_EJERCICIO EJE ON EJE.EJE_ID = CCC.EJE_ID  AND CCC.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = CCC.DD_CRA_ID  AND CRA.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = CCC.DD_SCR_ID AND SCR.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_ID = CCC.DD_STG_ID AND STG.BORRADO = 0
                            INNER JOIN '||V_ESQUEMA||'.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_ID = STG.DD_TGA_ID AND TGA.BORRADO = 0
                            WHERE CCC.BORRADO = 0 AND CCC.CCC_CUENTA_CONTABLE = ''6310000110''
                            AND SCR.DD_SCR_CODIGO = '''||V_SUBCARTERA||''' AND EJE.EJE_ANYO = ''2020''
                            AND STG.DD_STG_CODIGO = '''||V_SUBTIPO_GASTO||''' AND TGA.DD_TGA_CODIGO ='''||V_TIPO_GASTO||'''
                            AND CCC.CCC_ARRENDAMIENTO = 1) T2
                        ON ( T1.CCC_ID = T2.CCC_ID )
                        WHEN MATCHED THEN UPDATE SET 
                        T1.CCC_CUENTA_CONTABLE = ''6310000090'',
                        T1.USUARIOMODIFICAR = '''||V_USUARIO||''',
                        T1.FECHAMODIFICAR = SYSDATE';

		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO]: YA EXISTE PARTIDA Y SE MODIFICA ');        
	END IF;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('[INFO]: FIN');

EXCEPTION
     WHEN OTHERS THEN
          err_num := SQLCODE;
          err_msg := SQLERRM;

          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(err_msg);

          ROLLBACK;
          RAISE;          

END;

/

EXIT