--/*
--##########################################
--## AUTOR=GUILLEM REY
--## FECHA_CREACION=20201014
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-8123
--## PRODUCTO=NO
--##
--## Finalidad: Insertar informes borrados
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
	V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
	V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
	V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.   
	ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
	ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
	
	V_TABLA_ICO VARCHAR2(50 CHAR) := 'ACT_ICO_INFO_COMERCIAL';
	V_TABLA_VIV VARCHAR2(50 CHAR) := 'ACT_VIV_VIVIENDA';
	V_TABLA_LCO VARCHAR2(50 CHAR) := 'ACT_LCO_LOCAL_COMERCIAL';
	V_TABLA_APR VARCHAR2(50 CHAR) := 'ACT_APR_PLAZA_APARCAMIENTO';
	V_TABLA_EDI VARCHAR2(50 CHAR) := 'ACT_EDI_EDIFICIO';
	V_TABLA_DIS VARCHAR2(50 CHAR) := 'ACT_DIS_DISTRIBUCION';

	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-8123'; -- USUARIO CREAR/MODIFICAR
    
BEGIN	
	DBMS_OUTPUT.PUT_LINE('[INFO] INICIO'); 

	--INSERTAR BORRADOS VIVIENDA
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_VIV||' 
				SELECT ICO.ICO_ID
				,AVIV.DD_TPV_ID
				,AVIV.DD_TPO_ID
				,AVIV.DD_TPR_ID
				,AVIV.VIV_ULTIMA_PLANTA
				,AVIV.VIV_NUM_PLANTAS_INTERIOR
				,AVIV.VIV_REFORMA_CARP_INT
				,AVIV.VIV_REFORMA_CARP_EXT
				,AVIV.VIV_REFORMA_COCINA
				,AVIV.VIV_REFORMA_BANYO
				,AVIV.VIV_REFORMA_SUELO
				,AVIV.VIV_REFORMA_PINTURA
				,AVIV.VIV_REFORMA_INTEGRAL
				,AVIV.VIV_REFORMA_OTRO
				,AVIV.VIV_REFORMA_OTRO_DESC
				,AVIV.VIV_REFORMA_PRESUPUESTO
				,AVIV.VIV_DISTRIBUCION_TXT FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_VIV||' VIV ON VIV.ICO_ID = ICO.ICO_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_ICO||' AICO ON AICO.ACT_ID = ACT.ACT_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_VIV||' AVIV ON AVIV.ICO_ID = AICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND VIV.ICO_ID IS NULL';
				
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--INSERTAR VACIO SI NO TIENE VIVIENDA
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_VIV||'
				SELECT ICO.ICO_ID, NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_VIV||' VIV ON VIV.ICO_ID = ICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_TPA_ID = 2 AND VIV.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--ACTUALIZAR TIPOS ICO VIVENDA SI NO LO TIENEN
	V_MSQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_ICO||' SET DD_TIC_ID = 1, USUARIOMODIFICAR = '''||V_USUARIO||''', FECHAMODIFICAR = SYSDATE
				 WHERE ICO_ID IN (
					SELECT ICO.ICO_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ICO.ACT_ID = ACT.ACT_ID
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_VIV||' VIV ON VIV.ICO_ID = ICO.ICO_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_LCO||' LCO ON LCO.ICO_ID = ICO.ICO_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_APR||' APR ON APR.ICO_ID = ICO.ICO_ID
					WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_TPA_ID = 2 AND (ICO.DD_TIC_ID != 1 OR ICO.DD_TIC_ID IS NULL))';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	-- INSERTAR BORRADOS LOCALCOMERCIAL
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_LCO||'
				SELECT ICO.ICO_ID
				,ALCO.LCO_MTS_FACHADA_PPAL
				,ALCO.LCO_MTS_FACHADA_LAT
				,ALCO.LCO_MTS_LUZ_LIBRE
				,ALCO.LCO_MTS_ALTURA_LIBRE
				,ALCO.LCO_MTS_LINEALES_PROF
				,ALCO.LCO_DIAFANO
				,ALCO.LCO_USO_IDONEO
				,ALCO.LCO_USO_ANTERIOR
				,ALCO.LCO_OBSERVACIONES
				,ALCO.LCO_NUMERO_ESTANCIAS
				,ALCO.LCO_NUMERO_BANYOS
				,ALCO.LCO_NUMERO_ASEOS
				,ALCO.LCO_SALIDA_HUMOS
				,ALCO.LCO_SALIDA_EMERGENCIA
				,ALCO.LCO_ACCESO_MINUSVALIDOS
				,ALCO.LCO_OTROS_OTRAS_CARACT
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_LCO||' LCO ON LCO.ICO_ID = ICO.ICO_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_ICO||' AICO ON AICO.ACT_ID = ACT.ACT_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_LCO||' ALCO ON ALCO.ICO_ID = AICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND LCO.ICO_ID IS NULL';
				
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--INSERTAR VACIO SI NO TIENE LOCALCOMERCIAL
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_LCO||'
				SELECT ICO.ICO_ID, NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_LCO||' LCO ON LCO.ICO_ID = ICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_TPA_ID = 3 AND LCO.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--ACTUALIZAR TIPOS ICO LOCALCOMERCIAL SI NO LO TIENEN
	V_MSQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_ICO||' SET DD_TIC_ID = 2, USUARIOMODIFICAR = '''||V_USUARIO||''', FECHAMODIFICAR = SYSDATE
				 WHERE ICO_ID IN ( 
					SELECT ICO.ICO_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ICO.ACT_ID = ACT.ACT_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_VIV||' VIV ON VIV.ICO_ID = ICO.ICO_ID
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_LCO||' LCO ON LCO.ICO_ID = ICO.ICO_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_APR||' APR ON APR.ICO_ID = ICO.ICO_ID
					WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_TPA_ID = 3 AND (ICO.DD_TIC_ID != 2 OR ICO.DD_TIC_ID IS NULL))';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	-- INSERTAR BORRADOS PLAZAAPARCAMIENTO
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_APR||'
				SELECT ICO.ICO_ID
				,AAPR.APR_DESTINO_COCHE
				,AAPR.APR_DESTINO_MOTO
				,AAPR.APR_DESTINO_DOBLE
				,AAPR.DD_TUA_ID
				,AAPR.DD_TCA_ID
				,AAPR.APR_ANCHURA
				,AAPR.APR_PROFUNDIDAD
				,AAPR.APR_FORMA_IRREGULAR
				,AAPR.DD_TPV_ID
				,AAPR.APR_ALTURA
				,AAPR.DD_SPG_ID
				,AAPR.APR_LICENCIA
				,AAPR.APR_SERVIDUMBRE
				,AAPR.APR_ASCENSOR_MONTACARGA
				,AAPR.APR_COLUMNAS
				,AAPR.APR_SEGURIDAD
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_APR||' APR ON APR.ICO_ID = ICO.ICO_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_ICO||' AICO ON AICO.ACT_ID = ACT.ACT_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_APR||' AAPR ON AAPR.ICO_ID = AICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND APR.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--INSERTAR VACIO SI NO TIENE PLAZAAPARCAMIENTO
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_APR||'
				SELECT ICO.ICO_ID, NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL,NULL, NULL, NULL, NULL
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_APR||' LCO ON LCO.ICO_ID = ICO.ICO_ID
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_SAC_ID = 24 AND LCO.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--ACTUALIZAR TIPOS ICO PLAZAAPARCAMIENTO SI NO LO TIENEN
	V_MSQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_ICO||' SET DD_TIC_ID = 3, USUARIOMODIFICAR = '''||V_USUARIO||''', FECHAMODIFICAR = SYSDATE
				 WHERE ICO_ID IN (
					SELECT ICO.ICO_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ICO.ACT_ID = ACT.ACT_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_VIV||' VIV ON VIV.ICO_ID = ICO.ICO_ID
					LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_LCO||' LCO ON LCO.ICO_ID = ICO.ICO_ID
					INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_APR||' APR ON APR.ICO_ID = ICO.ICO_ID
					WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND ACT.DD_SAC_ID = 24 AND (ICO.DD_TIC_ID != 3 OR ICO.DD_TIC_ID IS NULL))';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--INSERTAR BORRADOS DISTRIBUCION
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_DIS||'
				SELECT 
				'||V_ESQUEMA||'.S_'||V_TABLA_DIS||'.NEXTVAL
				,ADIS.DIS_NUM_PLANTA
				,ADIS.DD_TPH_ID
				,ADIS.DIS_CANTIDAD
				,ADIS.DIS_SUPERFICIE
				,ADIS.VERSION
				,ADIS.USUARIOCREAR
				,ADIS.FECHACREAR
				,ADIS.USUARIOMODIFICAR
				,ADIS.FECHAMODIFICAR
				,ADIS.USUARIOBORRAR
				,ADIS.FECHABORRAR
				,ADIS.BORRADO
				,ADIS.DIS_DESCRIPCION
				,ICO.ICO_ID
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_DIS||' DIS ON DIS.ICO_ID = ICO.ICO_ID AND DIS.BORRADO = 0
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_ICO||' AICO ON AICO.ACT_ID = ACT.ACT_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_DIS||' ADIS ON ADIS.ICO_ID = AICO.ICO_ID AND ADIS.BORRADO = 0
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND DIS.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;
	
	
	--INSERTAR BORRADOS EDIFICIO
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_EDI||'
				SELECT 
				'||V_ESQUEMA||'.S_'||V_TABLA_EDI||'.NEXTVAL
				,ICO.ICO_ID
				,AEDI.DD_ECV_ID
				,AEDI.DD_TPF_ID
				,AEDI.EDI_ANO_REHABILITACION
				,AEDI.EDI_NUM_PLANTAS
				,AEDI.EDI_ASCENSOR
				,AEDI.EDI_NUM_ASCENSORES
				,AEDI.EDI_REFORMA_FACHADA
				,AEDI.EDI_REFORMA_ESCALERA
				,AEDI.EDI_REFORMA_PORTAL
				,AEDI.EDI_REFORMA_ASCENSOR
				,AEDI.EDI_REFORMA_CUBIERTA
				,AEDI.EDI_REFORMA_OTRA_ZONA
				,AEDI.EDI_REFORMA_OTRO
				,AEDI.EDI_REFORMA_OTRO_DESC
				,AEDI.EDI_DESCRIPCION
				,AEDI.EDI_ENTORNO_INFRAESTRUCTURA
				,AEDI.EDI_ENTORNO_COMUNICACION
				,AEDI.VERSION
				,AEDI.USUARIOCREAR
				,AEDI.FECHACREAR
				,AEDI.USUARIOMODIFICAR
				,AEDI.FECHAMODIFICAR
				,AEDI.USUARIOBORRAR
				,AEDI.FECHABORRAR
				,AEDI.BORRADO
				,AEDI.EDI_REFORMA_OTRO_ZONA_COM_DES
				,AEDI.EDI_DIVISIBLE
				,AEDI.EDI_DESC_PLANTAS
				,AEDI.EDI_OTRAS_CARACTERISTICAS
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_ICO||' ICO ON ACT.ACT_ID = ICO.ACT_ID 
				LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_EDI||' EDI ON EDI.ICO_ID = ICO.ICO_ID AND EDI.BORRADO = 0
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_ICO||' AICO ON AICO.ACT_ID = ACT.ACT_ID
				INNER JOIN '||V_ESQUEMA||'.AUX_'||V_TABLA_EDI||' AEDI ON AEDI.ICO_ID = AICO.ICO_ID AND AEDI.BORRADO = 0
				WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0 AND EDI.ICO_ID IS NULL';
	
	EXECUTE IMMEDIATE V_MSQL;

	
	COMMIT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] FIN');
   
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SQLERRM;

		DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
		DBMS_OUTPUT.put_line(err_msg);

		ROLLBACK;
		RAISE;          

END;
/
EXIT;
