--/*
--##########################################
--## AUTOR=Carlos Santos Vílchez
--## FECHA_CREACION=20210702
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-10085
--## PRODUCTO=NO
--## 
--## Finalidad: Actualización GESTOR
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE
	V_MSQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
 	V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
 	V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-10085'; -- USUARIO CREAR/MODIFICAR
	V_COUNT NUMBER(16); -- Vble. para comprobar
	err_num NUMBER; -- Numero de errores
	err_msg VARCHAR2(2048); -- Mensaje de error
	
	V_USERNAME VARCHAR2(50 CHAR) := 'grusbackoffice';
	V_PERFIL VARCHAR2(50 CHAR) := 'HAYASBOINM';

		TYPE T_TIPO_DATA IS TABLE OF VARCHAR2(150);
    TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
		T_TIPO_DATA('01'),
		T_TIPO_DATA('02'),
		T_TIPO_DATA('03'),
		T_TIPO_DATA('08'),
		T_TIPO_DATA('16')
		); 
    V_TMP_TIPO_DATA T_TIPO_DATA;
	
BEGIN
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');

	V_MSQL := 'TRUNCATE TABLE AUX_REMVIP_9367';
	EXECUTE IMMEDIATE V_MSQL;

	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA_M||'.USU_USUARIOS WHERE USU_USERNAME = '''||V_USERNAME||'''';
	EXECUTE IMMEDIATE V_MSQL INTO V_COUNT;

	IF V_COUNT = 1 THEN

		FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
		LOOP
		V_TMP_TIPO_DATA := V_TIPO_DATA(I);

			-- ACTIVOS
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.AUX_REMVIP_9367 (ACT_ID,ACT_NUM_ACTIVO,GEH_ID,DD_TGE_BY_GEH_ID,GEE_ID,DD_TGE_BY_GEE_ID,USU_ID_BY_GEE_ID)
							SELECT ACT.ACT_ID, ACT.ACT_NUM_ACTIVO,GEH.GEH_ID,GEH.DD_TGE_ID,GEE.GEE_ID,GEE.DD_TGE_ID,GEE.USU_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
							INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC ON GAC.ACT_ID = ACT.ACT_ID
							INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE ON GEE.GEE_ID = GAC.GEE_ID
								AND GEE.DD_TGE_ID = (SELECT DD_TGE_ID FROM '||V_ESQUEMA_M||'.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = '''||V_PERFIL||''')
								AND GEE.BORRADO = 0
							INNER JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH ON GAH.ACT_ID = ACT.ACT_ID
							INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH ON GEH.GEH_ID = GAH.GEH_ID
								AND GEH.DD_TGE_ID = (SELECT DD_TGE_ID FROM '||V_ESQUEMA_M||'.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = '''||V_PERFIL||''') AND GEH.GEH_FECHA_HASTA IS NULL 
								AND GEH.BORRADO = 0
							AND ACT.DD_CRA_ID = (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = '''||V_TMP_TIPO_DATA(1)||''')
							AND ACT.BORRADO = 0';
			EXECUTE IMMEDIATE V_MSQL;

			DBMS_OUTPUT.PUT_LINE('[INFO] INSERTADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN AUX_REMVIP_9367');

		END LOOP;

		V_MSQL := 'UPDATE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH SET 
				GEH_FECHA_HASTA = TO_DATE(SYSDATE, ''DD/MM/YY''),
				USUARIOMODIFICAR = '''||V_USUARIO||''',
				FECHAMODIFICAR = SYSDATE
				WHERE GEH_ID IN (SELECT GEH_ID FROM '||V_ESQUEMA||'.AUX_REMVIP_9367)';
		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN GEH_GESTOR_ENTIDAD_HIST');

		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (GEH_ID,USU_ID,DD_TGE_ID, GEH_FECHA_DESDE, USUARIOCREAR, FECHACREAR, USUARIOMODIFICAR)
					SELECT '||V_ESQUEMA||'.S_GEH_GESTOR_ENTIDAD_HIST.NEXTVAL,
					(SELECT USU_ID FROM '||V_ESQUEMA_M||'.USU_USUARIOS WHERE USU_USERNAME = '''||V_USERNAME||''' AND BORRADO = 0),
					(SELECT DD_TGE_ID FROM '||V_ESQUEMA_M||'.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = '''||V_PERFIL||''' AND BORRADO = 0),
					SYSDATE, '''||V_USUARIO||''',SYSDATE, TO_CHAR(AUX.ACT_ID) FROM '||V_ESQUEMA||'.AUX_REMVIP_9367 AUX';
		EXECUTE IMMEDIATE V_MSQL;  

		DBMS_OUTPUT.PUT_LINE('[INFO]: REGISTROS INSERTADOS EN GEH_GESTOR_ENTIDAD_HIST: ' ||sql%rowcount);

		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (GEH_ID, ACT_ID)
					SELECT GEH_ID, TO_NUMBER(USUARIOMODIFICAR) FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST WHERE USUARIOCREAR = '''||V_USUARIO||'''
					AND USUARIOMODIFICAR IS NOT NULL AND USUARIOMODIFICAR != '''||V_USUARIO||'''';
		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO]: REGISTROS INSERTADOS EN GAH_GESTOR_ACTIVO_HISTORICO: ' ||sql%rowcount);

		V_MSQL:='UPDATE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST 
					SET USUARIOMODIFICAR = NULL
					WHERE USUARIOCREAR = '''||V_USUARIO||''' AND USUARIOMODIFICAR IS NOT NULL';
		EXECUTE IMMEDIATE V_MSQL;

		V_MSQL := 'UPDATE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE SET 
				USU_ID = (SELECT USU_ID FROM '||V_ESQUEMA_M||'.USU_USUARIOS WHERE USU_USERNAME = '''||V_USERNAME||''' AND BORRADO = 0),
				USUARIOMODIFICAR = '''||V_USUARIO||''',
				FECHAMODIFICAR = SYSDATE
				WHERE GEE_ID IN (SELECT GEE_ID FROM '||V_ESQUEMA||'.AUX_REMVIP_9367)';
		EXECUTE IMMEDIATE V_MSQL;

		DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN GEE_GESTOR_ENTIDAD');

		COMMIT;
		
	ELSE 
	
		DBMS_OUTPUT.PUT_LINE('[INFO] NO EXISTE USUARIO '''||V_USERNAME||'''');
	
	END IF;

	DBMS_OUTPUT.PUT_LINE('[FIN] ');
	
	EXCEPTION
	
	    WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
		DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------');
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
		DBMS_OUTPUT.PUT_LINE(V_MSQL);
		ROLLBACK;
		RAISE;
END;
/
EXIT;