--/*
--######################################### 
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20210216
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=REMVIP-8950
--## PRODUCTO=NO
--## 
--## Finalidad: Modificación tarifas
--##                    
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;

DECLARE

    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01'; -- #ESQUEMA# Configuracion Esquema
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.

    
BEGIN

	DBMS_OUTPUT.PUT_LINE('[INFO] Merge ACT_TCT_TRABAJO_CFGTARIFA.TCT_PRECIO_UNITARIO. Carga masiva.');

    
    execute immediate '
	MERGE INTO '||V_ESQUEMA||'.ACT_TCT_TRABAJO_CFGTARIFA TCT USING(
	SELECT TCT.TCT_ID,
	TBJ.TBJ_NUM_TRABAJO,
	TTF.DD_TTF_CODIGO,
	TTF.DD_TTF_DESCRIPCION, 
	CFT.CFT_PRECIO_UNITARIO AS PRECIO_UNITARIO_TARIFA,
	TCT.TCT_PRECIO_UNITARIO AS PRECIO_UNITARIO_TRABAJO
	FROM '||V_ESQUEMA||'.DD_TTF_TIPO_TARIFA TTF 
	INNER JOIN '||V_ESQUEMA||'.ACT_CFT_CONFIG_TARIFA CFT ON CFT.DD_TTF_ID = TTF.DD_TTF_ID 
	INNER JOIN '||V_ESQUEMA||'.TMP_ACT_CFT_CONFIG_TARIFA  TMP ON TMP.CODIGO = TTF.DD_TTF_CODIGO 
	INNER JOIN '||V_ESQUEMA||'.DD_TTR_TIPO_TRABAJO TTR ON CFT.DD_TTR_ID = TTR.DD_TTR_ID
	INNER JOIN '||V_ESQUEMA||'.DD_STR_SUBTIPO_TRABAJO STR ON CFT.DD_STR_ID = STR.DD_STR_ID 
	INNER JOIN '||V_ESQUEMA||'.ACT_TCT_TRABAJO_CFGTARIFA TCT ON TCT.CFT_ID = CFT.CFT_ID 
	INNER JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TCT.TBJ_ID = TBJ.TBJ_ID
	WHERE CFT.DD_CRA_ID = 162 AND DD_TTF_CODIGO LIKE ''%BBVA%''
	AND (CFT.CFT_PRECIO_UNITARIO <> TCT.TCT_PRECIO_UNITARIO)
	) AUX ON (AUX.TCT_ID = TCT.TCT_ID)
	WHEN MATCHED THEN UPDATE SET
	TCT.TCT_PRECIO_UNITARIO = AUX.PRECIO_UNITARIO_TARIFA,
	TCT.USUARIOMODIFICAR = ''REMVIP-8950'',
	TCT.FECHAMODIFICAR = SYSDATE
    ';


    DBMS_OUTPUT.PUT_LINE('[INFO] Se han actualizado '||SQL%ROWCOUNT||' registros.');
    
    
        execute immediate '
	MERGE INTO '||V_ESQUEMA||'.ACT_TCT_TRABAJO_CFGTARIFA TCT USING(
	SELECT TCT.TCT_ID,
	TBJ.TBJ_NUM_TRABAJO,
	TTF.DD_TTF_CODIGO,
	TTF.DD_TTF_DESCRIPCION, 
	CFT.CFT_PRECIO_UNITARIO_CLIENTE AS PRECIO_UNITARIO_CLINTE_TARIFA,
	TCT.TCT_PRECIO_UNITARIO_CLIENTE AS PRECIO_UNITARIO_CLINTE_TRABAJO
	FROM '||V_ESQUEMA||'.DD_TTF_TIPO_TARIFA TTF 
	INNER JOIN '||V_ESQUEMA||'.ACT_CFT_CONFIG_TARIFA CFT ON CFT.DD_TTF_ID = TTF.DD_TTF_ID 
	INNER JOIN '||V_ESQUEMA||'.TMP_ACT_CFT_CONFIG_TARIFA  TMP ON TMP.CODIGO = TTF.DD_TTF_CODIGO 
	INNER JOIN '||V_ESQUEMA||'.DD_TTR_TIPO_TRABAJO TTR ON CFT.DD_TTR_ID = TTR.DD_TTR_ID
	INNER JOIN '||V_ESQUEMA||'.DD_STR_SUBTIPO_TRABAJO STR ON CFT.DD_STR_ID = STR.DD_STR_ID 
	INNER JOIN '||V_ESQUEMA||'.ACT_TCT_TRABAJO_CFGTARIFA TCT ON TCT.CFT_ID = CFT.CFT_ID 
	INNER JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TCT.TBJ_ID = TBJ.TBJ_ID
	WHERE CFT.DD_CRA_ID = 162 AND DD_TTF_CODIGO LIKE ''%BBVA%'' 
	AND (CFT.CFT_PRECIO_UNITARIO_CLIENTE <> TCT.TCT_PRECIO_UNITARIO_CLIENTE)
	) AUX ON (AUX.TCT_ID = TCT.TCT_ID)
	WHEN MATCHED THEN UPDATE SET
	TCT.TCT_PRECIO_UNITARIO_CLIENTE = AUX.PRECIO_UNITARIO_CLINTE_TARIFA,
	TCT.USUARIOMODIFICAR = ''REMVIP-8950'',
	TCT.FECHAMODIFICAR = SYSDATE
    ';


    DBMS_OUTPUT.PUT_LINE('[INFO] Se han actualizado '||SQL%ROWCOUNT||' registros.');


    COMMIT;


    DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
  WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('KO!');
    ERR_NUM := SQLCODE;
    ERR_MSG := SQLERRM;    
    DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
    DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
    DBMS_OUTPUT.put_line(ERR_MSG);    
    ROLLBACK;
    RAISE;        

END;
/
EXIT;
