--/*
--##########################################
--## AUTOR=GUILLEM REY
--## FECHA_CREACION=20191111
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-5721
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.   
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_TIPO_INFORME VARCHAR2(5 CHAR);
    V_USR VARCHAR2(30 CHAR) := 'REMVIP-5721'; -- USUARIOCREAR/USUARIOMODIFICAR
    
    TYPE T_TIPO_DATA IS TABLE OF NUMBER(25);
  	TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
		T_TIPO_DATA(6716148),
		T_TIPO_DATA(6722717),
		T_TIPO_DATA(6733272),
		T_TIPO_DATA(6736598),
		T_TIPO_DATA(5958963),
		T_TIPO_DATA(69578),
		T_TIPO_DATA(69579),
		T_TIPO_DATA(69718),
		T_TIPO_DATA(69719),
		T_TIPO_DATA(71425),
		T_TIPO_DATA(161638),
		T_TIPO_DATA(161639),
		T_TIPO_DATA(161640),
		T_TIPO_DATA(161641),
		T_TIPO_DATA(161973),
		T_TIPO_DATA(162294),
		T_TIPO_DATA(167738),
		T_TIPO_DATA(168038),
		T_TIPO_DATA(174841),
		T_TIPO_DATA(174843),
		T_TIPO_DATA(175072),
		T_TIPO_DATA(175209),
		T_TIPO_DATA(175210),
		T_TIPO_DATA(175212),
		T_TIPO_DATA(175213),
		T_TIPO_DATA(175434),
		T_TIPO_DATA(175578),
		T_TIPO_DATA(188546),
		T_TIPO_DATA(195143),
		T_TIPO_DATA(199142),
		T_TIPO_DATA(7020375),
		T_TIPO_DATA(7023378),
		T_TIPO_DATA(7023379),
		T_TIPO_DATA(7029994),
		T_TIPO_DATA(7094409),
		T_TIPO_DATA(7223968),
		T_TIPO_DATA(7226225),
		T_TIPO_DATA(7226277),
		T_TIPO_DATA(7226404),
		T_TIPO_DATA(7229261),
		T_TIPO_DATA(7293363),
		T_TIPO_DATA(7294175),
		T_TIPO_DATA(6983749),
		T_TIPO_DATA(6830122),
		T_TIPO_DATA(6830912),
		T_TIPO_DATA(7032117),
		T_TIPO_DATA(7068935),
		T_TIPO_DATA(7101627),
		T_TIPO_DATA(6813166),
		T_TIPO_DATA(6891414),
		T_TIPO_DATA(7055607),
		T_TIPO_DATA(6048087),
		T_TIPO_DATA(7097130),
		T_TIPO_DATA(5925378),
		T_TIPO_DATA(6048083),
		T_TIPO_DATA(6048084),
		T_TIPO_DATA(6048086),
		T_TIPO_DATA(6048088),
		T_TIPO_DATA(6048090),
		T_TIPO_DATA(6048091),
		T_TIPO_DATA(6057867),
		T_TIPO_DATA(6061337),
		T_TIPO_DATA(6813878),
		T_TIPO_DATA(6934356),
		T_TIPO_DATA(108773),
		T_TIPO_DATA(121126),
		T_TIPO_DATA(123493),
		T_TIPO_DATA(123862),
		T_TIPO_DATA(124867),
		T_TIPO_DATA(165828),
		T_TIPO_DATA(7036617),
		T_TIPO_DATA(7036618),
		T_TIPO_DATA(7037765),
		T_TIPO_DATA(7039446),
		T_TIPO_DATA(7042148),
		T_TIPO_DATA(7042149),
		T_TIPO_DATA(7042151),
		T_TIPO_DATA(7042211),
		T_TIPO_DATA(7044231),
		T_TIPO_DATA(7063129),
		T_TIPO_DATA(7063194),
		T_TIPO_DATA(7094360),
		T_TIPO_DATA(7293262),
		T_TIPO_DATA(7294181),
		T_TIPO_DATA(7089411),
		T_TIPO_DATA(7089412),
		T_TIPO_DATA(7089413),
		T_TIPO_DATA(7091254),
		T_TIPO_DATA(7098511),
		T_TIPO_DATA(7098552),
		T_TIPO_DATA(7292865),
		T_TIPO_DATA(7293192),
		T_TIPO_DATA(7293637),
		T_TIPO_DATA(7294134),
		T_TIPO_DATA(7294168),
		T_TIPO_DATA(7294169),
		T_TIPO_DATA(7294203),
		T_TIPO_DATA(7294284),
		T_TIPO_DATA(7294363),
		T_TIPO_DATA(7294378),
		T_TIPO_DATA(7294389),
		T_TIPO_DATA(7016379),
		T_TIPO_DATA(6967340),
		T_TIPO_DATA(6971950),
		T_TIPO_DATA(7099466),
		T_TIPO_DATA(7293638),
		T_TIPO_DATA(7294192),
		T_TIPO_DATA(7294360)
		); 
    V_TMP_TIPO_DATA T_TIPO_DATA;
    V_TIPO_ACTIVO NUMBER(16);
BEGIN	

		DBMS_OUTPUT.PUT_LINE('[INICIO]');
		FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
      		LOOP
	      
	        	V_TMP_TIPO_DATA := V_TIPO_DATA(I);
	        	V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1);
		        EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
	        	IF V_NUM_TABLAS > 0 THEN
			        V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
			        EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;
			        
					IF V_NUM_TABLAS > 0 THEN
						V_MSQL := 'SELECT NVL(DD_TIC_ID, 0) FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL 					
									WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
						EXECUTE IMMEDIATE V_MSQL INTO V_TIPO_INFORME;
						
						IF V_TIPO_INFORME = 1 THEN
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_LCO_LOCAL_COMERCIAL WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_APR_PLAZA_APARCAMIENTO WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							
						ELSIF V_TIPO_INFORME = 2 THEN
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_VIV_VIVIENDA WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_APR_PLAZA_APARCAMIENTO WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							
						ELSIF V_TIPO_INFORME = 3 THEN
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_VIV_VIVIENDA WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_LCO_LOCAL_COMERCIAL WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
							EXECUTE IMMEDIATE V_MSQL;
							
						ELSE 
							V_MSQL := 'SELECT NVL(DD_TPA_ID, 0) FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
							EXECUTE IMMEDIATE V_MSQL INTO V_TIPO_ACTIVO;
							IF V_TIPO_ACTIVO IS NULL THEN
								V_MSQL := 'SELECT NVL(DD_TPA_ID, 0) FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1);
								EXECUTE IMMEDIATE V_MSQL INTO V_TIPO_ACTIVO;						
							END IF;
							IF V_TIPO_ACTIVO = 2 THEN
								V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL SET USUARIOMODIFICAR = '''||V_USR||''', FECHAMODIFICAR = SYSDATE, DD_TIC_ID = (SELECT DD_TIC_ID FROM '||V_ESQUEMA||'.DD_TIC_TIPO_INFO_COMERCIAL WHERE DD_TIC_CODIGO = ''01'') WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_LCO_LOCAL_COMERCIAL WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_APR_PLAZA_APARCAMIENTO WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								
							ELSIF V_TIPO_ACTIVO = 3 THEN
								V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL SET USUARIOMODIFICAR = '''||V_USR||''', FECHAMODIFICAR = SYSDATE, DD_TIC_ID = (SELECT DD_TIC_ID FROM '||V_ESQUEMA||'.DD_TIC_TIPO_INFO_COMERCIAL WHERE DD_TIC_CODIGO = ''02'') WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_VIV_VIVIENDA WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_APR_PLAZA_APARCAMIENTO WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								
							ELSIF V_TIPO_ACTIVO = 7 THEN
								V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL SET USUARIOMODIFICAR = '''||V_USR||''', FECHAMODIFICAR = SYSDATE, DD_TIC_ID = (SELECT DD_TIC_ID FROM '||V_ESQUEMA||'.DD_TIC_TIPO_INFO_COMERCIAL WHERE DD_TIC_CODIGO = ''03'') WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_VIV_VIVIENDA WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_LCO_LOCAL_COMERCIAL WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								
							ELSE 
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_VIV_VIVIENDA WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_LCO_LOCAL_COMERCIAL WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
								V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.ACT_APR_PLAZA_APARCAMIENTO WHERE ICO_ID = (SELECT ICO_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL WHERE ACT_ID = (SELECT ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||'))';
								EXECUTE IMMEDIATE V_MSQL;
							END IF;					
						END IF;
					END IF;
				END IF;
	        END LOOP;
        DBMS_OUTPUT.PUT_LINE('[FIN]');
        
        COMMIT;
  
EXCEPTION
    WHEN OTHERS THEN
    err_num := SQLCODE;
    err_msg := SQLERRM;

    DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
    DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
    DBMS_OUTPUT.put_line(err_msg);
    DBMS_OUTPUT.put_line(V_MSQL);
    ROLLBACK;
    RAISE;          

END;

/

EXIT