--/*
--#########################################
--## AUTOR=Viorel Remus Ovidiu
--## FECHA_CREACION=20200221
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-6357
--## PRODUCTO=NO
--## 
--## Finalidad: 
--## 
--## INSTRUCCIONES:  
--## VERSIONES:
--## 		0.1 Versión inicial
--## 		0.2 HREOS-8191 Cambio relación con PROVEEDORES
--## 		0.3 HREOS-8147 Añadir LPAD hasta 5 posiciones en CODIGOS POSTALES
--## 		0.4 HREOS-8218 Corrección de nombres de campos en las interfaces de la migración Divarian
--## 		0.5 HREOS-8608 IKER ADOT Revision de campos divarian
--## 		0.6 Correcciones
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

	V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
	V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-6357';
	V_TABLA VARCHAR2(40 CHAR) := 'ACT_PRD_PROVEEDOR_DIRECCION';
	V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG2_PRD_PROVEEDOR_DIRECCION';
	V_SENTENCIA VARCHAR2(32000 CHAR);

BEGIN 

	--Inicio del proceso de volcado sobre ACT_PRD_PROVEEDOR_DIRECCION
	DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');

	V_SENTENCIA := ('
	INSERT INTO '||V_ESQUEMA||'.'||V_TABLA||' (
		PRD_ID,
		PVE_ID,
		DD_TDP_ID,
		DD_TVI_ID,
		PRD_NOMBRE,
		PRD_NUM,
		PRD_PTA,
		DD_UPO_ID,
		DD_PRV_ID,
		PRD_CP,
		PRD_TELEFONO,
		PRD_EMAIL,
		DD_LOC_ID,
		VERSION,
		USUARIOCREAR,
		FECHACREAR,
		BORRADO,
		PVE_COD_DIRECC_UVEM,
		--PRP_OBSERVACIONES, 							/*Añadido para Divarian*/
		PRD_LOCAL_ABIERTO_PUBLICO,					/*Añadido para Divarian*/
		PRD_ESCALERA,								/*Añadido para Divarian*/
		PRD_PLANTA,									/*Añadido para Divarian*/
		PRD_TELEFONO2								/*Añadido para Divarian*/
	)
	SELECT 
		'||V_ESQUEMA||'.S_'||V_TABLA||'.NEXTVAL 	PRD_ID,
		PVE.PVE_ID 									PVE_ID,
		TDP.DD_TDP_ID 								DD_TDP_ID,
		TVI.DD_TVI_ID 								DD_TVI_ID,
		MIG.PRD_NOMBRE 								PRD_NOMBRE,
		MIG.PRD_NUMERO 								PRD_NUM,
		MIG.PRD_PUERTA 								PRD_PTA,
		UPO.DD_UPO_ID 								DD_UPO_ID,
		PRV.DD_PRV_ID 								DD_PRV_ID,
		lpad(MIG.PRD_CODIGO_POSTAL,5,''0'') 		PRD_CP,
		MIG.PRD_TELEFONO 							PRD_TELEFONO,
		MIG.PRD_EMAIL 								PRD_EMAIL,
		LOC.DD_LOC_ID 								DD_LOC_ID,
		0 											VERSION,
		'''||V_USUARIO||''' 						USUARIOCREAR,
		SYSDATE 									FECHACREAR,
		0 											BORRADO,
		MIG.PVD_COD_DIRECCION 						PVE_COD_DIRECC_UVEM,
		--MIG.PRP_OBSERVACIONES 						PRD_OBSERVACIONES, 			/*Añadido para Divarian*/
		MIG.PRD_LOCAL_ABIERTO_PUBLICO 				PRD_LOCAL_ABIERTO_PUBLICO, 	/*Añadido para Divarian*/
		MIG.PRD_ESCALERA 							PRD_ESCALERA, 				/*Añadido para Divarian*/
		MIG.PRD_PLANTA 								PRD_PLANTA, 				/*Añadido para Divarian*/
		MIG.PRD_TELEFONO2 							PRD_TELEFONO2 				/*Añadido para Divarian*/
	FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
	INNER JOIN '||V_ESQUEMA||'.ACT_PVE_PROVEEDOR PVE ON PVE.PVE_COD_PRINEX = MIG.PVE_COD_ORIGEN /*(PVE.PVE_COD_PRINEX = MIG.PVE_COD_ORIGEN OR (MIG.PVE_COD_ORIGEN IS NULL AND PVE.PVE_COD_REM = MIG.PVE_REM_ID) AND PVE.PVE_FECHA_BAJA IS NULL)*/
	INNER JOIN '||V_ESQUEMA||'.DD_TDP_TIPO_DIR_PROVEEDOR TDP ON TDP.DD_TDP_CODIGO = MIG.PRD_COD_TIPO_DIRECCION AND TDP.BORRADO = 0
	INNER JOIN '||V_ESQUEMA_MASTER||'.DD_TVI_TIPO_VIA TVI ON TVI.DD_TVI_CODIGO = MIG.PRD_COD_TIPO_VIA AND TVI.BORRADO = 0
	LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_UPO_UNID_POBLACIONAL UPO  ON UPO.DD_UPO_CODIGO = TRIM(LEADING 0 FROM MIG.PRD_COD_UNIDADPOBLACIONAL) AND UPO.BORRADO = 0
	LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON PRV.DD_PRV_CODIGO = MIG.PRD_COD_PROVINCIA AND PRV.BORRADO = 0
	LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_LOC_LOCALIDAD LOC ON LOC.DD_LOC_CODIGO = MIG.PRD_COD_LOCALIDAD AND LOC.BORRADO = 0
	WHERE MIG.VALIDACION = 0 AND
	NOT EXISTS (
		SELECT 1 FROM '||V_ESQUEMA||'.'||V_TABLA||' AUX
		WHERE AUX.PVE_ID = PVE.PVE_ID AND
		AUX.PVE_COD_DIRECC_UVEM = MIG.PVD_COD_DIRECCION AND
		AUX.DD_TDP_ID = TDP.DD_TDP_ID
	)
	');

	--DBMS_OUTPUT.PUT_LINE(V_SENTENCIA);
	EXECUTE IMMEDIATE V_SENTENCIA;
	
      DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');
      
      COMMIT;
      
  V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''10''); END;';
  EXECUTE IMMEDIATE V_SENTENCIA;
      
EXCEPTION

      WHEN OTHERS THEN
            DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
            DBMS_OUTPUT.put_line('-----------------------------------------------------------');
            DBMS_OUTPUT.put_line(SQLERRM);
            ROLLBACK;
            RAISE;      
END;
/
EXIT;
