--/*
--##########################################
--## AUTOR=IVAN REPISO
--## FECHA_CREACION=20210224
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-9047
--## PRODUCTO=NO
--## 
--## Finalidad: Actualización 
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE
	V_MSQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
 	V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
 	V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-9047'; -- USUARIO CREAR/MODIFICAR
	V_COUNT NUMBER(16); -- Vble. para comprobar
	err_num NUMBER; -- Numero de errores
	err_msg VARCHAR2(2048); -- Mensaje de error
	
BEGIN
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');

	V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL T1 USING (
					SELECT DISTINCT ICO.ICO_ID, AUX.ICO_WEBCOM_ID FROM '||V_ESQUEMA||'.ACT_ICO_INFO_COMERCIAL ICO
					INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = ICO.ACT_ID
					INNER JOIN '||V_ESQUEMA||'.AUX_REMVIP_9047 AUX ON AUX.ACT_NUM_ACTIVO = ACT.ACT_NUM_ACTIVO 
					AND AUX.ACT_NUM_ACTIVO IN (SELECT ACT_NUM_ACTIVO FROM '||V_ESQUEMA||'.AUX_REMVIP_9047
												GROUP BY ACT_NUM_ACTIVO HAVING COUNT(*) = 1)
					WHERE ACT.BORRADO = 0 AND ICO.BORRADO = 0) T2
				ON (T1.ICO_ID = T2.ICO_ID)
				WHEN MATCHED THEN UPDATE SET
				ICO_WEBCOM_ID = T2.ICO_WEBCOM_ID,
				USUARIOMODIFICAR = '''||V_USUARIO||''',
				FECHAMODIFICAR = SYSDATE';
	EXECUTE IMMEDIATE V_MSQL;

	DBMS_OUTPUT.PUT_LINE('[INFO] MODIFICADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN ACT_ICO_INFO_COMERCIAL');

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('[FIN] ');
	
	EXCEPTION
	
	    WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
		DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------');
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
		DBMS_OUTPUT.PUT_LINE(V_MSQL);
		ROLLBACK;
		RAISE;
END;
/
EXIT;