--/*
--#########################################
--## AUTOR=GUILLEM REY
--## FECHA_CREACION=20210726
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-10212
--## PRODUCTO=NO
--## 
--## Finalidad: Aprovisionar la tabla 'TMP_GCO_GCH' con ECO_ID
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.   
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_ID NUMBER(16);
    V_TEXT_TABLA VARCHAR2(2400 CHAR) := 'TMP_GCO_GCH'; -- Vble. auxiliar para almacenar el nombre de la tabla de ref.
    V_INCIDENCIA VARCHAR2(25 CHAR) := 'REMVIP-10212';
    
BEGIN	
	
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');
      
    V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.TMP_GCO_GCH (ID, ECO_ID) 
    SELECT ROWNUM, ECO_ID FROM (
	SELECT DISTINCT 
    ECO.ECO_ID
		FROM REM01.ECO_EXPEDIENTE_COMERCIAL ECO
		INNER JOIN REM01.OFR_OFERTAS OFR ON OFR.OFR_ID = ECO.OFR_ID AND OFR.BORRADO = 0
		INNER JOIN REM01.ACT_OFR AOF ON AOF.OFR_ID = OFR.OFR_ID
		INNER JOIN REM01.ACT_ACTIVO ACT ON ACT.ACT_ID = AOF.ACT_ID AND ACT.BORRADO = 0
		INNER JOIN REM01.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = ACT.DD_SCR_ID AND SCR.BORRADO = 0
		INNER JOIN REM01.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID AND TBJ.BORRADO = 0
		INNER JOIN REM01.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = TBJ.TBJ_ID AND TRA.BORRADO = 0
		LEFT JOIN REM01.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
		INNER JOIN REM01.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
		INNER JOIN REM01.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
		INNER JOIN REM01.TAP_TAREA_PROCEDIMIENTO TAP ON TAP.TAP_ID = TEX.TAP_ID AND TAP.BORRADO = 0
		WHERE ECO.BORRADO = 0 AND SCR.DD_SCR_CODIGO IN (''151'', ''152'') --divarian
		AND ECO.ECO_ID NOT IN (
		    SELECT DISTINCT 
		    ECO.ECO_ID
		    FROM REM01.ECO_EXPEDIENTE_COMERCIAL ECO
		    INNER JOIN REM01.GCH_GESTOR_ECO_HISTORICO GCH ON GCH.ECO_ID = ECO.ECO_ID
		    INNER JOIN REM01.GEH_GESTOR_ENTIDAD_HIST GEH ON GEH.GEH_ID = GCH.GEH_ID AND GEH.BORRADO = 0 AND GEH.GEH_FECHA_HASTA IS NULL
		    INNER JOIN REMMASTER.DD_TGE_TIPO_GESTOR TGE ON GEH.DD_TGE_ID = TGE.DD_TGE_ID AND TGE.BORRADO = 0
		    INNER JOIN REM01.TGP_TIPO_GESTOR_PROPIEDAD TGP ON TGP.DD_TGE_ID = TGE.DD_TGE_ID AND TGP.TGP_CLAVE = ''DES_VALIDOS'' AND TGP.BORRADO = 0
		    INNER JOIN REMMASTER.DD_TDE_TIPO_DESPACHO TDE ON TDE.DD_TDE_CODIGO = TGP.TGP_VALOR AND TDE.BORRADO = 0
		    INNER JOIN REM01.DES_DESPACHO_EXTERNO DES ON DES.DD_TDE_ID = TDE.DD_TDE_ID AND DES.BORRADO = 0
		    INNER JOIN REM01.OFR_OFERTAS OFR ON OFR.OFR_ID = ECO.OFR_ID AND OFR.BORRADO = 0
		    INNER JOIN REM01.ACT_OFR AOF ON AOF.OFR_ID = OFR.OFR_ID
		    INNER JOIN REM01.ACT_ACTIVO ACT ON ACT.ACT_ID = AOF.ACT_ID AND ACT.BORRADO = 0
		    INNER JOIN REM01.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = ACT.DD_SCR_ID AND SCR.BORRADO = 0
		    INNER JOIN REM01.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID AND TBJ.BORRADO = 0
		    INNER JOIN REM01.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = TBJ.TBJ_ID AND TRA.BORRADO = 0
		    INNER JOIN REM01.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
		    INNER JOIN REM01.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
		    INNER JOIN REM01.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
		    INNER JOIN REM01.TAP_TAREA_PROCEDIMIENTO TAP ON TAP.TAP_ID = TEX.TAP_ID AND TAP.BORRADO = 0
		    WHERE ECO.BORRADO = 0 AND SCR.DD_SCR_CODIGO IN (''151'', ''152'') --divarian
		    AND TGE.DD_TGE_CODIGO = ''GCV''
		)
	)';

    EXECUTE IMMEDIATE V_MSQL;

    COMMIT;
   

EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;

          DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------'); 
          DBMS_OUTPUT.PUT_LINE(ERR_MSG);

          ROLLBACK;
          RAISE;          

END;

/

EXIT
