--/*
--#########################################
--## AUTOR=Viorel Remus Ovidiu
--## FECHA_CREACION=20191118
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-5781
--## PRODUCTO=NO
--## 
--## Finalidad: Cambiar usuario de tramite
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
TABLE_COUNT NUMBER(1,0) := 0;
V_MSQL VARCHAR2(4000 CHAR);
V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master

BEGIN			
			
	DBMS_OUTPUT.PUT_LINE('[INICIO]'); 

	V_MSQL :=  'MERGE INTO '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS T1 USING (
			WITH ACTIVO AS (
				SELECT ACT.ACT_ID, ACT_NUM_ACTIVO, OFR.OFR_NUM_OFERTA, ECO_FECHA_VENTA,ACT_VENTA_EXTERNA_FECHA, ECO_NUM_EXPEDIENTE, OFR.DD_EOF_ID, GEE.USU_ID 
				FROM   '||V_ESQUEMA||'.ACT_ACTIVO ACT
				LEFT JOIN '||V_ESQUEMA||'.ACT_OFR ACTOFR
				ON ACT.ACT_ID = ACTOFR.ACT_ID
				 JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
				ON ECO.OFR_ID = ACTOFR.OFR_ID
				LEFT JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR
				ON OFR.OFR_ID = ACTOFR.OFR_ID
				LEFT JOIN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO GCO ON GCO.ECO_ID = ECO.ECO_ID
				JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE ON GEE.GEE_ID = GCO.GEE_ID
				JOIN '||V_ESQUEMA_M||'.DD_TGE_TIPO_GESTOR TGE ON GEE.DD_TGE_ID = TGE.DD_TGE_ID
				WHERE   ACT.DD_CRA_ID IN (21,2) 
				AND TGE.DD_TGE_CODIGO IN (''GFORM'') 
				AND GCO.ECO_ID = ECO.ECO_ID
				GROUP BY ACT.ACT_ID,ACT_NUM_ACTIVO,ECO_FECHA_VENTA,ACT_VENTA_EXTERNA_FECHA,OFR.OFR_NUM_OFERTA,ECO_NUM_EXPEDIENTE, DD_EOF_ID, GEE.USU_ID)

				SELECT DISTINCT ECO_NUM_EXPEDIENTE,
				ACT.ACT_NUM_ACTIVO,OFR_NUM_OFERTA,
				TAR_TAREA, TRA.TRA_ID, 
				TAR.TAR_ID,
				ACT.USU_ID AS GESTOR_CORRECTO
				FROM ACTIVO ACT      
				  LEFT JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA
				  ON ACT.ACT_ID = TRA.ACT_ID
				LEFT JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC
				  ON TAC.TRA_ID = TRA.TRA_ID
				  LEFT JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR
				  ON TAR.TAR_ID = TAC.TAR_ID
				LEFT JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX  
				  ON TEX.TAR_ID = TAR.TAR_ID
				LEFT JOIN '||V_ESQUEMA||'.TAP_TAREA_PROCEDIMIENTO TAP
				  ON TAP.TAP_ID = TEX.TAP_ID
				 LEFT JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = ACT.DD_EOF_ID
				  WHERE TRA.DD_TPO_ID = (SELECT DD_TPO_ID FROM '||V_ESQUEMA||'.DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = ''T013'' )   

				  AND TRUNC(TAR.TAR_FECHA_INI) = TO_DATE(''15/11/2019'',''DD/MM/YYYY'')

				  AND TAR.TAR_TAREA IN (''Resultado PBC'') 
				  AND EOF.DD_EOF_ID <> 2 
				  AND TAR.TAR_FECHA_FIN IS NULL
		) T2
			ON (T1.TAR_ID = T2.TAR_ID AND T1.TRA_ID = T2.TRA_ID)
		WHEN MATCHED THEN UPDATE
               		SET T1.USU_ID = T2.GESTOR_CORRECTO, 
                    	T1.USUARIOMODIFICAR = ''REMVIP-5781'', 
                    	T1.FECHAMODIFICAR = SYSDATE';

	DBMS_OUTPUT.PUT_LINE(V_MSQL);  

	EXECUTE IMMEDIATE V_MSQL;

	DBMS_OUTPUT.PUT_LINE('	[INFO] '||SQL%ROWCOUNT||' expedientes actualizados.');  

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;

/

EXIT
