--/*
--#########################################
--## AUTOR=Juan Bautista Alfonso
--## FECHA_CREACION=20210527
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-9856
--## PRODUCTO=NO
--## 
--## Finalidad: Actualizar tabla 'GLD_GASTOS_LINEA_DETALLE'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
	
    err_num NUMBER; -- Numero de error.
    err_msg VARCHAR2(2048); -- Mensaje de error.
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas.
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas.
    V_USUARIOMODIFICAR VARCHAR(100 CHAR):= 'REMVIP-9856';
    V_SQL VARCHAR2(4000 CHAR);


BEGIN			
			

-----------------------------------------------------------------------------------------------------------------


	DBMS_OUTPUT.PUT_LINE('[INICIO] Actualiza ACT_ADN_ADJNOJUDICIAL - FECHA_POSESION');

/*
SELECT ACT.ACT_NUM_ACTIVO,ADN.ADN_ID,SPS.SPS_ID, ADN.ADN_FECHA_TITULO, ADN.FECHA_POSESION, SPS.SPS_FECHA_TOMA_POSESION, ESP_SPS.SPS_FECHA_TOMA_POSESION ESPARTA
FROM '||V_ESQUEMA||'.ACT_ADN_ADJNOJUDICIAL ADN
JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = ADN.ACT_ID AND ACT.BORRADO = 0
JOIN '||V_ESQUEMA||'.ACT_SPS_SIT_POSESORIA SPS ON SPS.ACT_ID = ACT.ACT_ID AND SPS.BORRADO = 0
LEFT JOIN '||V_ESQUEMA||'.ESPARTA_ACT_SPS_SIT_POSESORIA ESP_SPS ON ESP_SPS.ACT_ID = ACT.ACT_ID AND ESP_SPS.BORRADO = 0
JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID AND CRA.BORRADO = 0
WHERE CRA.DD_CRA_CODIGO = '02' AND ADN.ADN_FECHA_TITULO IS NOT NULL AND ADN.FECHA_POSESION IS NULL /*AND SPS.SPS_FECHA_TOMA_POSESION IS NULL*/





    --ADNOJUDICIAL
										
	 V_SQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_ADN_ADJNOJUDICIAL T1
		        USING (
					SELECT ACT.ACT_NUM_ACTIVO,ADN.ADN_ID,SPS.SPS_ID, ADN.ADN_FECHA_TITULO, ADN.FECHA_POSESION, SPS.SPS_FECHA_TOMA_POSESION, ESP_SPS.SPS_FECHA_TOMA_POSESION ESPARTA
                    FROM '||V_ESQUEMA||'.ACT_ADN_ADJNOJUDICIAL ADN
                    JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = ADN.ACT_ID AND ACT.BORRADO = 0
                    JOIN '||V_ESQUEMA||'.ACT_SPS_SIT_POSESORIA SPS ON SPS.ACT_ID = ACT.ACT_ID AND SPS.BORRADO = 0
                    LEFT JOIN '||V_ESQUEMA||'.ESPARTA_ACT_SPS_SIT_POSESORIA ESP_SPS ON ESP_SPS.ACT_ID = ACT.ACT_ID AND ESP_SPS.BORRADO = 0
                    JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID AND CRA.BORRADO = 0
                    WHERE CRA.DD_CRA_CODIGO = ''02'' AND ADN.ADN_FECHA_TITULO IS NOT NULL AND ADN.FECHA_POSESION IS NULL 
                
        		) T2 
        	  ON (T1.ADN_ID = T2.ADN_ID )
				WHEN MATCHED THEN UPDATE SET 
                    T1.FECHA_POSESION = T2.ADN_FECHA_TITULO,
	    			T1.USUARIOMODIFICAR = ''' || V_USUARIOMODIFICAR || ''',
	    			T1.FECHAMODIFICAR   = SYSDATE';

	EXECUTE IMMEDIATE V_SQL;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] Actualizados '||SQL%ROWCOUNT||' registros en ACT_ADN_ADNOJUDICIAL');  

--SPS
	DBMS_OUTPUT.PUT_LINE('[INICIO] Actualiza ACT_SPS_SIT_POSESORIA - FECHA_POSESION');

		 V_SQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_SPS_SIT_POSESORIA T1
		        USING (
					SELECT ACT.ACT_NUM_ACTIVO,ADN.ADN_ID,SPS.SPS_ID, ADN.ADN_FECHA_TITULO, ADN.FECHA_POSESION, SPS.SPS_FECHA_TOMA_POSESION, ESP_SPS.SPS_FECHA_TOMA_POSESION ESPARTA
                    FROM '||V_ESQUEMA||'.ACT_ADN_ADJNOJUDICIAL ADN
                    JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = ADN.ACT_ID AND ACT.BORRADO = 0
                    JOIN '||V_ESQUEMA||'.ACT_SPS_SIT_POSESORIA SPS ON SPS.ACT_ID = ACT.ACT_ID AND SPS.BORRADO = 0
                    LEFT JOIN '||V_ESQUEMA||'.ESPARTA_ACT_SPS_SIT_POSESORIA ESP_SPS ON ESP_SPS.ACT_ID = ACT.ACT_ID AND ESP_SPS.BORRADO = 0
                    JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID AND CRA.BORRADO = 0
                    WHERE CRA.DD_CRA_CODIGO = ''02'' AND ADN.ADN_FECHA_TITULO IS NOT NULL AND SPS.SPS_FECHA_TOMA_POSESION IS NULL
                
        		) T2 
        	  ON (T1.SPS_ID = T2.SPS_ID )
				WHEN MATCHED THEN UPDATE SET 
                    T1.SPS_FECHA_TOMA_POSESION = T2.ADN_FECHA_TITULO,
	    			T1.USUARIOMODIFICAR = ''' || V_USUARIOMODIFICAR || ''',
	    			T1.FECHAMODIFICAR   = SYSDATE';

	EXECUTE IMMEDIATE V_SQL;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] Actualizados '||SQL%ROWCOUNT||' registros en ACT_SPS_SIT_POSESORIA');




-----------------------------------------------------------------------------------------------------------------


	COMMIT;

	DBMS_OUTPUT.PUT_LINE('[FIN]');
	

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/
EXIT
