--/*
--#########################################
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20210727
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.3
--## INCIDENCIA_LINK=HREOS-14680
--## PRODUCTO=NO
--##
--## Finalidad: Creación de tabla de migración
--##
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

TABLE_COUNT NUMBER(1,0) := 0;
V_ESQUEMA_1 VARCHAR2(20 CHAR) := 'REM01';
V_ESQUEMA_2 VARCHAR2(20 CHAR) := 'REM01'; --SE CREA UNA SEGUNDA VARIABLE DE ESQUEMA POR SI EN ALGÚN MOMENTO QUEREMOS CREAR LA TABLA EN UN ESQUEMA DIFERENTE AL DEL USUARIO QUE LA ACCEDE O VICEVERSA
V_TABLA VARCHAR2(40 CHAR) := 'MIG2_ECO_EXPEDIENTE_CAIXA';

BEGIN

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA||'' AND OWNER= ''||V_ESQUEMA_1||'';

IF TABLE_COUNT > 0 THEN

    DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
    EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'';
    
END IF;

EXECUTE IMMEDIATE '
CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'
(
	ECO_NUM_EXPEDIENTE	NUMBER(16,0)	,
	OFR_ID	NUMBER(16,0)	,
	DD_EEC_ID	NUMBER(16,2)	,
	ECO_FECHA_ALTA	DATE	,
	ECO_FECHA_SANCION	DATE	,
	ECO_FECHA_ANULACION	DATE	,
	ECO_FECHA_CONT_PROPIETARIO	DATE	,
	ECO_PETICIONARIO_ANULACION	VARCHAR2(256 CHAR)	,
	ECO_IMP_DEV_ENTREGAS	NUMBER(16,2)	,
	ECO_FECHA_DEV_ENTREGAS	DATE	,
	ECO_FECHA_INICIO_ALQUILER	DATE	,
	ECO_FECHA_FIN_ALQUILER	DATE	,
	ECO_IMPORTE_RENTA_ALQUILER	NUMBER(16,2)	,
	ECO_NUMERO_CONTRATO_ALQUILER	VARCHAR2(50 CHAR)	,
	ECO_PLAZO_OPCION_COMPRA	DATE	,
	ECO_PRIMA_OPCION_COMPRA	NUMBER(16,2)	,
	ECO_PRECIO_OPCION_COMPRA	NUMBER(16,2)	,
	ECO_CONDICIONES_OPCION_COMPRA	VARCHAR2(256 CHAR)	,
	ECO_CONFLICTO_INTERESES	NUMBER(1,0)	,
	ECO_RIESGO_REPUTACIONAL	NUMBER(1,0)	,
	DD_COS_ID	NUMBER(16,0)	,
	DD_COS_ID_PROPUESTO	NUMBER(16,0)	,
	ECO_FECHA_SANCION_COMITE	DATE	,
	ECO_ESTADO_PBC	NUMBER(1,0)	,
	ECO_FECHA_VENTA	DATE	,
	DD_MAN_ID	NUMBER(16,0)	,
	ECO_BLOQUEADO	NUMBER(1,0)	,
	DD_MDE_ID	NUMBER(16,0)	,
	ECO_MDE_OTROS	VARCHAR2(250 CHAR)	,
	DD_EEC_ID_ANT	NUMBER(16,2)	,
	TBJ_ID	NUMBER(16,0)	,
	DD_COS_ID_SUPERIOR	NUMBER(16,0)	,
	ECO_NECESITA_FINANCIACION	NUMBER(1,0)	,
	ECO_ASISTENCIA_PBC	NUMBER(1,0)	,
	ECO_ASISTENCIA_PBC_DESCRIPCION	VARCHAR2(450 CHAR)	,
	DD_TAL_ID	NUMBER(16,0)	,
	ECO_TUBO_INQUILINO_DONE	NUMBER(1,0)	,
	DD_MAO_ID	NUMBER(16,0)	,
	DD_MRE_ID	NUMBER(16,0)	,
	DD_COA_ID	NUMBER(16,0)	,
	ECO_DOCUMENTACION_OK	NUMBER(1,0)	,
	ECO_FECHA_VALIDACION	DATE	,
	ECO_FECHA_POSICIONAMIENTO_PREVISTA	DATE	,
	ECO_CORRECW	NUMBER(4,0)	,
	ECO_COMOA3	NUMBER(4,0)	,
	ECO_DEVOL_AUTO_NUMBER	NUMBER(1,0)	,
	ECO_FECHA_RECOMENDACION_CES	DATE	,
	ECO_ESTADO_PBC_R	NUMBER(1,0)	,
	ECO_FECHA_ENVIO_ADVISORY_NOTE	DATE	,
	ECO_FECHA_CONT_VENTA	DATE	,
	ECO_FECHA_GRAB_VENTA	DATE	,
	DD_EEB_ID	NUMBER(16,0)	,
	ECO_ESTADO_ARRAS	NUMBER(1,0)	,
	ECO_ESTADO_CN	NUMBER(1,0)	,
	ECO_FECHA_RESER_DEPOS	DATE	,
	ECO_FECHA_CONTAB	DATE	,
	ECO_FECHA_FIRMA_CONT	DATE	,
	ECO_NUM_PROTOCOLO	VARCHAR2(50 CHAR)	
)
'
;

DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA||' CREADA');  

IF V_ESQUEMA_2 != V_ESQUEMA_1 THEN

	EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA||'" TO "'||V_ESQUEMA_2||'" WITH GRANT OPTION';
	DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' OTORGADOS A '||V_ESQUEMA_2||''); 

END IF;

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

EXIT;
