--/*
--#########################################
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20210727
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-14680
--## PRODUCTO=NO
--##
--## Finalidad: Creación de tabla de migración
--##
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

	TABLE_COUNT 		NUMBER(1,0) 		:= 0;
	V_ESQUEMA_1 		VARCHAR2(20 CHAR) 	:= 'REM01';
	V_ESQUEMA_MASTER 	VARCHAR2(20 CHAR) 	:= 'REMMASTER';
	V_TABLA 			VARCHAR2(40 CHAR) 	:= 'MIG2_OFA_OFERTAS_ACTIVO_CAIXA';

BEGIN

	SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA||'' AND OWNER= ''||V_ESQUEMA_1||'';

	IF TABLE_COUNT > 0 THEN

		DBMS_OUTPUT.PUT_LINE('[INFO] TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' YA EXISTENTE. SE PROCEDE A BORRAR Y CREAR DE NUEVO.');
		EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'';
		
	END IF;
	--v0.2
	EXECUTE IMMEDIATE '
	CREATE TABLE '||V_ESQUEMA_1||'.'||V_TABLA||'
	(
			ACT_ID	NUMBER(16,0),
			OFR_ID	NUMBER(16,0),
			ACT_OFR_IMPORTE	NUMBER(16,2),
			VERSION	NUMBER(38,0),
			OFR_ACT_PORCEN_PARTICIPACION	NUMBER(5,2) 
	)'
	;

	DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.'||V_TABLA||' CREADA');  

	IF V_ESQUEMA_MASTER != V_ESQUEMA_1 THEN

		EXECUTE IMMEDIATE 'GRANT ALL ON "'||V_ESQUEMA_1||'"."'||V_TABLA||'" TO "'||V_ESQUEMA_MASTER||'" WITH GRANT OPTION';
		DBMS_OUTPUT.PUT_LINE('[INFO] PERMISOS SOBRE LA TABLA '||V_ESQUEMA_1||'.'||V_TABLA||' OTORGADOS A '||V_ESQUEMA_MASTER||''); 

	END IF;

	EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_OFA_OFERTAS_ACTIVO.OFA_COD_OFERTA IS ''Código identificador único de la Oferta''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_OFA_OFERTAS_ACTIVO.OFA_ACT_NUMERO_ACTIVO IS ''Código identificador único del activo''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_OFA_OFERTAS_ACTIVO.OFA_PORCENTAJE_PARTICIPACION IS ''Porcentaje del Grado de Participación en la Oferta.''';
	EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || V_ESQUEMA_1 || '.MIG2_OFA_OFERTAS_ACTIVO.OFA_IMPORTE_PARTICIPACION IS ''Importe de dicha Participación''';

	EXCEPTION

		WHEN OTHERS THEN
			DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
			DBMS_OUTPUT.put_line('-----------------------------------------------------------');
			DBMS_OUTPUT.put_line(SQLERRM);
			ROLLBACK;
			RAISE;
END;
/
EXIT;
