OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_2622
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	NUM_ACTIVO_HAYA					NULLIF(NUM_ACTIVO_HAYA=BLANKS)				"TRIM(:NUM_ACTIVO_HAYA)",
	FC_PRIMERA_PUBLI				NULLIF(FC_PRIMERA_PUBLI=BLANKS)				"TRIM(:FC_PRIMERA_PUBLI)",
	FC_ULTIMA_PUBLI					NULLIF(FC_ULTIMA_PUBLI=BLANKS)				"TRIM(:FC_ULTIMA_PUBLI)"
	
)
