
drop sequence S_CRC_CICLO_RECOBRO_CNT;

drop table CRC_CICLO_RECOBRO_CNT;

drop sequence S_CRP_CICLO_RECOBRO_PER;

drop table CRP_CICLO_RECOBRO_PER;

ALTER TABLE CRE_CICLO_RECOBRO_EXP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRE_CICLO_RECOBRO_EXP CASCADE CONSTRAINTS;

ALTER TABLE EXR_EXPEDIENTE_RECOBRO
 DROP PRIMARY KEY CASCADE;

 DROP TABLE EXR_EXPEDIENTE_RECOBRO CASCADE CONSTRAINTS;

drop sequence S_CRE_CICLO_RECOBRO_EXP;

alter table exp_expedientes drop column DD_TPX_ID;

drop sequence s_DD_TPX_TIPO_EXPEDIENTE;

drop table DD_TPX_TIPO_EXPEDIENTE;

drop sequence S_CRT_CICLO_RECOBRO_TAREA_NOTI;

drop table CRT_CICLO_RECOBRO_TAREA_NOTI;
