set verify off;

define MASTER_SCHEMA = &Introduce_el_master_schema;

CREATE TABLE GEE_GESTOR_ENTIDAD
(
  GEE_ID            NUMBER(16),
  USU_ID            NUMBER(16),
  DD_TGE_ID         NUMBER(16),
  VERSION           INTEGER                     DEFAULT 0,
  USUARIOCREAR      VARCHAR2(10 BYTE),
  FECHACREAR        DATE,
  USUARIOMODIFICAR  VARCHAR2(10 BYTE),
  FECHAMODIFICAR    DATE,
  USUARIOBORRAR     VARCHAR2(10 BYTE),
  FECHABORRAR       DATE,
  BORRADO           NUMBER(1)                   DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX GEE_GESTOR_ENTIDAD_PK ON GEE_GESTOR_ENTIDAD
(GEE_ID);


ALTER TABLE GEE_GESTOR_ENTIDAD ADD (
  CONSTRAINT GEE_GESTOR_ENTIDAD_PK
 PRIMARY KEY
 (GEE_ID));

ALTER TABLE GEE_GESTOR_ENTIDAD ADD (
  CONSTRAINT GEE_USU_FK 
 FOREIGN KEY (USU_ID) 
 REFERENCES &MASTER_SCHEMA..USU_USUARIOS (USU_ID),
  CONSTRAINT GEE_TGE_FK
 FOREIGN KEY (DD_TGE_ID) 
 REFERENCES &MASTER_SCHEMA..DD_TGE_TIPO_GESTOR (DD_TGE_ID));


 
CREATE TABLE GAA_GESTOR_ADD_ASUNTO
(
  GEE_ID  NUMBER(16),
  ASU_ID  NUMBER(16)
);


CREATE UNIQUE INDEX GAA_GESTOR_ADD_ASUNTO_PK ON GAA_GESTOR_ADD_ASUNTO
(GEE_ID);


ALTER TABLE GAA_GESTOR_ADD_ASUNTO ADD (
  CONSTRAINT GAA_GESTOR_ADD_ASUNTO_PK
 PRIMARY KEY
 (GEE_ID));

ALTER TABLE GAA_GESTOR_ADD_ASUNTO ADD (
 CONSTRAINT GAA_GEE_FK
 FOREIGN KEY (GEE_ID) 
 REFERENCES GEE_GESTOR_ENTIDAD (GEE_ID),
  CONSTRAINT GAA_ASU_FK 
 FOREIGN KEY (ASU_ID) 
 REFERENCES ASU_ASUNTOS (ASU_ID));

 
CREATE TABLE GAE_GESTOR_ADD_EXPEDIENTE
(
  GEE_ID  NUMBER(16),
  EXP_ID  NUMBER(16)
);


CREATE UNIQUE INDEX GAE_GESTOR_ADD_EXPEDIENTE_PK ON GAE_GESTOR_ADD_EXPEDIENTE
(GEE_ID);


ALTER TABLE GAE_GESTOR_ADD_EXPEDIENTE ADD (
  CONSTRAINT GAE_GESTOR_ADD_EXPEDIENTE_PK
 PRIMARY KEY
 (GEE_ID));

ALTER TABLE GAE_GESTOR_ADD_EXPEDIENTE ADD (
  CONSTRAINT GAE_GEE_FK 
 FOREIGN KEY (GEE_ID) 
 REFERENCES GEE_GESTOR_ENTIDAD (GEE_ID),
  CONSTRAINT GAE_EXP_FK
 FOREIGN KEY (EXP_ID) 
 REFERENCES EXP_EXPEDIENTES (EXP_ID));

CREATE TABLE GEH_GESTOR_ENTIDAD_HIST
(
  GEH_ID            NUMBER(16),
  USU_ID            NUMBER(16),
  DD_TGE_ID         NUMBER(16),
  GEH_FECHA_DESDE   DATE,
  GEH_FECHA_HASTA   DATE,
  VERSION           INTEGER                     DEFAULT 0,
  USUARIOCREAR      VARCHAR2(10 BYTE)           NOT NULL,
  FECHACREAR        DATE                        NOT NULL,
  USUARIOMODIFICAR  VARCHAR2(10 BYTE),
  FECHAMODIFICAR    DATE,
  USUARIOBORRAR     VARCHAR2(10 BYTE),
  FECHABORRAR       DATE,
  BORRADO           NUMBER(1)                   DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX GEH_GESTOR_ENTIDAD_HISTPK ON GEH_GESTOR_ENTIDAD_HIST
(GEH_ID);


ALTER TABLE GEH_GESTOR_ENTIDAD_HIST ADD (
  CONSTRAINT GEH_GESTOR_ENTIDAD_HISTPK
 PRIMARY KEY
 (GEH_ID));

ALTER TABLE GEH_GESTOR_ENTIDAD_HIST ADD (
  CONSTRAINT GEH_TGE_FK
 FOREIGN KEY (DD_TGE_ID) 
 REFERENCES &MASTER_SCHEMA..DD_TGE_TIPO_GESTOR (DD_TGE_ID));


CREATE TABLE GEH_GESTOR_EXPEDIENTE_HIST
(
  GEH_ID  NUMBER(16),
  EXP_ID  NUMBER(16)
);


CREATE UNIQUE INDEX GEH_GESTOR_EXPEDIENTE_HISTO_PK ON GEH_GESTOR_EXPEDIENTE_HIST
(GEH_ID);


ALTER TABLE GEH_GESTOR_EXPEDIENTE_HIST ADD (
  CONSTRAINT GEH_GESTOR_EXPEDIENTE_HISTO_PK
 PRIMARY KEY
 (GEH_ID));

ALTER TABLE GEH_GESTOR_EXPEDIENTE_HIST ADD (
  CONSTRAINT GEH_GEH_FK 
 FOREIGN KEY (GEH_ID) 
 REFERENCES GEH_GESTOR_ENTIDAD_HIST (GEH_ID),
  CONSTRAINT GEH_EXP_FK
 FOREIGN KEY (EXP_ID) 
 REFERENCES EXP_EXPEDIENTES (EXP_ID));


CREATE TABLE GAH_GESTOR_ASUNTO_HIST
(
  GEH_ID  NUMBER(16),
  ASU_ID  NUMBER(16)
);


CREATE UNIQUE INDEX GAH_GESTOR_ASUNTO_HIST_PK ON GAH_GESTOR_ASUNTO_HIST
(GEH_ID);


ALTER TABLE GAH_GESTOR_ASUNTO_HIST ADD (
  CONSTRAINT GAH_GESTOR_ASUNTO_HIST_PK
 PRIMARY KEY
 (GEH_ID));

ALTER TABLE GAH_GESTOR_ASUNTO_HIST ADD (
  CONSTRAINT GAH_GEH_FK
 FOREIGN KEY (GEH_ID) 
 REFERENCES GEH_GESTOR_ENTIDAD_HIST (GEH_ID),
  CONSTRAINT GAH_ASU_FK 
 FOREIGN KEY (ASU_ID) 
 REFERENCES ASU_ASUNTOS (ASU_ID));

