
set verify off;

define MASTER_SCHEMA = &Introduce_el_master_schema;


CREATE TABLE DD_TII_TIPO_INCIDENCIA
(
  DD_TII_ID                 NUMBER(16),
  DD_TII_CODIGO             NUMBER(16),
  DD_TII_DESCRIPCION        VARCHAR2(100 BYTE),
  DD_TII_DESCRIPCION_LARGA  VARCHAR2(200 BYTE),
  VERSION            INTEGER                    DEFAULT 0                     NOT NULL,
  FECHACREAR         DATE                       NOT NULL,
  USUARIOCREAR       VARCHAR2(10 BYTE)          NOT NULL,
  FECHAMODIFICAR     DATE,
  USUARIOMODIFICAR   VARCHAR2(10 BYTE),
  FECHABORRAR        DATE,
  USUARIOBORRAR      VARCHAR2(10 BYTE),
  BORRADO            NUMBER(1)                  DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX DD_TII_TIPO_INCIDENCIA_PK ON DD_TII_TIPO_INCIDENCIA
(DD_TII_ID);


ALTER TABLE DD_TII_TIPO_INCIDENCIA ADD (
  CONSTRAINT DD_TII_TIPO_INCIDENCIA_PK
 PRIMARY KEY
 (DD_TII_ID));



Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (1, 1, 'Inconformidad de deuda', 'Inconformidad de deuda', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (2, 2, 'Fallecimiento', 'Fallecimiento', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (3, 3, 'Concurso de acreedores', 'Concurso de acreedores', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (4, 4, 'Aplicación errónea', 'Aplicación errónea', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (5, 5, 'Amenaza denuncia', 'Amenaza denuncia', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (6, 6, 'Fraudes', 'Fraudes', 0, sysdate, 'BADR-478', 0);
Insert into DD_TII_TIPO_INCIDENCIA
   (DD_TII_ID, DD_TII_CODIGO, DD_TII_DESCRIPCION, DD_TII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (7, 7, 'Relevación de garantías', 'Relevación de garantías', 0, sysdate, 'BADR-478', 0);
COMMIT;


CREATE TABLE DD_SII_SITUACION_EXPEDIENTE
(
  DD_SII_ID                 NUMBER(16),
  DD_SII_CODIGO             VARCHAR2(20 BYTE),
  DD_SII_DESCRIPCION        VARCHAR2(100 BYTE),
  DD_SII_DESCRIPCION_LARGA  VARCHAR2(200 BYTE),
  VERSION                   INTEGER             DEFAULT 0                     NOT NULL,
  FECHACREAR                DATE                NOT NULL,
  USUARIOCREAR              VARCHAR2(10 BYTE)   NOT NULL,
  FECHAMODIFICAR            DATE,
  USUARIOMODIFICAR          VARCHAR2(10 BYTE),
  FECHABORRAR               DATE,
  USUARIOBORRAR             VARCHAR2(1 BYTE),
  BORRADO                   NUMBER(1)           DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX DD_SII_SITUACION_EXPEDIENTE_PK ON DD_SII_SITUACION_EXPEDIENTE
(DD_SII_ID);


ALTER TABLE DD_SII_SITUACION_EXPEDIENTE ADD (
  CONSTRAINT DD_SII_SITUACION_EXPEDIENTE_PK
 PRIMARY KEY
 (DD_SII_ID));


 
 
Insert into DD_SII_SITUACION_EXPEDIENTE
   (DD_SII_ID, DD_SII_CODIGO, DD_SII_DESCRIPCION, DD_SII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (2, '2', 'Incorrecto', 'Incorrecto', 0, sysdate, 'BADR-478', 0);
Insert into DD_SII_SITUACION_EXPEDIENTE
   (DD_SII_ID, DD_SII_CODIGO, DD_SII_DESCRIPCION, DD_SII_DESCRIPCION_LARGA, VERSION, FECHACREAR, USUARIOCREAR, BORRADO)
 Values
   (1, '1', 'Correcto', 'Correcto', 0, sysdate, 'BADR-478', 0);

commit;

CREATE TABLE IEX_INCIDENCIA_EXPEDIENTE
(
  IEX_ID             NUMBER(16),
  PER_ID             NUMBER(16),
  CNT_ID             NUMBER(16),
  DD_TII_ID          NUMBER(16),
  DD_SII_ID          NUMBER(16),
  USU_ID             NUMBER(16),
  DES_ID             NUMBER(16),
  EXP_ID             NUMBER(16),
  IEX_OBSERVACIONES  VARCHAR2(2000),
  VERSION            INTEGER                    DEFAULT 0                     NOT NULL,
  FECHACREAR         DATE                       NOT NULL,
  USUARIOCREAR       VARCHAR2(10 BYTE)          NOT NULL,
  FECHAMODIFICAR     DATE,
  USUARIOMODIFICAR   VARCHAR2(10 BYTE),
  FECHABORRAR        DATE,
  USUARIOBORRAR      VARCHAR2(10 BYTE),
  BORRADO            NUMBER(1)                  DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX IEX_INCIDENCIA_EXPEDIENTE_PK ON IEX_INCIDENCIA_EXPEDIENTE
(IEX_ID);


ALTER TABLE IEX_INCIDENCIA_EXPEDIENTE ADD (
  CONSTRAINT IEX_INCIDENCIA_EXPEDIENTE_PK
 PRIMARY KEY
 (IEX_ID));

ALTER TABLE IEX_INCIDENCIA_EXPEDIENTE ADD (
  CONSTRAINT IEX_PER_FK 
 FOREIGN KEY (PER_ID) 
 REFERENCES PER_PERSONAS (PER_ID),
  FOREIGN KEY (CNT_ID) 
 REFERENCES CNT_CONTRATOS (CNT_ID),
  CONSTRAINT IEX_TII_FK 
 FOREIGN KEY (DD_TII_ID) 
 REFERENCES DD_TII_TIPO_INCIDENCIA (DD_TII_ID),
  CONSTRAINT IEX_SII_FK 
 FOREIGN KEY (DD_SII_ID) 
 REFERENCES DD_SII_SITUACION_EXPEDIENTE (DD_SII_ID),
  CONSTRAINT IEX_USU_FK 
 FOREIGN KEY (USU_ID) 
 REFERENCES &MASTER_SCHEMA..USU_USUARIOS (USU_ID),
  CONSTRAINT IEX_DES_FK 
 FOREIGN KEY (DES_ID) 
 REFERENCES DES_DESPACHO_EXTERNO (DES_ID));

