package es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_ACTIVOS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MAESTROACTIVOS", targetNamespace = "http://alamo.haya.es/IntegracionSOA/schemas", wsdlLocation = "http://10.10.25.196:8080/WSMaestroActivos/wsdl/ws.wsdl")
public class MAESTROACTIVOS
    extends Service
{

    private final static URL MAESTROACTIVOS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_ACTIVOS.MAESTROACTIVOS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_ACTIVOS.MAESTROACTIVOS.class.getResource(".");
            url = new URL(baseUrl, "http://10.10.25.196:8080/WSMaestroActivos/wsdl/ws.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.25.196:8080/WSMaestroActivos/wsdl/ws.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MAESTROACTIVOS_WSDL_LOCATION = url;
    }

    public MAESTROACTIVOS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MAESTROACTIVOS() {
        super(MAESTROACTIVOS_WSDL_LOCATION, new QName("http://alamo.haya.es/IntegracionSOA/schemas", "MAESTROACTIVOS"));
    }

    /**
     * 
     * @return
     *     returns SMGESTIONDOCUMENTALType
     */
    @WebEndpoint(name = "MAESTROACTIVOSPort")
    public MAESTROACTIVOSType getSMGESTIONDOCUMENTALPort() {
        return super.getPort(new QName("http://alamo.haya.es/IntegracionSOA/schemas", "MAESTROACTIVOSPort"), MAESTROACTIVOSType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMGESTIONDOCUMENTALType
     */
    @WebEndpoint(name = "MAESTROACTIVOSPort")
    public MAESTROACTIVOSType getSMGESTIONDOCUMENTALPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://alamo.haya.es/IntegracionSOA/schemas", "MAESTROACTIVOSPort"), MAESTROACTIVOSType.class, features);
    }

}
