CREATE TABLE TMP_REC_EXP_REPARTO_AGENCIAS_B AS SELECT * FROM TMP_REC_EXP_REPARTO_AGENCIAS;

SELECT DISTINCT * FROM (
  SELECT EXP_ID, RCF_AGE_ID, RCF_SCA_ID, ARQ_ID_NEW FROM TMP_REC_EXP_REARQUETIPADO
  UNION
  SELECT EXP_ID, RCF_AGE_ID, RCF_SCA_ID, ARQ_ID_NEW FROM TMP_REC_EXP_ROTACION
);

SELECT * FROM TMP_REC_EXP_REPARTO_AGENCIAS;

DELETE FROM TMP_REC_EXP_ROTACION;
COMMIT;

SELECT CRE.*
FROM CRE_CICLO_RECOBRO_EXP CRE
WHERE CRE.CRE_FECHA_BAJA IS NULL;

SELECT * FROM BANKMASTER.DD_MOB_MOTIVOS_BAJA;

SELECT * FROM RCF_SUA_SUBCARTERA_AGENCIAS WHERE RCF_SCA_ID = 4;
SELECT * FROM RCF_SCA_SUBCARTERA --WHERE RCF_SCA_ID = 2
;
SELECT * FROM RCF_ESC_ESQUEMA_CARTERAS WHERE RCF_ESC_ID = 3;

INSERT INTO TMP_REC_EXP_ROTACION VALUES
    (377867 --EXP_ID
    , 3 --AGE_ID
    , 2 -- SCA_ID
    , 2 -- ARQ_ID_NEW
);

INSERT INTO TMP_REC_EXP_REARQUETIPADO VALUES
    (377866 --EXP_ID
    , 4 --AGE_ID
    , 4 -- SCA_ID
    , 2 -- ARQ_ID_OLD
    , 3 -- ARQ_ID_NEW
);


MERGE INTO TMP_REC_EXP_REPARTO_AGENCIAS REP
USING 
(SELECT DISTINCT * FROM (
  SELECT EXP_ID, RCF_AGE_ID, RCF_SCA_ID, ARQ_ID_NEW FROM TMP_REC_EXP_REARQUETIPADO
  UNION
  SELECT EXP_ID, RCF_AGE_ID, RCF_SCA_ID, ARQ_ID_NEW FROM TMP_REC_EXP_ROTACION
)) R
ON (REP.EXP_ID = R.EXP_ID)
WHEN MATCHED THEN UPDATE
SET REP.RCF_SCA_ID = R.RCF_SCA_ID
  , REP.RCF_AGE_ID = R.RCF_AGE_ID
  , REP.CAR_ID = R.ARQ_ID_NEW;
  
COMMIT;