--/*
--#########################################
--## AUTOR=IVAN REPISO
--## FECHA_CREACION=20220720
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-12818
--## PRODUCTO=NO
--## 
--## Finalidad: Script que añade en CPR_OBSERV_COM_PROP.
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
	
	V_TABLA_TMP VARCHAR2(50 CHAR) := 'AUX_REMVIP_12818'; -- Variable para tabla 	
	V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01';-- '#ESQUEMA#'; -- Configuracion Esquema
	V_ESQUEMA_M VARCHAR2(25 CHAR):= 'REMMASTER';-- '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	ERR_NUM NUMBER;-- Numero de errores
	ERR_MSG VARCHAR2(2048);-- Mensaje de error
	V_MSQL VARCHAR2(4000 CHAR);--Variable para consultar la existencia de registros en la tabla
	V_NUM NUMBER(16); --Variable para comprobar si existen registros
	PL_OUTPUT VARCHAR2(32000 CHAR);
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-12818';
	V_NUM_ACTIVO VARCHAR2(32000 CHAR);
	

BEGIN

	DBMS_OUTPUT.PUT_LINE('[INICIO]'||CHR(10));		

	-- Comprobar que existen los activos
    V_MSQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.'||V_TABLA_TMP||' WHERE ACT_NUM_ACTIVO IN (SELECT ACT_NUM_ACTIVO FROM '||V_ESQUEMA||'.ACT_ACTIVO WHERE BORRADO = 0)';
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM;
	
	IF V_NUM > 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] Se han encontrado '||V_NUM||' registros en la tabla de activos');	

		DBMS_OUTPUT.PUT_LINE('[INFO] INFORMAMOS CPR_ID PARA PRECISION ACTIVOS Y CPR_OBSERV_COM_PROP_OLD PARA ALMACENAR INFO ANTERIOR');
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.'||V_TABLA_TMP||' T1 USING 
						(SELECT DISTINCT ACT.ACT_NUM_ACTIVO,CPR.CPR_ID, CPR.CPR_OBSERV_COM_PROP FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
						JOIN '||V_ESQUEMA||'.'||V_TABLA_TMP||' TMP ON TMP.ACT_NUM_ACTIVO = ACT.ACT_NUM_ACTIVO
						JOIN '||V_ESQUEMA||'.ACT_CPR_COM_PROPIETARIOS CPR ON CPR.CPR_ID = ACT.CPR_ID AND CPR.BORRADO = 0
						WHERE ACT.BORRADO = 0) T2
					ON (T1.ACT_NUM_ACTIVO = T2.ACT_NUM_ACTIVO)
					WHEN MATCHED THEN UPDATE SET
					T1.CPR_ID = T2.CPR_ID,
					T1.CPR_OBSERV_COM_PROP_OLD = T2.CPR_OBSERV_COM_PROP';
		EXECUTE IMMEDIATE V_MSQL;	

		DBMS_OUTPUT.PUT_LINE('[INFO] Se han ACTUALIZADO '||SQL%ROWCOUNT||' registros: '||V_TABLA_TMP||'');  
	END IF;
	 
	COMMIT;

	DBMS_OUTPUT.PUT_LINE('[INFO] VOLCAMOS CPR_OBSERV_COM_PROP DE AUXILIAR EN TABLA FINAL');
		
	V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_CPR_COM_PROPIETARIOS T1 USING
					(SELECT CPR_ID,CPR_OBSERV_COM_PROP FROM '||V_ESQUEMA||'.'||V_TABLA_TMP||'
                     WHERE CPR_ID IN (SELECT DISTINCT CPR_ID
                     FROM '||V_ESQUEMA||'.'||V_TABLA_TMP||' WHERE CPR_ID IS NOT NULL
                     GROUP BY CPR_ID HAVING COUNT(*)=1)) T2
				ON (T1.CPR_ID = T2.CPR_ID)
				WHEN MATCHED THEN UPDATE SET
				T1.CPR_OBSERV_COM_PROP = T2.CPR_OBSERV_COM_PROP,
				T1.USUARIOMODIFICAR = '''||V_USUARIO||''',
				T1.FECHAMODIFICAR = SYSDATE';
	EXECUTE IMMEDIATE V_MSQL;	

	DBMS_OUTPUT.PUT_LINE('[INFO] Se han ACTUALIZADO '||SQL%ROWCOUNT||' registros: ACT_CPR_COM_PROPIETARIOS');
	 
	COMMIT;	


	DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
    WHEN OTHERS THEN
      PL_OUTPUT := PL_OUTPUT ||'[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(SQLCODE)||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||'-----------------------------------------------------------'||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||SQLERRM||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||V_MSQL||CHR(10);
      DBMS_OUTPUT.PUT_LINE(PL_OUTPUT);
      ROLLBACK;
      RAISE;
END;
/
EXIT;
