OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999, SKIP=1)
LOAD DATA
CHARACTERSET WE8ISO8859P15
INFILE './CTL/IN/oficinas_caixabank.csv'
BADFILE './CTL/BAD/oficinas_caixabank.bad'
DISCARDFILE './CTL/REJECTS/oficinas_caixabank.bad'
INTO TABLE REM01.APR_AUX_HREOS_15319
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	COD_BANKIA "TRIM(:COD_BANKIA)",
	NOMBRE_BANKIA "TRIM(:NOMBRE_BANKIA)",
	COD_CAIXABANK "TRIM(:COD_CAIXABANK)",
	NOMBRE_CAIXABANK "TRIM(:NOMBRE_CAIXABANK)"
)
