--/*
--#########################################
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20210727
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.11
--## INCIDENCIA_LINK=HREOS-14680
--## PRODUCTO=NO
--## 
--## Finalidad: 
--## 
--## INSTRUCCIONES:  
--## VERSIONES:
--## 		0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

	TABLE_COUNT NUMBER(10,0) := 0;
	V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
	V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
	V_USUARIO VARCHAR2(50 CHAR) := 'MIG_CAIXA';
	V_TABLA VARCHAR2(40 CHAR) := 'GEX_GASTOS_EXPEDIENTE';
	V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG2_GEX_GASTOS_EXPEDIENTE_CAIXA';
	V_SENTENCIA VARCHAR2(32000 CHAR);
	V_NUM_TABLAS NUMBER(16);
	V_MSQL VARCHAR2(32000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.

BEGIN

	--Inicio del proceso de volcado sobre GEX_GASTOS_EXPEDIENTE
V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||'';

EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;

IF V_NUM_TABLAS = 0 THEN
DBMS_OUTPUT.PUT_LINE('La tabla/s de migración implicada está vacía. No se realiza ninguna acción');

ELSE
	DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');
	
	EXECUTE IMMEDIATE 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA||' GEX (
		GEX_ID,
		ECO_ID,
		DD_ACC_ID, 							--GEX_COD_CONCEPTO_GASTO
		DD_TCC_ID, 							--GEX_COD_TIPO_CALCULO / GEX_TIPO_CALCULO_ALQUILER
		GEX_IMPORTE_CALCULO,
		GEX_IMPORTE_FINAL,
		GEX_PAGADOR,
		GEX_APROBADO,
		GEX_PROVEEDOR,
		ACT_ID,
		--,GEX_IMPORTE_CALCULO_ALQUILER 		--No existe
		VERSION,
		USUARIOCREAR,
		FECHACREAR,
		USUARIOMODIFICAR,
		FECHAMODIFICAR,
		USUARIOBORRAR,
		FECHABORRAR,
		BORRADO,
		GEX_EDITADO
	)
	SELECT
		'||V_ESQUEMA||'.S_'||V_TABLA||'.NEXTVAL				AS GEX_ID,
		ECO.ECO_ID											AS ECO_ID,
		DD_ACC.DD_ACC_ID,
		DD_TCC.DD_TCC_ID,
		CASE
			WHEN MIG2.GEX_COD_TIPO_CALCULO = ''01'' AND MIG2.GEX_IMPORTE_CALCULO = 0 THEN 
				0 
			WHEN MIG2.GEX_COD_TIPO_CALCULO = ''02'' THEN 
				MIG2.GEX_IMPORTE_FINAL 
			WHEN MIG2.GEX_COD_TIPO_CALCULO = ''01'' THEN 
				MIG2.GEX_IMPORTE_FINAL/MIG2.GEX_IMPORTE_CALCULO*100
			WHEN MIG2.GEX_TIPO_CALCULO_ALQUILER = ''03'' AND MIG2.GEX_IMPORTE_CALCULO_ALQUILER = 0 THEN 
				0 
			WHEN MIG2.GEX_TIPO_CALCULO_ALQUILER = ''04'' THEN 
				MIG2.GEX_IMPORTE_FINAL 
			WHEN MIG2.GEX_TIPO_CALCULO_ALQUILER = ''03'' THEN 
				MIG2.GEX_IMPORTE_FINAL/MIG2.GEX_IMPORTE_CALCULO_ALQUILER*100
			/*WHEN MIG2.GEX_TIPO_CALCULO_ALQUILER = ''05'' THEN 
				MIG2.GEX_IMPORTE_FINAL/12  -- COMENTADO A FALTA DE SABER SI HAY MENSUALIDAD*/
		END 												GEX_IMPORTE_CALCULO,
		MIG2.GEX_IMPORTE_FINAL 								GEX_IMPORTE_FINAL,
		MIG2.GEX_IND_PAGADOR 								GEX_PAGADOR,
		MIG2.GEX_IND_APROBADO 								GEX_APROBADO,
		PVE.PVE_ID 											GEX_PROVEEDOR,
		ACT.ACT_ID,
		--MIG2.GEX_IMPORTE_CALCULO_ALQUILER 	GEX_IMPORTE_CALCULO_ALQUILER, Eliminado para Divarian
		0 													VERSION,
		'''||V_USUARIO||''' 								USUARIOCREAR,
		SYSDATE 											FECHACREAR,
		NULL 												USUARIOMODIFICAR,
		NULL 												FECHAMODIFICAR,
		NULL 												USUARIOBORRAR,
		NULL 												FECHABORRAR,
		0 													BORRADO,
		1													GEX_EDITADO
		--MIG2.GEX_WEBCOM_ID, 						Eliminado para Divarian
		--NULL 					GEX_OBSERVACIONES, 	Eliminado para Divarian
		--DD_DEG.DD_DEG_ID 		DD_DEG_ID, 			Eliminado para Divarian
		FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG2
		INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS 				OFR 	ON OFR.OFR_NUM_OFERTA = MIG2.GEX_COD_OFERTA
		INNER JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO 	ON ECO.OFR_ID = OFR.OFR_ID
		INNER JOIN '||V_ESQUEMA||'.DD_ACC_ACCION_GASTOS 	DD_ACC 	ON DD_ACC.DD_ACC_CODIGO = MIG2.GEX_COD_CONCEPTO_GASTO
		INNER JOIN '||V_ESQUEMA||'.DD_TCC_TIPO_CALCULO 		DD_TCC 	ON DD_TCC.DD_TCC_CODIGO = NVL(MIG2.GEX_COD_TIPO_CALCULO,MIG2.GEX_TIPO_CALCULO_ALQUILER)
		LEFT JOIN '||V_ESQUEMA||'.ACT_PVE_PROVEEDOR 		PVE 	ON PVE.PVE_COD_ORIGEN = MIG2.GEX_COD_PROVEEDOR 
			AND PVE.DD_TPR_ID IS NOT NULL 
			AND PVE.PVE_FECHA_BAJA IS NULL 
			AND PVE.BORRADO = 0
			AND ROWNUM = 1
		LEFT JOIN '||V_ESQUEMA||'.ACT_ACTIVO 				ACT 	ON ACT.ACT_NUM_ACTIVO = MIG2.GEX_ACT_NUMERO_ACTIVO
		--INNER JOIN '||V_ESQUEMA||'.DD_TCC_TIPO_CALCULO 		TCC 	ON TCC.DD_TCC_CODIGO = MIG2.GEX_COD_TIPO_CALCULO
		--JOIN '||V_ESQUEMA||'.DD_DEG_DESTINATARIOS_GASTO 		DD_DEG 	ON DD_DEG.DD_DEG_CODIGO = MIG2.GEX_COD_DESTINATARIO 
		--	AND DD_DEG.BORRADO = 0
		WHERE MIG2.VALIDACION = 0 AND
		NOT EXISTS (
			SELECT 1 FROM '||V_ESQUEMA||'.'||V_TABLA||' AUX
			WHERE AUX.ECO_ID = ECO.ECO_ID AND
			AUX.DD_ACC_ID = DD_ACC.DD_ACC_ID AND
			NVL(AUX.GEX_PROVEEDOR,''-1'') = NVL(GEX_PROVEEDOR,''-1'')
		)
	';

	DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');

	COMMIT;

	V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''10''); END;';
	EXECUTE IMMEDIATE V_SENTENCIA;
END IF;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
		DBMS_OUTPUT.put_line('-----------------------------------------------------------');
		DBMS_OUTPUT.put_line(SQLERRM);
		ROLLBACK;
		RAISE;
END;
/
EXIT;
