
package org.cajamar.ws.S_M_GESTIONDOCUMENTAL;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "S_M_GESTIONDOCUMENTAL", targetNamespace = "http://cajamar.org/webservice", wsdlLocation = "https://multidesa.larural.es:515/RECOVERY/services/S_M_GESTIONDOCUMENTAL?wsdl")
public class SMGESTIONDOCUMENTAL
    extends Service
{

    private final static URL SMGESTIONDOCUMENTAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.cajamar.ws.S_M_GESTIONDOCUMENTAL.SMGESTIONDOCUMENTAL.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.cajamar.ws.S_M_GESTIONDOCUMENTAL.SMGESTIONDOCUMENTAL.class.getResource(".");
            url = new URL(baseUrl, "https://multidesa.larural.es:515/RECOVERY/services/S_M_GESTIONDOCUMENTAL?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://multidesa.larural.es:515/RECOVERY/services/S_M_GESTIONDOCUMENTAL?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SMGESTIONDOCUMENTAL_WSDL_LOCATION = url;
    }

    public SMGESTIONDOCUMENTAL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMGESTIONDOCUMENTAL() {
        super(SMGESTIONDOCUMENTAL_WSDL_LOCATION, new QName("http://cajamar.org/webservice", "S_M_GESTIONDOCUMENTAL"));
    }

    /**
     * 
     * @return
     *     returns SMGESTIONDOCUMENTALType
     */
    @WebEndpoint(name = "S_M_GESTIONDOCUMENTALPort")
    public SMGESTIONDOCUMENTALType getSMGESTIONDOCUMENTALPort() {
        return super.getPort(new QName("http://cajamar.org/webservice", "S_M_GESTIONDOCUMENTALPort"), SMGESTIONDOCUMENTALType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMGESTIONDOCUMENTALType
     */
    @WebEndpoint(name = "S_M_GESTIONDOCUMENTALPort")
    public SMGESTIONDOCUMENTALType getSMGESTIONDOCUMENTALPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cajamar.org/webservice", "S_M_GESTIONDOCUMENTALPort"), SMGESTIONDOCUMENTALType.class, features);
    }

}
