-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

CREATE DEFINER=`lindorff`@`62.15.160.2` PROCEDURE `Crear_Dim_Tarea`(OUT o_error_status varchar(500))
MY_BLOCK_DIM_TAR: BEGIN

-- ===============================================================================================
-- Autor: Gonzalo Martín, PFS Group
-- Fecha creación: Septiembre 2013
-- Responsable última modificación: Gonzalo Martín, PFS Group
-- Fecha última modificación: 10/12/2013
-- Motivos del cambio: SP Lindorff v0
-- Cliente: Recovery BI Lindorff  
--
-- Descripción: Procedimiento almancenado que crea las tablas de la dimensión Tarea.
-- ===============================================================================================

-- --------------------------------------------------------------------------------
-- DEFINICIÓN DE LOS HANDLER DE ERROR
-- --------------------------------------------------------------------------------
DECLARE EXIT handler for 1062 set o_error_status := 'Error 1062: La tabla ya existe';
DECLARE EXIT handler for 1048 set o_error_status := 'Error 1048: Has intentado insertar un valor nulo'; 
DECLARE EXIT handler for 1318 set o_error_status := 'Error 1318: Número de parámetros incorrecto'; 

-- --------------------------------------------------------------------------------
-- DEFINICIÓN DEL HANDLER GENÉRICO DE ERROR
-- --------------------------------------------------------------------------------
DECLARE EXIT handler for sqlexception set o_error_status:= 'Se ha producido un error en el proceso';


 CREATE TABLE IF NOT EXISTS DIM_TAREA_TIPO(
  `TIPO_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `TIPO_TAREA_DESC` VARCHAR(50) NULL ,
  `TIPO_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`TIPO_TAREA_ID`));


 CREATE TABLE IF NOT EXISTS DIM_TAREA_TIPO_DETALLE (
  `TIPO_TAREA_DETALLE_ID` DECIMAL(16,0) NOT NULL ,
  `TIPO_TAREA_DETALLE_DESC` VARCHAR(250) NULL ,
  `TIPO_TAREA_DETALLE_DESC_ALT` VARCHAR(250) NULL ,
  `TIPO_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`TIPO_TAREA_DETALLE_ID`));
  
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_RESOLUCION_PRORROGA(
  `RESOLUCION_PRORROGA_ID` DECIMAL(16,0) NOT NULL ,
  `RESOLUCION_PRORROGA_DESC` VARCHAR(50) NULL ,
  `RESOLUCION_PRORROGA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`RESOLUCION_PRORROGA_ID`));
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_MOTIVO_PRORROGA (
  `MOTIVO_PRORROGA_ID` DECIMAL(16,0) NOT NULL ,
  `MOTIVO_PRORROGA_DESC` VARCHAR(250) NULL ,
  `MOTIVO_PRORROGA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`MOTIVO_PRORROGA_ID`));
 
 
 CREATE TABLE IF NOT EXISTS DIM_TAREA_PENDIENTE_RESPUESTA(
  `PENDIENTE_RESPUESTA_ID` DECIMAL(16,0) NOT NULL ,
  `PENDIENTE_RESPUESTA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`PENDIENTE_RESPUESTA_ID`)); 


 CREATE TABLE IF NOT EXISTS DIM_TAREA_ESTADO_PRORROGA(
  `ESTADO_PRORROGA_ID` DECIMAL(16,0) NOT NULL ,
  `ESTADO_PRORROGA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`ESTADO_PRORROGA_ID`));
  
 
 CREATE TABLE IF NOT EXISTS DIM_TAREA_ALERTA(
  `TAREA_ALERTA_ID` DECIMAL(16,0) NOT NULL ,
  `TAREA_ALERTA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`TAREA_ALERTA_ID`));
   
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_AMBITO(
  `AMBITO_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `AMBITO_TAREA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`AMBITO_TAREA_ID`));
 

  CREATE TABLE IF NOT EXISTS DIM_TAREA_REALIZACION(
  `REALIZACION_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `REALIZACION_TAREA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`REALIZACION_TAREA_ID`));
  
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_CUMPLIMIENTO(
  `CUMPLIMIENTO_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `CUMPLIMIENTO_TAREA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`CUMPLIMIENTO_TAREA_ID`));
 
 
  CREATE TABLE IF NOT EXISTS DIM_TAREA_PENDIENTE_RESPUESTA(
  `PENDIENTE_RESPUESTA_ID` DECIMAL(16,0) NOT NULL ,
  `PENDIENTE_RESPUESTA_DESC` VARCHAR(50) NULL ,
  PRIMARY KEY (`PENDIENTE_RESPUESTA_ID`)); 
  
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_DESPACHO_GESTOR (
  `DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `DESPACHO_GESTOR_TAREA_DESC` VARCHAR(250) NULL ,
  `TIPO_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `ZONA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,  
  PRIMARY KEY (`DESPACHO_GESTOR_TAREA_ID`));
  
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_TIPO_DESPACHO_GESTOR(
  `TIPO_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `TIPO_DESPACHO_GESTOR_TAREA_DESC` VARCHAR(50) NULL ,
  `TIPO_DESPACHO_GESTOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`TIPO_DESPACHO_GESTOR_TAREA_ID`));
  
 
  CREATE TABLE IF NOT EXISTS DIM_TAREA_GESTOR (
  `GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `GESTOR_TAREA_NOMBRE_COMPLETO` VARCHAR(250) NULL ,
  `GESTOR_TAREA_NOMBRE` VARCHAR(250) NULL ,
  `GESTOR_TAREA_APELLIDO1` VARCHAR(250) NULL ,
  `GESTOR_TAREA_APELLIDO2` VARCHAR(250) NULL ,
  `ENTIDAD_GESTOR_TAREA_ID` DECIMAL(16,0) NULL , 
  `DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,  
  PRIMARY KEY (`GESTOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_ENTIDAD_GESTOR(
  `ENTIDAD_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `ENTIDAD_GESTOR_TAREA_DESC` VARCHAR(255) NULL ,
  PRIMARY KEY (`ENTIDAD_GESTOR_TAREA_ID`));
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_NIVEL_DESPACHO_GESTOR( 
  `NIVEL_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `NIVEL_DESPACHO_GESTOR_TAREA_DESC` VARCHAR(50) NULL ,
  `NIVEL_DESPACHO_GESTOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`NIVEL_DESPACHO_GESTOR_TAREA_ID`));
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_OFICINA_DESPACHO_GESTOR( 
  `OFICINA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `OFICINA_DESPACHO_GESTOR_TAREA_DESC` VARCHAR(50) NULL ,
  `OFICINA_DESPACHO_GESTOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  `PROVINCIA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`OFICINA_DESPACHO_GESTOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_PROVINCIA_DESPACHO_GESTOR( 
  `PROVINCIA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `PROVINCIA_DESPACHO_GESTOR_TAREA_DESC` VARCHAR(50) NULL ,
  `PROVINCIA_DESPACHO_GESTOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`PROVINCIA_DESPACHO_GESTOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_ZONA_DESPACHO_GESTOR( 
  `ZONA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `ZONA_DESPACHO_GESTOR_TAREA_DESC` VARCHAR(50) NULL ,
  `ZONA_DESPACHO_GESTOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  `NIVEL_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `OFICINA_DESPACHO_GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`ZONA_DESPACHO_GESTOR_TAREA_ID`));
  
 
 CREATE TABLE IF NOT EXISTS DIM_TAREA_DESPACHO_SUPERVISOR (
  `DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(250) NULL ,
  `TIPO_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `ZONA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,  
  PRIMARY KEY (`DESPACHO_SUPERVISOR_TAREA_ID`));
  
  
  CREATE TABLE IF NOT EXISTS DIM_TAREA_TIPO_DESPACHO_SUPERVISOR(
  `TIPO_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `TIPO_DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(50) NULL ,
  `TIPO_DESPACHO_SUPERVISOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`TIPO_DESPACHO_SUPERVISOR_TAREA_ID`));
  
 
  CREATE TABLE IF NOT EXISTS DIM_TAREA_SUPERVISOR (
  `SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `SUPERVISOR_TAREA_NOMBRE_COMPLETO` VARCHAR(250) NULL ,
  `SUPERVISOR_TAREA_NOMBRE` VARCHAR(250) NULL ,
  `SUPERVISOR_TAREA_APELLIDO1` VARCHAR(250) NULL ,
  `SUPERVISOR_TAREA_APELLIDO2` VARCHAR(250) NULL ,
  `ENTIDAD_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL , 
  `DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,  
  PRIMARY KEY (`SUPERVISOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_ENTIDAD_SUPERVISOR(
  `ENTIDAD_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `ENTIDAD_SUPERVISOR_TAREA_DESC` VARCHAR(255) NULL ,
  PRIMARY KEY (`ENTIDAD_SUPERVISOR_TAREA_ID`));
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_NIVEL_DESPACHO_SUPERVISOR( 
  `NIVEL_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `NIVEL_DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(50) NULL ,
  `NIVEL_DESPACHO_SUPERVISOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`NIVEL_DESPACHO_SUPERVISOR_TAREA_ID`));
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_OFICINA_DESPACHO_SUPERVISOR( 
  `OFICINA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `OFICINA_DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(50) NULL ,
  `OFICINA_DESPACHO_SUPERVISOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  `PROVINCIA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`OFICINA_DESPACHO_SUPERVISOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_PROVINCIA_DESPACHO_SUPERVISOR( 
  `PROVINCIA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `PROVINCIA_DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(50) NULL ,
  `PROVINCIA_DESPACHO_SUPERVISOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  PRIMARY KEY (`PROVINCIA_DESPACHO_SUPERVISOR_TAREA_ID`));
  

 CREATE TABLE IF NOT EXISTS DIM_TAREA_ZONA_DESPACHO_SUPERVISOR( 
  `ZONA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `ZONA_DESPACHO_SUPERVISOR_TAREA_DESC` VARCHAR(50) NULL ,
  `ZONA_DESPACHO_SUPERVISOR_TAREA_DESC_ALT` VARCHAR(250) NULL ,
  `NIVEL_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `OFICINA_DESPACHO_SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`ZONA_DESPACHO_SUPERVISOR_TAREA_ID`));
 
 
 CREATE TABLE IF NOT EXISTS DIM_TAREA_DESCRIPCION(
  `DESCRIPCION_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `DESCRIPCION_TAREA_DESC` VARCHAR(100) NULL ,
  PRIMARY KEY (`DESCRIPCION_TAREA_ID`));  
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA_RESPONSABLE(
  `RESPONSABLE_TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `RESPONSABLE_TAREA_DESC` VARCHAR(100) NULL ,
  PRIMARY KEY (`RESPONSABLE_TAREA_ID`));  
  
  
 CREATE TABLE IF NOT EXISTS DIM_TAREA( 
  `TAREA_ID` DECIMAL(16,0) NOT NULL ,
  `TAREA_EMISOR` VARCHAR(50) NULL ,
  `DESCRIPCION_TAREA_ID` DECIMAL(16,0) NULL ,
  `GESTOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL ,
  `FECHA_INICIO_TAREA` DATE NULL,
  `FECHA_FIN_TAREA` DATE NULL,
  `FECHA_VENCIMIENTO_TAREA` DATE NULL,
  `FECHA_VENCIMIENTO_REAL_TAREA` DATE NULL,
  `TIPO_TAREA_DETALLE_ID` DECIMAL(16,0) NULL ,
  `AMBITO_TAREA_ID` DECIMAL(16,0) NULL ,
  `PENDIENTE_RESPUESTA_ID` DECIMAL(16,0) NULL ,
  `TAREA_ALERTA_ID` DECIMAL(16,0) NULL ,
  `CUMPLIMIENTO_TAREA_ID` DECIMAL(16,0) NULL ,
  PRIMARY KEY (`TAREA_ID`));
  


 CREATE TABLE IF NOT EXISTS TEMP_TAREA_GESTOR( 
  `TAREA_ID` DECIMAL(16,0) NULL, 
  `GESTOR_TAREA_ID` DECIMAL(16,0) NULL
 ); 
 
 
  CREATE TABLE IF NOT EXISTS TEMP_TAREA_SUPERVISOR( 
  `TAREA_ID` DECIMAL(16,0) NULL, 
  `SUPERVISOR_TAREA_ID` DECIMAL(16,0) NULL
 ); 
  
 

END MY_BLOCK_DIM_TAR
