--/*
--#########################################
--## AUTOR=Pablo Meseguer
--## FECHA_CREACION=20170213
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-719
--## PRODUCTO=NO
--## 
--## Finalidad: ASIGNACION DE GESTORES PARA LOS NUEVOS ACTIVOS
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

declare
--v0.3

V_USUARIO	VARCHAR2(100 char) := 'MIG2';
PL_OUTPUT    VARCHAR2(4000 char);
V_ESQUEMA VARCHAR2(15 CHAR) := 'REM01';
V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER';
V_NUM NUMBER(8);
v_count_1 NUMBER(8);

BEGIN

  DBMS_OUTPUT.PUT_LINE('[INFO] SE VA A PROCEDER A CREAR LA RELACION DE ACTIVOS CON SU GESTOR.');


  DBMS_OUTPUT.PUT_LINE('[INFO] CREANDO TABLA TEMPORAL TMP_GEST_ACT...');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    

  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ACT_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;
  
  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;  
  
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )

    SELECT DISTINCT ACT.ACT_NUM_ACTIVO, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
    INNER JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
      ON ACT.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
      ON GAC.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GAH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GAC.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestor de activos''
    AND GEE.BORRADO = 0 '
  ;
--------------------------------------------------------------------
----------- ASIGNAMOS GESTORES DE ACTIVO ---------------------------
--------------------------------------------------------------------

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTORES DEL ACTIVO--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ACT_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ACT.ACT_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_ACT_ACTIVO MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.ACT_GESTOR_ACTIVO = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
    ON ACT.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');


  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GACT''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := '[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA GESTORES DEL ACTIVO. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAC_GESTOR_ADD_ACTIVO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO (
  gee_id,
  act_id
  )
  SELECT
  TMP.gee_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO PARA GESTORES DEL ACTIVO. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAC_GESTOR_ADD_ACTIVO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  --PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA GESTORES DEL ACTIVO. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAH_GESTOR_ACTIVO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (
  geh_id,
  act_id
  )
  SELECT
  TMP.geh_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO PARA GESTORES DEL ACTIVO. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAH_GESTOR_ACTIVO_HISTORICO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';      

  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('');
----------------------------------------------------------------------
----------- ASIGNAMOS GESTORES COMERCIALES ---------------------------
----------------------------------------------------------------------

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ACT_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;
 
  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;    
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )

    SELECT DISTINCT ACT.ACT_NUM_ACTIVO, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
    INNER JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
      ON ACT.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
      ON GAC.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GAH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GAC.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestor comercial''
    AND GEE.BORRADO = 0 '
  ;
  
  --ASIGNAMOS GESTORES COMERCIALES 'GCOM'

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTORES COMERCIALES--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ACT_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ACT.ACT_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_ACT_ACTIVO MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.ACT_GESTOR_COMERCIAL = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
    ON ACT.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');

  --ASIGNAMOS GESTORES COMERCIALES

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GCOM''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA GESTORES COMERCIALES. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAC_GESTOR_ADD_ACTIVO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO (
  gee_id,
  act_id
  )
  SELECT
  TMP.gee_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO PARA GESTORES COMERCIALES. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAC_GESTOR_ADD_ACTIVO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA GESTORES COMERCIALES. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAH_GESTOR_ACTIVO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (
  geh_id,
  act_id
  )
  SELECT
  TMP.geh_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO PARA GESTORES COMERCIALES. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAH_GESTOR_ACTIVO_HISTORICO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;
  
  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
  '
  ;    
  
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('');
----------------------------------------------------------------------
----------- ASIGNAMOS GESTORÍAS DE ADMISION -------------------------
----------------------------------------------------------------------

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ACT_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;    
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )

    SELECT DISTINCT ACT.ACT_NUM_ACTIVO, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
    INNER JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
      ON ACT.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
      ON GAC.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GAH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GAC.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestoría de admisión''
    AND GEE.BORRADO = 0 '
  ;

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTORÍAS DE ADMISIÓN--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ACT_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ACT.ACT_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_ACT_ACTIVO MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.ACT_GESTORIA_ADMISION = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
    ON ACT.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');

  --ASIGNAMOS GESTORÍA DE ADMISIÓN

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GGADM''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA GESTORÍAS DE ADMISIÓN. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAC_GESTOR_ADD_ACTIVO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO (
  gee_id,
  act_id
  )
  SELECT
  TMP.gee_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO PARA GESTORÍAS DE ADMISIÓN. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAC_GESTOR_ADD_ACTIVO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA GESTORÍAS DE ADMISIÓN. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAH_GESTOR_ACTIVO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (
  geh_id,
  act_id
  )
  SELECT
  TMP.geh_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO PARA GESTORÍAS DE ADMISIÓN. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAH_GESTOR_ACTIVO_HISTORICO cargada 4. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
  ';    
  
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('');
----------------------------------------------------------------------
----------- ASIGNAMOS GESTORÍAS DE ADMINISTRACION --------------------
----------------------------------------------------------------------

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ACT_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;    
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      ACT_NUM_ACTIVO,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )

    SELECT DISTINCT ACT.ACT_NUM_ACTIVO, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
    INNER JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
      ON ACT.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
      ON GAC.ACT_ID = GAH.ACT_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GAH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GAC.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestoría de administración''
    AND GEE.BORRADO = 0 '
  ;

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTORÍAS DE ADMINISTRACION--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ACT_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ACT.ACT_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_ACT_ACTIVO MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.ACT_GESTORIA_ADMINISTRACION = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
    ON ACT.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.ACT_NUM_ACTIVO = MIG2.ACT_NUMERO_ACTIVO)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');

  --ASIGNAMOS GESTORÍA DE ADMINISTRACION

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GIAADMT''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA GESTORÍAS DE ADMINISTRACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAC_GESTOR_ADD_ACTIVO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO (
  gee_id,
  act_id
  )
  SELECT
  TMP.gee_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO PARA GESTORÍAS DE ADMINISTRACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAC_GESTOR_ADD_ACTIVO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA GESTORÍAS DE ADMINISTRACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GAH_GESTOR_ACTIVO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (
  geh_id,
  act_id
  )
  SELECT
  TMP.geh_id,
  TMP.act_id
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO PARA GESTORÍAS DE ADMINISTRACION. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GAH_GESTOR_ACTIVO_HISTORICO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
  ';    

DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('');  
------------------------------------------------------------------
----------- ASIGNAMOS GESTOR DE FORMALIZACION --------------------
------------------------------------------------------------------

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ECO_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      OFR_NUM_OFERTA                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;    
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      OFR_NUM_OFERTA,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )
	SELECT DISTINCT OFR.OFR_NUM_OFERTA, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.MIG2_OFR_OFERTAS MIG
    INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR
      ON MIG.OFR_COD_OFERTA = OFR.OFR_NUM_OFERTA
    INNER JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
      ON OFR.OFR_ID = ECO.OFR_ID
    INNER JOIN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO GCH
      ON ECO.ECO_ID = GCH.ECO_ID
    INNER JOIN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO GCO
      ON GCO.ECO_ID = GCH.ECO_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GCH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GCO.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestor formalización''
    AND GEE.BORRADO = 0 
   '
   ;

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTOR DE FORMALIZACION--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ECO_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ECO.ECO_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_OFR_OFERTAS MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.OFR_GESTOR_FORMALIZACION = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR
    ON OFR.OFR_NUM_OFERTA = MIG2.OFR_COD_OFERTA
  INNER JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
    ON ECO.OFR_ID = OFR.OFR_ID
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.OFR_NUM_OFERTA = MIG2.OFR_COD_OFERTA)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');

  --ASIGNAMOS GESTOR DE FORMALIZACION

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GFORM''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA  GESTOR DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GCO_GESTOR_ADD_ECO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO (
  gee_id,
  ECO_ID
  )
  SELECT
  TMP.gee_id,
  TMP.ECO_ID
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO  GESTOR DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GCO_GESTOR_ADD_ECO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA  GESTOR DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GCH_GESTOR_ECO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO (
  geh_id,
  ECO_ID
  )
  SELECT
  TMP.geh_id,
  TMP.ECO_ID
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO PARA  GESTOR DE FORMALIZACION. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GCH_GESTOR_ECO_HISTORICO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
  '; 
  
DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('');  
------------------------------------------------------------------
----------- ASIGNAMOS GESTORÍA DE FORMALIZACION ------------------
------------------------------------------------------------------

  EXECUTE IMMEDIATE '
  SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME LIKE ''TMP_GEST_ACT'' AND OWNER LIKE '''||V_ESQUEMA||'''
  '
  INTO V_NUM
  ;

  IF V_NUM != 0 THEN

    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
    '
    ;
    EXECUTE IMMEDIATE '
    DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
    ';    
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT (
      ECO_ID                      NUMBER(16,0),
      USU_ID                      NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      GEH_ID                      NUMBER(16,0)
    )
  '
  ;

  EXECUTE IMMEDIATE '
    CREATE TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      OFR_NUM_OFERTA                      NUMBER(16,0),
      GEH_ID     NUMBER(16,0),
      GEE_ID                      NUMBER(16,0),
      DD_TGE_ID     NUMBER(16,0),
      DD_TGE_DESCRIPCION                      VARCHAR2(50 CHAR)
    )
  '
  ;    
  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR (
      OFR_NUM_OFERTA,
      GEH_ID,
      GEE_ID,
      DD_TGE_ID,
      DD_TGE_DESCRIPCION 
  )
	SELECT DISTINCT OFR.OFR_NUM_OFERTA, GEH.GEH_ID, GEE.GEE_ID, GEE.DD_TGE_ID, TGE.DD_TGE_DESCRIPCION
    FROM '||V_ESQUEMA||'.MIG2_OFR_OFERTAS MIG
    INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR
      ON MIG.OFR_COD_OFERTA = OFR.OFR_NUM_OFERTA
    INNER JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
      ON OFR.OFR_ID = ECO.OFR_ID
    INNER JOIN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO GCH
      ON ECO.ECO_ID = GCH.ECO_ID
    INNER JOIN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO GCO
      ON GCO.ECO_ID = GCH.ECO_ID
    INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
      ON GEH.GEH_ID = GCH.GEH_ID
    INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GCO.GEE_ID
    LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
      ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
    WHERE TGE.DD_TGE_ID IS NOT NULL
    AND TGE.DD_TGE_DESCRIPCION = ''Gestoría de formalización''
    AND GEE.BORRADO = 0 
   '
   ;

  DBMS_OUTPUT.PUT_LINE('[INFO] --GESTORÍA DE FORMALIZACION--');
  DBMS_OUTPUT.PUT_LINE('');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.TMP_GEST_ACT (
    ECO_ID,
    USU_ID,
    GEE_ID,
    GEH_ID
  )
  SELECT
  ECO.ECO_ID,
  USU.USU_ID,
  '||V_ESQUEMA||'.s_gee_gestor_entidad.NEXTVAL gee_id,
  '||V_ESQUEMA||'.s_geh_gestor_entidad_hist.NEXTVAL geh_id
  FROM '||V_ESQUEMA||'.MIG2_OFR_OFERTAS MIG2
  INNER JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
    ON MIG2.OFR_GESTORIA_FORMALIZACION = USU.USU_USERNAME
  INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR
    ON OFR.OFR_NUM_OFERTA = MIG2.OFR_COD_OFERTA
  INNER JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
    ON ECO.OFR_ID = OFR.OFR_ID
  WHERE NOT EXISTS (
  SELECT 1 FROM '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR TMP WHERE TMP.OFR_NUM_OFERTA = MIG2.OFR_COD_OFERTA)
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' TMP_GEST_ACT cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.TMP_GEST_ACT ANALIZADA.');

  --ASIGNAMOS GESTORÍA DE FORMALIZACION

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEE_GESTOR_ENTIDAD...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD (
  gee_id,
  usu_id,
  dd_tge_id,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  TMP.gee_id,
  TMP.usu_id,
  (SELECT dd_tge_id FROM '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor WHERE dd_tge_codigo = ''GIAFORM''),
  0,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD PARA  GESTORÍA DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEE_GESTOR_ENTIDAD cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GCO_GESTOR_ADD_ECO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO (
  gee_id,
  ECO_ID
  )
  SELECT
  TMP.gee_id,
  TMP.ECO_ID
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO  GESTORÍA DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GCO_GESTOR_ADD_ECO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GEH_GESTOR_ENTIDAD_HIST...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (
  geh_id,
  usu_id,
  dd_tge_id,
  geh_fecha_desde,
  geh_fecha_hasta,
  VERSION,
  usuariocrear,
  fechacrear,
  borrado
  )
  SELECT
  tmp.geh_id,
  tmp.usu_id,
  gee.dd_tge_id,
  SYSDATE,
  NULL,
  1,
  '''||V_USUARIO||''',
  SYSDATE,
  0
  FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
  INNER JOIN '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    ON TMP.GEE_ID = GEE.GEE_ID
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST PARA GESTORÍA DE FORMALIZACION. '||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GEH_GESTOR_ENTIDAD_HIST cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST COMPUTE STATISTICS');

  DBMS_OUTPUT.PUT_LINE('[INFO] CARGANDO LA TABLA GCH_GESTOR_ECO_HISTORICO...');

  EXECUTE IMMEDIATE '
  INSERT INTO '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO (
  geh_id,
  ECO_ID
  )
  SELECT
  TMP.geh_id,
  TMP.ECO_ID
  FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
  WHERE TMP.USU_ID IS NOT NULL
  '
  ;

  v_count_1 := SQL%ROWCOUNT;
  PL_OUTPUT := PL_OUTPUT||'[INFO] INSERTADOS '||v_count_1||' REGISTROS EN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO PARA GESTORÍA DE FORMALIZACION. '||CHR(10)||CHR(10);

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' GCH_GESTOR_ECO_HISTORICO cargada. '||v_count_1||' Filas.');

  COMMIT;

  EXECUTE IMMEDIATE('ANALYZE TABLE '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO COMPUTE STATISTICS');

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT PURGE
  '
  ;

  EXECUTE IMMEDIATE '
  DROP TABLE '||V_ESQUEMA||'.GESTOR_ACTIVOS_NO_INSERTAR
  ';   

  
  DBMS_OUTPUT.PUT_LINE('[OK] - PROCESO FINALIZADO.');


EXCEPTION

    WHEN OTHERS THEN

        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion: '||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);

    ROLLBACK;
    RAISE;

END SP_AGA_ASIGNA_GESTOR_ACTIVO;
 
 
