--/*
--#########################################
--## AUTOR=DAP
--## FECHA_CREACION=20171214
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=2.0.10
--## INCIDENCIA_LINK=HREOS-3359
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración ''||V_TABLA_MIG||'' -> 'ACT_TBJ_TRABAJO', 'ACT_TBJ'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

    V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
    V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
    V_USUARIO VARCHAR2(50 CHAR) := 'HREOS-3359';
    V_TABLA VARCHAR2(40 CHAR) := 'ACT_TBJ_TRABAJO';
    V_TABLA_2 VARCHAR2(40 CHAR) := 'ACT_TBJ';
    V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG_ATR_TRABAJO_REC';
    V_SENTENCIA VARCHAR2(2000 CHAR);

BEGIN

    DBMS_OUTPUT.PUT_LINE('[INICIO]');
    DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE VOLCADO SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');

    EXECUTE IMMEDIATE 'DELETE FROM '||V_ESQUEMA||'.'||V_TABLA_2||' T1 WHERE EXISTS (SELECT 1 FROM '||V_ESQUEMA||'.'||V_TABLA||' TP JOIN '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA_2||' borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_PRT_PRESUPUESTO_TRABAJO T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_PRT_PRESUPUESTO_TRABAJO borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_TCT_TRABAJO_CFGTARIFA T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_TCT_TRABAJO_CFGTARIFA borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_TBO_TRABAJO_OBS T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_TBO_TRABAJO_OBS borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_ADT_ADJUNTO_TRABAJO T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_ADT_ADJUNTO_TRABAJO borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_PSU_PROVISION_SUPLIDO T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_PSU_PROVISION_SUPLIDO borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.ACT_RPV_RECARGOS_PROVEEDOR T1 WHERE EXISTS (SELECT 1 FROM REM01.ACT_TBJ_TRABAJO TP JOIN REM01.'||V_TABLA_MIG||' MIG ON TP.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = TP.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.ACT_RPV_RECARGOS_PROVEEDOR borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM REM01.GPV_TBJ T1 WHERE EXISTS (SELECT 1 FROM REM01.'||V_TABLA_MIG||' MIG JOIN REM01.ACT_TBJ_TRABAJO T2 ON T2.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0 WHERE T1.TBJ_ID = T2.TBJ_ID)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA||' borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE 'DELETE FROM '||V_ESQUEMA||'.'||V_TABLA||' T1 WHERE EXISTS (SELECT 1 FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG WHERE T1.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO AND MIG.VALIDACION = 0)';
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA||' borrada (Registros que vienen en la migración). '||SQL%ROWCOUNT||' Filas.');
    
    EXECUTE IMMEDIATE ('INSERT INTO '||V_ESQUEMA||'.'||V_TABLA||' (TBJ_ID, AGR_ID, TBJ_NUM_TRABAJO, PVC_ID, DD_TTR_ID, DD_STR_ID, DD_EST_ID, TBJ_DESCRIPCION
            , TBJ_FECHA_SOLICITUD, TBJ_FECHA_APROBACION, TBJ_FECHA_INICIO, TBJ_FECHA_FIN, TBJ_CONTINUO_OBSERVACIONES, TBJ_FECHA_FIN_COMPROMISO, TBJ_FECHA_TOPE, TBJ_FECHA_HORA_CONCRETA
            , TBJ_URGENTE, TBJ_CON_RIESGO_TERCEROS, TBJ_CUBRE_SEGURO, TBJ_CIA_ASEGURADORA, DD_TCA_ID, TBJ_TERCERO_NOMBRE, TBJ_TERCERO_EMAIL, TBJ_TERCERO_DIRECCION
            , TBJ_TERCERO_CONTACTO, TBJ_TERCERO_TEL1, TBJ_TERCERO_TEL2, TBJ_IMPORTE_PENAL_DIARIO, TBJ_OBSERVACIONES, TBJ_IMPORTE_TOTAL, TBJ_FECHA_RECHAZO, USUARIOCREAR, FECHACREAR)
        WITH TRABAJOS AS (SELECT DISTINCT AGR.AGR_ID, MIG.TBJ_NUM_TRABAJO TBJ_NUM_TRABAJO
                , (SELECT PVC.PVC_ID FROM REM01.ACT_PVC_PROVEEDOR_CONTACTO PVC JOIN REM01.ACT_PVE_PROVEEDOR PVE ON PVE.PVE_ID = PVC.PVE_ID WHERE PVE.PVE_COD_UVEM = MIG.PVC_DOCIDENTIF AND ROWNUM = 1) PVC_ID
                , TTR.DD_TTR_ID DD_TTR_ID, STR.DD_STR_ID DD_STR_ID, EST.DD_EST_ID DD_EST_ID, MIG.TBJ_DESCRIPCION TBJ_DESCRIPCION, MIG.TBJ_FECHA_SOLICITUD TBJ_FECHA_SOLICITUD
                , MIG.TBJ_FECHA_APROBACION TBJ_FECHA_APROBACION, MIG.TBJ_FECHA_INICIO TBJ_FECHA_INICIO, MIG.TBJ_FECHA_FIN TBJ_FECHA_FIN, MIG.TBJ_CONTINUO_OBSERVACIONES TBJ_CONTINUO_OBSERVACIONES
                , MIG.TBJ_FECHA_FIN_COMPROMISO TBJ_FECHA_FIN_COMPROMISO, MIG.TBJ_FECHA_TOPE TBJ_FECHA_TOPE, MIG.TBJ_FECHA_HORA_CONCRETA TBJ_FECHA_HORA_CONCRETA, MIG.TBJ_URGENTE TBJ_URGENTE
                , MIG.TBJ_CON_RIESGO_TERCEROS TBJ_CON_RIESGO_TERCEROS, MIG.TBJ_CUBRE_SEGURO TBJ_CUBRE_SEGURO, MIG.TBJ_CIA_ASEGURADORA TBJ_CIA_ASEGURADORA
                , TCA.DD_TCA_ID DD_TCA_ID, MIG.TBJ_TERCERO_NOMBRE TBJ_TERCERO_NOMBRE, MIG.TBJ_TERCERO_EMAIL TBJ_TERCERO_EMAIL, MIG.TBJ_TERCERO_DIRECCION TBJ_TERCERO_DIRECCION
                , MIG.TBJ_TERCERO_CONTACTO TBJ_TERCERO_CONTACTO, MIG.TBJ_TERCERO_TEL1 TBJ_TERCERO_TEL1, MIG.TBJ_TERCERO_TEL2 TBJ_TERCERO_TEL2, MIG.TBJ_IMPORTE_PENAL_DIARIO TBJ_IMPORTE_PENAL_DIARIO
                , MIG.TBJ_OBSERVACIONES TBJ_OBSERVACIONES, MIG.TBJ_IMPORTE_TOTAL TBJ_IMPORTE_TOTAL, MIG.TBJ_FECHA_DENEGACION TBJ_FECHA_RECHAZO, '''||V_USUARIO||''' USUARIOCREAR, SYSDATE FECHACREAR
            FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
            LEFT JOIN '||V_ESQUEMA||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_NUM_AGRUP_UVEM = MIG.AGR_UVEM
            LEFT JOIN '||V_ESQUEMA||'.DD_TTR_TIPO_TRABAJO TTR ON TTR.DD_TTR_CODIGO = MIG.TIPO_TRABAJO
            LEFT JOIN '||V_ESQUEMA||'.DD_STR_SUBTIPO_TRABAJO STR ON STR.DD_STR_CODIGO = MIG.SUBTIPO_TRABAJO
            LEFT JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_CODIGO = MIG.ESTADO_TRABAJO
            LEFT JOIN '||V_ESQUEMA||'.DD_TCA_TIPO_CALIDAD TCA ON TCA.DD_TCA_CODIGO = MIG.TIPO_CALIDAD
            LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA||' TBJ ON TBJ.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO
            WHERE MIG.VALIDACION = 0 AND TBJ.TBJ_ID IS NULL)
        SELECT '||V_ESQUEMA||'.S_ACT_TBJ_TRABAJO.NEXTVAL TBJ_ID, TBJ.*
        FROM TRABAJOS TBJ');
    
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');
    
    DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE VOLCADO SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA_2||'.');
    
    EXECUTE IMMEDIATE ('INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_2||' (ACT_ID, TBJ_ID, ACT_TBJ_PARTICIPACION)
        SELECT DISTINCT ACT.ACT_ID, TBJ.TBJ_ID, 0 ACT_TBJ_PARTICIPACION
        FROM '||V_ESQUEMA||'.'||V_TABLA||' TBJ
        INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG ON TBJ.TBJ_NUM_TRABAJO = MIG.TBJ_NUM_TRABAJO
        INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO = MIG.ACT_NUMERO_ACTIVO
        LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_2||' AT ON AT.TBJ_ID = TBJ.TBJ_ID AND AT.ACT_ID = ACT.ACT_ID
        WHERE AT.TBJ_ID IS NULL AND AT.ACT_ID IS NULL');
    
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' '||V_ESQUEMA||'.'||V_TABLA_2||' cargada. '||SQL%ROWCOUNT||' Filas.');
    
    V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''1''); END;';
    EXECUTE IMMEDIATE V_SENTENCIA;
    
    V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA_2||''',''1''); END;';
    EXECUTE IMMEDIATE V_SENTENCIA;

    DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/
EXIT;