OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_2419
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ID_HAYA						NULLIF(ID_HAYA=BLANKS)						"TRIM(:ID_HAYA)",
	PROPIETARIO_MALO				NULLIF(PROPIETARIO_MALO=BLANKS)					"TRIM(:PROPIETARIO_MALO)",
	PROPIETARIO_BUENO				NULLIF(PROPIETARIO_BUENO=BLANKS)				"TRIM(:PROPIETARIO_BUENO)",
	NIF					        NULLIF(NIF=BLANKS)						"TRIM(:NIF)"
)
