/* Formatted on 2009/01/12 16:31 (Formatter Plus v4.8.8) */
REVOKE DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dd_tpo_tipo_procedimiento FROM pfs04 CASCADE CONSTRAINTS;

REVOKE DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dd_tpo_tipo_procedimiento FROM pfs03 CASCADE CONSTRAINTS;

REVOKE DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dd_tpo_tipo_procedimiento FROM pfs02 CASCADE CONSTRAINTS;

REVOKE DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dd_tpo_tipo_procedimiento FROM pfs01 CASCADE CONSTRAINTS;

ALTER TABLE dd_tpo_tipo_procedimiento
 DROP PRIMARY KEY CASCADE;
DROP TABLE dd_tpo_tipo_procedimiento CASCADE CONSTRAINTS;

ALTER TABLE dd_tpo_tipo_procedimiento_lg
 DROP PRIMARY KEY CASCADE;
DROP TABLE dd_tpo_tipo_procedimiento_lg CASCADE CONSTRAINTS;

--Esta tabla ha sido renombrada a DD_EFC_ESTADO_FINAN_CNT_LG
ALTER TABLE DD_EFC_ESTADO_FINAN_CNT_LNG
 DROP PRIMARY KEY CASCADE;
DROP TABLE DD_EFC_ESTADO_FINAN_CNT_LNG CASCADE CONSTRAINTS;

--Esta tabla ha sido renombrada a DD_ESC_ESTADO_CNT_LG
ALTER TABLE DD_ESC_ESTADO_CNT_LNG
 DROP PRIMARY KEY CASCADE;
DROP TABLE DD_ESC_ESTADO_CNT_LNG CASCADE CONSTRAINTS;




DROP SEQUENCE s_dd_tpo_tipo_procedimiento_lg;

DROP SEQUENCE s_dd_tpo_tipo_procedimiento;

DROP SEQUENCE DEFEREDEVENT_SEQ;

DROP SEQUENCE S_DD_PRA_PROPUESTA_AAA_LG;

DROP SEQUENCE S_DD_CIM_CAUSAS_IMPAGO_LG;
DROP SEQUENCE S_DD_CPR_CAUSA_PRORROGA_LG;
DROP SEQUENCE S_DD_CTL_CAUSA_EXCLUSION_LG;
DROP SEQUENCE S_DD_DTI_TIPO_INCIDENCIAS_LG;
DROP SEQUENCE S_DD_EIN_ENT_INFO_LG;
DROP SEQUENCE S_DD_EST_EST_ITI_LG;
DROP SEQUENCE S_DD_FMG_FASES_MG_LG;
DROP SEQUENCE S_DD_LOC_LOCALIDAD_LG;
DROP SEQUENCE S_DD_MON_MONEDAS_LG;
DROP SEQUENCE S_DD_PRV_PROVINCIA_LG;
DROP SEQUENCE S_DD_RPR_RAZON_PRORROGA_LG;
DROP SEQUENCE S_DD_SMG_SUBFASES_MG_LG;
DROP SEQUENCE S_DD_STA_SUBTIPO_TAREA_BASE_LG;
DROP SEQUENCE S_DD_STI_SITUACION_LG;
DROP SEQUENCE S_DD_TAA_TIP_AYUDA_ACT_LG;
DROP SEQUENCE S_DD_TAC_TIPO_ACTUACION_LG;
DROP SEQUENCE S_DD_TAR_TIPO_TAREA_BASE_LG;
DROP SEQUENCE S_DD_TBI_TIPO_BIEN_LG;
DROP SEQUENCE S_DD_TDI_TIPO_DOCUMENTO_ID_LG;
DROP SEQUENCE S_DD_TGA_TIPO_GARANTIA_LG;
DROP SEQUENCE S_DD_TIG_TIPO_INGRESO_LG;
DROP SEQUENCE S_DD_TPE_TIPO_PERSONA_LG;
DROP SEQUENCE S_DD_TRE_TIPO_RECLAMACION_LG;
DROP SEQUENCE S_DD_TTG_TIPO_TIT_GEN_LG;
DROP SEQUENCE S_DD_TTI_TIPO_TITULO_LG;
DROP SEQUENCE S_DD_TVI_TIPO_VIA_LG;
DROP SEQUENCE S_DD_PRO_PROPIEDAD;
DROP SEQUENCE S_DD_VCO_VISTA_COMPONENTE;
DROP SEQUENCE S_DD_COM_COMPONENTE;
DROP SEQUENCE S_DD_VIS_VISTA;
DROP SEQUENCE S_DD_DFR_FAVORABLE_RECURSO;



ALTER TABLE DD_DTI_TIPO_INCIDENCIAS DROP COLUMN USUARIOMODIF;

ALTER TABLE DD_DTI_TIPO_INCIDENCIAS_LG DROP COLUMN USUARIOMODIF;

ALTER TABLE DD_EDE_ESTADOS_DECISION_LG DROP COLUMN DD_EDE_CODIGO;

ALTER TABLE DD_DFR_FAVORABLE_RECURSO_LG
 DROP PRIMARY KEY CASCADE;
DROP TABLE DD_DFR_FAVORABLE_RECURSO_LG CASCADE CONSTRAINTS;

ALTER TABLE DD_DFR_FAVORABLE_RECURSO
 DROP PRIMARY KEY CASCADE;
DROP TABLE DD_DFR_FAVORABLE_RECURSO CASCADE CONSTRAINTS;

COMMIT;
