INSERT INTO exp_expedientes (EXP_ID, ARQ_ID, OFI_ID,AAA_ID,DCO_ID,DD_EST_ID,DD_EEX_ID,EXP_PROCESS_BPM,EXP_FECHA_EST_ID,USUARIOCREAR,FECHACREAR,BORRADO) 
VALUES (500,9999,1,null,null,3,1,null,${sql.function.curdate},'BATCH_USER',${sql.function.curdate},0);

INSERT INTO cnt_contratos (CNT_ID,DD_TPE_ID,OFI_ID,ZON_ID,DD_MON_ID,DD_TPR_ID,CNT_FECHA_EXTRACCION,CNT_COD_ENTIDAD,CNT_COD_OFICINA,CNT_COD_CENTRO,CNT_CONTRATO,DD_EFC_ID,CNT_FECHA_EFC,DD_ESC_ID,CNT_FECHA_ESC,CNT_FECHA_CREACION,CNT_FECHA_CARGA,CNT_FICHERO_CARGA,USUARIOCREAR,FECHACREAR,BORRADO) 
VALUES (101,1,1,1,1,10101,${sql.function.curdate},1001,1,666666,101,1,${sql.function.curdate},1,${sql.function.curdate},null,${sql.function.curdate},'fichero','BATCH_USER',${sql.function.curdate},0);

INSERT INTO MOV_MOVIMIENTOS (MOV_ID,CNT_ID,MOV_POS_VIVA_NO_VENCIDA,MOV_POS_VIVA_VENCIDA,MOV_FECHA_POS_VENCIDA,MOV_SALDO_DUDOSO,MOV_FECHA_DUDOSO, MOV_PROVISION,MOV_INT_REMUNERATORIOS, MOV_INT_MORATORIOS,MOV_COMISIONES, MOV_GASTOS,MOV_FECHA_EXTRACCION, MOV_FECHA_CARGA,MOV_FICHERO_CARGA,USUARIOCREAR,FECHACREAR)
VALUES (301,101,10000,215,${sql.function.curdate}-1,15,${sql.function.curdate}-1,22,5,10,25,45,${sql.function.curdate},${sql.function.curdate},'FICHERO1','BATCH',${sql.function.curdate});

INSERT INTO cex_contratos_expediente (CEX_ID, CNT_ID, EXP_ID,CEX_PASE, USUARIOCREAR, FECHACREAR, BORRADO)
VALUES(501, 101, 500, 1,'BATCH_USER',${sql.function.curdate},0 );

INSERT INTO asu_asuntos(ASU_ID,EXP_ID, GAS_ID, DD_EST_ID, DD_EAS_ID, ASU_PROCESS_BPM, USUARIOCREAR, FECHACREAR, ASU_FECHA_EST_ID)
VALUES (601, 500,1, 6, 2, null, 'BATCH', ${sql.function.curdate},${sql.function.curdate});

INSERT INTO prc_procedimientos (PRC_ID,  ASU_ID, CEX_ID, USUARIOCREAR, FECHACREAR)
VALUES(1212134, 601, 501,'BATCH', ${sql.function.curdate});