-- nuevos tipos de inputs de procedimiento monitorio

/*
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'INADM_CON_PROC_LEGAL', 'Inadmisión con procurador legal', 'Inadmisión con procurador legal',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);

Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'INADM_SIN_PROC_LEGAL', 'Inadmisión sin procurador legal', 'Inadmisión sin procurador legal',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
   

Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'REQ_PAG_POS_CON_PROC_LEG', 'Requerimiento pago positivo con procurador total', 'Requerimiento pago positivo con procurador total',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'REQ_PAG_POS_SIN_PROC_LEG', 'Requerimiento pago positivo sin procurador total', 'Requerimiento pago positivo sin procurador total',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
   
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'REQ_PAG_NEG_CON_PROC_LEG', 'Requerimiento pago negativo con procurador', 'Requerimiento pago negativo con procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);

Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'REQ_PAG_NEG_SIN_PROC_LEG', 'Requerimiento pago negativo sin procurador', 'Requerimiento pago negativo sin procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
      
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_POS_CON_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Positiva con procurador)', 'Contestación Oficios de Localización (Averiguación Positiva con procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_POS_SIN_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Positiva sin procurador)', 'Contestación Oficios de Localización (Averiguación Positiva sin procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
    
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_NEG_CON_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Negativa con procurador)', 'Contestación Oficios de Localización (Averiguación Negativa con procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);

Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_NEG_SIN_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Negativa sin procurador)', 'Contestación Oficios de Localización (Averiguación Negativa sin procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
   
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_REP_CON_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Repetida con procurador)', 'Contestación Oficios de Localización (Averiguación Repetida con procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'AVERIG_REP_SIN_PROC_LEG', 'Contestación Oficios de Localización (Averiguación Repetida sin procurador)', 'Contestación Oficios de Localización (Averiguación Repetida sin procurador)',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
    
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'SOL_CTA_INGRESO_CON_PROC_LEG', 'Solicitud cta para ingreso de cta consignada con procurador', 'Solicitud cta para ingreso de cta consignada con procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'SOL_CTA_INGRESO_SIN_PROC_LEG', 'Solicitud cta para ingreso de cta consignada sin procurador', 'Solicitud cta para ingreso de cta consignada sin procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
    
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'COMUNIC_PAGO_CTA_LEG', 'Comunicación pago en cta sin procurador', 'Comunicación pago en cta sin procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
  
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'CONTINUAR_PRC_CON_PROC', 'DECISION: Continuar con procurador', 'DECISION: Continuar con procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
 
Insert into BPM_DD_TIN_TIPO_INPUT
   (BPM_DD_TIN_ID, BPM_DD_TIN_CODIGO, BPM_DD_TIN_DESCRIPCION, BPM_DD_TIN_DESCRIPCION_LARGA,BPM_DD_TAC_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_BPM_DD_TIN_TIPO_INPUT.nextval , 'CONTINUAR_PRC_SIN_PROC', 'DECISION: Continuar sin procurador', 'DECISION: Continuar sin procurador',(SELECT BPM_DD_TAC_ID FROM BPM_DD_TAC_TIPO_ACCION WHERE BPM_DD_TAC_CODIGO='GDOC') , 0, 'MASIVO', sysdate , 0);
    
COMMIT; 
*/

-- creación de diccionario de datos de tipos de generación de escritos
  
--DROP SEQUENCE S_DD_TGE_TIPO_GENERACION_ESCRITO;
--CREATE SEQUENCE S_DD_TGE_TIPO_GENERACION_ESCRITO;

--DROP TABLE DD_TGE_TIPO_GENERACION_ESCRITO;
/*
CREATE TABLE DD_TGE_TIPO_GENERACION_ESCRITO  (
   DD_TGE_ID		 			NUMBER(16)			NOT NULL,
   DD_TGE_CODIGO           		VARCHAR2(50 BYTE)   NOT NULL,
   DD_TGE_DESCRIPCION       	VARCHAR2(50 BYTE),
   DD_TGE_DESCRIPCION_LARGA     VARCHAR2(250 BYTE),
   VERSION                  	INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             	VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               	TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         	VARCHAR2(10 BYTE),
   FECHAMODIFICAR           	TIMESTAMP(6),
   USUARIOBORRAR            	VARCHAR2(10 BYTE),
   FECHABORRAR              	TIMESTAMP(6),
   BORRADO                 		 NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT DD_TGE_TIPO_GENERACION_ESCRITO PRIMARY KEY (DD_TGE_ID)
);  

INSERT INTO DD_TGE_TIPO_GENERACION_ESCRITO (DD_TGE_ID,DD_TGE_CODIGO,DD_TGE_DESCRIPCION,DD_TGE_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_TGE_TIPO_GENERACION_ESCRITO.nextVal,'DIRECTA','Generación directa','Generación directa','DD',SYSDATE);
	
INSERT INTO DD_TGE_TIPO_GENERACION_ESCRITO (DD_TGE_ID,DD_TGE_CODIGO,DD_TGE_DESCRIPCION,DD_TGE_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_TGE_TIPO_GENERACION_ESCRITO.nextVal,'DIFERIDA','Generación diferida','Generación diferida','DD',SYSDATE);	
	
commit;
*/


   