ALTER TABLE ITP_INFORMES_TPO
 DROP PRIMARY KEY CASCADE;
DROP TABLE ITP_INFORMES_TPO CASCADE CONSTRAINTS;

CREATE TABLE ITP_INFORMES_TPO
(
  ITP_ID                 NUMBER(16)             NOT NULL,
  ITP_CODIGO             VARCHAR2(50 BYTE),
  ITP_DESCRIPCION        VARCHAR2(50 BYTE),
  ITP_DESCRIPCION_LARGA  VARCHAR2(250 BYTE),
  DD_TPO_ID              NUMBER(16)             NOT NULL
);


CREATE UNIQUE INDEX PK_ITP_INFORMES_TPO ON ITP_INFORMES_TPO
(ITP_ID)
LOGGING
TABLESPACE LIN001
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ITP_INFORMES_TPO ADD (
  CONSTRAINT PK_ITP_INFORMES_TPO
 PRIMARY KEY
 (ITP_ID)
    USING INDEX 
    TABLESPACE LIN001
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ITP_INFORMES_TPO ADD (
  CONSTRAINT FK_ITP_TPO 
 FOREIGN KEY (DD_TPO_ID) 
 REFERENCES DD_TPO_TIPO_PROCEDIMIENTO (DD_TPO_ID));


CREATE SEQUENCE S_ITP_INFORMES_TPO
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
  
  /*Informar los datos*/
  
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ARCHIVO_LEV_EB_ETJ','Archivo y levantamiento EB','Archivo y levantamiento EB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LEVANT_SUSP','Alzamiento de Suspensión','Alzamiento de Suspensión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACLARACION_CUANTIA','Aclaración de cuantía','Aclaración de cuantía', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ACREDIT_TITUL_CUENT','Acreditar titularidad de cuenta','Acreditar titularidad de cuenta', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CERTIFICADO_DEUDA','Certificado de deuda','Certificado de deuda', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CERTIF_DOBLE_CESION','Certificado de doble cesión','Certificado de doble cesión', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'COMUNIC_PAGOS_ETJ','Comunicación de pagos','Comunicación de pagos', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

  Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_ETJ','Demanda de procedimiento de ejecución','Demanda de procedimiento de ejecución', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_ETJ','Demanda de procedimiento de ejecución','Demanda de procedimiento de ejecución', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
   
  Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_ETJ_BARNEY','Demanda de procedimiento de ejecución (BARNEY)','Demanda de procedimiento de ejecución (BARNEY)', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_ETJ_BARNEY','Demanda de procedimiento de ejecución (BARNEY)','Demanda de procedimiento de ejecución (BARNEY)', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
   
Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_MONITORIO','Demanda de proceso monitorio','Demanda de proceso monitorio', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P71'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DEMANDA_MONITORIO','Demanda de proceso monitorio','Demanda de proceso monitorio', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'DESGLOSE','Desglose','Desglose', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ENVIO_MDTO_EXHORTO','Envío mandamiento por exhorto','Envío mandamiento por exhorto', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_NOCTURNAS','Escrito habilitando horas nocturnas','Escrito habilitando horas nocturnas', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_EMBARGO','Escrito de embargo','Escrito de embargo', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'ESCRITO_AV_DNI_NUEV_AB_ETJ','Escrito averiguación DNI y nueva AB','Escrito averiguación DNI y nueva AB', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'INGRESO_CUANTIA','Ingreso de cuantía consignada','Ingreso de cuantía consignada', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));

 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'LIBRAR_OFC_LOCAL','Librar oficios para localización','Librar oficios para localización', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'REQ_DOMICILIO_LABORAL','Requerimiento en domicilio laboral','Requerimiento en domicilio laboral', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'REQ_OTROS_DOMICILIO','Requerimiento en otros domicilios','Requerimiento en otros domicilios', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'SOL_DEC_FIN_MONIT','Solicitud decreto que pone fin a monitorio','Solicitud decreto que pone fin a monitorio', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
     
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P70'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P72'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P76'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P80'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P79'));
 Insert into ITP_INFORMES_TPO (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID) Values (S_ITP_INFORMES_TPO.NEXTVAL, 'CESION_CREDITO','Escrito cesión de crédito','Escrito cesión de crédito', (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO = 'P78'));
 
 Insert into ITP_INFORMES_TPO
   (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID)
 Values
   (S_ITP_INFORMES_TPO.NEXTVAL, 'SOL_COM_EDICTOS_ETJ', 'Solicitud comunicación por edictos ETJ', 'Solicitud comunicación por edictos ETJ',
   (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO='P72'));
   
Insert into ITP_INFORMES_TPO
   (ITP_ID, ITP_CODIGO, ITP_DESCRIPCION, ITP_DESCRIPCION_LARGA, DD_TPO_ID)
 Values
   (S_ITP_INFORMES_TPO.NEXTVAL, 'NUEV_AVERIG_ETJ', 'Solicitud nueva averiguación ETJ', 'Solicitud nueva averiguación ETJ',
   (SELECT DD_TPO_ID FROM DD_TPO_TIPO_PROCEDIMIENTO WHERE DD_TPO_CODIGO='P72'));
 
commit;   
 