--/*
--##########################################
--## AUTOR=JAVIER DIAZ RAMOS
--## FECHA_CREACION=20150724
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=CMREC-443
--## PRODUCTO=NO
--## 
--## Finalidad: Inserción de datos de Diccionarios RECIBOS Cajamar , esquema #ESQUEMA#.
--## INSTRUCCIONES:  Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
DECLARE
  
   TYPE T_TRE IS TABLE OF VARCHAR2(150);
   TYPE T_ARRAY_TRE IS TABLE OF T_TRE;

   TYPE T_SIR IS TABLE OF VARCHAR2(150);
   TYPE T_ARRAY_SIR IS TABLE OF T_SIR;

   TYPE T_MID IS TABLE OF VARCHAR2(150);
   TYPE T_ARRAY_MID IS TABLE OF T_MID;

   TYPE T_MIR IS TABLE OF VARCHAR2(150);
   TYPE T_ARRAY_MIR IS TABLE OF T_MIR;
--/*
--##########################################
--## Configuraciones a rellenar
--##########################################
--*/
  -- Configuracion Esquemas
   V_ESQUEMA VARCHAR(25) := '#ESQUEMA#';
   V_ESQUEMA_MASTER VARCHAR(25) := '#ESQUEMA_MASTER#';
   

   V_USUARIO_CREAR VARCHAR2(10) := 'INICIAL';
   
  
   

   
--/* Configuracion DD_TRE_TIPO_RECIBO
--	(
--	  DD_TRE_CODIGO             VARCHAR2(50 CHAR)   NOT NULL,
--	  DD_TRE_DESCRIPCION        VARCHAR2(50 CHAR),
--	  DD_TRE_DESCRIPCION_LARGA  VARCHAR2(250 CHAR)
--	)*/
                                   
   V_TRE T_ARRAY_TRE := T_ARRAY_TRE(
		T_TRE('000','SIN VALORES','SIN VALORES')
		
                                   );

--/* Configuracion DD_SIR_SITUACION_RECIBO
--	(
--	  DD_SIR_CODIGO             VARCHAR2(50 CHAR)   NOT NULL,
--	  DD_SIR_DESCRIPCION        VARCHAR2(50 CHAR),
--	  DD_SIR_DESCRIPCION_LARGA  VARCHAR2(250 CHAR)
--	)*/
                                   
   V_SIR T_ARRAY_SIR := T_ARRAY_SIR(
		T_SIR('0','RECIBO NO COBRADO (TOTAL O PARCIALMENTE)','RECIBO NO COBRADO (TOTAL O PARCIALMENTE)'),
		T_SIR('1','RECIBO COBRADO (CON ALGÚN COBRO PARCIAL)','RECIBO COBRADO (CON ALGÚN COBRO PARCIAL)'),
		T_SIR('2','RECIBO COBRADO (SIN COBROS PARCIALES)','RECIBO COBRADO (SIN COBROS PARCIALES)'),
		T_SIR('3','RECIBO DESACTIVADO POR PASE A LITIGIO','RECIBO DESACTIVADO POR PASE A LITIGIO'),
		T_SIR('4','RECIBO GENERADO DURANTE EL PERIODO DE LITIGIO EL CUAL HA SIDO REGULARIZADO','RECIBO GENERADO DURANTE EL PERIODO DE LITIGIO EL CUAL HA SIDO REGULARIZADO')
                                   );

--/* Configuracion DD_MID_MOTIVO_DEVOLUCION
--	(
--	  DD_MID_CODIGO             VARCHAR2(50 CHAR)   NOT NULL,
--	  DD_MID_DESCRIPCION        VARCHAR2(50 CHAR),
--	  DD_MID_DESCRIPCION_LARGA  VARCHAR2(250 CHAR)
--	)*/
                                   
   V_MID T_ARRAY_MID := T_ARRAY_MID(
		T_MID('000','SIN VALORES','SIN VALORES')
 );
--/* Configuracion DD_MIR_MOTIVO_RECHAZO
--	(
--	  DD_MIR_CODIGO             VARCHAR2(50 CHAR)   NOT NULL,
--	  DD_MIR_DESCRIPCION        VARCHAR2(50 CHAR),
--	  DD_MIR_DESCRIPCION_LARGA  VARCHAR2(250 CHAR)
--	)*/
                                   
   V_MIR T_ARRAY_MIR := T_ARRAY_MIR(
		T_MIR('000','SIN VALORES','SIN VALORES')
 );
--/*
--##########################################
--## FIN Configuraciones a rellenar
--##########################################
--*/  
   
   V_MSQL VARCHAR(5000);
   V_EXIST NUMBER(10);

   V_ENTIDAD_ID NUMBER(16);
   V_PEF_ID NUMBER;
   
   V_TMP_SIR T_SIR;
   V_TMP_TRE T_TRE;
   V_TMP_MID T_MID;
   V_TMP_MIR T_MIR;

   err_num NUMBER;
   err_msg VARCHAR2(255);
BEGIN
	DBMS_OUTPUT.PUT_LINE('Se borra la configuración de TIPO RECIBO.');
	EXECUTE IMMEDIATE('DELETE FROM '|| V_ESQUEMA ||'.DD_TRE_TIPO_RECIBO');

	DBMS_OUTPUT.PUT_LINE('Se borra la configuración de SITUACION_RECIBO.');
	EXECUTE IMMEDIATE('DELETE FROM '|| V_ESQUEMA ||'.DD_SIR_SITUACION_RECIBO');

	DBMS_OUTPUT.PUT_LINE('Se borra la configuración de MOTIVO_DEVOLUCION.');
	EXECUTE IMMEDIATE('DELETE FROM '|| V_ESQUEMA ||'.DD_MID_MOTIVO_DEVOLUCION');

	DBMS_OUTPUT.PUT_LINE('Se borra la configuración de MOTIVO_RECHAZO.');
	EXECUTE IMMEDIATE('DELETE FROM '|| V_ESQUEMA ||'.DD_MIR_MOTIVO_RECHAZO');

    DBMS_OUTPUT.PUT_LINE('Reseteamos los contadores......');
    V_ENTIDAD_ID:=0;
    SELECT count(*) INTO V_ENTIDAD_ID
    FROM all_sequences
    WHERE sequence_name = 'S_DD_TRE_TIPO_RECIBO' and sequence_owner=V_ESQUEMA;
    if V_ENTIDAD_ID is not null and V_ENTIDAD_ID = 1 then
	DBMS_OUTPUT.PUT_LINE('Contador 1');
	EXECUTE IMMEDIATE('DROP SEQUENCE '|| V_ESQUEMA || '.S_DD_TRE_TIPO_RECIBO');
    end if;
    EXECUTE IMMEDIATE('CREATE SEQUENCE '|| V_ESQUEMA || '.S_DD_TRE_TIPO_RECIBO
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 1
	NOCYCLE
	CACHE 20
	NOORDER');	

    V_ENTIDAD_ID:=0;
    SELECT count(*) INTO V_ENTIDAD_ID
    FROM all_sequences
    WHERE sequence_name = 'S_DD_SIR_SITUACION_RECIBO' and sequence_owner=V_ESQUEMA;
    if V_ENTIDAD_ID is not null and V_ENTIDAD_ID = 1 then
	DBMS_OUTPUT.PUT_LINE('Contador 2');
	EXECUTE IMMEDIATE('DROP SEQUENCE '|| V_ESQUEMA || '.S_DD_SIR_SITUACION_RECIBO');
    end if;
    EXECUTE IMMEDIATE('CREATE SEQUENCE '|| V_ESQUEMA || '.S_DD_SIR_SITUACION_RECIBO
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 1
	NOCYCLE
	CACHE 20
	NOORDER');	

    V_ENTIDAD_ID:=0;
    SELECT count(*) INTO V_ENTIDAD_ID
    FROM all_sequences
    WHERE sequence_name = 'S_DD_MID_MOTIVO_DEVOLUCION' and sequence_owner=V_ESQUEMA;
    if V_ENTIDAD_ID is not null and V_ENTIDAD_ID = 1 then
	DBMS_OUTPUT.PUT_LINE('Contador 3');
	EXECUTE IMMEDIATE('DROP SEQUENCE '|| V_ESQUEMA || '.S_DD_MID_MOTIVO_DEVOLUCION');
    end if;
    EXECUTE IMMEDIATE('CREATE SEQUENCE '|| V_ESQUEMA || '.S_DD_MID_MOTIVO_DEVOLUCION
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 1
	NOCYCLE
	CACHE 20
	NOORDER');

    V_ENTIDAD_ID:=0;
    SELECT count(*) INTO V_ENTIDAD_ID
    FROM all_sequences
    WHERE sequence_name = 'S_DD_MIR_MOTIVO_RECHAZO' and sequence_owner=V_ESQUEMA;
    if V_ENTIDAD_ID is not null and V_ENTIDAD_ID = 1 then
	DBMS_OUTPUT.PUT_LINE('Contador 4');
	EXECUTE IMMEDIATE('DROP SEQUENCE '|| V_ESQUEMA || '.S_DD_MIR_MOTIVO_RECHAZO');
    end if;
    EXECUTE IMMEDIATE('CREATE SEQUENCE '|| V_ESQUEMA || '.S_DD_MIR_MOTIVO_RECHAZO
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 1
	NOCYCLE
	CACHE 20
	NOORDER');

   DBMS_OUTPUT.PUT_LINE('Creando DD_TRE_TIPO_RECIBO......');
   FOR I IN V_TRE.FIRST .. V_TRE.LAST
   LOOP
   	V_MSQL := 'SELECT '||V_ESQUEMA||'.S_DD_TRE_TIPO_RECIBO.NEXTVAL FROM DUAL';
   	EXECUTE IMMEDIATE V_MSQL INTO V_ENTIDAD_ID;
      V_TMP_TRE := V_TRE(I);
      DBMS_OUTPUT.PUT_LINE('Creando TRE: '||V_TMP_TRE(1));   

      V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.DD_TRE_TIPO_RECIBO (DD_TRE_ID, DD_TRE_CODIGO, DD_TRE_DESCRIPCION,' ||
		'DD_TRE_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO) ' ||
                 ' VALUES ('||  V_ENTIDAD_ID || ','''||V_TMP_TRE(1)||''','''||V_TMP_TRE(2)||''','''
		 ||V_TMP_TRE(3)||''',0,'''||V_USUARIO_CREAR||''',SYSDATE,0)';
      EXECUTE IMMEDIATE V_MSQL;
   END LOOP; --LOOP TIPO_RECIBO
   V_TMP_TRE := NULL;
   V_TRE := NULL;

   DBMS_OUTPUT.PUT_LINE('Creando DD_SIR_SITUACION_RECIBO......');
   FOR I IN V_SIR.FIRST .. V_SIR.LAST
   LOOP
   	V_MSQL := 'SELECT '||V_ESQUEMA||'.S_DD_SIR_SITUACION_RECIBO.NEXTVAL FROM DUAL';
   	EXECUTE IMMEDIATE V_MSQL INTO V_ENTIDAD_ID;
      V_TMP_SIR := V_SIR(I);
      DBMS_OUTPUT.PUT_LINE('Creando SIR: '||V_TMP_SIR(1));   

      V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.DD_SIR_SITUACION_RECIBO (DD_SIR_ID, DD_SIR_CODIGO, DD_SIR_DESCRIPCION,' ||
		'DD_SIR_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO) ' ||
                 ' VALUES ('||  V_ENTIDAD_ID || ','''||V_TMP_SIR(1)||''','''||SUBSTR(V_TMP_SIR(2),1,50)||''','''
		 ||V_TMP_SIR(3)||''',0,'''||V_USUARIO_CREAR||''',SYSDATE,0)';
      EXECUTE IMMEDIATE V_MSQL;
   END LOOP; --LOOP TIPO_SITUACIONRECIBO
   V_TMP_SIR := NULL;
   V_SIR := NULL;

   DBMS_OUTPUT.PUT_LINE('Creando DD_MID_MOTIVO_DEVOLUCION......');
   FOR I IN V_MID.FIRST .. V_MID.LAST
   LOOP
   	V_MSQL := 'SELECT '||V_ESQUEMA||'.S_DD_MID_MOTIVO_DEVOLUCION.NEXTVAL FROM DUAL';
   	EXECUTE IMMEDIATE V_MSQL INTO V_ENTIDAD_ID;
      V_TMP_MID := V_MID(I);
      DBMS_OUTPUT.PUT_LINE('Creando MID: '||V_TMP_MID(1));   

      V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.DD_MID_MOTIVO_DEVOLUCION (DD_MID_ID, DD_MID_CODIGO, DD_MID_DESCRIPCION,' ||
		'DD_MID_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO) ' ||
                 ' VALUES ('||  V_ENTIDAD_ID || ','''||V_TMP_MID(1)||''','''||V_TMP_MID(2)||''','''
		 ||V_TMP_MID(3)||''',0,'''||V_USUARIO_CREAR||''',SYSDATE,0)';
      EXECUTE IMMEDIATE V_MSQL;
   END LOOP; --LOOP MOTIVO_DEVOLUCION
   V_TMP_MID := NULL;
   V_MID := NULL;

   DBMS_OUTPUT.PUT_LINE('Creando DD_MIR_MOTIVO_RECHAZO......');
   FOR I IN V_MIR.FIRST .. V_MIR.LAST
   LOOP
   	V_MSQL := 'SELECT '||V_ESQUEMA||'.S_DD_MIR_MOTIVO_RECHAZO.NEXTVAL FROM DUAL';
   	EXECUTE IMMEDIATE V_MSQL INTO V_ENTIDAD_ID;
      V_TMP_MIR := V_MIR(I);
      DBMS_OUTPUT.PUT_LINE('Creando MIR: '||V_TMP_MIR(1));   

      V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.DD_MIR_MOTIVO_RECHAZO (DD_MIR_ID, DD_MIR_CODIGO, DD_MIR_DESCRIPCION,' ||
		'DD_MIR_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO) ' ||
                 ' VALUES ('||  V_ENTIDAD_ID || ','''||V_TMP_MIR(1)||''','''||V_TMP_MIR(2)||''','''
		 ||V_TMP_MIR(3)||''',0,'''||V_USUARIO_CREAR||''',SYSDATE,0)';
      EXECUTE IMMEDIATE V_MSQL;
   END LOOP; --LOOP MOTIVO_DEVOLUCION
   V_TMP_MIR := NULL;
   V_MIR := NULL;

   COMMIT;

EXCEPTION

WHEN OTHERS THEN  
  err_num := SQLCODE;
  err_msg := SQLERRM;

  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
  
  ROLLBACK;
  RAISE;
END;
/
EXIT;