OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_4149
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	GPV_NUM_GASTO_HAYA			NULLIF(GPV_NUM_GASTO_HAYA=BLANKS)			"TRIM(:GPV_NUM_GASTO_HAYA)",
	PRO_DOCIDENTIF				NULLIF(PRO_DOCIDENTIF=BLANKS)				"TRIM(:PRO_DOCIDENTIF)"
)
