--/*
--##########################################
--## AUTOR=Alejandra García
--## FECHA_CREACION=20220704
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-18259
--## PRODUCTO=NO
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE

    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar    
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_TABLESPACE_IDX VARCHAR2(25 CHAR):= '#TABLESPACE_INDEX#'; -- Configuracion Tablespace de Indices
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.  
    V_NUM_SEQ NUMBER(16); -- Vble. para validar la existencia de una secuencia.  
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.

    V_TEXT1 VARCHAR2(2400 CHAR); -- Vble. auxiliar 
    V_TEXT_TABLA VARCHAR2(2400 CHAR) := 'AUX_BCR_STOCK_CONCURRENCIA_REJ'; -- Vble. auxiliar para almacenar el nombre de la tabla de ref.
    V_COMMENT_TABLE VARCHAR2(500 CHAR):= 'Tabla auxiliar con lois rechazos debido a la concurrencia'; -- Vble. para los comentarios de las tablas

BEGIN
    
    DBMS_OUTPUT.PUT_LINE('********' ||V_TEXT_TABLA|| '********'); 
    DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.'||V_TEXT_TABLA||'... Comprobaciones previas');
    

    -- Verificar si la tabla ya existe
    V_MSQL := 'SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME = '''||V_TEXT_TABLA||''' and owner = '''||V_ESQUEMA||'''';
    EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS; 
    IF V_NUM_TABLAS = 1 THEN
        DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.'||V_TEXT_TABLA||'... Ya existe. Se borrará.');
        EXECUTE IMMEDIATE 'DROP TABLE '||V_ESQUEMA||'.'||V_TEXT_TABLA||' CASCADE CONSTRAINTS';
        
    END IF;

    
    -- Creamos la tabla
    DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA|| '.'||V_TEXT_TABLA||'...');
    V_MSQL := 'CREATE TABLE ' ||V_ESQUEMA||'.'||V_TEXT_TABLA||'
    (
           
          NUM_IDENTIFICATIVO	VARCHAR2(8 CHAR)
        , NUM_UNIDAD	VARCHAR2(8 CHAR)
        , CLASE_USO	VARCHAR2(4 CHAR)
        , NUM_INMUEBLE	VARCHAR2(16 CHAR)
        , CUOTA	VARCHAR2(10 CHAR)
        , GRADO_PROPIEDAD	VARCHAR2(2 CHAR)
        , FEC_VALIDO_DE	VARCHAR2(8 CHAR)
        , FEC_VALIDO_A	VARCHAR2(8 CHAR)
        , STATUS_USUARIO	VARCHAR2(4 CHAR)
        , SITUACION_ALQUILER	VARCHAR2(1 CHAR)
        , SOCIEDAD_PATRIMONIAL	VARCHAR2(4 CHAR)
        , SUBTIPO_VIVIENDA	VARCHAR2(6 CHAR)
        , SUBTIPO_SUELO	VARCHAR2(3 CHAR)
        , NUM_INMUEBLE_ANTERIOR	VARCHAR2(20 CHAR)
        , PRODUCTO	VARCHAR2(2 CHAR)
        , PROCEDENCIA_PRODUCTO	VARCHAR2(2 CHAR)
        , SOCIEDAD_ORIGEN	VARCHAR2(4 CHAR)
        , BANCO_ORIGEN	VARCHAR2(4 CHAR)
        , FINCA	VARCHAR2(10 CHAR)
        , LIBRO	VARCHAR2(4 CHAR)
        , TOMO	VARCHAR2(4 CHAR)
        , FOLIO	VARCHAR2(4 CHAR)
        , INSCRIPCION	VARCHAR2(4 CHAR)
        , NUM_CARTILLA	VARCHAR2(40 CHAR)
        , ORIGEN_REGULATORIO	VARCHAR2(2 CHAR)
        , CLASE_USO_REGISTRAL	VARCHAR2(4 CHAR)
        , IDUFIR	VARCHAR2(20 CHAR)
        , VIVIENDA_HABITUAL	VARCHAR2(1 CHAR)
        , FEC_PRESENTACION_REGISTRO	VARCHAR2(8 CHAR)
        , FEC_INSC_TITULO	VARCHAR2(8 CHAR)
        , FEC_ADJUDICACION	VARCHAR2(8 CHAR)
        , FEC_TITULO_FIRME	VARCHAR2(8 CHAR)
        , IMPORTE_CESION	VARCHAR2(10 CHAR)
        , FEC_CESION_REMATE	VARCHAR2(8 CHAR)
        , FEC_PRESENTADO	VARCHAR2(8 CHAR)
        , INDICADOR_LLAVES	VARCHAR2(1 CHAR)
        , FEC_RECEP_LLAVES	VARCHAR2(8 CHAR)
        , NUM_AUTOS_JUZGADO	VARCHAR2(10 CHAR)
        , TIPO_IMPUESTO_COMPRA	VARCHAR2(2 CHAR)
        , SUBTIPO_IMPUESTO_COMPRA	VARCHAR2(4 CHAR)
        , PORC_IMPUESTO_COMPRA	VARCHAR2(11 CHAR)
        , COD_TP_IVA_COMPRA	VARCHAR2(2 CHAR)
        , NUM_CARGAS	VARCHAR2(1 CHAR)
        , COD_GESTORIA	VARCHAR2(9 CHAR)
        , NOMBRE_REGISTRO_PROPIEDAD	VARCHAR2(40 CHAR)
        , NUMERO_REGISTRO_PROPIEDAD	VARCHAR2(40 CHAR)
        , COD_GESTORIA_ADMINIS	VARCHAR2(9 CHAR)
        , TIPO_ALQUILER	VARCHAR2(2 CHAR)
        , COMPLEMENTO	VARCHAR2(10 CHAR)
        , CALLE	VARCHAR2(60 CHAR)
        , NUMERO	VARCHAR2(10 CHAR)
        , APARTADO	VARCHAR2(5 CHAR)
        , POBLACION	VARCHAR2(5 CHAR)
        , REGION	VARCHAR2(2 CHAR)
        , PAIS	VARCHAR2(2 CHAR)
        , CALLE2	VARCHAR2(40 CHAR)
        , DISTRITO	VARCHAR2(40 CHAR)
        , ALA_EDIFICIO	VARCHAR2(2 CHAR)
        , PLANTA	VARCHAR2(3 CHAR)
        , NUM_UBICACION	VARCHAR2(5 CHAR)
        , X_GOOGLE	VARCHAR2(23 CHAR)
        , Y_GOOGLE	VARCHAR2(23 CHAR)
        , SIGLA_EDIFICIO	VARCHAR2(20 CHAR)
        , ESTADO_TITULARIDAD	VARCHAR2(3 CHAR)
        , FEC_ESTADO_TITULARIDAD	VARCHAR2(8 CHAR)
        , ESTADO_POSESORIO	VARCHAR2(3 CHAR)
        , FEC_ESTADO_POSESORIO	VARCHAR2(8 CHAR)
        , ESTADO_COMERCIAL_ALQUILER	VARCHAR2(3 CHAR)
        , FEC_ESTADO_COMERCIAL_ALQUILER	VARCHAR2(8 CHAR)
        , ESTADO_COMERCIAL_VENTA	VARCHAR2(3 CHAR)
        , FEC_ESTADO_COMERCIAL_VENTA	VARCHAR2(8 CHAR)
        , ESTADO_TECNICO	VARCHAR2(3 CHAR)
        , FEC_ESTADO_TECNICO	VARCHAR2(8 CHAR)
        , EST_COMERCIAL_SERVICER	VARCHAR2(3 CHAR)
        , FEC_COMERCIAL_SERVICER	VARCHAR2(8 CHAR)
        , EST_DESA_PROMO_DETALLADO	VARCHAR2(3 CHAR)
        , FEC_DESA_PROMO_DETALLADO	VARCHAR2(8 CHAR)
        , EST_DESA_PROMO_GENERAL	VARCHAR2(3 CHAR)
        , FEC_DESA_PROMO_GENERAL	VARCHAR2(8 CHAR)
        , EST_ENTR_PROD_MANT_VENTA	VARCHAR2(3 CHAR)
        , FEC_ENTR_PROD_MANT_VENTA	VARCHAR2(8 CHAR)
        , EST_ENTR_PROD_MANT_ALQ	VARCHAR2(3 CHAR)
        , FEC_ENTR_PROD_MANT_ALQ	VARCHAR2(8 CHAR)
        , PROMO_CONJUNTA_OB_REM	VARCHAR2(8 CHAR)
        , PROMO_CONJUNTA_VENTA	VARCHAR2(8 CHAR)
        , PROMO_CONJUNTA_ALQUILER	VARCHAR2(8 CHAR)
        , ACTIVO_CARTERA_CONCENTRADA	VARCHAR2(1 CHAR)
        , ACTIVO_AAMM	VARCHAR2(1 CHAR)
        , ACTIVO_PROMO_ESTRATEG	VARCHAR2(1 CHAR)
        , DESTINO_COMERCIAL	VARCHAR2(2 CHAR)
        , CANAL_DISTRIBUCION_VENTA	VARCHAR2(2 CHAR)
        , MOTIVO_NO_COMERCIAL	VARCHAR2(2 CHAR)
        , FEC_INICIO_CONCURENCIA	VARCHAR2(8 CHAR)
        , FEC_FIN_CONCURENCIA	VARCHAR2(8 CHAR)
        , FEC_VISITA_INMB_SERVICER	VARCHAR2(8 CHAR)
        , FEC_PUBLICACION_SERVICER	VARCHAR2(8 CHAR)
        , PUBLICABLE_PORT_PUBLI_VENTA	VARCHAR2(1 CHAR)
        , PUBLICABLE_PORT_PUBLI_ALQUI	VARCHAR2(1 CHAR)
        , PUBLICABLE_PORT_INVER_VENTA	VARCHAR2(1 CHAR)
        , PUBLICABLE_PORT_INVER_ALQUI	VARCHAR2(1 CHAR)
        , PUBLICABLE_PORT_API_VENTA	VARCHAR2(1 CHAR)
        , PUBLICABLE_PORT_API_ALQUI	VARCHAR2(1 CHAR)
        , NECESIDAD_ARRAS	VARCHAR2(2 CHAR)
        , MOT_NECESIDAD_ARRAS	VARCHAR2(40 CHAR)
        , RENUNCIA_EXENSION	VARCHAR2(1 CHAR)
        , CARTERA_VENTA_ACTIVOS	VARCHAR2(4 CHAR)
        , CARTERA_VENTA_CREDITOS	VARCHAR2(4 CHAR)
        , CAT_COMERCIALIZACION	VARCHAR2(2 CHAR)
        , TRIBUT_PROPUESTA_VENTA	VARCHAR2(2 CHAR)
        , TRIBUT_PROPUESTA_CLI_EXT_IVA	VARCHAR2(2 CHAR)
        , CANAL_DISTRIBUCION_ALQ	VARCHAR2(2 CHAR)
        , PROMO_COMERCIAL	VARCHAR2(8 CHAR)
        , TXT_COMERCIAL_CAS_1	VARCHAR2(3000 CHAR)
        , TXT_COMERCIAL_CAS_2	VARCHAR2(3000 CHAR)
        , TXT_COMERCIAL_ENG_1	VARCHAR2(3000 CHAR)
        , TXT_COMERCIAL_ENG_2	VARCHAR2(3000 CHAR)
        , FEC_PUBLI_SERVICER_APIS	VARCHAR2(8 CHAR)
        , FEC_PUBLI_PORT_INVERSOR	VARCHAR2(8 CHAR)
        , FEC_INICIO_INFORME	VARCHAR2(8 CHAR)
        , FEC_FIN_INFORME	VARCHAR2(8 CHAR)
        , ANYO_CONCESION	VARCHAR2(4 CHAR)
        , FEC_FIN_CONCESION	VARCHAR2(8 CHAR)
        , CALIFICACION_ENERGETICA	VARCHAR2(2 CHAR)
        , CERTIFICADO_REGISTRADO	VARCHAR2(1 CHAR)
        , FEC_SOLICITUD	VARCHAR2(8 CHAR)
        , FEC_FIN_VIGENCIA	VARCHAR2(8 CHAR)
        , LISTA_EMISIONES	VARCHAR2(2 CHAR)
        , VALORES_EMISIONES	VARCHAR2(10 CHAR)
        , LISTA_ENERGIA	VARCHAR2(2 CHAR)
        , VALOR_ENERGIA	VARCHAR2(10 CHAR)
        , CEDULA_HABITABILIDAD	VARCHAR2(2 CHAR)
        , PRECIO_MAX_MOD_VENTA	VARCHAR2(10 CHAR)
        , PRECIO_MAX_MOD_ALQUILER	VARCHAR2(10 CHAR)
        , SITUACION_VPO	VARCHAR2(4 CHAR)
        , NECESARIA_AUTORI_TRANS	VARCHAR2(1 CHAR)
        , TANTEO_RETRACTO_TRANS	VARCHAR2(1 CHAR)
        , IND_COMPRADOR_ACOGE_AYUDA	VARCHAR2(1 CHAR)
        , IMP_AYUDA_FINANCIACION	VARCHAR2(10 CHAR)
        , FEC_VENCIMIENTO_SEGURO	VARCHAR2(8 CHAR)
        , FEC_DEVOLUCION_AYUDA	VARCHAR2(8 CHAR)
        , SITUACION_CEE	VARCHAR2(2 CHAR)
        , MOTIVO_EXONERACION_CEE	VARCHAR2(2 CHAR)
        , INCIDENCIA_CEE	VARCHAR2(2 CHAR)
        , NUMERO_CEE	VARCHAR2(10 CHAR)
        , CODIGO_SST	VARCHAR2(10 CHAR)
        , SUP_TASACION_SOLAR	VARCHAR2(10 CHAR)
        , PORC_OBRA_EJECUTADA	VARCHAR2(10 CHAR)
        , SUP_TASACION_UTIL	VARCHAR2(10 CHAR)
        , SUP_REGISTRAL_UTIL	VARCHAR2(10 CHAR)
        , SUP_TASACION_CONSTRUIDA	VARCHAR2(10 CHAR)
        , NUM_HABITACIONES	VARCHAR2(10 CHAR)
        , NUM_BANYOS	VARCHAR2(10 CHAR)
        , NUM_TERRAZAS	VARCHAR2(10 CHAR)
        , ANYO_CONSTRUCCION	VARCHAR2(4 CHAR)
        , ANYO_ULTIMA_REFORMA	VARCHAR2(4 CHAR)
        , SUP_SOBRE_RASANTE	VARCHAR2(10 CHAR)
        , SUP_BAJO_RASANTE	VARCHAR2(10 CHAR)
        , NUM_APARACAMIENTOS	VARCHAR2(10 CHAR)
        , IDEN_PL_PARKING	VARCHAR2(3 CHAR)
        , IDEN_TRASTERO	VARCHAR2(3 CHAR)
        , SUP_REG_CONSTRUIDA	VARCHAR2(12 CHAR)
        , SUP_REG_SOLAR	VARCHAR2(12 CHAR)
        , TIENE_ASCENSOR	VARCHAR2(1 CHAR)
        , TIENE_TRASTERO	VARCHAR2(1 CHAR)
        , INMUEBLE_VACACIONAL	VARCHAR2(6 CHAR)
        , EQUIPAMIENTO_015001	VARCHAR2(6 CHAR)
        , BALCON	VARCHAR2(6 CHAR)
        , CALEFACCION	VARCHAR2(6 CHAR)
        , COCINA_EQUIPADA	VARCHAR2(6 CHAR)
        , EST_CONSERVACION	VARCHAR2(6 CHAR)
        , JARDIN	VARCHAR2(6 CHAR)
        , USO_JARDIN	VARCHAR2(6 CHAR)
        , PISCINA	VARCHAR2(6 CHAR)
        , SALIDA_HUMOS	VARCHAR2(6 CHAR)
        , TERRAZA	VARCHAR2(6 CHAR)
        , TIPO_VIVIENDA_INF	VARCHAR2(6 CHAR)
        , TIPOLOGIA_EDIFICIO	VARCHAR2(6 CHAR)
        , SEG_INVERSION_PROM	VARCHAR2(6 CHAR)
        , IMP_PRECIO_VENTA	VARCHAR2(10 CHAR)
        , PRECIO_VENTA_NEGOCIABLE	VARCHAR2(1 CHAR)
        , DESC_COLEC_PRECIO_ALQUI	VARCHAR2(60 CHAR)
        , IMP_PRECIO_ALQUI	VARCHAR2(10 CHAR)
        , PRECIO_ALQUI_NEGOCIABLE	VARCHAR2(1 CHAR)
        , DESC_COL_PRECIO_CAMP_ALQUI	VARCHAR2(60 CHAR)
        , IMP_PRECIO_CAMP_ALQUI	VARCHAR2(10 CHAR)
        , PRECIO_CAMP_ALQUI_NEGOCIABLE	VARCHAR2(1 CHAR)
        , DESC_COL_PRECIO_CAMP_VENTA	VARCHAR2(60 CHAR)
        , IMP_PRECIO_CAMP_VENTA	VARCHAR2(10 CHAR)
        , PRECIO_CAMP_VENTA_NEGOCIABLE	VARCHAR2(1 CHAR)
        , DESC_COL_PRECIO_VENTA	VARCHAR2(60 CHAR)
        , IMP_PRECIO_REF_ALQUI	VARCHAR2(10 CHAR)
        , FEC_INICIO_PRECIO_VENTA	VARCHAR2(8 CHAR)
        , FEC_FIN_PRECIO_VENTA	VARCHAR2(8 CHAR)
        , FEC_INICIO_PRECIO_ALQUI	VARCHAR2(8 CHAR)
        , FEC_FIN_PRECIO_ALQUI	VARCHAR2(8 CHAR)
        , FEC_INICIO_PRECIO_CAMP_VENTA	VARCHAR2(8 CHAR)
        , FEC_FIN_PRECIO_CAMP_VENTA	VARCHAR2(8 CHAR)
        , FEC_INICIO_PRECIO_CAMP_ALQUI	VARCHAR2(8 CHAR)
        , FEC_FIN_PRECIO_CAMP_ALQUI	VARCHAR2(8 CHAR)
        , FEC_POSESION	VARCHAR2(8 CHAR)
        , FEC_SENYAL_LANZAMIENTO	VARCHAR2(8 CHAR)
        , FEC_LANZAMIENTO	VARCHAR2(8 CHAR)
        , AVISO_OCUP_SERVICER	VARCHAR2(1 CHAR)
        , IND_FUERZA_PUBLICA	VARCHAR2(1 CHAR)
        , IND_OCUPANTES_VIVIENDA	VARCHAR2(1 CHAR)
        , FEC_RESOLUCION_MORA	VARCHAR2(8 CHAR)
        , IND_ENTREGA_VOL_POSESI	VARCHAR2(1 CHAR)
        , SEGMENTACION_CARTERA	VARCHAR2(2 CHAR)
        , FLAG_EN_REM	NUMBER(1,0)
        , FLAG_FICHEROS	VARCHAR2(1 CHAR)
        , FLAG_OFERTA_VIVA	NUMBER(1,0)
        , ERRORCODE                   VARCHAR2(255 CHAR)
        , ERRORMESSAGE                VARCHAR2(512 CHAR)
        



        
    )
    LOGGING 
    NOCOMPRESS 
    NOCACHE
    NOPARALLEL
    NOMONITORING
    ';
    EXECUTE IMMEDIATE V_MSQL;
    DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.'||V_TEXT_TABLA||'... Tabla creada.');
    

    
    -- Creamos comentario   
    V_MSQL := 'COMMENT ON TABLE '||V_ESQUEMA||'.'||V_TEXT_TABLA||' IS '''||V_COMMENT_TABLE||'''';       
    EXECUTE IMMEDIATE V_MSQL;
    DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.'||V_TEXT_TABLA||'... Comentario creado.');
    
    
    DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.'||V_TEXT_TABLA||'... OK');

   


COMMIT;


EXCEPTION
     WHEN OTHERS THEN
          err_num := SQLCODE;
          err_msg := SQLERRM;

          DBMS_OUTPUT.PUT_LINE('KO no modificada');
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(err_msg);

          ROLLBACK;
          RAISE;          

END;

/

EXIT
