--/*
--##########################################
--## AUTOR=GUILLEM REY
--## FECHA_CREACION=20210301
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-9116
--## PRODUCTO=NO
--## 
--## Finalidad: Modificar tev add unic constraint
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE
	V_MSQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
 	V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
 	V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-9083'; -- USUARIO CREAR/MODIFICAR
	V_COUNT NUMBER(16); -- Vble. para comprobar
	err_num NUMBER; -- Numero de errores
	err_msg VARCHAR2(2048); -- Mensaje de error
	V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.
	
BEGIN
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');
	-- Verificar si la FK ya existe. Si ya existe la FK, no se hace nada.
	V_MSQL := 'SELECT COUNT(1) FROM ALL_CONSTRAINTS WHERE OWNER = '''||V_ESQUEMA||''' AND TABLE_NAME = ''TEV_TAREA_EXTERNA_VALOR'' AND CONSTRAINT_NAME = ''UK_TEV_TEX_NOMBRE''';
	EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TABLAS;	
	IF V_NUM_TABLAS = 0 THEN
		--No existe la FK seguimos
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TEV_TAREA_EXTERNA_VALOR TEV USING (
				    SELECT RN, RN2, TFI_ID, TEV_ID, TEV_NOMBRE, TFI_NOMBRE, TAP_ID FROM 
				    (
				        SELECT 
				        ROW_NUMBER() OVER (PARTITION BY TFI.TFI_ID, TEV.TEX_ID ORDER BY TFI.TFI_ID,TEV.TEV_ID ASC) RN, 
				        ROW_NUMBER() OVER (PARTITION BY TEV.TEV_ID, TEV.TEX_ID ORDER BY TFI.TFI_ID,TEV.TEV_ID ASC) RN2, 
				        TFI.TFI_ID, TEV.TEV_ID, TEV.TEX_ID, TEV.TEV_NOMBRE, TFI.TFI_NOMBRE, TEX.TAP_ID
				        FROM REM01.TEV_TAREA_EXTERNA_VALOR TEV
				        INNER JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TEX_ID = TEV.TEX_ID
				        INNER JOIN '||V_ESQUEMA||'.TFI_TAREAS_FORM_ITEMS TFI ON TFI.TAP_ID = TEX.TAP_ID AND TFI.TFI_NOMBRE = TEV.TEV_NOMBRE
				    )
				    WHERE RN = RN2 AND RN > 1) AUX ON (AUX.TEV_ID = TEV.TEV_ID)
				WHEN MATCHED THEN UPDATE SET TEV.TEV_NOMBRE = AUX.TEV_NOMBRE||AUX.RN, TEV.USUARIOMODIFICAR = '''||V_USUARIO||''', TEV.FECHAMODIFICAR = SYSDATE';
					
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] MODIFICADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN TEV_TAREA_EXTERNA_VALOR');
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TFI_TAREAS_FORM_ITEMS TFI USING (
				    SELECT DISTINCT RN, TFI_ID, TFI_NOMBRE, TAP_ID FROM 
				    (
				        SELECT 
				        ROW_NUMBER() OVER (PARTITION BY TFI.TFI_NOMBRE,TFI.TAP_ID ORDER BY TFI.TFI_ID ASC) RN, 
				        TFI.TFI_ID, TFI.TFI_NOMBRE, TAP.TAP_ID
				        FROM '||V_ESQUEMA||'.TAP_TAREA_PROCEDIMIENTO TAP
				        INNER JOIN '||V_ESQUEMA||'.TFI_TAREAS_FORM_ITEMS TFI ON TFI.TAP_ID = TAP.TAP_ID
				    )
				    WHERE RN > 1) AUX ON (AUX.TFI_ID = TFI.TFI_ID)
				WHEN MATCHED THEN UPDATE SET TFI.TFI_NOMBRE = AUX.TFI_NOMBRE||AUX.RN, TFI.USUARIOMODIFICAR = '''||V_USUARIO||''', TFI.FECHAMODIFICAR = SYSDATE';
		
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] MODIFICADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN TFI_TAREAS_FORM_ITEMS');
		
		V_MSQL := 'DELETE FROM '||V_ESQUEMA||'.TEV_TAREA_EXTERNA_VALOR WHERE TEV_ID IN (
					SELECT TEV_ID FROM (
						SELECT TEV_ID, TEX_ID, TEV_NOMBRE, 
						ROW_NUMBER() OVER (PARTITION BY TEX_ID, TEV_NOMBRE ORDER BY TEV_ID ASC) RN
						FROM REM01.TEV_TAREA_EXTERNA_VALOR 
						GROUP BY TEV_ID, TEX_ID, TEV_NOMBRE
						)
					WHERE RN > 1)';
		
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] BORRADOS  '|| SQL%ROWCOUNT ||' REGISTROS EN TEV_TAREA_EXTERNA_VALOR');
	
		COMMIT;
		
		EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.TEV_TAREA_EXTERNA_VALOR ADD CONSTRAINT UK_TEV_TEX_NOMBRE UNIQUE(TEX_ID, TEV_NOMBRE)';
		EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.TFI_TAREAS_FORM_ITEMS ADD CONSTRAINT UK_TFI_TAP_NOMBRE UNIQUE(TAP_ID, TFI_NOMBRE)';
		COMMIT;
	END IF;
	DBMS_OUTPUT.PUT_LINE('[FIN] ');
	
	EXCEPTION
	
	    WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
		DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------');
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
		DBMS_OUTPUT.PUT_LINE(V_MSQL);
		ROLLBACK;
		RAISE;
END;
/
EXIT;