--/*
--##########################################
--## AUTOR=Carles Molins
--## FECHA_CREACION=20190510
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.5
--## INCIDENCIA_LINK=REMVIP-3912
--## PRODUCTO=NO
--##
--## INSTRUCCIONES: 
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;

DECLARE

    V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01'; -- Configuracion Esquemas
    V_ESQUEMA_M VARCHAR2(25 CHAR):= 'REMMASTER'; -- Configuracion Esquema Master
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_ITEM VARCHAR2(30 CHAR) := 'REMVIP-3912'; -- USUARIOCREAR/USUARIOMODIFICAR.
    V_PEF_CODIGO VARCHAR2(50) := 'GESTIAFORMLBK';
    V_PEF_DESCRIPCION VARCHAR2(255) := 'Gestoría de formalización Liberbank';
    V_PEF_DESCRIPCION_LARGA VARCHAR2(255) := 'Gestoría de formalización Liberbank';
	V_NUM_PERFILES NUMBER(16); 
	V_NUM_FPS NUMBER(16); 

    V_SQL_CONSULTA VARCHAR(2048) := 'SELECT COUNT(*) FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = :1';
	V_SQL_INSERT_PERFIL VARCHAR(2048) := 'INSERT INTO '||V_ESQUEMA||'.PEF_PERFILES (PEF_ID, PEF_CODIGO, PEF_DESCRIPCION, PEF_DESCRIPCION_LARGA, 
		VERSION, USUARIOCREAR, FECHACREAR, BORRADO ) VALUES ('||V_ESQUEMA||'.S_PEF_PERFILES.NEXTVAL,:1,:2,:3,0,:4,SYSDATE,0)';
	V_SQL_UPDATE_PERFIL VARCHAR(2048) := 'UPDATE '||V_ESQUEMA||'.PEF_PERFILES SET PEF_DESCRIPCION=:1, PEF_DESCRIPCION_LARGA=:2,
		USUARIOMODIFICAR=:3, FECHAMODIFICAR=SYSDATE, BORRADO=0 WHERE PEF_CODIGO=:4';
	V_CONSULTA_PEF_ID VARCHAR2(2048) := 'SELECT PEF_ID FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO=:1';
	V_PEF_ID NUMBER;

BEGIN	

	DBMS_OUTPUT.PUT_LINE('[INICIO] INSERCION PERFIL: ' || V_PEF_CODIGO);
	EXECUTE IMMEDIATE V_SQL_CONSULTA INTO V_NUM_PERFILES USING V_PEF_CODIGO;
	
	IF V_NUM_PERFILES = 0 THEN
		EXECUTE IMMEDIATE V_SQL_INSERT_PERFIL USING V_PEF_CODIGO, V_PEF_DESCRIPCION, V_PEF_DESCRIPCION_LARGA, V_ITEM;
		DBMS_OUTPUT.PUT_LINE('[INFO] REGISTRO INSERTADO ' || V_PEF_CODIGO || ',' || V_PEF_DESCRIPCION || ': ' || sql%rowcount);
	ELSE
		EXECUTE IMMEDIATE V_SQL_UPDATE_PERFIL USING V_PEF_DESCRIPCION, V_PEF_DESCRIPCION_LARGA, V_ITEM, V_PEF_CODIGO;
		DBMS_OUTPUT.PUT_LINE('[INFO] REGISTRO ACTUALIZADO ' || V_PEF_CODIGO || ',' || V_PEF_DESCRIPCION || ': ' || sql%rowcount);
	END IF;

	COMMIT;
	DBMS_OUTPUT.PUT_LINE('[FIN] PERFIL ' || V_PEF_CODIGO || ',' || V_PEF_DESCRIPCION || ' Y PERMISOS CORRECTAMENTE ACTUALIZADOS.');
 
EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------');
          DBMS_OUTPUT.put_line(ERR_MSG);
          ROLLBACK;
          RAISE;   
END;
/
EXIT;
