--/*
--##########################################
--## AUTOR=Daniel Algaba
--## FECHA_CREACION=20200629
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-10920
--## PRODUCTO=NO
--##
--## Finalidad: Actualizar instrucciones
--## INSTRUCCIONES: 
--## VERSIONES:
--##        0.1 Version inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.   
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
	  V_ID NUMBER(16); -- Vble. auxiliar para almacenar temporalmente el numero de la sequencia.
	  V_TEXT_TABLA VARCHAR2(2400 CHAR) := 'DD_CCS_CAMPOS_CONV_SAREB'; -- Vble. auxiliar para almacenar el nombre de la tabla de ref.

    TYPE T_TIPO_DATA IS TABLE OF VARCHAR2(32000 CHAR);
    TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
      T_TIPO_DATA('TMP_CONV_SAREB',	'ACT_NUM_ACTIVO_SAREB',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB', 'ACT_NUM_ACTIVO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB', 'TIPO_ACTIVO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUBTIPO_ACTIVO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'USO_DOMINANTE',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ALQUILADO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'OKUPADO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_FISICO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'RIESGO_OCUPACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PUERTA_ANTIOKUPA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'VIGILANCIA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ASCENSOR',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_INSCRIPCION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_INSCRIPCION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TIPO_TITULO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUBTIPO_TITULO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_TOMA_POS',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PORCENTAJE_PROPIEDAD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'GRADO_PROPIEDAD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'VPO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_SENY_LANZAMIENTO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PROPIETARIO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CON_CARGAS',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ID_CARGA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TIPO_CARGA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUBTIPO_CARGA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TITULAR_CARGA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'IMPORTE_REGISTRAL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_REGISTRAL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_ECONOMICO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_CAN_CRG_ECO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_PRES_CAN',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_CAN_REG',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TIPO_VIA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'NOMBRE_VIA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'NUMERO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESCALERA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PLANTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PUERTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PROVINCIA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'MUNICIPIO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'COM_AUTONOMA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PAIS',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CODIGO_POSTAL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'LATITUD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'LONGITUD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'DIV_HOR_NO_INSCRITA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRV_REGISTRO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'POB_REGISTRO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'NUM_REGISTRO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TOMO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'LIBRO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FOLIO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FINCA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'IDUFIR',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'REFERENCIA_CATASTRAL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUPERFICIE_CONSTRUIDA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUPERFICIE_UTIL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUPERFICIE_PARCELA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'BOLETIN_AGUA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'BOLETIN_ELECTRICIDAD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'BOLETIN_GAS',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CEDULA_HABITABILIDAD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_OBT_CED_HABITABILIDAD',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CERTIFICADO_ENERGETICO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'INFORME0',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'DEST_COMERCIAL_OBJ',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_COMERCIAL',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CFO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_CFO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'LPO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_LPO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TAPIADO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ESTADO_ADECUACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRECIO_VENTA_WEB',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRECIO_RENTA_WEB',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRECIO_MIN_AUT_VENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TASACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_TASACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_SOL_TASACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_RECEP_TASACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TECNICO_TASADORA_ASOC',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'IMPORTE_TASACION_FIN',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'TIPO_TASACION',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRECIO_VISIBLE_VENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_INI_VIG_PRECIO_VENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_FIN_VIG_PRECIO_VENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'PRECIO_VISIBLE_RENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_INI_VIG_PRECIO_RENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_FIN_VIG_PRECIO_RENTA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'UNIDAD_ALQUILABLE',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ID_ACTIVO_PADRE',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'ADECUACION_ALQ',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_PREV_FIN_ADECUACION_ALQ',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'NUM_RESERVA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'FECHA_CONT_RESERVA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CARTERA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'SUBCARTERA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'RUINA',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'VANDALIZADO',1 ,0, NULL)
      , T_TIPO_DATA('TMP_CONV_SAREB',	'CEE_EN_TRAMITE',1 ,0, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'ACT_NUM_ACTIVO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'ACT_NUM_ACTIVO_SAREB',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_TPA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_SAC_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_TUD_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'SPS_OCUPADO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'DD_TPA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'SPS_OCUPADO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO', 'DD_EAC_ID',0 ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'SPS_RIESGO_OCUPACION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'SPS_ACC_ANTIOCUPA',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ZCO_ZONA_COMUN',	'ZCO_CONSERJE_VIGILANCIA',0  ,1, NULL)
      , T_TIPO_DATA('ACT_EDI_EDIFICIO',	'EDI_ASCENSOR',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TIT_TITULO',	'DD_ETI_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TIT_TITULO',	'TIT_FECHA_INSC_REG',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_TTA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_STA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA', 'SPS_FECHA_TOMA_POSESION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_PAC_PROPIETARIO_ACTIVO',	'PAC_PORC_PROPIEDAD',0  ,1, NULL)
      , T_TIPO_DATA('ACT_PAC_PROPIETARIO_ACTIVO',	'DD_TGP_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'ACT_VPO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_ADJ_ADJUDICACION', 'BIE_ADJ_F_SEN_LANZAMIENTO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_PAC_PROPIETARIO_ACTIVO',	'PRO_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'CRG_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_CAR_CARGAS',	'BIE_CAR_ID_RECOVERY',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'DD_TCA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'DD_STC_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_CAR_CARGAS',	'BIE_CAR_TITULAR',0  ,1, NULL)
      , T_TIPO_DATA('BIE_CAR_CARGAS',	'BIE_CAR_IMPORTE_REGISTRAL',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'DD_ECG_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'BIE_CAR_FECHA_CANCELACION',0  ,1, NULL)
      , T_TIPO_DATA('BIE_CAR_CARGAS',	'BIE_CAR_FECHA_PRESENTACION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_CRG_CARGAS',	'CRG_FECHA_CANCEL_REGISTRAL',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'DD_TVI_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_NOMBRE_VIA',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_NUMERO_DOMICILIO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_ESCALERA',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_PISO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_PUERTA',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'DD_PRV_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'DD_LOC_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_LOCALIZACION', 'BIE_LOC_COD_POST',0  ,1, NULL)
      , T_TIPO_DATA('ACT_LOC_LOCALIZACION', 'LOC_LATITUD',0  ,1, NULL)
      , T_TIPO_DATA('ACT_LOC_LOCALIZACION', 'LOC_LONGITUD',0  ,1, NULL)
      , T_TIPO_DATA('ACT_REG_INFO_REGISTRAL',	'REG_DIV_HOR_INSCRITO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'DD_PRV_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'DD_LOC_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_NUM_REGISTRO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_TOMO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_LIBRO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_FOLIO',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_NUM_FINCA',0  ,1, NULL)
      , T_TIPO_DATA('ACT_REG_INFO_REGISTRAL',	'REG_IDUFIR',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_REFERENCIA_CATASTRAL',0  ,1, NULL)
      , T_TIPO_DATA('BIE_DATOS_REGISTRALES', 'BIE_DREG_SUPERFICIE_CONSTRUIDA',0  ,1, NULL)
      , T_TIPO_DATA('ACT_REG_INFO_REGISTRAL',	'REG_SUPERFICIE_UTIL',0  ,1, NULL)
      , T_TIPO_DATA('ACT_REG_INFO_REGISTRAL',	'REG_SUPERFICIE_PARCELA',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ADO_ADMISION_DOCUMENTO',	'DD_EDC_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ADO_ADMISION_DOCUMENTO',	'ADO_FECHA_OBTENCION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_APU_ACTIVO_PUBLICACION',	'DD_POR_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_SCM_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_REG_INFO_REGISTRAL',	'REG_FECHA_CFO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_SPS_SIT_POSESORIA',	'SPS_ACC_TAPIADO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_PTA_PATRIMONIO_ACTIVO', 'DD_ADA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_VAL_VALORACIONES', 'DD_TPC_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TAS_TASACION', 'TAS_ID',0  ,1, NULL)
      , T_TIPO_DATA('BIE_VALORACIONES', 'BIE_FECHA_VALOR_TASACION',0  ,1, NULL)
      , T_TIPO_DATA('BIE_VALORACIONES', 'BIE_F_SOL_TASACION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TAS_TASACION', 'TAS_FECHA_RECEPCION_TASACION',0  ,1, NULL)
      , T_TIPO_DATA('BIE_VALORACIONES', 'DD_TRA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TAS_TASACION', 'TAS_IMPORTE_TAS_FIN',0  ,1, NULL)
      , T_TIPO_DATA('ACT_TAS_TASACION', 'DD_TTS_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_VAL_VALORACIONES', 'VAL_FECHA_INICIO',0  ,1, NULL)
      , T_TIPO_DATA('ACT_VAL_VALORACIONES', 'VAL_FECHA_FIN',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO', 'ACT_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_PTA_PATRIMONIO_ACTIVO', 'ACT_PTA_ID',0  ,1, NULL)
      , T_TIPO_DATA('RES_RESERVAS', 'RES_NUM_RESERVA',0  ,1, NULL)
      , T_TIPO_DATA('RES_RESERVAS', 'RES_FECHA_CONTABILIZACION',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_CRA_ID',0  ,1, NULL)
      , T_TIPO_DATA('ACT_ACTIVO',	'DD_SCR_ID',0  ,1, NULL)
    ); 
    V_TMP_TIPO_DATA T_TIPO_DATA;
BEGIN
DBMS_OUTPUT.PUT_LINE('[INICIO]');


    -- LOOP para insertar los valores --
    DBMS_OUTPUT.PUT_LINE('[INFO]: INSERCION EN '||V_TEXT_TABLA);
    FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
      LOOP
        V_TMP_TIPO_DATA := V_TIPO_DATA(I);
        --Comprobar el dato a insertar.
        V_SQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.'||V_TEXT_TABLA||' 
					WHERE DD_CCS_TABLA = '''||TRIM(V_TMP_TIPO_DATA(1))||''' AND DD_CCS_CAMPO = '''||TRIM(V_TMP_TIPO_DATA(2))||''' 
          AND DD_CCS_ORIGEN = '''||TRIM(V_TMP_TIPO_DATA(3))||''' AND DD_CCS_DESTINO = '''||TRIM(V_TMP_TIPO_DATA(4))||''' AND BORRADO = 0';
        EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
        IF V_NUM_TABLAS = 1 THEN
          DBMS_OUTPUT.PUT_LINE('[INFO]: El valor '''||TRIM(V_TMP_TIPO_DATA(1))||'''.'''||TRIM(V_TMP_TIPO_DATA(2))||''' ya existe');
        ELSE
          -- Si no existe se inserta.
            V_MSQL := 'SELECT '||V_ESQUEMA||'.S_'||V_TEXT_TABLA||'.NEXTVAL FROM DUAL';
            EXECUTE IMMEDIATE V_MSQL INTO V_ID;
            V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TEXT_TABLA||' (
              DD_CCS_ID,
              DD_CCS_TABLA,
              DD_CCS_CAMPO,
              DD_CCS_ORIGEN,
              DD_CCS_DESTINO,
              DD_CCS_DESCRIPCION,
              VERSION,
              USUARIOCREAR,
              FECHACREAR,
              BORRADO
              ) VALUES (
              '||V_ID||',
              '''||TRIM(V_TMP_TIPO_DATA(1))||''',
              '''||TRIM(V_TMP_TIPO_DATA(2))||''',
              '''||TRIM(V_TMP_TIPO_DATA(3))||''',
              '''||TRIM(V_TMP_TIPO_DATA(4))||''',
              '''||TRIM(V_TMP_TIPO_DATA(5))||''',
              0,
              ''HREOS-10920'',
              SYSDATE,
              0
                        )';
            EXECUTE IMMEDIATE V_MSQL;
            DBMS_OUTPUT.PUT_LINE('[INFO]: Se ha insertado el valor '''||TRIM(V_TMP_TIPO_DATA(1))||'''.'''||TRIM(V_TMP_TIPO_DATA(2))||'''');

        END IF;
      END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('[FIN]: TABLA '||V_TEXT_TABLA||' ACTUALIZADO CORRECTAMENTE ');

EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(ERR_MSG);
          ROLLBACK;
          RAISE;   
END;
/
EXIT;
