WHENEVER SQLERROR EXIT SQL.SQLCODE;

UPDATE CMMASTER.ENTIDADCONFIG SET DATAVALUE='/ora11g/instantclient/sqlldr' WHERE DATAKEY='pathToSqlLoader' AND ENTIDAD_ID=1;
UPDATE CMMASTER.ENTIDADCONFIG SET DATAVALUE='jdbc:oracle:thin:CM01/j0b3d2CHe3I=04045316@//cajamar-bbdd:1521/orcl' WHERE DATAKEY='url' AND ENTIDAD_ID=1;
UPDATE CMMASTER.ENTIDADCONFIG SET DATAVALUE='CM01' WHERE DATAKEY='username' AND ENTIDAD_ID=1;
UPDATE CMMASTER.ENTIDADCONFIG SET DATAVALUE='j0b3d2CHe3I=04045316' WHERE DATAKEY='password' AND ENTIDAD_ID=1;
UPDATE CMMASTER.ENTIDADCONFIG SET DATAVALUE='CM01/j0b3d2CHe3I=04045316@//cajamar-bbdd:1521/orcl' WHERE DATAKEY='connectionInfo' AND ENTIDAD_ID=1;

exit;
