OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999, SKIP=1)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INFILE './CTL/IN/MapeoOficinas.csv'
BADFILE './CTL/BAD/MapeoOficinas.bad'
DISCARDFILE './CTL/REJECTS/MapeoOficinas.bad'
INTO TABLE REM01.TMP_HREOS_7298
TRUNCATE
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
	USUARIO_REM "TRIM(:USUARIO_REM)", 
	ID_OFICINA "TRIM(:ID_OFICINA)",
	ID_ENTIDAD "TRIM(:ID_ENTIDAD)"
)
