#!/bin/bash

operacion="$2"
if [[ "$operacion" == "merge" ]] ; then
	ramaorigen=`cat $1 | grep Merge | cut -d"'" -f2`
	echo -e "Intentas mergear desde la rama '$ramaorigen'"
	if [[ ! -f ./config/hooks/tool/test-merge.sh ]] ; then
		echo "No podemos garantizar que estés autorizado a realizar este merge."
	else
		./config/hooks/tool/test-merge.sh . $ramaorigen
		if [[ $? == 0 ]] ; then
			exit 0
		fi
	fi
	echo -e "\n\033[0;31mNo estás autorizado a realizar este merge.\nPor favor, ejecuta: git merge --abort\033[0m"
	echo -e "\nIgnora el siguiente mensaje de git:"
	exit 1
fi
