OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999, SKIP=0)
LOAD DATA
CHARACTERSET WE8ISO8859P15
INFILE './CTL/IN/propietarios_caixa.txt'
BADFILE './CTL/BAD/propietarios_caixa.bad'
DISCARDFILE './CTL/REJECTS/propietarios_caixa.bad'
INTO TABLE REM01.APR_AUX_HREOS_14718
TRUNCATE
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
	SOCIEDAD "TRIM(:SOCIEDAD)",
	ID_UVEM "TO_NUMBER(:ID_UVEM)",
	ID_HAYA "TO_NUMBER(:ID_HAYA)",
	NUM_UNIDAD "TRIM(:NUM_UNIDAD)",
	ID_CAIXA "TRIM(:ID_CAIXA)"
)
