ALTER TABLE RES_RESOLUCIONES_MASIVO
ADD RES_MSV_TMP_ID NUMBER(16);

ALTER TABLE RES_RESOLUCIONES_MASIVO ADD (
  CONSTRAINT FK_RES_MSV_TMP_ID
 FOREIGN KEY (RES_MSV_TMP_ID) 
 REFERENCES MSV_TMP_FILES (MSV_TMP_ID));

