Insert into DD_OPM_OPERACION_MASIVA
   (DD_OPM_ID, DD_OPM_CODIGO, DD_OPM_DESCRIPCION, DD_OPM_DESCRIPCION_LARGA, FUN_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_OPM_VALIDACION_FORMATO)
 Values
   (S_DD_OPM_OPERACION_MASIVA.nextval, 'ALO', 'Alta Lotes', 'Alta de Lotes', 622, 0, 'DD', TO_TIMESTAMP('09/05/2013 12:58:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'n*,n*,n*,s,n,n,s*,b*,b*,n*,n*,i*,i*');