--/*
--#########################################
--## AUTOR=Daniel Algaba
--## FECHA_CREACION=20201020
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-11766
--## PRODUCTO=NO
--## 
--## Finalidad: Añadir subfases nuevas
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF; 
DECLARE
    V_SQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar    
    V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01'; -- Configuracion Esquemas
    V_ESQUEMA_M VARCHAR2(25 CHAR):= 'REMMASTER'; -- Configuracion Esquema Master
    V_TABLA VARCHAR2(35 CHAR):= 'ACT_ART_ADMISION_REV_TITULO'; -- Nombre de la tabla
    V_NUM_TABLA NUMBER(16); -- Vble. para validar la existencia de una tabla.
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_USUARIO VARCHAR2(30 CHAR) := 'HREOS-11766'; -- USUARIOCREAR/USUARIOMODIFICAR.	

    TYPE T_TIPO_DATA IS TABLE OF VARCHAR2(2048);
    TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
		T_TIPO_DATA(6980540,'Sin titulo de adjudicación, sin documento que acredite posesión, según NS que se encuentra en la tasación de fecha febrero 2019, inscrito a nombre de Bankia a fecha 28/09/2018, pleno dominio 100%, según adjudicación con fecha 05/07/2018, en construcción no aplica ya que es un suelo/urbano solar, en su momento la gestión de este activo le correspondía a Montalvo, VPO no aplica.'),
		T_TIPO_DATA(6980541,'Con titulo adjudicación titularidad de BMN, sin inscripción, Local comercial, libertad arredanticia?????, subido mandamiento de cancelación de cargas, certificado de dominio y cargas, VPO no aplica al ser local comercial, 100% pleno dominio BMN, gestión de Maretra.'),
		T_TIPO_DATA(6980547,'Sin titulo de adjudicación fecha informada en el sistema, subido mandamiento cancelación cargas, activo BMN, construcción terminado, sin documento que acredite la posesión, VPO no, libertad arrendaticia?????? Gestión de Maretra.'),
		T_TIPO_DATA(6980718,'Con titulo de adjudicación titularidad de BMN, con inscripción sin fechas informadas, la fecha de inscripción no aparece en el la NS, libre de cargas, VPO no, construido, 100 % pleno dominio BMN, libertad arrendaticia si, documento de posesión no se encuentra subido a REM.'),
		T_TIPO_DATA(6981142,'Sin titulo de adjudicación, sin inscribir, es una gestión que le habría correspondido a Maretra, aparece alteración catastral subida por Qipert, PEDIR A MONTALVO, Nadia solicito información a Montalvo en noviembre 2019 y la respuesta fue la siguiente: Sigue pendiente de inscripción , en cuanto quede libre uno de los juegos de testimonios de las segregaciones lo aportaremos conforme requiere el registro para complementar la instancia de cesión de titularidad de hipoteca.03/04/2020 se procedió a presentar de nuevo todo a Registro, teniendo entrada en el mismo el 9/3/20. EL 14/3/20 se decretó el estado de alarma y entre otras consecuencias los plazos registrales se han ampliado, pasando a ser el doble de lo habitual. No tenemos notificación del Registro, procederemos a reclamarles la inscripción pero estos días la respuesta habitual general por parte de los Registros es que los plazos son mayores para su resolución.  En cuanto tengamos noticias os trasladamos. '),
		T_TIPO_DATA(6981143,'Sin titulo de adjudicación, sin inscribir, es una gestión que le habría correspondido a Maretra, aparece alteración catastral subida por Qipert, PEDIR A MONTALVO, Nadia solicito información a Montalvo en noviembre 2019 y la respuesta fue la siguiente: Sigue pendiente de inscripción , en cuanto quede libre uno de los juegos de testimonios de las segregaciones lo aportaremos conforme requiere el registro para complementar la instancia de cesión de titularidad de hipoteca.'),
		T_TIPO_DATA(6981342,'Sin titulo de adjudicación, se solicita a gestoría, activo procedente de BMN, tiene una carga propia con Caja de Ahorros de Murcia, se envia a gestoría Maretra.'),
		T_TIPO_DATA(6981344,'Activo con titulo de adjudicación de septiembre 2017, se envia a gestoría para que procedan a su inscripción y cancelación de cargas, cartera Jarama'),
		T_TIPO_DATA(6981386,'Activo con titulo de adjudicación de febrero 2018, se envía a gestoría para su inscripción y cancelación de cargas '),
		T_TIPO_DATA(6981495,'Activo sin titulo, ni posesión, solicitamos a la gestoría que se encargue de la tramitación y gestión del activo se le envia a gestoría qipert ya que la alteración catastral la han gestionado ellos y este expediente se pudo pasar a posteriori a la gestoría del nuevo reparto '),
		T_TIPO_DATA(6981536,'Activo con titulo sin inscripción enviado a Maretra ya que es un activo, procedente de BMN, se envia para que procedan a la inscripción y cancelación de cargas MAretra '),
		T_TIPO_DATA(6981557,'Activo con titulo sin inscripción enviado a Maretra ya que es un activo, procedente de BMN, se envia para que procedan a la inscripción y cancelación de cargas MAretra '),
		T_TIPO_DATA(6981558,'Activo con titulo es inscrito, se subo NS inscrita libre de cargas, tiene fecha de posesión se pone pendiente de obtención ya que el documento no aparece subido a REM, no alquilado, VPO no, se envía gestoría para que procedan a informar correctamente en el sistema Montalvo.'),
		T_TIPO_DATA(6981566,NULL),
		T_TIPO_DATA(6981736,'Activo sin titulo, sin inscripción enviado a Maretra ya que es un activo, procedente de BMN, se envia para que suban documentación y procedan a la inscripción y cancelación de cargas Maretra '),
		T_TIPO_DATA(6981792,'Activo origen BMN con título firme desde octubre 2018, pendiente de posesión, se envía a gestoría Maretra la gestión de la inscripción y la cancelación de cargas, aparece en REM en trámite.'),
		T_TIPO_DATA(6981909,'Activo origen BMN con título firme desde febrero 2018, pendiente de posesión, se envía a gestoría Maretra la gestión de la inscripción y la cancelación de cargas, aparece en REM en trámite.'),
		T_TIPO_DATA(6981965,'Activo origen BMN con título firme desde octubre 2018, pendiente de posesión, se envía a gestoría Maretra la gestión de la inscripción y la cancelación de cargas, aparece en REM en trámite.'),
		T_TIPO_DATA(6981969,'Activo con titulo e inscrito, libre de cargas, no alquilado, VPO no, la posesión esta marcada en el sistema como si, pero se ha marcado pendiente de posesión ya que el documento no se encuentra subido a REM, fechas informadas en el sistema correctamente.'),
		T_TIPO_DATA(6982005,'Activo con titulo, calificado defectuoso en 2018, pendiente de posesión, VPO no, alquilada no se envía a Montalvo para que nos indique si existen avances sobre la inscripción del activo de referencia.'),
		T_TIPO_DATA(6982006,NULL),
		T_TIPO_DATA(6982007,'Activo con título febrero 2018 origen BMN, tiene fecha de posesión pero el documento no se encuentra subido, se encuentra mandamiento de cancelación de cargas, según esta informado en el sistema la inscripción esta en tramite, se envia correo a Maretra para que nos informen en que estado se encuentra, así como para que agilicen la inscripción del activo de referencia.'),
		T_TIPO_DATA(6982082,'Activo inscrito sin cargas, no tiene documentación ni fecha informadas, penediente toma de posesión, se envía a Maretra para que suban la documentación faltante e informen correctamente el activo '),
		T_TIPO_DATA(6982138,'Activo inscrito sin cargas, no tiene documentación ni fechas informadas, marcada posesión en REM se marca como pendiente de posesión por que el documento no esta subido, se envia a Maretra para que procedan a subir documentación al sistema '),
		T_TIPO_DATA(6982142,'Activo sin titulo origen BMN , sin posesión, se envia a Maretra para que procedan a la reclamación del titulo y empiecen la tramitación y gestión del activo '),
		T_TIPO_DATA(6982268,'Activo inscrito origen BMN, se manda para que suban documentación e informen fechas correctamente, sin posesión, en el apartado de posesión aparece como pendiente de auto/ titulo, cuando el activo según NS de febrero 2020, eta inscrito y sin cargas.'),
		T_TIPO_DATA(6982316,'Activo origen BMN, con titulo, alquilado, según esta indicado en el email que esta subido al sistema, aparentemente tambien se encuentra inscrito según esta reflejado en el email mencionado, tiene posesión, se envia a gestoría para que aclaren e informen correctamente el activo.'),
		T_TIPO_DATA(6982507,'Activo sin titulo origen BMN, se envia a maretra para que procedan a su inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6982572,'Activo con documento de dación en pago, no esta inscrito, ocupado sin titulo, se marca posesión si ya que es una dación y se obtiene automaticamente la posesión del activo, se envia a gestoría Maretra.'),
		T_TIPO_DATA(6982695,'Activo origen BMN con titulo y mandamiento de cancelación de cargas, sin inscribir, no se encuentra documento de posesión, se envía gestoría para que procedan a la inscripción o nos informen en que estado se encuentra.'),
		T_TIPO_DATA(6982740,'Activo origen BMN subido documento dación del 2015, sin inscribir y sin cargas canceladas se envía a Maretra para que nos informen sobre el estado en el que se encuentra, la posesión del activo es si al ser dacuón.'),
		T_TIPO_DATA(6982868,'Activo origen BMN, sin decreto firme, informado como en tramitación la inscripción del activo, sin posesión, enviado a Maretra para que informen y suban documentación que acredite titularidad así como que informen de la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6982909,'Activo origen BMN, con titulo, sin inscribir que aparece en tramitación en REM, no se encuentra el documento de la posesión, se envía email a Maretra para que nos informen en el estado en el que se encuentra la inscripción y agilicen su tramitación.'),
		T_TIPO_DATA(6982910,'Activo origen BMN, con titulo, sin inscribir que aparece en tramitación en REM, no se encuentra el documento de la posesión, se envía email a Maretra para que nos informen en el estado en el que se encuentra la inscripción y agilicen su tramitación.'),
		T_TIPO_DATA(6982944,'Activo origen BMN, con titulo, sin inscripción, no se encuentra el documento de posesión '),
		T_TIPO_DATA(6983032,'Activo origen BMN, con titulo de mayo 2017, sin inscribir, se envia a gestoría para que procedan a cancelar cargas y la inscripción, pendiente toma de posesión. '),
		T_TIPO_DATA(6983414,'Activo con auto firme de 2019, sin inscripción y sin cancelar cargas, activo asignado de gestión Montalvo, sin posesión.'),
		T_TIPO_DATA(6983417,'Activo sin auto firme, subido acta de subasta que indica que la subasta concluyo sin pujas, se envia a gestoría Maretra para que nos informen en que estado se encuentra el activo de referencia.'),
		T_TIPO_DATA(6983504,'Activo BMN con auto firme septiembre 2018, se envia a Maretra para que procedan a la cancelación e inscripción del activo, sin posesión.'),
		T_TIPO_DATA(6983505,'Activo BMN con auto firme septiembre 2018, se envia a Maretra para que procedan a la cancelación e inscripción del activo, sin posesión.'),
		T_TIPO_DATA(6983604,'Activo BMN con auto firme y mandamiento de cancelación, sin posesión, se envia a Maretra para que nos indiquen en que estado se encuentra.'),
		T_TIPO_DATA(6983641,'Activo BMN sin auto firme, se envia a gestoría solicitando el titulo así como la tramtiación y gestión del activo de referencia, sin posesión.'),
		T_TIPO_DATA(6983644,'Activo BMN sin auto firme, se envia a gestoría solicitando el titulo así como la tramtiación y gestión del activo de referencia, sin posesión.'),
		T_TIPO_DATA(6983674,'Activo inscrito que pertenecen ambos al mismo auto, se encuentra la NS inscrita del activo 6983674, se envia a la gestoría para que informen correctamente este activo y se suba y se informe el activo 6983675, posesión marcada aunque no se encuentra el documento de posesión del activo.'),
		T_TIPO_DATA(6983675,'Activo inscrito que pertenecen ambos al mismo auto, se encuentra la NS inscrita del activo 6983674, se envia a la gestoría para que informen correctamente este activo y se suba y se informe el activo 6983675, posesión marcada aunque no se encuentra el documento de posesión del activo.'),
		T_TIPO_DATA(6983693,'Activo BMN con titulo de octubre 2018, sin inscribir, se envia a Maretra para que procedan a la inscripción y cancelación de las cargas, posesión marcada como obtenida, no se encuentra el documento que acredite la posesión.'),
		T_TIPO_DATA(6983729,'Titulo judicial pendiente de inscripción FR arrendada, las cargas se purgaran con la inscripción terminado fisica y registralmente, VPO no, según el contrato de arrendamiento se encuentra unida con el activo 6983728, activo BMN'),
		T_TIPO_DATA(6983761,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6983779,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6983781,'Activo BMN con tiítulo firme con fecha marzo 2018, aparece marcado en el sistema como en subsanación, se envia a gestoría Maretra para que nos indiquen en que estado se encuentra la inscripción del activo de referencia, pendiente toma de posesión.'),
		T_TIPO_DATA(6983913,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6983929,'Activo BMN con titulo de 2017 y mandamiento de cancelación de cargas, pendiente de inscripción, pendiente toma de posesión, se envía email a Maretra para que procedan a su inscirpicón.'),
		T_TIPO_DATA(6984204,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6984891,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6984910,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6984919,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6984973,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6984974,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6985088,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6985185,'Activo BMN sin titulo de adjudicación, en sistemas marcado como fecha de titulo firme mayo 2018, inscripción aparece en tramitación, pendiente toma de posesión, se envia a Maretra para que suban la documentación que acredite titularidad firme y se encarga que nos informen sobre el estado en el que se encuentra la tramitación de inscripción del activo.'),
		T_TIPO_DATA(6985209,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985214,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985215,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985297,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985300,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985306,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985371,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985597,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985655,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985681,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6985686,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6986021,'Activo BMN, sin titulo firme, solo se encuentra subido acta de subasta, tiene fecha de titulo firme informado 07/05/2018, aparece inscripción en tramitación, se envia email para que procedan a informar sobre la inscripción y cancelación de cargas.'),
		T_TIPO_DATA(6986300,'Activo BMN, con titulo e inscrito sin cargas, con posesión, se sube Ns inscrita.'),
		T_TIPO_DATA(6986356,'Activo BMN con titulo, pendiente de inscripción y de posesión, se envia email a Maretra para que procedan a su gestión.'),
		T_TIPO_DATA(6986357,'Activo BMN con titulo, pendiente de inscripción y de posesión, se envia email a Maretra para que procedan a su gestión.'),
		T_TIPO_DATA(6986541,'Activo BMN con titulo, pendiente de inscripción y de posesión, se envia email a Maretra para que procedan a su gestión.'),
		T_TIPO_DATA(6986680,'Activo BMN con titulo, pendiente de inscripción y de posesión, se envia email a Maretra para que procedan a su gestión.'),
		T_TIPO_DATA(6986687,'Activo BMN con titulo, pendiente de inscripción y de posesión, se envia email a Maretra para que procedan a su gestión.'),
		T_TIPO_DATA(6986709,'Activo inscrito sin cargas, pendiente de toma de posesión.'),
		T_TIPO_DATA(6986713,NULL),
		T_TIPO_DATA(6986714,NULL),
		T_TIPO_DATA(6986853,NULL),
		T_TIPO_DATA(6986857,NULL),
		T_TIPO_DATA(6986903,NULL),
		T_TIPO_DATA(6986981,NULL),
		T_TIPO_DATA(6986983,NULL),
		T_TIPO_DATA(6987079,NULL),
		T_TIPO_DATA(6987110,NULL),
		T_TIPO_DATA(6987487,NULL),
		T_TIPO_DATA(6987654,NULL),
		T_TIPO_DATA(6988191,NULL),
		T_TIPO_DATA(6988192,NULL),
		T_TIPO_DATA(6988195,NULL),
		T_TIPO_DATA(6988196,NULL),
		T_TIPO_DATA(6988197,NULL),
		T_TIPO_DATA(6988362,NULL),
		T_TIPO_DATA(6988367,NULL),
		T_TIPO_DATA(6988477,NULL),
		T_TIPO_DATA(6988496,NULL),
		T_TIPO_DATA(6988744,NULL),
		T_TIPO_DATA(6988745,NULL),
		T_TIPO_DATA(6988746,NULL),
		T_TIPO_DATA(6988916,NULL),
		T_TIPO_DATA(6782722,'Finca adquirida por Bankia mediante título judicia/Incluida en agrupación restringida (fincas 10508-10337)/Pdte inscripción por estar calificado negativamente: No consta certificación acreditativa del precio del remate y de la deuda pendiente/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar. Se solicita cambio de tipología de la plaza de garaje, finca 10337'),
		T_TIPO_DATA(6782726,'Finca adquirida por Bankia mediante título judicia/Incluida en agrupación restringida (fincas 10508-10337)/Pdte inscripción por estar calificado negativamente: No consta certificación acreditativa del precio del remate y de la deuda pendiente/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar. Se solicita cambio de tipología de la plaza de garaje, finca 10337. 20/04-cambio realizado'),
		T_TIPO_DATA(6782915,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente por : 1-No constar el quien ha intervenido en calidad de representante de los dchos e intereses de la herencia yaciente.2-La adjudicación a favor del acreedor debía haberse realizado por el 70% del valor de tasación o bien por la parte íntegramente debida. 3-Al tratarse de vvda habitual de los deudores, las costas exigibles no pueden superar el 5% de la cantidad reclamada  en la demanda ejecutiva./SIN POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar (sin visita interior)   '),
		T_TIPO_DATA(6787715,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente por : 1-No se acredita el haber presentado en el Ayto la declaración del impuesto sobre el Incremento de Valor de los Terrenos de Naturaleza Urbana .2-No se declara arrendamientos concertados con anterioridad del 06/06/2013. DEFECTO SUBSANADO presentado de nuevo en registro/CON POSESION/ Las cargas se purgan con la inscripción/Inmueble que se encontraba acogido a los beneficios de VPO pero actualmente libre de cargas por haber superado 30 años  de antigüedad/Tasación: Al no haber tenido acceso al interior del inmueble, se toma la marcada en catastro, inferior a la que consta en registro.'),
		T_TIPO_DATA(6787813,'Finca adquirida por Madrid RMBS III Fondo Titulación de Activos mediante título judicial/Pdte inscripción por estar calificado negativamente: el registro no calificó, suspendió la calificación porque la comunicación de plusvalía no reunía los requisitos que ellos estiman. DEFECTO SUBSANADO pendiente de inscripción/SIN POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar. '),
		T_TIPO_DATA(6788080,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: En este caso aparte de que la norma no puede amparar un empobrecimiento desmesurado del ejecutado tampoco puede amparar el enriquecimiento injusto de un acreedor en perjuicio de otros acreedores posteriores que podrán acceder al sobrante. La finca aparece gravada además de la hipoteca con una notación preventiva de embargo a favor de la Tesorería General de la Seguridad Social/SIN POSESION/ Las cargas se purgan con la inscripción/Contingencia registral: según tasación sería pertinente una modificación de la dirección registral, ya que se ha modificado el nº de la calle.'),
		T_TIPO_DATA(6788373,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: 1-falta de inscripción de título previo, 2-Falta de testimonio. La calificación está enviada al letrado y Procurador y la gestoría está a la espera de que les envíen el testimonio a que hace referencia la calificación/SIN POSESION/ Las cargas se purgan con la inscripción/Tasación sin acceso al interior del inmueble/VPO: estuvo calificada como VPO. La calificación queda sin efecto por haber transcurrido el plazo de protección.  '),
		T_TIPO_DATA(6788377,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: no ha habido certificación de dominio y carga en el /SIN POSESION/ Las cargas se purgan con la inscripción/Condicionantes de la tasación: La vivienda no cumple plenamente con la normativa vigente ya que la edificación se adosa a uno de los muros laterales. Se debe a que originalmente ocupaba el centro de la parcela la cual pudo haberse segregado. Se halla inscrita y catastrada desde 1983 según catastro al amparo de una normativa anterior y en apariencia consolidada. Se ha realizado la consulta a los servicios de Urbanismo de la localidad donde no se ha podido confirmar la existencia de expediente sancionador. Dicho expediente debe solicitarlo el titular/Según nota simple: los titulares de la finca y los titulares de la finca colindante, se confieren recíprocamente consentimiento para poder edificar en sus respectivas fincas, a distancia menor de 5m desde el linde común de las mismas.'),
		T_TIPO_DATA(6788486,'Finca adquirida por Madrid RMBS III Fondo Titulación de Activos mediante título judicial junto con la finca registral 14712 ( activo 28441513 actualmente ocupado con título)/Pdte inscripción, presentado en Hacienda el 02/03/20/SIN POSESION/ Las cargas se purgan con la inscripción/Tasación: en las dos tasaciones disponibles se tasa una plaza de garaje pero según auto y registro, se trata de un local. No hay visita interior ni fotos para comprobar la realidad física del inmueble/VPO: tiene concedida la calificación de vivienda VPO (1977), hoy de precio libre.'),
		T_TIPO_DATA(6788910,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: debe ordenarse la cancelación de todas las cargas posteriores sin excepción/Sin posesión/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar. '),
		T_TIPO_DATA(6789196,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: El defecto de la cesión ya fue subsanado por Montalvo con inscripción de la instancia al respecto. El  problema fundamental son los terceros poseedores que adquirieron la finca previo a la demanda, y no se dirige la demanda contra ellos. El  30/09/2019 remitió el letrado nuevo test y mandamientos que fueron nuevamente calificados con defecto. El 27/2/20 se recibió nueva adición que se ha presentado a Registro, pendiente de calificación/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin acceso al interior del inmueble, sin condicionantes importantes. '),
		T_TIPO_DATA(6789379,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: 1-No se aporta certificado de la deuda pendiente, 2-No consta el desglose en pago de principal de crédito, de los intereses y de las costas, 3-Pdte aportar documentación precisa para inscribir previamente el derecho (tracto sucesivo). A la espera de adición por el Juzgado/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin acceso al interior del inmueble, sin condicionantes importantes'),
		T_TIPO_DATA(6789437,'Finca adquirida por Bankia mediante título judicial/ Pdte inscripción por estar calificado negativamente: Cantidades adjudicación, notificado al letrado y al procurador sin que por el momento se haya recibido adición expedida por el Jugado para subsanar/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes importantes. VPO: La vivienda perteneció a VPO, aunque se considera que todas las viviendas protegidas de Promoción Privada calificadas provisionalmente al amparo de leyes anteriores al 31/11/78,decreto 3141/78, son de venta y renta libre atendiendo al RD 727/1993. '),
		T_TIPO_DATA(6789464,'Finca adquirida por Madrid RMBS IV Fondo Titulación de Activos mediante título judicial/ Pdte inscripción por estar calificado negativamente: Calificado con defecto por la titularidad de la hipoteca ejecutada. Subsanado por la gestoría con inscripción de la instancia al efecto. Presentado de nuevo a inscribir y pte calificación/CON POSESION/ Las cargas se purgan con la inscripción/Tasación sin condicionantes importantes.  '),
		T_TIPO_DATA(6791287,NULL),
		T_TIPO_DATA(6791867,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-Pdte libertad de arrendamientos, 2-Pdte firmeza del auto, 3-Cesión de titularidad, 4-Pdte licitadores. Los defectos respecto a la libertad de arrendamientos y la cesión de la titularidad de la hipoteca ya están con las correspondientes instancias /Sin posesión/ Las cargas se purgan con la inscripción/Tasación: sin acceso al interior del inmueble. Registralmente el inmueble tiene 94,50m2 pero en catastro 243m2 construidos (vivienda de tres plantas). Existe discrepancia físico-jurídica/descripción registral.'),
		T_TIPO_DATA(6796802,'Finca adquirida por Madrid RMBS III Fondo Titulación de Activos mediante título judicial/Pdte inscripción por estar calificado negativamente: 1- Pdte inscribir título previo, 2-concretar escritura constitución del fondo y certificado de transmisión de hipoteca, 3- mandamiento de cancelación/ALQUILADO, duración un año (actualmente finalizado)/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar. '),
		T_TIPO_DATA(6797135,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: Existe contradicción puesto que si la adjudicación se realiza por la cantidad reclamada por todos los conceptos, no puede haber cantidad pendiente de pago/Con posesión: Arrendado/Activo alquilado desde 06/04/2018 con duración de un año (desconocemos si se ha renovado)/ Las cargas se purgan con la inscripción/ Tasación: El inmueble no se ha podido inspeccionar interiormente, por lo que la valoración se ha realizado basada en su descripción registral y a la visita exterior efectuada. El edificio presenta patologías evidentes de aluminosis en los balcones y una falta total de conservación, que afecta al valor de la vivienda.'),
		T_TIPO_DATA(6797148,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción: por estar calificado negativamente: 1- La hipoteca que se ejecuta aparece inscrita a favor de una entidad distinta del acreedor ejecutante, 2-Notificación de arrendatarios /CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin acceso al interior del inmueble: La denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de correcta identificación. Se recomienda su correcta inscripción. Existen discrepancias de superficies entre la registral y la catastral, desconociéndose a qué es debido'),
		T_TIPO_DATA(6798270,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Pdte acreditar la liquidación, 2-Pdte importes/CON POSESION/ Con cargas ajenas/ Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6798412,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: ausencia acta libertad de arrendatarios/Con posesión/ Las cargas se purgan con la inscripción/ Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6800142,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-No consta libertad de arrendatarios, 2-Se ordena la cancelación de la anotación preventiva de embargo que ha originado la adjudicación cuando se trata de una ejecución hipotecaria, 3- No se ordena expresamente la cancelación de las anotaciones preventivas de embargo /Con posesión/Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6801014,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Pdte acreditar liquidación, 2-Falta autenticidad de uno de los mandamientos ya que no está firmado, 3-Pdte aclarar que se practicó el requerimiento de pago judicial o extrajudicial al deudor, 4-Pdte completar datos de DNI, domicilio y datos de inscripción en el registro mercantil, 5-La vivienda se tiene que adjudicar por un precio superior/CON POSESION/ Las cargas se purgan con la inscripción/ Tasación sin acceso al interior del inmueble. '),
		T_TIPO_DATA(6801431,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: Existe contradicción puesto que si la adjudicación se realiza por la cantidad reclamada por todos los conceptos, no puede haber cantidad pendiente de pago/Con posesión: Arrendado/Activo alquilado desde 06/04/2018 con duración de un año (desconocemos si se ha renovado)/ Las cargas se purgan con la inscripción/ Tasación: El inmueble no se ha podido inspeccionar interiormente, por lo que la valoración se ha realizado basada en su descripción registral y a la visita exterior efectuada. El edificio presenta patologías evidentes de aluminosis en los balcones y una falta total de conservación, que afecta al valor de la vivienda. Sin visita interior.'),
		T_TIPO_DATA(6801435,'Finca adquirida por Bankia mediante título judicial/INSCRITO (12/11/19)/SIN POSESION/ Sin cargas/Tasación: Inicialmente disponía de una superficie construida de 1.011m2 (y así figura en el auto de adjudicación). De esta superficie, se segregaron 263m2 correspondientes al local 1 según plano que se adjunta en la tasación, dando lugal a los 747m2 que figuran en nota simple y que corresponden al local de referencia. Al parecer se pretendía segregar el resto de finca y se advierte que las segregaciones efectuadas, deberán registrarse debidamente a todos los efectos. No se puede establecer la correspondencia entre la realidad física del inmueble y la catastral al no haberse realizado la visita interior al inmueble.'),
		T_TIPO_DATA(6803408,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Pdte acreditar la titularidad sobre el crédito hipotecario a favor del ejecutante, 2- Pdte fecha celebración de la subasta, 3-Pdte precio de remate y deuda pdte por todos los conceptos/SIN POSESION/ Cargas: embargo vigente TGSS/ Tasación sin acceso al interior del inmueble. La denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de correcta identificación. Se recomienda su correcta inscripción.'),
		T_TIPO_DATA(6803409,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: del testimonio no resulta si ha habido o no postores en la subasta/SIN POSESION/ Las cargas se purgan con la inscripción /VPO: El inmueble se encuentra sujeto a la legislación de Viviendas con Protección Pública de Promoción Pública , por 50 años (fecha calificación 23/11/1976) /Tasación: sin acceso al interior del inmueble. Según consulta realizada al Arquitecto Municipal, la escalera nueve no está afectada por la construcción del túnel previsto de ejecución por el planeamiento, ya que afectará a las escaleras 11 y 13, a nivel de plantas bajas y hasta la planta segunda. '),
		T_TIPO_DATA(6803411,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: del testimonio no resulta si ha habido o no postores en la subasta/SIN POSESION/ Las cargas se purgan con la inscripción /VPO: El inmueble se encuentra sujeto a la legislación de Viviendas con Protección Pública de Promoción Pública , por 50 años (fecha calificación 23/11/1976) /Tasación: sin acceso al interior del inmueble. Según consulta realizada al Arquitecto Municipal, la escalera nueve no está afectada por la construcción del túnel previsto de ejecución por el planeamiento, ya que afectará a las escaleras 11 y 13, a nivel de plantas bajas y hasta la planta segunda. '),
		T_TIPO_DATA(6803428,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Pdte acreditar la titularidad sobre el crédito hipotecario a favor del ejecutante, 2- Pdte fecha celebración de la subasta, 3-Pdte precio de remate y deuda pdte por todos los conceptos/SIN POSESION/ Cargas: embargo vigente TGSS/ Tasación sin acceso al interior del inmueble. La denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de correcta identificación. Se recomienda su correcta inscripción.'),
		T_TIPO_DATA(6804136,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: No se acompaña la certificación del tribunal acreditativa de la deuda pendiente por todos los conceptos tras la adjudicación/Con posesión/ Las cargas se purgan con la inscripción/Tasación sin condicionantes a destacar.  '),
		T_TIPO_DATA(6804138,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción: No hay calificación. Este decreto se recibió primeramente el  24/4/17, vencido  al ser del 21/3/17, y sin mandamiento de cancelación. Se les devolvió para que pidieran otro con fecha actualizada. El 24/5/17 Se recibe el mismo decreto pero con otro donde se acuerda rectificar el anterior, pero sigue  faltando el mandamiento de cancelación. Se procedió a liquidar impuesto. El 30/6/17 se recibe decreto adjudicación indicando la firmeza del mismo. Falta el mandamiento de cancelación /SIN POSESION/ Las cargas se purgan con la inscripción/Tasación: sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6804149,'Finca adquirida por Bankia mediante título judicial/INSCRITO (19/12/19)/CON POSESION/ Sin cargas/Tasación: sin acceso al interior del inmueble. '),
		T_TIPO_DATA(6809739,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: no consta certificación acreditativa del precio de remate/CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6809742,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción: El Registro no ha calificado. Denegó la presentación a inscripción dado que el documento judicial tiene la firma digital del secretario pero va sin CSV válido (comunicado y reclamado a la procuradora) /SIN POSESION/ Las cargas se purgan con la inscripción/Tasación: sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6809903,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: no poder practicarse junto con el testimonio del decreto al estar este calificado desfavorable/CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6809954,NULL),
		T_TIPO_DATA(6810004,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Debe acreditarse la plusvalía, 2- Pdte libertad de arrendatarios, 3 – Pdte mandamientos de cancelación, 4-Firmeza del auto/SIN POSESION/ Cargas: embargo vigente de Hacienda Pública/ Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6810009,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Debe acreditarse la plusvalía, 2- Pdte libertad de arrendatarios, 3 – Pdte mandamientos de cancelación, 4-Firmeza del auto/SIN POSESION/ Cargas: embargo vigente de Hacienda Pública/ Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6810010,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Debe acreditarse la plusvalía, 2- Pdte libertad de arrendatarios, 3 – Pdte mandamientos de cancelación, 4-Firmeza del auto/SIN POSESION/ Cargas: embargo vigente de Hacienda Pública/ Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6810023,'Finca adquirida por Bankia mediante título judicial/INSCRITO (26/09/19) “la entidad titular de esta finca está afectada por el derecho de los deudores ejecutados a la reducción de su deuda por la revalorización de esta finca en caso de enajenarse la misma durante el plazo de diez años/Con posesión/Sin cargas/Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes'),
		T_TIPO_DATA(6810474,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: la adjudicación se ha aprobado por un porcentaje inferior el exigido por ley/CON POSESION/ SIN CARGAS/ Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6810486,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: error importes económicos /CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin acceso al interior del inmueble. Esta finca tiene VINCULADA OB REM una participación de las FINCAS PROCOMUNALES 46628 Y 46630 de su subcomunidad, de modo que su propiedad queda atribuida a los propietarios de cada uno de los elementos independientes que integran esta subcomunidad, en proporción a sus respectivas cuotas de participación en la propiedad horizontal y vinculada de forma inseparable a la propiedad de los respectivos elementos privativos. Torre Pacheco, a 6 de septiembre de 2016. Se advierte que existen discrepancias entre la dirección registral y la real del inmueble a tasar tras la inspección ocular del mismo. Sería pertinente una modificación de la dirección registral  '),
		T_TIPO_DATA(6812065,'Finca adquirida por Bankia mediante título judicial/INSCRITO (27/01/20)/Con posesión/Sin cargas/Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6812074,NULL),
		T_TIPO_DATA(6812117,'Finca adquirida por Bankia mediante título judicial/INSCRITO (17/02/20)/Con posesión/Sin cargas/Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6812408,'Finca adquirida por Madrid RMBS II Fondo Titulación de Activos mediante título judicial/ Pdte inscripción por estar calificado negativamente: 1-Plusvalía, 2-Instancia Libertad de Arrendatarios, 3-Sellos del Juzgado en todas las hojas, 4-No se dice si es vivienda habitual, 5-Falta el domicilio de la entidad adjudicataria, 6-Mandamiento de cancelación incompleto, 7-Pdte importe adjudicación, 8-Pdte si habrá sobrante /CON POSESION/ Las cargas se purgan con la inscripción/Tasación: Se advierte de que la vivienda valorada figura inscrita como vivienda de protección oficial, si bien atendiendo al RD 727/1993 actualmente es libre de venta y renta al estar calificada al amparo de una Ley anterior al 31/11/78, decreto 3141/78. Sin visita interior.'),
		T_TIPO_DATA(6814467,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: pdte notificación de arrendatarios/SIN POSESION/ Las cargas se purgan con la inscripción /VPO: según nota simple, concedida calificación definitiva de VPO según cédula de fecha 01/02/1979/Tasación: sin acceso al interior del inmueble. '),
		T_TIPO_DATA(6814532,' Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-Pdte acreditar liquidación o plusvalía, 2-Pdte instancia de representante del adjudicatario, 3-Pdte acreditar firmeza, 4-Pdte documentación judicial/CON POSESION/ Las cargas se purgan con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior. '),
		T_TIPO_DATA(6814676,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-No constar que se ha requerido de pago a los deudores hipotecantes, 2-No constar que lo entregado al acreedor , no excede del límite de la respectiva cobertura hipotecaria, 3-Pdte certificación del tribunal con precio de remate y deuda pendiente, 4- Pdte instancia libertad de arrendatarios/CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación con visita interior. Advertencias: En la nota simple registral figura Avenida Manuel Quiroga, nº 88, pero el número de policía municipal actual es Avda. Manuel Quiroga, 84. Existen discrepancias debido a que la superficie comprobada es mayor a la adoptada de referencia registral.'),
		T_TIPO_DATA(6814681,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-No constar que se ha requerido de pago a los deudores hipotecantes, 2-No constar que lo entregado al acreedor , no excede del límite de la respectiva cobertura hipotecaria, 3-Pdte certificación del tribunal con precio de remate y deuda pendiente, 4- Pdte instancia libertad de arrendatarios/CON POSESION/OCUPADO/Con cargas que se purgarán con la inscripción/ Tasación sin visita interior. Advertencias: Se advierte de que no coincide la denominación de calle y/o el nº de policía con el reflejado en la documentación registral. Se recomienda su adecuación registral (Registralmente figura con el número 6 y catastralmente con el 4.)'),
		T_TIPO_DATA(6815808,'Finca adquirida por Bankia mediante título judicial/INSCRITO (074/10/2019)/Sin posesión/Sin cargas/Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6815947,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción: presentado en Hacienda el 25/02/20 /CON POSESION/ Con cargas que se purgan con la inscripción/ Tasación: la denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de su correcta identificación. Se recomienda su correcta inscripción.'),
		T_TIPO_DATA(6818271,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción: pdte justificar carácter no habitual de la vivienda adjudicada y en su caso, se concrete el importe de la deuda pendiente/SIN POSESION/ Con cargas ajenas/ Tasación sin acceso al interior del inmueble sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6818276,'Finca adquirida por Bankia mediante título judicial/INSCRITO (20/03/20)/Con posesión/Sin cargas/Tasación: La referencia catastral que consta en la nota simple aportada es errónea'),
		T_TIPO_DATA(6824737,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: Pdte instancia libertad de arrendatarios/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior.'),
		T_TIPO_DATA(6824739,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: Pdte certificación del Tribunal acreditativa de la deuda pendiente por todos los conceptos/CON POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin acceso al interior del inmueble. Existen discrepancias entre la dirección registral y la real del inmueble a tasar tras la inspección ocular del mismo. Sería pertinente una modificación de la dirección registral'),
		T_TIPO_DATA(6824752,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: Pdte instancia libertad de arrendatarios/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior.'),
		T_TIPO_DATA(6824754,'Solcitamos defecto a Garsa'),
		T_TIPO_DATA(6824809,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: Ausencia indicación de firmeza/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior/VPO: La vivienda estuvo calificada como V.P.O. (Vivienda con Calificación definitiva de viviendas de renta limitada subvencionadas , expediente A-VS-678-64)'),
		T_TIPO_DATA(6824843,'Finca adquirida por Madrid Residencial II Fondo de titulización de activos mediante título judicial/INSCRITO (24/09/2019)/Con posesión/Sin cargas/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior'),
		T_TIPO_DATA(6824905,'Finca adquirida por FONDO BANCAJA 10 DE TITULIZACIÓN DE ACTIVOS mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-No existe claridad en la determinación de las cantidades reclamadas, 2-Es necesario el desglose de las cantidades entregadas al acreedor, 3-Pdte si es vivienda habitual o n o, 4-es preciso que además de la firmeza del decreto, conste que no se halla pendiente un recurso de apelación, 5-Pdte completar circunstancias personales para la inscripción, 6-Pdte notificación de arrendatarios/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior/VPO: La vivienda objeto de valoración actualmente es de venta y renta libre al estar acogida regímenes anteriores al R.D. Ley 31/1978 según R.D. 727/93 y ser de promoción privada'),
		T_TIPO_DATA(6828433,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Aclarar si es vivienda habitual o no, dada la contradicción entre la información del decreto y la información obrante en el Registro de la propiedad. En caso de ser vivienda habitual, aplicación de esta circunstancia al valor de adjudicación, 2- Error en el importe total en acta saldo deudor/CON POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes.  Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Aclarar si es vivienda habitual o no, dada la contradicción entre la información del decreto y la información obrante en el Registro de la propiedad. En caso de ser vivienda habitual, aplicación de esta circunstancia al valor de adjudicación, 2- Error en el importe total en acta saldo deudor/CON POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes.    '),
		T_TIPO_DATA(6828435,'Finca adquirida por MADRID RMBS IV FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial/Pdte de inscripción por estar calificado negativamente: falta tracto sucesivo/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin visita interior. Zona consolidada por viviendas unifamiliares en suelo no urbanizable, sin intención de legalización, y únicamente pendiente de la redacción de planeamiento especial que regule la dotación de servicios mínimos. Situaciones clandestinas que se consolidan por el paso del tiempo. Se permiten sus inscripciones en el registro aportando certificados de antigüedad y de no infracción urbanística. La construcción tienen una antigüedad superior a 4 años.'),
		T_TIPO_DATA(6828534,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: discrepancia en la identificación del ejecutado. Registralmente consta con NIE y en la ejecución por DNI. Los defectos respecto a la comunicación de plusvalía y libertad de arrendamientos ya han sido subsanados /SIN POSESION/Con cargas que se purgarán con la inscripción/ VPO: Sí, y según consta en documentación registral, tiene el número de expediente 45-1-0182/91 fecha de calificación definitiva 09/11/1992/Tasación: Se ha observado que existen discrepancias entre la dirección física y la catastral, ya que en Catastro como número 24. Sin visita interior.'),
		T_TIPO_DATA(6828884,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: 1-Cesión de remate, 2-Error cantidad de adjudicación/CON POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior. '),
		T_TIPO_DATA(6828900,'Finca adquirida por MADRID RMBS IV FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial/Pdte de inscripción por estar calificado negativamente: falta tracto sucesivo/SIN POSESION/Con cargas que se purgarán con la inscripción/ Tasación sin visita interior. Existen discrepancias entre la superficie comprobada del inmueble y la registral y/o catastral. La denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de su correcta identificación. Se recomienda su correcta inscripción.'),
		T_TIPO_DATA(6830181,'Finca adquirida por Bankia mediante título judicial/INSCRITO (20/03/2020)/Con posesión/Sin cargas/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior'),
		T_TIPO_DATA(6830190,'Finca adquirida por Bankia mediante título judicial/INSCRITO (12/03/2020)/Con posesión/Sin cargas/ Tasación sin visita interior. En nota simple registral no figura número de policía, sin embargo la descripción de linderos permite su identificación así como la referencia catastral. VPO: Vivienda de protección Oficial, con expediente TO-82/030. Según información obtenida VPP con actual libre de venta y renta.'),
		T_TIPO_DATA(6831685,'Finca adquirida por BANCAJA 10 FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial/Pdte de inscripción por estar calificado negativamente: error importes económicos/CON POSESION/Con cargas que se purgarán con la inscripción/ Tasación, sin visita interior. VPO: La vivienda estuvo calificada como V.P.O.'),
		T_TIPO_DATA(6831767,'Finca adquirida por Bankia mediante título judicial/Pdte de inscripción por estar calificado negativamente: error importes económicos /SIN POSESION/ Con cargas que se purgarán con la inscripción/ Tasación sin acceso al interior del inmueble. '),
		T_TIPO_DATA(6832585,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-Pdte desglose del importe del precio de adjudicación, 2-No se acredita la representación de Garsa a Bankia/CON POSESION/ Las cargas se purgan con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior (lote vivienda, garaje y buhardilla).'),
		T_TIPO_DATA(6832602,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-Pdte desglose del importe del precio de adjudicación, 2-No se acredita la representación de Garsa a Bankia/CON POSESION/ Las cargas se purgan con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior (lote vivienda, garaje y buhardilla).'),
		T_TIPO_DATA(6832614,'Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: 1-Pdte desglose del importe del precio de adjudicación, 2-No se acredita la representación de Garsa a Bankia/CON POSESION/ Las cargas se purgan con la inscripción/ Tasación sin advertencias ni condicionantes importantes. Sin visita interior (lote vivienda, garaje y buhardilla).'),
		T_TIPO_DATA(6833269,'Finca adquirida por Bankia mediante título judicial/INSCRITO (07/01/2020)/Sin posesión/Sin cargas/ Tasación sin visita interior/ VPO: el edificio al que pertenece ha obtenido calificación definitiva de viviendas VPO, expediente O-VS-589/67, según cédula expedida en Madrid el 08/09/1969.'),
		T_TIPO_DATA(6837240,' Finca adquirida por Bankia mediante título judicial/Pdte inscripción por estar calificado negativamente: dependía de un documento notarial que ya se encuentra presentad en el Registro para la subsanación.  /SINN POSESION/ Las cargas se purgan con la inscripción/ Tasación sin visita interior. La denominación del registro de la propiedad y de policía no coinciden, no existiendo dudas de su identificación. Se recomienda su correcta inscripción.'),
		T_TIPO_DATA(6886569,' Finca adquirida por BANCAJA 10 FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial/Pdte de inscripción por estar calificado negativamente: falta tracto sucesivo/SIN POSESION/Con cargas que se purgarán con la inscripción/Tasación sin acceso al interior del inmueble.  '),
		T_TIPO_DATA(5925587,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que se ha calificado negativamente  por no manifestar que los bienes no son esenciales a la activad de la empresa. Una vez inscrita se cancelaran todas las cargas. Tasación sin visita al interior del inmueble, solicitamos a capa de control que modifique el activo debido a que es un edificio completo compuesto por cuatro viviendas'),
		T_TIPO_DATA(5925728,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN SUBIDA A REM, aunque esta marcada en sistema como que tiene.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que esta calificado negativamente,  Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble sin advertencias ni condicionantes importantes. '),
		T_TIPO_DATA(5925880,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que se ha calificado negativamente  por las clausulas de la ley 1/2013. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5926991,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5928265,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por CISA CARTERA DE INMUEBLES S.L.U.,mediante título judicial. Pendiente de inscripción. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5928411,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN SUBIDA A REM, aunque esta marcada en sistema como que tiene.  Finca adquirida por RBMS IV FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial. Pendiente de inscripción, debido a que esta calificado negativamente por no constar en el título las cantidades.  Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble sin advertencias ni condicionantes importantes. '),
		T_TIPO_DATA(5928616,'Procedimiento tramitado por Uniges en su día. Comentario de activo en observaciones'),
		T_TIPO_DATA(5928868,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bancaja Habitat mediante título judicial. Pendiente de inscripción, dado que se está subsanando el título. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5929817,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN. Finca adquirida por RBMS II FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial. Pendiente de inscripción, debido a que esta calificado negativamente por no constar en el título las cantidades.  Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble sin advertencias ni condicionantes importantes. '),
		T_TIPO_DATA(5930149,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha sido calificado negativamente el título por no indicar si es vivienda habitual del ejecutado, pendiente de adicción para su inscripción. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5930153,'Procedimiento tramitado por Uniges en su día. Comentario de activo en observaciones'),
		T_TIPO_DATA(5932370,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha sido calificado negativamente y se ha presentado por segunda vez en el registro para su calificación. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5933058,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. INSCRITA. Finca  libre de cargas salvo afecciones fiscales y el derecho de tanteo y retracto de a favor de la Generalitat de Cataluña. Finca calificada como vpo anterior a 1978, por tanto, de venta libre. Pendiente de obtener posesión.  Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5937265,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN MARCADA EN SISTEMA.  Finca adquirida por Bankia mediante título judicial. Inscrita. Pendiente de cancelación de hipoteca a favor de Caja Rural de Toledo.  En tasación se recoge que existe un exceso de superficie construida sin registrar se ha edificado un trastero en el patio delantero unido a la vivienda.'),
		T_TIPO_DATA(5937411,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN. Finca adquirida por RBMS I FONDO TITULIZACIÓN DE ACTIVOS mediante título judicial y cesión de remtate. Pendiente de inscripción, debido a que esta calificado negativamente por no notificar a los deudores en su domicilio.  Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble sin advertencias ni condicionantes importantes. '),
		T_TIPO_DATA(5937438,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bancaja Habitat mediante título judicial. Pendiente de inscripción, dado que se está subsanando el título. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble. Vivienda que estuvo calificada como vpo'),
		T_TIPO_DATA(5937632,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por BFA mediante título judicial. Pendiente de inscripción, dado que solo se tiene decreto. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble, tasado como solar debido a que la construcción que se está construyendo no se ha tenido en cuenta.'),
		T_TIPO_DATA(5937899,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción. Finca Vpo vigente. Calificado negativamente debido a que No consta que se ha demandado y requerido de pago al deudor, No consta que se haya notificado la existencia del procedimiento a los acreedores y terceros cuyo derecho ha sido anotado o inscrito con posterioridad a la hipoteca,  No constar que lo de lo entregado no excede del límite de la respectiva cobertura hipotecaria.'),
		T_TIPO_DATA(5937923,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha habido calificación negativa por el importe del valor de adjudicación, pendiente de subsanación. Tasación sin acceso al interior del inmueble'),
		T_TIPO_DATA(5940049,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha habido calificación negativa por el importe del valor de adjudicación, pendiente de subsanación. En principio finca cedido el remate a RMBS I, pero no consta dicha cesión de remate.Tasación sin acceso al interior del inmueble'),
		T_TIPO_DATA(5940706,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bancaja Habitat mediante título judicial. Pendiente de inscripción debido a que ha habido calificación negativa por el importe del valor de adjudicación, pendiente de subsanación.Tasación sin acceso al interior del inmueble. Finca vpo anterior a 1978, por tanto de venta libre.'),
		T_TIPO_DATA(5942974,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha habido calificación negativa. Tasación sin acceso al interior del inmueble'),
		T_TIPO_DATA(5944601,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que ha habido calificación negativa por el estado de ocupación del inmueble. Tasación sin acceso al interior del inmueble'),
		T_TIPO_DATA(5945241,'solicitado título y defecto a la gestoria'),
		T_TIPO_DATA(5947569,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bancaja Habitat mediante título judicial. Pendiente de inscripción, dado que se está subsanando el título. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5947637,'aunque el titulo a favor de Bankia esta subido en rem, pero no está inscrito, desconocemos si está presentado, vivienda con limitación vpo , el expediente  es  35-1E-0038/36-16.no sabemos quien gestiona el activo,'),
		T_TIPO_DATA(5948457,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por RMBS IV por cesión de remate. Pendiente de inscripción, dado que ha sido calificada negativamente y esta pendiente de adición judicial. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Finca vpo de venta libre por el transcurso del tiempo. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5948458,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Cisa cartera de inmuebles por cesión de remate. Pendiente de inscripción, dado que ha sido calificada negativamente y esta pendiente de adición judicial. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. . Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5948941,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, debido a que no consta el fallecimiento del titular regisrtral y la notificación a los herederos. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán.'),
		T_TIPO_DATA(5949870,'Procedimiento tramitado por Uniges en su día. Comentario de activo en observaciones'),
		T_TIPO_DATA(5949953,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, se ha solicitado a la gestoría estado de la adicción del título. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. En el título judicial se adjudican 2 viviendas y 3 garajes. Según tasación las viviendas que son el 3º B y 3º C están unidas físicamente, ponemos comentario en breve descripción del activo debido a que deben venderse juntas.'),
		T_TIPO_DATA(5950035,'Procedimiento tramitado por Uniges en su día. Comentario de activo en observaciones'),
		T_TIPO_DATA(5950662,'Proyecto depuración inmovilizado uso propio. Revisado ok'),
		T_TIPO_DATA(5951384,'Procedimiento tramitado por Uniges en su día. Comentario de activo en observaciones'),
		T_TIPO_DATA(5951441,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON  POSESIÓN MARCADA EN REM.  Finca adquirida por Bankia por adjudicación . Pendiente de inscripción. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. . Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5951629,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN  POSESIÓN.  Finca adquirida por Bankia por adjudicación . Pendiente de inscripción debido a que ha sido calificada negativamente por faltar tracto de hipoteca a favor de Bankia. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. . Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5953981,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, . Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5954443,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Fondo titulización de activos  mediante título judicial. Pendiente de calificación por el registro. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5955494,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por RMBS II  Fondo de Titulización de Activo mediante título judicial. Inscrito y libre de cargas. Tasación sin acceso al interior del inmueble y sin advertencias ni condicionantes relevantes. Finca calificada como Vpo anterior a 1978, por tanto, de venta libre.'),
		T_TIPO_DATA(5955570,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción que ha sido calificado negativamente el título  por no estar inscrito el concurso y por no haberse notificado a todos los acreedores. Tasación sin advertencias ni condicionantes relevantes.'),
		T_TIPO_DATA(5956397,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado que ha sido calificado el título negativamente . Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Finca vpo  calificada el 25/07/1995'),
		T_TIPO_DATA(5957497,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por RMBS IV mediante título judicial. Pendiente de inscripción, ha sido calificada negativamente al no existir mandamiento de cancelación. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. '),
		T_TIPO_DATA(5958214,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Cisa Cartera de Inmuebles mediante título judicial. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Finca calificada de vpo pero de venta libre por el transcurso del tiempo. Tasación sin advertencias ni condicionantes importante.'),
		T_TIPO_DATA(5958226,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que ha sido calificada negativamente. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. '),
		T_TIPO_DATA(5959430,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Cisa Cartera de inmuebles mediante título judicial. Pendiente de inscripción, dado que ha sido calificado el título negativamente . Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Finca que estuvo calificada de protección oficial, actualmente de venta libre.'),
		T_TIPO_DATA(5960086,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN marcada en Rem.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción debido a que falta tracto sucesivo de la carga ejecutada. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin acceso al interior del inmueble, sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5960587,NULL),
		T_TIPO_DATA(5960630,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Finca calificada de vpo pero de venta libre por el transcurso del tiempo. Tasación sin advertencias ni condicionantes importante.'),
		T_TIPO_DATA(5962883,'solicitado título y defecto a la gestoria'),
		T_TIPO_DATA(5963480,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN MARCADA EN REM.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que ha sido calificada negativamente por tracto sucesivo titular de la hipoteca ejecutada. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran.  Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5963720,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción,dado que ha sido calificado negativamente por no constar en el auto si es vivienda habitual y no haber notificado al ejecutado. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(5964029,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL. SIN POSESIÓN. Finca adquirida por Bankia en virtud de adjudicación judicial. Pendiente de inscribir a favor de la entidad bancaria, dado que ha sido calificado negativamente por el RP. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.'),
		T_TIPO_DATA(5964061,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL. SIN POSESIÓN. Finca adquirida por Bankia en virtud de adjudicación judicial. Pendiente de inscribir a favor de la entidad bancaria, dado que ha sido calificado negativamente por no identificar correctamente la hipoteca ejecutada debido a que es la inscripción 1ª y en título habla de la 3ª. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable. Vivienda que tiene como anejo un garaje y un trastero.'),
		T_TIPO_DATA(5964065,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que ha sido calificada negativamente por tracto sucesivo en la hipoteca que se ejecuta, pendiente de subsanación. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión.  Finca calificada vpo del año 1971, por tanto, de venta libre por paso del tiempo. Tasación sin advertencias ni condicionantes relevantes.'),
		T_TIPO_DATA(5964789,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que el título ha sido calificado negativamente por ejecutar la segunda certificación de dominio y carga en vez de la primera, pendiente de cancelación de  la primera certificación de dominio y carga. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble'),
		T_TIPO_DATA(5965120,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Inscrita a favor de Bankia y libre de cargas. Tasación sin acceso al interior del inmueble, sin condicionantes ni advertencias relevantes.'),
		T_TIPO_DATA(5966284,'REVISIÓN TITULO.  Finca pendiente de posesión. Finca inscrita a favor de Bankia por titulo judicial. Solicitamos a la gestoriía que suba nota simple actualizada e inscrita. Tasación sin advertencias ni condicionantes.'),
		T_TIPO_DATA(5966906,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que el título ha sido calificado negativamente por no notificar a todos los intervinientes. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble. Finca vpo anterior al 1978, por tanto, de venta libre.'),
		T_TIPO_DATA(5968208,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, debido a que el título ha sido calificado negativamente por no notificar a todos los intervinientes. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. Tasación sin acceso al interior del inmueble. Finca vpo anterior al 1978, por tanto, de venta libre.'),
		T_TIPO_DATA(5968941,'REVISIÓN DE TITULO. SIN POSESIÓN. Finca adquirida por RMBS II, por título judicial, pendiente de inscripción debido a que en el testimonio no se hace mención a la cesión de remate a favor de RMBS II, pendiente de subsanación. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5968980,'REVISIÓN DE TITULO. SIN POSESIÓN. Finca adquirida por RMBS III, por título judicial, pendiente de inscripción debido a que en el testimonio no se hace mención si el bien ejecutado es vivienda habitual, pendiente de subsanación. Tasación sin acceso al interior del inmueble. Una vez inscrito se debe cancelar carga a favor del Instituto de la Vivienda a ser una carga que no se cancelará por los mandamientos de cancelación al ser carga previa a la hipoteca que se ejecuta.'),
		T_TIPO_DATA(5969955,'REVISIÓN DE TITULO. ALQUILADO. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo de la hipoteca a favor de Bancaja a Bankia. Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación se recogen discrepancias físico- Jurídica debido a que se ha construido un garaje y un trastero no inscritos. '),
		T_TIPO_DATA(5971466,'REVISIÓN DE TITULO. SIN POSESIÓN. Finca adquirida por Bankia, por título judicial, pendiente de inscripción, pendiente de adicción del testimonio. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6044562,'REVISIÓN DE TITULO. SIN POSESIÓN. Finca adquirida por Bankia, por título judicial, pendiente de inscripción debido a que ha sido calificada negativamente al no recoger el título si es domicilio habitual de los ejecutados. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6044694,'REVISIÓN TITULO. SIN POSESIÓN. Finca Rústica, inscrita a favor de Bankia, por título de adjudicación. Tasación sin advertencias ni condicionantes importantes'),
		T_TIPO_DATA(6045708,'REVISIÓN DE TITULO. SIN POSESIÓN. Finca adquirida por Bankia, por título judicial, pendiente de inscripción debido a que ha sido calificada negativamente al no recoger el título si es domicilio habitual de los ejecutados. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6045738,'REVISIÓN TÍTULO. PENDIENTE DE POSESIÓN. Finca adjudicada a Bankia en virtud de título judicial, pendiente de inscripción debido a que ha sido calificado negativamente por no constar certificado de Deuda y la notificación al deudor. Analizada la tasación, no consta registralmente inscrito la finalización de obra y  la  división horizontal. Tasación sin acceso al interior del inmueble, por tanto, no podemos observar si físicamente la construcción está terminada.'),
		T_TIPO_DATA(6045968,'REVISIÓN TÍTULO. PENDIENTE DE POSESIÓN. Finca adjudicada a RMBS II Fondo de titulización de activo en virtud de título judicial, pendiente de inscripción debido a que ha sido calificado negativamente por no constar si el bien ejecutado es vivienda habitual Analizada la tasación,no hay advertencias ni condicionantes relevantes, tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6046178,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo de la hipoteca a favor de Caja Madrid a Bankia. Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6047301,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta certificación de cargas pendiente de adición. Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6047424,'REVISIÓN TÍTULO. SIN POSESIÓN SUBIDA A REM. Finca adjudicada a RMBS III Fondo de titulización de activo en virtud de título judicial, pendiente de inscripción debido a que ha sido calificado negativamente por no constar el tracto sucesivo en la hipoteca, falta aclaración finca regiistral e indicar datos societarios, pendiente de adicionar. Analizada la tasación,no hay advertencias ni condicionantes relevantes, tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6048350,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por Bankia, por titulo judicial pendiente de inscripción. Incluimos el inmueble incluido en la agrupaciaón restringida 100021226 debido a que si bien se a inscrito la división horizontal, en la realizad física no se ha iniciado la construcción, por tanto, es un suelo y se deben vender todos los activos juntos'),
		T_TIPO_DATA(6048351,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por Bankia, por titulo judicial pendiente de inscripción. Incluimos el inmueble incluido en la agrupaciaón restringida 100021226 debido a que si bien se a inscrito la división horizontal, en la realizad física no se ha iniciado la construcción, por tanto, es un suelo y se deben vender todos los activos juntos'),
		T_TIPO_DATA(6048352,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por Bankia, por titulo judicial pendiente de inscripción. Incluimos el inmueble incluido en la agrupaciaón restringida 100021226 debido a que si bien se a inscrito la división horizontal, en la realizad física no se ha iniciado la construcción, por tanto, es un suelo y se deben vender todos los activos juntos'),
		T_TIPO_DATA(6048353,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por Bankia, por titulo judicial pendiente de inscripción. Incluimos el inmueble incluido en la agrupaciaón restringida 100021226 debido a que si bien se a inscrito la división horizontal, en la realizad física no se ha iniciado la construcción, por tanto, es un suelo y se deben vender todos los activos juntos'),
		T_TIPO_DATA(6048420,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo correcto de la hipoteca Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6049036,'REVISIÓN DE TITULO. CON POSESIÓN MARCADA EN SISTEMA, Finca que estuvo alquilada al ejecutado, pero aparece sin alquiler. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo correcto de la hipoteca Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6049391,'REVISIÓN DE TITULO. PENDIENTE DE POSESIÓN. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo correcto de la hipoteca y notificar el procedimiento a todos los titulares de la finca. Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación hay disparidad físico jurídica entre catastro y registro y la realizad física.'),
		T_TIPO_DATA(6049496,'REVISIÓN DE TITULO. CON POSESIÓN MARCADA EN SISTEMA, sin que este subido a Rem el documento de posesión. Finca adquirida por BANKIA, por título judicial, pendiente de inscripción debido a a que falta el tracto sucesivo correcto de la hipoteca Las cargas se purgarán por el mandamiento de cancelación. Analizada la tasación sin advertencias ni condicionantes importantes.'),
		T_TIPO_DATA(6050500,'REVISIÓN DEL TITULO. SIN POSESIÓN. Finca adquirida por Bankia en virtud de título judicial, pendiente de inscripción debido a que ha sido calificada negativamente por no contar las cantidades de la ejecución, no contar con la notificación a los deudores y no contar con la cesión de remate firme, una vez inscrita y con el mandamiento de cancelación se cancelaran todas las cargas.Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6050611,'REVISIÓN DEL TITULO. SIN POSESIÓN. Finca adquirida por Bankia en virtud de título judicial, pendiente de inscripción debido a que ha sido calificada negativamente por no encontrarse la hipoteca a favor de Bankia, una vez inscrita y con el mandamiento de cancelación se cancelaran todas las cargas. Finca que estuvo calificada de vpo, pero que actualmente es de venta libre. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6051610,'REVISIÓN DEL TITULO. SIN POSESIÓN. Finca adquirida por Bankia en virtud de título judicial, pendiente de inscripción debido a que ha sido calificada negativamente por existir cargas anteriores a la certificación de dominio y cargas, pendiente de subsanación. Tasación sin advertencias relevantes y sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6052039,'REVISIÓN DE TITULO. FINCA CON POSESIÓN MARCADA EN EL SISTEMA. Finca inscrita a favor de Bankia por titulo judicial, libre de cargas salvo condición resolutoria a mantener por el periodo de 30 años el uso de nave industrial, no cancelable. En tasación se recoge un exceso de cabida inferior al 20 entre la realidad física del inmueble y la registral y catastral.'),
		T_TIPO_DATA(6058171,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado que aún no se ha presentado toda la documentación en el RP. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. Finca en construcción registralmente.'),
		T_TIPO_DATA(6058252,'REVISIÓN TÍTULO. COMPRAVENTA. CONCURSO DE ACREEDORES. CON POSESIÓN. Finca adquirida por Bankia mediante título de compraventa. Pendiente de inscripción dado que no se ha presentado en el registro la autorización judicial de venta. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.  '),
		T_TIPO_DATA(6058253,'REVISIÓN TÍTULO. COMPRAVENTA. CONCURSO DE ACREEDORES. CON POSESIÓN. Finca adquirida por Bankia mediante título de compraventa. Pendiente de inscripción dado que no se ha presentado en el registro la autorización judicial de venta. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.  '),
		T_TIPO_DATA(6058254,'REVISIÓN TÍTULO. COMPRAVENTA. CONCURSO DE ACREEDORES. CON POSESIÓN. Finca adquirida por Bankia mediante título de compraventa. Pendiente de inscripción dado que no se ha presentado en el registro la autorización judicial de venta. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.  '),
		T_TIPO_DATA(6058255,'REVISIÓN TÍTULO. COMPRAVENTA. CONCURSO DE ACREEDORES. CON POSESIÓN. Finca adquirida por Bankia mediante título de compraventa. Pendiente de inscripción dado que no se ha presentado en el registro la autorización judicial de venta. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.  '),
		T_TIPO_DATA(6058256,'REVISIÓN TÍTULO. COMPRAVENTA. CONCURSO DE ACREEDORES. CON POSESIÓN. Finca adquirida por Bankia mediante título de compraventa. Pendiente de inscripción dado que no se ha presentado en el registro la autorización judicial de venta. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable.  '),
		T_TIPO_DATA(6058680,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL. SIN POSESIÓN. Finca adquirida por Bankia en virtud de adjudicación judicial. Pendiente de inscribir a favor de la entidad bancaria, dado que ha sido calificado negativamente por el RP debido a que no se ha notificado a todos los deudores. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable. '),
		T_TIPO_DATA(6058743,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL. Finca Inscrita a favor de Bankia, libre de cargas. CON POSESIÓN MARCADA EN EL SISTEMA. Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(6063292,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL CON POSESIÓN MARCADA EN REM. Finca adquirida por Bankia en virtud de adjudicación judicial. Pendiente de inscribir a favor de la entidad bancaria, dado que ha sido calificado negativamente por el RP debido a que no se expresa la totalidad de las cantidades económica de la adjudicación, pendiente de subsanación. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable. '),
		T_TIPO_DATA(5952970,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, se ha solicitado a la gestoría estado de la adicción del título. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. En el título judicial se adjudican 2 viviendas y 3 garajes. Según tasación las viviendas que son el 3º B y 3º C están unidas físicamente, ponemos comentario en breve descripción del activo debido a que deben venderse juntas.'),
		T_TIPO_DATA(5933727,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, se ha solicitado a la gestoría estado de la adicción del título. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. En el título judicial se adjudican 2 viviendas y 3 garajes. Según tasación las viviendas que son el 3º B y 3º C están unidas físicamente, ponemos comentario en breve descripción del activo debido a que deben venderse juntas.'),
		T_TIPO_DATA(6051131,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, se ha solicitado a la gestoría estado de la adicción del título. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. En el título judicial se adjudican 2 viviendas y 3 garajes. Según tasación las viviendas que son el 3º B y 3º C están unidas físicamente, ponemos comentario en breve descripción del activo debido a que deben venderse juntas.'),
		T_TIPO_DATA(5947652,'REVISIÓN TÍTULO. TITULO JUDICIAL. CON POSESIÓN.  Finca adquirida por Bankia mediante título judicial. Pendiente de inscripción, dado ha sido calificado negativamente, se ha solicitado a la gestoría estado de la adicción del título. Una vez inscrita se cancelarán todas las cargas posteriores, ya que se purgarán. En el título judicial se adjudican 2 viviendas y 3 garajes. Según tasación las viviendas que son el 3º B y 3º C están unidas físicamente, ponemos comentario en breve descripción del activo debido a que deben venderse juntas.'),
		T_TIPO_DATA(6058681,'REVISIÓN TÍTULO. ADJUDICACIÓN JUDICIAL. SIN POSESIÓN. Finca adquirida por Bankia en virtud de adjudicación judicial. Pendiente de inscribir a favor de la entidad bancaria, dado que ha sido calificado negativamente por el RP debido a que no se ha notificado a todos los deudores. Tras revisar tasación no existe condicionantes o advertencias legales de carácter reseñable. '),
		T_TIPO_DATA(5948379,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN  POSESIÓN.  Finca adquirida por Bankia por adjudicación . Pendiente de inscripción debido a que ha sido calificada negativamente por faltar tracto de hipoteca a favor de Bankia. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. . Tasación sin acceso al interior del inmueble.'),
		T_TIPO_DATA(5935624,'REVISIÓN TÍTULO. TITULO JUDICIAL. SIN  POSESIÓN.  Finca adquirida por Bankia por adjudicación . Pendiente de inscripción debido a que ha sido calificada negativamente por faltar tracto de hipoteca a favor de Bankia. Una vez inscrita se cancelaran todas las cargas posteriores, ya que se purgaran. Pendiente de obtener posesión. . Tasación sin acceso al interior del inmueble.')
		); 
    V_TMP_TIPO_DATA T_TIPO_DATA;


BEGIN		

	DBMS_OUTPUT.PUT_LINE('[INICIO]');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] BUSCAR TABLA '||V_TABLA||'');	

        V_SQL := 'SELECT COUNT(1) FROM ALL_TABLES WHERE OWNER = '''||V_ESQUEMA||''' AND TABLE_NAME = '''||V_TABLA||''''; 
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLA;

		IF V_NUM_TABLA = 1 THEN

			DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZACIÓN OBSERVACIONES');

			FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
			LOOP      
				V_TMP_TIPO_DATA := V_TIPO_DATA(I);

				DBMS_OUTPUT.PUT_LINE('[INFO] OBSERVACIONES ACTIVO '''||V_TMP_TIPO_DATA(1)||'''');
				V_SQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA||' ART SET 
					ART.ART_OBSERVACIONES = TRIM(CONVERT('''||V_TMP_TIPO_DATA(2)||''', ''UTF8'', ''AL32UTF8''))
					WHERE ART.ACT_ID = (SELECT ACT.ACT_ID FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT WHERE ACT.ACT_NUM_ACTIVO = '||V_TMP_TIPO_DATA(1)||')';
				EXECUTE IMMEDIATE V_SQL;
			END LOOP;
		ELSE		
			DBMS_OUTPUT.PUT_LINE('[INFO] LA TABLA '||V_TABLA||' NO EXISTE');
		END IF;

	COMMIT;
	
	DBMS_OUTPUT.PUT_LINE('[FIN]');
 
EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(ERR_MSG);
          ROLLBACK;
          RAISE;   
END;
/
EXIT;
