--/*
--#########################################
--## AUTOR=Adrián Molina Garrido
--## FECHA_CREACION=20211214
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-16666
--## PRODUCTO=NO
--## 
--## Finalidad: Creación de tabla 'AUX_HREOS-16666'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

TABLE_COUNT NUMBER(1,0) := 0;
V_ESQUEMA_1 VARCHAR2(20 CHAR) := 'REM01';
V_ESQUEMA_2 VARCHAR2(20 CHAR) := 'REMMASTER';
V_TABLESPACE_IDX VARCHAR2(30 CHAR) := 'REM_IDX';
V_TABLA VARCHAR2(40 CHAR) := 'AUX_HREOS_16666';

BEGIN

SELECT COUNT(1) INTO TABLE_COUNT FROM ALL_TABLES WHERE TABLE_NAME = ''||V_TABLA||'' AND OWNER= ''||V_ESQUEMA_1||'';

IF TABLE_COUNT > 0 THEN

    EXECUTE IMMEDIATE '
		MERGE INTO '||V_ESQUEMA_1||'.ACT_ADN_ADJNOJUDICIAL T1 USING
		(
			SELECT ADN.ADN_ID, AUX.FECHA_POSESION 
			FROM '||V_ESQUEMA_1||'.ACT_ACTIVO ACT
			JOIN '||V_ESQUEMA_1||'.ACT_ADN_ADJNOJUDICIAL ADN ON ADN.ACT_ID = ACT.ACT_ID AND ADN.BORRADO = 0
			JOIN '||V_ESQUEMA_1||'.'||V_TABLA||' AUX ON AUX.ACT_NUM_ACTIVO = ACT.ACT_NUM_ACTIVO 
			WHERE ACT.BORRADO = 0
		) T2 ON(T1.ADN_ID = T2.ADN_ID) WHEN MATCHED THEN UPDATE SET 
		T1.FECHA_POSESION = TO_DATE(TO_CHAR(TO_DATE(T2.FECHA_POSESION,''MM/DD/YYYY''), ''DD/MM/YYYY''), ''DD/MM/YYYY''),
		USUARIOMODIFICAR = ''HREOS-16666'',
		FECHAMODIFICAR = SYSDATE';
    
END IF;

DBMS_OUTPUT.PUT_LINE('[INFO] '||SQL%ROWCOUNT||' REGISTROS MODIFICADOS'); 
DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA_1||'.ACT_ADN_ADJNOJUDICIAL MODIFICADA');  

COMMIT;

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/


EXIT;

