--/*
--##########################################
--## AUTOR=GUSTAVO MORA NAVARRO
--## FECHA_CREACION=20150914
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=CMREC-533
--## PRODUCTO=NO
--## 
--## Finalidad: Creación tabla y DD de job_validation DD_JVI_JOB_VAL_INTERFAZ, DD_JVS_JOB_VAL_SEVERITY y BATCH_JOB_VALIDATION
--##                               , esquema CMMASTER, considerando FKs comno IDs
--## INSTRUCCIONES:  Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;


DECLARE

 V_SCHEMA_MASTER VARCHAR(25) := '#ESQUEMA_MASTER#';
 V_SCHEMA VARCHAR(25) := '#ESQUEMA#'; 
 TABLA1 VARCHAR(30) :='DD_JVS_JOB_VAL_SEVERITY'; 
 TABLA2 VARCHAR(30) :='DD_JVI_JOB_VAL_INTERFAZ';  
 TABLA3 VARCHAR(30) :='BATCH_JOB_VALIDATION'; 
 ITABLE_SPACE VARCHAR(25) :='IRECOVERYONL8M';
 TABLE_SPACE VARCHAR(25)  :='DRECOVERYONL8M';
 err_num NUMBER;
 err_msg VARCHAR2(2048); 
 V_MSQL1 VARCHAR2(8500 CHAR);
 V_MSQL2 VARCHAR2(8500 CHAR);
 V_MSQL3 VARCHAR2(8500 CHAR);
 V_EXISTE NUMBER (1):=null;


BEGIN 

--Validamos si la tabla existe antes de crearla
  SELECT COUNT(*) INTO V_EXISTE
  FROM ALL_TABLES
  WHERE TABLE_NAME = ''||TABLA1||'';


 
  IF V_EXISTE = 1 THEN   
     EXECUTE IMMEDIATE ('DROP TABLE '||V_SCHEMA_MASTER||'.'||TABLA3 );
     DBMS_OUTPUT.PUT_LINE(''||TABLA3||' BORRADA');
     EXECUTE IMMEDIATE ('DROP TABLE '||V_SCHEMA_MASTER||'.'||TABLA1 );
     DBMS_OUTPUT.PUT_LINE(''||TABLA1||' BORRADA');
     EXECUTE IMMEDIATE ('DROP TABLE '||V_SCHEMA_MASTER||'.'||TABLA2 );
     DBMS_OUTPUT.PUT_LINE(''||TABLA2||' BORRADA');
  END IF;   
          


  V_MSQL1 := 'CREATE TABLE '||V_SCHEMA_MASTER||'.'||TABLA1||'  
  (	
     DD_JVS_ID NUMBER(16,0) NOT NULL ENABLE, 
	   DD_JVS_CODIGO VARCHAR2(50 CHAR),
	   DD_JVS_DESCRIPCION VARCHAR2(50 CHAR), 
	   DD_JVS_DESCRIPCION_LARGA VARCHAR2(250 CHAR), 
	   VERSION NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	   USUARIOCREAR VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	   FECHACREAR DATE NOT NULL ENABLE, 
	   USUARIOMODIFICAR VARCHAR2(10 CHAR), 
	   FECHAMODIFICAR DATE, 
	   USUARIOBORRAR VARCHAR2(10 CHAR), 
	   FECHABORRAR DATE, 
	   BORRADO NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
 	 CONSTRAINT DD_JVS_JOB_VAL_INTERFAZ_PK PRIMARY KEY (DD_JVS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
          PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
          )  TABLESPACE '||ITABLE_SPACE||'  ENABLE, 
	 CONSTRAINT DD_JVS_JOB_VAL_SEVERITY_UK UNIQUE (DD_JVS_CODIGO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
          PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
          )  TABLESPACE '||ITABLE_SPACE||'  ENABLE  
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE '||TABLE_SPACE||'';
          

     EXECUTE IMMEDIATE V_MSQL1;
     DBMS_OUTPUT.PUT_LINE(''||TABLA1||' CREADA');

  
  V_MSQL2 := 'CREATE TABLE '||V_SCHEMA_MASTER||'.'||TABLA2||'  
  (	
     DD_JVI_ID NUMBER(16,0) NOT NULL ENABLE, 
     DD_JVI_CODIGO VARCHAR2(50 CHAR) NOT NULL ENABLE, 
     DD_JVI_DESCRIPCION VARCHAR2(50 CHAR), 
     DD_JVI_DESCRIPCION_LARGA VARCHAR2(250 CHAR), 
     DD_JVI_BLOQUE  VARCHAR2(50 CHAR),      
     VERSION NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
     USUARIOCREAR VARCHAR2(10 CHAR) NOT NULL ENABLE, 
     FECHACREAR DATE NOT NULL ENABLE, 
     USUARIOMODIFICAR VARCHAR2(10 CHAR), 
     FECHAMODIFICAR DATE, 
     USUARIOBORRAR VARCHAR2(10 CHAR), 
     FECHABORRAR DATE, 
     BORRADO NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
 CONSTRAINT DD_JVI_JOB_VAL_INTERFAZ_PK PRIMARY KEY (DD_JVI_ID)
 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
       TABLESPACE '||ITABLE_SPACE||'   ENABLE, 
 CONSTRAINT DD_JVI_JOB_VAL_INTERFAZ_UK UNIQUE (DD_JVI_CODIGO)
 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
       TABLESPACE '||ITABLE_SPACE||'  ENABLE  
 ) SEGMENT CREATION IMMEDIATE 
       PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
       STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
       PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
       TABLESPACE '||TABLE_SPACE||'';
 
 
     EXECUTE IMMEDIATE V_MSQL2;
     DBMS_OUTPUT.PUT_LINE(''||TABLA2||' CREADA');

  
    
  V_MSQL3 := 'CREATE TABLE '||V_SCHEMA_MASTER||'.'||TABLA3||'  
  ( 
     JOB_VAL_ID       NUMBER(16) NOT NULL ENABLE
   , JOB_VAL_CODIGO   VARCHAR2(100 CHAR) NOT NULL ENABLE
   , JOB_VAL_ENTITY   NUMBER(16)
   , JOB_VAL_ORDER    NUMBER(5)
   , JOB_VAL_VALUE    VARCHAR2(2500 CHAR)
   , JOB_VAL_INTERFAZ NUMBER(16) 
   , JOB_VAL_SEVERITY NUMBER(16) 
   , JOB_VAL_TOKEN    VARCHAR2(2500 CHAR)
   , VERSION NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE 
   , USUARIOCREAR VARCHAR2(10 CHAR) NOT NULL ENABLE
   , FECHACREAR DATE NOT NULL ENABLE
   , USUARIOMODIFICAR VARCHAR2(10 CHAR)
   , FECHAMODIFICAR DATE
   , USUARIOBORRAR VARCHAR2(10 CHAR)
   , FECHABORRAR DATE
   , BORRADO NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE   
   , CONSTRAINT PK_BATCH_JOB_VALIDATION PRIMARY KEY (JOB_VAL_ID)
     USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
     STORAGE(
             INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
             ) TABLESPACE '||ITABLE_SPACE||'  ENABLE
	 , CONSTRAINT UK_BATCH_JOB_VALIDATION UNIQUE (JOB_VAL_CODIGO)
     USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
     STORAGE(
             INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
            ) TABLESPACE '||ITABLE_SPACE||'  ENABLE
   , CONSTRAINT FK_JOB_VAL_FK_JVI_VAL_INTERFAZ FOREIGN KEY (JOB_VAL_INTERFAZ)
           REFERENCES '||V_SCHEMA_MASTER||'.DD_JVI_JOB_VAL_INTERFAZ (DD_JVI_ID) ENABLE
   , CONSTRAINT FK_JOB_VAL_FK_JVS_VAL_SEVERITY FOREIGN KEY (JOB_VAL_SEVERITY)
	   REFERENCES '||V_SCHEMA_MASTER||'.DD_JVS_JOB_VAL_SEVERITY (DD_JVS_ID) ENABLE     
   , CONSTRAINT FK_JOB_VAL_FK_ENTITY FOREIGN KEY (JOB_VAL_ENTITY)
	   REFERENCES '||V_SCHEMA_MASTER||'.ENTIDAD (ID) ENABLE  	   
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   
  TABLESPACE '||TABLE_SPACE||'';
  
     EXECUTE IMMEDIATE V_MSQL3;
     DBMS_OUTPUT.PUT_LINE(''||TABLA3||' CREADA');  


   EXECUTE IMMEDIATE ('grant insert, select, update on '||V_SCHEMA_MASTER||'.'||TABLA1||' to '||V_SCHEMA||''); 
   EXECUTE IMMEDIATE ('grant insert, select, update on '||V_SCHEMA_MASTER||'.'||TABLA2||' to '||V_SCHEMA||''); 
   EXECUTE IMMEDIATE ('grant insert, select, update on '||V_SCHEMA_MASTER||'.'||TABLA3||' to '||V_SCHEMA||'');      
/* */     
     
EXCEPTION
WHEN OTHERS THEN  
  err_num := SQLCODE;
  err_msg := SQLERRM;

  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
  
  ROLLBACK;
  RAISE;
END;
/
EXIT;   



