--/*
--#########################################
--## AUTOR=GUILLEM REY
--## FECHA_CREACION=20170608
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-2209
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración MIG2_GDE_GASTOS_DET_ECONOMICO -> GDE_GASTOS_DETALLE_ECONOMICO
--##                    
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

TABLE_COUNT NUMBER(10,0) := 0;
V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
V_USUARIO VARCHAR2(50 CHAR) := '#USUARIO_MIGRACION#';
V_TABLA VARCHAR2(40 CHAR) := 'GDE_GASTOS_DETALLE_ECONOMICO';
V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG2_GDE_GASTOS_DET_ECONOMICO';
V_SENTENCIA VARCHAR2(32000 CHAR);

BEGIN

      DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');
      
      V_SENTENCIA := '
INSERT INTO REM01.GDE_GASTOS_DETALLE_ECONOMICO (GDE_ID, GPV_ID, GDE_PRINCIPAL_SUJETO, GDE_PRINCIPAL_NO_SUJETO
    , GDE_RECARGO, GDE_INTERES_DEMORA, GDE_COSTAS, GDE_OTROS_INCREMENTOS, GDE_PROV_SUPLIDOS
    , GDE_IMP_IND_EXENTO
    , GDE_IMP_IND_RENUNCIA_EXENCION, GDE_IMP_IND_TIPO_IMPOSITIVO, GDE_IMP_IND_CUOTA, GDE_IRPF_TIPO_IMPOSITIVO
    , GDE_IRPF_CUOTA, GDE_IMPORTE_TOTAL, GDE_FECHA_TOPE_PAGO, GDE_REPERCUTIBLE_INQUILINO, GDE_IMPORTE_PAGADO
    , GDE_FECHA_PAGO, DD_TPA_ID, DD_TPP_ID, DD_DEP_ID, USUARIOCREAR, FECHACREAR, GDE_REEMBOLSO_TERCERO
    , GDE_INCLUIR_PAGO_PROVISION, GDE_ABONO_CUENTA, GDE_IBAN, GDE_TITULAR_CUENTA, GDE_NIF_TITULAR_CUENTA
    , GDE_PAGADO_CONEXION_BANKIA, GDE_NUMERO_CONEXION, GDE_OFICINA_BANKIA, DD_TIT_ID)
SELECT REM01.S_GDE_GASTOS_DETALLE_ECONOMICO.NEXTVAL GDE_ID, GPV.GPV_ID, GDE.GDE_PRINCIPAL_SUJETO, GDE.GDE_PRINCIPAL_NO_SUJETO
    , GDE.GDE_RECARGO, GDE.GDE_INTERES_DEMORA, GDE.GDE_COSTAS, GDE.GDE_OTROS_INCREMENTOS, GDE.GDE_PROVISIONES_SUPLIDOS
    , CASE WHEN GDE.GDE_IMP_IND_CUOTA = 0 AND GDE.GDE_IND_IMP_INDIRECTO_EXENTO IS NULL AND DD_TIT_CODIGO = ''01''
        THEN (SELECT DD_SIN_ID FROM REMMASTER.DD_SIN_SINO T3 WHERE T3.DD_SIN_CODIGO = ''01'')
        ELSE GDE.GDE_IND_IMP_INDIRECTO_EXENTO END GDE_IMP_IND_EXENTO
    , GDE.GDE_IND_IMP_INDIR_RENUN_EXENC, GDE.GDE_IMP_INDIR_TIPO_IMPOSITIVO, GDE.GDE_IMP_IND_CUOTA, GDE.GDE_IRPF_TIPO_IMPOSITIVO
    , GDE.GDE_IRPF_CUOTA, GDE.GDE_IMPORTE_TOTAL, GDE.GDE_FECHA_TOPE_PAGO, GDE.GDE_IND_REPERCUTIBLE_INQUILINO, GDE.GDE_IMPORTE_PAGADO
    , GDE.GDE_FECHA_PAGO, TPA.DD_TPA_ID, TPP.DD_TPP_ID, DEP.DD_DEP_ID, '''||V_USUARIO||''', SYSDATE, GDE.GDE_REEMBOLSO_TERCERO
    , GDE.GDE_INCLUIR_PAGO_PROVISION, GDE.GDE_ABONO_CUENTA, GDE.GDE_IBAN, GDE.GDE_TITULAR_CUENTA, GDE.GDE_NIF_TITULAR_CUENTA
    , GDE.GDE_PAGADO_CONEXION_BANKIA, GDE.GDE_NUMERO_CONEXION, GDE.GDE_OFICINA_BANKIA, TIT.DD_TIT_ID
FROM REM01.MIG2_GDE_GASTOS_DET_ECONOMICO GDE
JOIN REM01.GPV_GASTOS_PROVEEDOR GPV ON GPV.GPV_NUM_GASTO_HAYA = GDE.GDE_GPV_ID
LEFT JOIN REM01.DD_TIT_TIPOS_IMPUESTO TIT ON TIT.DD_TIT_CODIGO = GDE.GDE_COD_TIPO_IMPUESTO
LEFT JOIN REM01.DD_TPA_TIPOS_PAGADOR TPA ON TPA.DD_TPA_CODIGO = GDE.GDE_COD_TIPO_PAGADOR
LEFT JOIN REM01.DD_TPP_TIPOS_PAGO TPP ON TPP.DD_TPP_CODIGO = GDE.GDE_COD_TIPO_PAGO
LEFT JOIN REM01.DD_DEP_DESTINATARIOS_PAGO DEP ON DEP.DD_DEP_CODIGO = GDE.GDE_COD_RESP_PAGO_FUERA_PLAZO
LEFT JOIN REM01.GDE_GASTOS_DETALLE_ECONOMICO GDE2 ON GDE2.GPV_ID = GPV.GPV_ID
WHERE GDE.VALIDACION = 0 AND GDE2.GDE_ID IS NULL
                '
                ;
      EXECUTE IMMEDIATE V_SENTENCIA     ;
      
      DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');
      
      COMMIT;
      
      V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''1''); END;';
      EXECUTE IMMEDIATE V_SENTENCIA;
      
EXCEPTION
      WHEN OTHERS THEN
            DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
            DBMS_OUTPUT.put_line('-----------------------------------------------------------');
            DBMS_OUTPUT.put_line(SQLERRM);
            ROLLBACK;
            RAISE;
END;

/

EXIT;
