--/*
--#########################################
--## AUTOR=DAP
--## FECHA_CREACION=20170622
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-2209
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración 'MIG_ADJ_JUDICIAL' -> 'ACT_AJD_ADJJUDICIAL', 'BIE_ADJ_ADJUDICACION (Merge)'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
V_USUARIO VARCHAR2(50 CHAR) := '#USUARIO_MIGRACION#';
V_TABLA VARCHAR2(40 CHAR) := 'ACT_AJD_ADJJUDICIAL';
V_TABLA_2 VARCHAR2(40 CHAR) := 'BIE_ADJ_ADJUDICACION';
V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG_ADJ_JUDICIAL';
V_SENTENCIA VARCHAR2(2000 CHAR);

BEGIN
  
    DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');

	EXECUTE IMMEDIATE ('
	INSERT INTO '||V_ESQUEMA||'.'||V_TABLA||' (
	AJD_ID,
	ACT_ID,
	BIE_ADJ_ID,
	DD_JUZ_ID,
	DD_PLA_ID,
	DD_EDJ_ID,
	DD_EEJ_ID,
	AJD_FECHA_ADJUDICACION,
	AJD_NUM_AUTO,
	AJD_PROCURADOR,
	AJD_LETRADO,
	AJD_ID_ASUNTO,
	VERSION,
	USUARIOCREAR,
	FECHACREAR,
	USUARIOMODIFICAR,
	FECHAMODIFICAR,
	USUARIOBORRAR,
	FECHABORRAR,
	BORRADO
	)
	SELECT
  	'||V_ESQUEMA||'.S_ACT_AJD_ADJJUDICIAL.NEXTVAL         AJD_ID,
	AUX.*
	FROM (
	SELECT
	ACT.ACT_ID,
	BIE.BIE_ADJ_ID,
	(SELECT DD_JUZ_ID
	  FROM '||V_ESQUEMA||'.DD_JUZ_JUZGADOS_PLAZA
	  WHERE DD_JUZ_CODIGO = MIG.JUZGADO)                  DD_JUZ_ID,
	(SELECT DD_PLA_ID
	  FROM '||V_ESQUEMA||'.DD_PLA_PLAZAS
	  WHERE DD_PLA_CODIGO = MIG.PLAZA_JUZGADO)            DD_PLA_ID,
	(SELECT DD_EDJ_ID
	  FROM '||V_ESQUEMA||'.DD_EDJ_ESTADO_ADJUDICACION
	  WHERE DD_EDJ_CODIGO = MIG.ESTADO_ADJUDICACION)      DD_EDJ_ID,
	(SELECT DD_EEJ_ID
	  FROM '||V_ESQUEMA||'.DD_EEJ_ENTIDAD_EJECUTANTE
	  WHERE DD_EEJ_CODIGO = MIG.ENTIDAD_EJECUTANTE)       DD_EEJ_ID,
	MIG.ADJ_FECHA_ADJUDICACION                            AJD_FECHA_ADJUDICACION,
	MIG.ADJ_NUM_AUTO                                      AJD_NUM_AUTO,
	MIG.ADJ_PROCURADOR                                    AJD_PROCURADOR,
	MIG.ADJ_LETRADO                                       AJD_LETRADO,
	MIG.ADJ_ID_ASUNTO                                     AJD_ID_ASUNTO,
	''0''                                                 VERSION,
	'''||V_USUARIO||'''                                               USUARIOCREAR,
	SYSDATE                                               FECHACREAR,
	NULL                                                  USUARIOMODIFICAR,
	NULL                                                  FECHAMODIFICAR,
	NULL                                                  USUARIOBORRAR,
	NULL                                                  FECHABORRAR,
	0                                                     BORRADO
	FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
    JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO = MIG.ACT_NUMERO_ACTIVO AND ACT.BORRADO = 0
    JOIN REM01.BIE_ADJ_ADJUDICACION BIE ON BIE.BIE_ID = ACT.BIE_ID AND BIE.BORRADO = 0
    WHERE MIG.VALIDACION = 0 AND NOT EXISTS (SELECT 1 FROM '||V_ESQUEMA||'.'||V_TABLA||' AUX WHERE AUX.ACT_ID = ACT.ACT_ID AND AUX.BORRADO = 0)
    ) AUX
	')
	;
  
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');
  
  --------
    commit;

  V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''10''); END;';
  EXECUTE IMMEDIATE V_SENTENCIA;
  
	DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA_2||'. [BIE_ADJ_F_SEN_POSESION, BIE_ADJ_IMPORTE_ADJUDICACION y ADJ_FECHA_DECRETO_FIRME]');

	EXECUTE IMMEDIATE ('
	MERGE INTO '||V_ESQUEMA||'.'||V_TABLA_2||' BIE 
	USING (
		SELECT ACT.BIE_ADJ_ID, MIG.ADJ_IMPORTE, MIG.ADJ_FECHA_SEN_POSESION, MIG.ADJ_FECHA_DECRETO_FIRME
		FROM '||V_ESQUEMA||'.'||V_TABLA||' ACT
		INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACTIV
		ON ACTIV.ACT_ID = ACT.ACT_ID
		INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
		ON MIG.ACT_NUMERO_ACTIVO = ACTIV.ACT_NUM_ACTIVO
		WHERE MIG.VALIDACION = 0
	) TMP
	ON (BIE.BIE_ADJ_ID = TMP.BIE_ADJ_ID)
	WHEN MATCHED THEN UPDATE SET
	BIE.BIE_ADJ_F_SEN_POSESION = TMP.ADJ_FECHA_SEN_POSESION,
	BIE.BIE_ADJ_IMPORTE_ADJUDICACION = TMP.ADJ_IMPORTE,
	BIE.BIE_ADJ_F_DECRETO_FIRME = TMP.ADJ_FECHA_DECRETO_FIRME
	')  
	;
  
  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' actualizada. '||SQL%ROWCOUNT||' Filas. Merge.');
  
	execute immediate 'MERGE INTO ACT_SPS_SIT_POSESORIA T1
		USING (SELECT T1.ACT_ID, T4.BIE_ADJ_F_SEN_POSESION
		    FROM ACT_SPS_SIT_POSESORIA T1
		    JOIN ACT_AJD_ADJJUDICIAL T2 ON T1.ACT_ID = T2.ACT_ID AND T2.BORRADO = 0
		    JOIN ACT_ACTIVO T3 ON T3.ACT_ID = T2.ACT_ID AND T3.BORRADO = 0
		    JOIN BIE_ADJ_ADJUDICACION T4 ON T4.BIE_ID = T3.BIE_ID AND T4.BORRADO = 0
		    WHERE T1.BORRADO = 0 AND T4.BIE_ADJ_F_SEN_POSESION IS NOT NULL AND T1.SPS_FECHA_TOMA_POSESION IS NULL) T2
		ON (T1.ACT_ID = T2.ACT_ID)
		WHEN MATCHED THEN UPDATE SET
		    T1.SPS_FECHA_TOMA_POSESION = T2.BIE_ADJ_F_SEN_POSESION';

  DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.ACT_SPS_SIT_POSESORIA actualizada. '||SQL%ROWCOUNT||' Filas. Merge.');

  COMMIT;

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

EXIT;
