--/*
--#########################################
--## AUTOR=DAP
--## FECHA_CREACION=20170608
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-2209
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración MIG2_GPV_GASTOS_PROVEEDORES -> GPV_GASTOS_PROVEEDOR
--##                    
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

    TABLE_COUNT NUMBER(10,0) := 0;
    TABLE_COUNT_2 NUMBER(10,0) := 0;
    TABLE_COUNT_3 NUMBER(10,0) := 0;
    MAX_NUM_GASTO_HAYA NUMBER(10,0) := 0;
    V_NUM_TABLAS NUMBER(10,0) := 0;
    V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
    V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
    V_USUARIO VARCHAR2(50 CHAR) := '#USUARIO_MIGRACION#'; 
    V_TABLA VARCHAR2(40 CHAR) := 'GPV_GASTOS_PROVEEDOR';
    V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG2_GPV_GASTOS_PROVEEDORES';
    V_SENTENCIA VARCHAR2(32000 CHAR);
    TYPE T_VAL is table of VARCHAR2(4000); 
    TYPE T_ARRAY_VAL IS TABLE OF T_VAL;
    V_VAL T_ARRAY_VAL := T_ARRAY_VAL(
        T_VAL('AND FIL.PRIORIDAD = 0','ADMINISTRACION'),
        T_VAL('AND FIL.PRIORIDAD = 1','ENTIDAD'),
        T_VAL('AND FIL.PRIORIDAD = 2','PROVEEDOR'),
        T_VAL('AND FIL.PRIORIDAD = 3','GESTORIA'),
        T_VAL('','POR DEFECTO')
    );  
    V_TMP_VAL T_VAL; 

BEGIN
    DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');

    EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.'||V_TABLA||' NOLOGGING';
    V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||'''); END;';
    EXECUTE IMMEDIATE V_SENTENCIA;

    FOR i IN V_VAL.FIRST..V_VAL.LAST
        LOOP
        V_TMP_VAL := V_VAL(i);
			V_SENTENCIA := '
			        INSERT INTO /*+ APPEND */ REM01.GPV_GASTOS_PROVEEDOR
					(GPV_ID, GPV_NUM_GASTO_HAYA, GPV_NUM_GASTO_GESTORIA, GPV_REF_EMISOR, DD_TGA_ID
					    ,DD_STG_ID, GPV_CONCEPTO, DD_TPE_ID, PVE_ID_EMISOR, GPV_FECHA_EMISION, GPV_FECHA_NOTIFICACION, DD_DEG_ID, GPV_CUBRE_SEGURO
					    ,GPV_OBSERVACIONES, GPV_COD_GASTO_AGRUPADO, GPV_COD_TIPO_OPERACION, GPV_NUMERO_FACTURA_UVEM, GPV_NUMERO_PROVISION_FONDOS
					    ,GPV_NUMERO_PRESUPUESTO, DD_TOG_ID, PVE_ID_GESTORIA, USUARIOCREAR, FECHACREAR, PRG_ID)
					SELECT
					    REM01.S_GPV_GASTOS_PROVEEDOR.NEXTVAL GPV_ID
					    ,MIG2.GPV_ID
					    ,MIG2.GPV_COD_GASTO_PROVEEDOR
					    ,MIG2.GPV_REFERENCIA_EMISOR
					    ,TGA.DD_TGA_ID
					    ,STG.DD_STG_ID
					    ,MIG2.GPV_CONCEPTO
					    ,TPE.DD_TPE_ID
					    ,PVE.PVE_ID
					    ,MIG2.GPV_FECHA_EMISION
					    ,MIG2.GPV_FECHA_NOTIFICACION
					    ,(SELECT DEG.DD_DEG_ID FROM REM01.DD_DEG_DESTINATARIOS_GASTO DEG WHERE DEG.DD_DEG_CODIGO = ''01'')
					    ,MIG2.GPV_IND_CUBRE_SEGURO
					    ,MIG2.GPV_OBSERVACIONES
					    ,MIG2.GPV_COD_GASTO_AGRUPADO
					    ,MIG2.GPV_COD_TIPO_OPERACION   
					    ,MIG2.GPV_NUMERO_FACTURA_UVEM
					    ,MIG2.GPV_NUMERO_PROVISION_FONDOS
					    ,MIG2.GPV_NUMERO_PRESUPUESTO
					    ,TOG.DD_TOG_ID
					    ,CASE WHEN GDE.GDE_COD_TIPO_IMPUESTO IS NULL THEN PVE.PVE_ID ELSE NULL END PVE_ID_GESTORIA
					    ,'''||V_USUARIO||'''
					    ,SYSDATE
					    ,(SELECT MIN(PRG.PRG_ID) FROM REM01.PRG_PROVISION_GASTOS PRG WHERE PRG.PRG_NUM_PROVISION = MIG2.GPV_NUMERO_PROVISION_FONDOS)
					FROM REM01.MIG2_GPV_GASTOS_PROVEEDORES MIG2
					LEFT JOIN REM01.GPV_GASTOS_PROVEEDOR GPV ON GPV.GPV_NUM_GASTO_HAYA = MIG2.GPV_ID
					JOIN REM01.MIG2_GDE_GASTOS_DET_ECONOMICO GDE ON GDE.GDE_GPV_ID = MIG2.GPV_ID
					JOIN REM01.MIG_AUX_ACT_PVE_PROVEEDOR PVE ON PVE.PVE_COD_UVEM = TO_CHAR(MIG2.GPV_COD_PVE_UVEM_EMISOR)
					JOIN REM01.DD_TGA_TIPOS_GASTO TGA ON TGA.DD_TGA_CODIGO = MIG2.GPV_COD_TIPO_GASTO
					JOIN REM01.DD_STG_SUBTIPOS_GASTO STG ON STG.DD_STG_CODIGO = MIG2.GPV_COD_SUBTIPO_GASTO
					JOIN REM01.DD_TPR_TIPO_PROVEEDOR TPR ON PVE.DD_TPR_ID = TPR.DD_TPR_ID
					JOIN REM01.MIG_AUX_GASTOS_FILTRO FIL ON NVL(FIL.DD_TGA_CODIGO,TGA.DD_TGA_CODIGO) = TGA.DD_TGA_CODIGO AND FIL.DD_TPR_CODIGO = TPR.DD_TPR_CODIGO AND NVL(FIL.DD_STG_CODIGO,STG.DD_STG_CODIGO) = STG.DD_STG_CODIGO
					LEFT JOIN REM01.DD_TPE_TIPOS_PERIOCIDAD TPE ON TPE.DD_TPE_CODIGO = NVL(MIG2.GPV_COD_PERIODICIDAD, ''01'')
					LEFT JOIN REM01.DD_TOG_TIPO_OPERACION_GASTO TOG ON TOG.DD_TOG_CODIGO = MIG2.GPV_COD_TIPO_OPERACION
					WHERE MIG2.VALIDACION = 0 AND GPV.GPV_ID IS NULL '||V_TMP_VAL(1);
            EXECUTE IMMEDIATE V_SENTENCIA;
            DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'''||V_TABLA||''' cargada. '||SQL%ROWCOUNT||' Filas de gastos de proveedores '||V_TMP_VAL(2)||'.');

            V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''1''); END;';
    		EXECUTE IMMEDIATE V_SENTENCIA;
        END LOOP;

    EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.'||V_TABLA||' LOGGING';

EXCEPTION
      WHEN OTHERS THEN
            DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
            DBMS_OUTPUT.put_line('-----------------------------------------------------------');
            DBMS_OUTPUT.put_line(SQLERRM);
            ROLLBACK;
            RAISE;
END;
/
EXIT