--/*
--#########################################
--## AUTOR=DAP
--## FECHA_CREACION=20170612
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-2209
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración MIG2_GGE_GASTOS_GESTION -> GGE_GASTOS_GESTION
--##                    
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01';
V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER';
V_USUARIO VARCHAR2(50 CHAR) := '#USUARIO_MIGRACION#';
V_TABLA VARCHAR2(40 CHAR) := 'GGE_GASTOS_GESTION';
V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG2_GGE_GASTOS_GESTION';
V_SENTENCIA VARCHAR2(32000 CHAR);

BEGIN

      DBMS_OUTPUT.PUT_LINE('[INFO] COMIENZA EL PROCESO DE MIGRACION SOBRE LA TABLA '||V_ESQUEMA||'.'||V_TABLA||'.');
      
      V_SENTENCIA := '
        INSERT INTO REM01.GGE_GASTOS_GESTION (GGE_ID, GPV_ID, GGE_AUTORIZACION_PROPIETARIO, DD_MAP_ID, GGE_OBSERVACIONES
            , GGE_FECHA_ALTA, USU_ID_ALTA, DD_EAH_ID, GGE_FECHA_EAH, USU_ID_EAH
            , DD_MRH_ID, DD_EAP_ID, GGE_FECHA_EAP, GGE_MOTIVO_RECHAZO_PROP, GGE_FECHA_ANULACION
            , USU_ID_ANULACION, DD_MAG_ID, GGE_FECHA_RP, USU_ID_RP, DD_MRP_ID, USUARIOCREAR, FECHACREAR)
        SELECT REM01.S_GGE_GASTOS_GESTION.NEXTVAL, GPV.GPV_ID, MIG.GGE_IND_AUTORIZ_PROP, MAP.DD_MAP_ID, MIG.GGE_OBSERVACIONES
            , MIG.GGE_FECHA_ALTA, USU_ALT.USU_ID, EAH.DD_EAH_ID, MIG.GGE_FECHA_ESTADO_AUTORIZ_HAYA, USU_EAH.USU_ID
            , MRH.DD_MRH_ID, EAP.DD_EAP_ID, MIG.GGE_FECHA_EST_AUTORIZ_PROP, MIG.GGE_MOT_RECHAZO_PROP, MIG.GGE_FECHA_ANULACION
            , USU_ANU.USU_ID, MAG.DD_MAG_ID, MIG.GGE_FECHA_RETENCION_PAGO, USU_RPA.USU_ID, MRP.DD_MRP_ID, '''||V_USUARIO||''', SYSDATE
        FROM REM01.MIG2_GGE_GASTOS_GESTION MIG
        JOIN REM01.GPV_GASTOS_PROVEEDOR GPV ON GPV.GPV_NUM_GASTO_HAYA = MIG.GGE_GPV_ID
        LEFT JOIN REM01.DD_MAP_MOT_AUT_PROP_GASTO MAP ON MAP.DD_MAP_CODIGO = MIG.GGE_COD_MOT_AUTORIZ_PROP
        LEFT JOIN REM01.DD_EAH_ESTADOS_AUTORIZ_HAYA EAH ON EAH.DD_EAH_CODIGO = MIG.GGE_COD_EST_AUTORIZ_HAYA
        LEFT JOIN REM01.DD_MRH_MOTIVOS_RECHAZO_HAYA MRH ON MRH.DD_MRH_CODIGO = MIG.GGE_COD_MOT_RECH_AUTORIZ_HAYA
        LEFT JOIN REM01.DD_EAP_ESTADOS_AUTORIZ_PROP EAP ON EAP.DD_EAP_CODIGO = MIG.GGE_COD_EST_AUTORIZ_PROP
        LEFT JOIN REM01.DD_MAG_MOTIVOS_ANULACION_GASTO MAG ON MAG.DD_MAG_CODIGO = MIG.GGE_COD_MOTIVO_ANULACION_GASTO
        LEFT JOIN REM01.DD_MRP_MOTIVOS_RET_PAGO MRP ON MRP.DD_MRP_CODIGO = MIG.GGE_COD_MOTIVO_RETENCION_PAGO
        LEFT JOIN REMMASTER.USU_USUARIOS USU_ALT ON USU_ALT.USU_USERNAME = MIG.GGE_COD_USUARIO_ALTA
        LEFT JOIN REMMASTER.USU_USUARIOS USU_EAH ON USU_EAH.USU_USERNAME = MIG.GGE_COD_USU_EST_AUTORIZ_HAYA
        LEFT JOIN REMMASTER.USU_USUARIOS USU_ANU ON USU_ANU.USU_USERNAME = MIG.GGE_COD_USUARIO_ANULACION
        LEFT JOIN REMMASTER.USU_USUARIOS USU_RPA ON USU_RPA.USU_USERNAME = MIG.GGE_COD_USUARIO_RETENCION_PAGO
        LEFT JOIN REM01.GGE_GASTOS_GESTION GGE ON GGE.GPV_ID = GPV.GPV_ID
        WHERE MIG.VALIDACION = 0 AND GGE.GPV_ID IS NULL
                '
                ;
      EXECUTE IMMEDIATE V_SENTENCIA;
      
      DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');
      
      COMMIT;
      
      V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''1''); END;';
      EXECUTE IMMEDIATE V_SENTENCIA;
      DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.'||V_TABLA||' ANALIZADA.');
 
EXCEPTION
      WHEN OTHERS THEN
            DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
            DBMS_OUTPUT.put_line('-----------------------------------------------------------');
            DBMS_OUTPUT.put_line(SQLERRM);
            ROLLBACK;
            RAISE;
END;

/

EXIT;
