OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_8330
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ACT_NUM_ACTIVO_UVEM			NULLIF(ACT_NUM_ACTIVO_UVEM=BLANKS)			"TRIM(:ACT_NUM_ACTIVO_UVEM)",
	DD_RTG_DESCRIPCION			NULLIF(DD_RTG_DESCRIPCION=BLANKS)			"TRIM(:DD_RTG_DESCRIPCION)"
)
