-- diccionario de tipos de operación
--DROP SEQUENCE S_DD_OPM_OPERACION_MASIVA;
CREATE SEQUENCE S_DD_OPM_OPERACION_MASIVA;

--DROP TABLE DD_OPM_OPERACION_MASIVA;
CREATE TABLE DD_OPM_OPERACION_MASIVA  (
   DD_OPM_ID		 			NUMBER(16)			NOT NULL,
   DD_OPM_CODIGO           		VARCHAR2(20 BYTE)   NOT NULL,
   DD_OPM_DESCRIPCION       	VARCHAR2(50 BYTE),
   DD_OPM_DESCRIPCION_LARGA     VARCHAR2(250 BYTE),
   FUN_ID			    		NUMBER(16)			NOT NULL,
   VERSION                  	INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             	VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               	TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         	VARCHAR2(10 BYTE),
   FECHAMODIFICAR           	TIMESTAMP(6),
   USUARIOBORRAR            	VARCHAR2(10 BYTE),
   FECHABORRAR              	TIMESTAMP(6),
   BORRADO                 		 NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_DD_OPM_OPERACION_MASIVA PRIMARY KEY (DD_OPM_ID),
  -- CONSTRAINT UK_DD_OPM_OPERACION_MASIVA UNIQUE KEY (DD_OPM_CODIGO),
   CONSTRAINT FK_DD_OPM_FUN_ID FOREIGN KEY (FUN_ID)REFERENCES LINMASTER.FUN_FUNCIONES (FUN_ID)
);

INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'AAS','Alta asuntos','Alta asuntos',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_BO'),'DD',SYSDATE);

	
INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'CRCO','Confirmar recepción contrato original','Confirmar recepcion contrato original',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_BO'),'DD',SYSDATE);
	
INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'CRT','Confirmar recepción testimonio','Confirmar recepcion testimonio',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_BO'),'DD',SYSDATE);

INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'IMD','Impresión documentación','Impresión documentación',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_BO'),'DD',SYSDATE);

INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'EJZ','Envío Juzgado','Envío Juzgado',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_BO'),'DD',SYSDATE);
	
	
INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'RAS','Reorganización asuntos','Reorganización asuntos',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_LEGAL'),'DD',SYSDATE);
	
INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'CPA','Cancelación/Paralización','Cancelación/Paralización',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_LEGAL'),'DD',SYSDATE);
	
INSERT INTO DD_OPM_OPERACION_MASIVA (DD_OPM_ID,DD_OPM_CODIGO,DD_OPM_DESCRIPCION,DD_OPM_DESCRIPCION_LARGA,FUN_ID,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_OPM_OPERACION_MASIVA.nextVal,'AUP','Autoprórroga','Autoprórroga',(select fun_id from linmaster.fun_funciones where fun_descripcion='ROLE_LEGAL'),'DD',SYSDATE);
		
	
-- plantillas
--DROP SEQUENCE S_POP_PLANTILLAS_OPERACION ;
CREATE SEQUENCE S_POP_PLANTILLAS_OPERACION;

--DROP TABLE POP_PLANTILLAS_OPERACION;
CREATE TABLE POP_PLANTILLAS_OPERACION  (
   POP_ID			 			NUMBER(16)			NOT NULL,
   POP_NOMBRE			       	VARCHAR2(250 BYTE)  NOT NULL,
   POP_DIRECTORIO				VARCHAR2(250 BYTE)  NOT NULL,
   DD_OPM_ID			    	NUMBER(16)			NOT NULL,
   VERSION                  	INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             	VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               	TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         	VARCHAR2(10 BYTE),
   FECHAMODIFICAR           	TIMESTAMP(6),
   USUARIOBORRAR            	VARCHAR2(10 BYTE),
   FECHABORRAR              	TIMESTAMP(6),
   BORRADO                 		 NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_POP_PLANTILLAS_OPERACION PRIMARY KEY (POP_ID),
   CONSTRAINT FK_POP_DD_OPM_ID FOREIGN KEY (DD_OPM_ID) REFERENCES DD_OPM_OPERACION_MASIVA (DD_OPM_ID)
);

-- Tipos de juicio DD_TJ_TIPO_JUICIO

CREATE SEQUENCE S_DD_TJ_TIPO_JUICIO
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE TABLE DD_TJ_TIPO_JUICIO
(
  DD_TJ_ID                 NUMBER(16)           NOT NULL,
  DD_TJ_CODIGO             VARCHAR2(20 BYTE)    NOT NULL,
  DD_TJ_DESCRIPCION        VARCHAR2(50 BYTE),
  DD_TJ_DESCRIPCION_LARGA  VARCHAR2(250 BYTE),
  VERSION                  INTEGER              DEFAULT 0                     NOT NULL,
  USUARIOCREAR             VARCHAR2(10 BYTE)    NOT NULL,
  FECHACREAR               TIMESTAMP(6)         NOT NULL,
  USUARIOMODIFICAR         VARCHAR2(10 BYTE),
  FECHAMODIFICAR           TIMESTAMP(6),
  USUARIOBORRAR            VARCHAR2(10 BYTE),
  FECHABORRAR              TIMESTAMP(6),
  BORRADO                  NUMBER(1)            DEFAULT 0                     NOT NULL
);

CREATE UNIQUE INDEX PK_DD_TJ_TIPO_JUICIO ON LIN001.DD_TJ_TIPO_JUICIO (DD_TJ_ID);


ALTER TABLE LIN001.DD_TJ_TIPO_JUICIO ADD (
  CONSTRAINT PK_DD_TJ_TIPO_JUICIO
 PRIMARY KEY
 (DD_TJ_ID)
    USING INDEX );
               
               
Insert into DD_TJ_TIPO_JUICIO
   (DD_TJ_ID, DD_TJ_CODIGO, DD_TJ_DESCRIPCION, DD_TJ_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (1, 'MON', 'Monitorio', 'Monitorio', 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into DD_TJ_TIPO_JUICIO
   (DD_TJ_ID, DD_TJ_CODIGO, DD_TJ_DESCRIPCION, DD_TJ_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (2, 'ETJ', 'ETJ', 'ETJ', 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into DD_TJ_TIPO_JUICIO
   (DD_TJ_ID, DD_TJ_CODIGO, DD_TJ_DESCRIPCION, DD_TJ_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (3, 'BOF', 'BackOffice', 'BackOffice', 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0);
COMMIT;
	
-- Tipos de resolución. 


CREATE SEQUENCE S_DD_TR_TIPOS_RESOLUCION
  START WITH 21
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
 CREATE TABLE DD_TR_TIPOS_RESOLUCION
(
  DD_TR_ID                 NUMBER(16)           NOT NULL,
  DD_TR_CODIGO             VARCHAR2(20 BYTE)    NOT NULL,
  DD_TR_DESCRIPCION        VARCHAR2(50 BYTE),
  DD_TR_DESCRIPCION_LARGA  VARCHAR2(250 BYTE),
  DD_TJ_ID                 NUMBER(16)           NOT NULL,
  VERSION                  INTEGER              DEFAULT 0                     NOT NULL,
  USUARIOCREAR             VARCHAR2(10 BYTE)    NOT NULL,
  FECHACREAR               TIMESTAMP(6)         NOT NULL,
  USUARIOMODIFICAR         VARCHAR2(10 BYTE),
  FECHAMODIFICAR           TIMESTAMP(6),
  USUARIOBORRAR            VARCHAR2(10 BYTE),
  FECHABORRAR              TIMESTAMP(6),
  BORRADO                  NUMBER(1)            DEFAULT 0                     NOT NULL,
  DD_TR_AYUDA              VARCHAR2(2000 BYTE)
);


CREATE UNIQUE INDEX PK_DD_TR_TIPOS_RESOLUCION ON DD_TR_TIPOS_RESOLUCION (DD_TR_ID);


ALTER TABLE DD_TR_TIPOS_RESOLUCION ADD (
  CONSTRAINT PK_DD_TR_TIPOS_RESOLUCION
 PRIMARY KEY
 (DD_TR_ID)
    USING INDEX 
);

ALTER TABLE DD_TR_TIPOS_RESOLUCION ADD (
  CONSTRAINT FK_DD_TJ_ID 
 FOREIGN KEY (DD_TJ_ID) 
 REFERENCES DD_TJ_TIPO_JUICIO (DD_TJ_ID));
 

 Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (1, 'MDP', 'Mon: Demanda presentada', 'Mon: Demanda presentada', 1, 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 1');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (2, 'MID', 'Mon: Inadmisión de la demanda', 'Mon: Inadmisión de la demanda', 1, 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 2');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (3, 'MRP', 'Mon: Requerimientos previos', 'Mon: Requerimientos previos', 1, 0, 'SUPER', TO_TIMESTAMP('25/02/0213 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 3');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (4, 'MAPD', 'Mon: Admisión parcial de la demanda', 'Mon: Admisión parcial de la demanda', 2, 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 4');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (5, 'MATD', 'Mon: Admisión total de la demanda', 'Mon: Admisión total de la demanda', 2, 0, 'SUPER', TO_TIMESTAMP('25/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 5');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (6, 'MRPP', 'Mon: Requerimiento Pago Positivo', 'Mon: Requerimiento Pago Positivo', 3, 0, 'SUPER', TO_TIMESTAMP('25/02/0213 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 6');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (7, 'MRPN', 'Mon: Requerimiento pago negativo', 'Mon: Requerimiento pago negativo', 3, 0, 'SUPER', TO_TIMESTAMP('27/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 7');
Insert into DD_TR_TIPOS_RESOLUCION
   (DD_TR_ID, DD_TR_CODIGO, DD_TR_DESCRIPCION, DD_TR_DESCRIPCION_LARGA, DD_TJ_ID, VERSION, USUARIOCREAR, FECHACREAR, BORRADO, DD_TR_AYUDA)
 Values
   (8, 'MSOL', 'Mon: Solicitud de oficios de Localización', 'Mon: Solicitud de oficios de Localización', 3, 0, 'SUPER', TO_TIMESTAMP('27/02/2013 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 0, 'Ayuda 8');
COMMIT;
	