-- CREACIÓN DE LA TABLA DD_TCC_TIPO_CONTROL_CALIDAD

CREATE SEQUENCE S_DD_TCC_TIPO_CONTROL_CALIDAD;

CREATE TABLE DD_TCC_TIPO_CONTROL_CALIDAD (    
    DD_TCC_ID                  NUMBER(16)         NOT NULL,
    DD_TCC_CODIGO			         VARCHAR2(50 CHAR)	NOT NULL,
    DD_TCC_DESCRIPCION			   VARCHAR2(100 CHAR)	NOT NULL,
    DD_TCC_DESCRIPCION_LARGA  VARCHAR2(250 CHAR)	NOT NULL,
    DD_TCC_NOMBRE_TABLA		     VARCHAR2(250 CHAR)	NOT NULL,
    DD_TCC_NOMBRE_ENTIDAD	    VARCHAR2(250 CHAR)	NOT NULL,
    VERSION                 INTEGER    			DEFAULT 0 NOT NULL,
    USUARIOCREAR            VARCHAR2(10 CHAR)   NOT NULL,
    FECHACREAR              TIMESTAMP(6)       NOT NULL,
    USUARIOMODIFICAR        VARCHAR2(10 CHAR),
    FECHAMODIFICAR          TIMESTAMP(6),
    USUARIOBORRAR           VARCHAR2(10 CHAR),
    FECHABORRAR             TIMESTAMP(6),
    BORRADO                 NUMBER(1)  DEFAULT 0  NOT NULL,
    CONSTRAINT PK_TCC_ID PRIMARY KEY (DD_TCC_ID)
);

CREATE INDEX IX_TCC_DD_TCC_CODIGO ON DD_TCC_TIPO_CONTROL_CALIDAD (DD_TCC_CODIGO);


-- CREACIÓN DE LA TABLA CCP_CONTROL_CALIDAD_PROC

CREATE SEQUENCE S_CCP_CONTROL_CALIDAD_PROC;

CREATE TABLE CCP_CONTROL_CALIDAD_PROC (    
    CCP_ID                  NUMBER(16)          NOT NULL,
    CCP_ID_BPM		        NUMBER(16)          NOT NULL,
    CCP_DESCRIPCION			VARCHAR2(250 CHAR)	NOT NULL,
    CCP_REVISADO			NUMBER(1)			DEFAULT 0 NOT NULL,
    CCA_ID	            	NUMBER(16)          NOT NULL,
    PRC_ID	            	NUMBER(16)          NULL,        
    VERSION                 INTEGER    			DEFAULT 0 NOT NULL,
    USUARIOCREAR            VARCHAR2(10 CHAR)   NOT NULL,
    FECHACREAR              TIMESTAMP(6)       NOT NULL,
    USUARIOMODIFICAR        VARCHAR2(10 CHAR),
    FECHAMODIFICAR          TIMESTAMP(6),
    USUARIOBORRAR           VARCHAR2(10 CHAR),
    FECHABORRAR             TIMESTAMP(6),
    BORRADO                 NUMBER(1)  DEFAULT 0  NOT NULL,
    CONSTRAINT PK_CCP_ID PRIMARY KEY (CCP_ID)    
);

CREATE INDEX IX_CCP_CCA_ID ON CCP_CONTROL_CALIDAD_PROC (CCA_ID);
CREATE INDEX IX_CCP_PRC_ID ON CCP_CONTROL_CALIDAD_PROC (PRC_ID);


-- CREACIÓN DE LA TABLA CCA_CONTROL_CALIDAD

CREATE SEQUENCE S_CCA_CONTROL_CALIDAD;

CREATE TABLE CCA_CONTROL_CALIDAD (    
    CCA_ID                  NUMBER(16)          NOT NULL,
    CCA_ID_ENTIDAD          NUMBER(16)          NULL,
    CCA_DESCRIPCION			VARCHAR2(250 CHAR)	NOT NULL,
    DD_EIN_ID            	NUMBER(16)          NOT NULL,
    DD_TCC_ID            	NUMBER(16)          NOT NULL,        
    VERSION                 INTEGER    			DEFAULT 0 NOT NULL,
    USUARIOCREAR            VARCHAR2(10 CHAR)   NOT NULL,
    FECHACREAR              TIMESTAMP(6)       NOT NULL,
    USUARIOMODIFICAR        VARCHAR2(10 CHAR),
    FECHAMODIFICAR          TIMESTAMP(6),
    USUARIOBORRAR           VARCHAR2(10 CHAR),
    FECHABORRAR             TIMESTAMP(6),
    BORRADO                 NUMBER(1)  DEFAULT 0  NOT NULL,
    CONSTRAINT PK_CCA_ID PRIMARY KEY (CCA_ID),
    CONSTRAINT UK_CCA_ID_ENTIDAD_DD_EIN_ID UNIQUE (CCA_ID_ENTIDAD, DD_EIN_ID),
    CONSTRAINT FK_CCA_DD_TCC_ID FOREIGN KEY (DD_TCC_ID) REFERENCES DD_TCC_TIPO_CONTROL_CALIDAD (DD_TCC_ID)
);

CREATE INDEX IX_CCA_ID_ENTIDAD ON CCA_CONTROL_CALIDAD (CCA_ID_ENTIDAD);
CREATE INDEX IX_CCA_DD_EIN_ID ON CCA_CONTROL_CALIDAD (DD_EIN_ID);
CREATE INDEX IX_CCA_DD_TCC_ID ON CCA_CONTROL_CALIDAD (DD_TCC_ID);

ALTER TABLE CCA_CONTROL_CALIDAD ADD CONSTRAINT FK_CCA_DD_EIN_ID FOREIGN KEY (DD_EIN_ID) REFERENCES BANKMASTER.DD_EIN_ENTIDAD_INFORMACION (DD_EIN_ID);
ALTER TABLE CCP_CONTROL_CALIDAD_PROC ADD CONSTRAINT FK_CCP_CCA_ID FOREIGN KEY (CCA_ID) REFERENCES CCA_CONTROL_CALIDAD (CCA_ID);
