--/*
--#########################################
--## AUTOR=David González
--## FECHA_CREACION=20151101
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=BKREC-1335
--## PRODUCTO=NO
--## 
--## Finalidad: 
--## INSTRUCCIONES:  
--## VERSIONES:
--##        	0.1 Versión inicial
--##		
--#########################################
--*/
 
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE GEST_SUB_PRO AUTHID CURRENT_USER AS

BEGIN
/* v0.1 */

	INSERT INTO #ESQUEMA_MINIREC#.RCV_GEST_LOG VALUES (#ESQUEMA_MINIREC#.S_RCV_GEST_LOG.NEXTVAL, 'RCV_GEST_SUB_PRO', 'INSERT EN MINIREC.RCV_GEST_SUB_PRO', 'INICIO', TO_CHAR(SYSTIMESTAMP, 'DD/MM/RR HH24:MI:SS'));

	DBMS_OUTPUT.PUT_LINE('[INFO] La tabla MINIREC.RCV_GEST_SUB_PRO va a ser truncada.');

	#ESQUEMA_MINIREC#.OPERACION_DDL.DDL_TABLE('TRUNCATE','RCV_GEST_SUB_PRO');

COMMIT;

	DBMS_OUTPUT.PUT_LINE('[INFO] Tabla MINIREC.RCV_GEST_SUB_PRO truncada.');

	DBMS_OUTPUT.PUT_LINE('[INFO] Se van a insertar registros en MINIREC.RCV_GEST_SUB_PRO.');

INSERT INTO #ESQUEMA_MINIREC#.RCV_GEST_SUB_PRO
	SELECT 
	  A.ID_PROPUESTA_RCV
	  ,LOS.LOS_NUM_LOTE 																								LOTE
	  ,DECODE(MAX(BAD.BIE_ADJ_CESION_REMATE),1,'CES',DECODE(MIN(UPPER(EAD.DD_EAD_DESCRIPCION)),'ENTIDAD','ADJ','TER')) 	RESULTADO_SUBASTA
	  ,DECODE(MAX(BAD.BIE_ADJ_CESION_REMATE),1,'1',DECODE(MIN(UPPER(EAD.DD_EAD_DESCRIPCION)),'ENTIDAD','1','2'))  		ID_RESULTADO_SUBASTA_RCV
	  ,DECODE(MAX(BAD.BIE_ADJ_CESION_REMATE),1,'CESION',MIN(UPPER(EAD.DD_EAD_DESCRIPCION)))   							RESULTADO_SUBASTA_RCV       
	  ,MIN(EAD.DD_EAD_CODIGO)             																				ENTIDAD_ADJ_RCV			
	  ,DECODE(MAX(BAD.BIE_ADJ_CESION_REMATE),1,'S',' ') 																CESION_REMATE_RCV 
	FROM #ESQUEMA_MINIREC#.RCV_GEST_PROPUESTA 	A
		,#ESQUEMA#.SUB_SUBASTA 						SUB
		,#ESQUEMA#.DD_EAD_ENTIDAD_ADJUDICA 			EAD
		,#ESQUEMA#.BIE_ADJ_ADJUDICACION      		BAD
		,#ESQUEMA#.LOB_LOTE_BIEN             		LOB
		,#ESQUEMA#.LOS_LOTE_SUBASTA          		LOS
	WHERE A.ID_PROPUESTA_RCV = SUB.PRC_ID
		AND SUB.SUB_ID = LOS.SUB_ID
		AND LOS.LOS_ID = LOB.LOS_ID
		AND LOB.BIE_ID = BAD.BIE_ID
		AND BAD.DD_EAD_ID  = EAD.DD_EAD_ID
	GROUP BY A.ID_PROPUESTA_RCV
			 ,LOS.LOS_NUM_LOTE;
         
COMMIT;


	DBMS_OUTPUT.PUT_LINE('[INFO] Registros insertados en MINIREC.RCV_GEST_SUB_PRO.');

	DBMS_OUTPUT.PUT_LINE('[FIN]: Script ejecutado correctamente');
	
	INSERT INTO #ESQUEMA_MINIREC#.RCV_GEST_LOG VALUES (#ESQUEMA_MINIREC#.S_RCV_GEST_LOG.NEXTVAL, 'RCV_GEST_SUB_PRO', 'INSERT EN MINIREC.RCV_GEST_SUB_PRO', 'FIN', TO_CHAR(SYSTIMESTAMP, 'DD/MM/RR HH24:MI:SS'));


EXCEPTION
	
	WHEN OTHERS THEN
     
		DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion: '||TO_CHAR(SQLCODE));
		DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
		DBMS_OUTPUT.put_line(SQLERRM);

	ROLLBACK;
	RAISE;          

END GEST_SUB_PRO;
/

EXIT;
