--/*
--##########################################
--## AUTOR=OSCAR DORADO
--## FECHA_CREACION=20150723
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.1.12-bk
--## INCIDENCIA_LINK=FASE-1470
--## PRODUCTO=SI
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;


DECLARE

    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar    
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.  
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.

    V_TEXT1 VARCHAR2(2400 CHAR); -- Vble. auxiliar

    BEGIN


	DBMS_OUTPUT.PUT_LINE('[START]  tabla BIE_DATOS_REGISTRALES');
	
	
     -- ********** CNV_AUX_CCDD_PR_CONV_CIERR_DD - PK A ID_ACUERDO_CIERRE

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CNV_AUX_CCDD_PR_CONV_CIERR_DD'' AND CONSA.CONSTRAINT_TYPE = ''P''
	AND COLSA.COLUMN_NAME = ''ID_ACUERDO_CIERRE'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
   
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD  ADD 
			CONSTRAINT PK_CDD PRIMARY KEY (ID_ACUERDO_CIERRE)';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... PK_CDD Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... PK_CDD ya existe'); 
   
    END IF;
        
     -- ********** CNV_AUX_CCDD_PR_CONV_CIERR_DD - FK A BIE_ID

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CNV_AUX_CCDD_PR_CONV_CIERR_DD'' AND CONSA.CONSTRAINT_TYPE = ''R''
	AND COLSA.COLUMN_NAME = ''BIE_ID'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD  ADD (
			CONSTRAINT FK_CDD_BIE FOREIGN KEY (BIE_ID) 
				 REFERENCES ' || V_ESQUEMA || '.BIE_BIEN (BIE_ID))';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK_CDD_BIE Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK A BIE_BIEN ya existe'); 
   
    END IF;
    
        
      -- ********** CNV_AUX_CCDD_PR_CONV_CIERR_DD - FK A ASU_ID

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CNV_AUX_CCDD_PR_CONV_CIERR_DD'' AND CONSA.CONSTRAINT_TYPE = ''R''
	AND COLSA.COLUMN_NAME = ''ASU_ID'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD  ADD (
			CONSTRAINT FK_CDD_ASU FOREIGN KEY (ASU_ID) 
				 REFERENCES ' || V_ESQUEMA || '.ASU_ASUNTOS (ASU_ID))';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK_CDD_ASU Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK A ASU_ASUNTOS ya existe'); 
   
    END IF;
    
    
      -- ********** CNV_AUX_CCDD_PR_CONV_CIERR_DD - FK A PRC_ID

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CNV_AUX_CCDD_PR_CONV_CIERR_DD'' AND CONSA.CONSTRAINT_TYPE = ''R''
	AND COLSA.COLUMN_NAME = ''PRC_ID'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD  ADD (
			CONSTRAINT FK_CDD_PRC FOREIGN KEY (PRC_ID) 
				 REFERENCES ' || V_ESQUEMA || '.PRC_PROCEDIMIENTOS (PRC_ID))';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK_CDD_PRC Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK A PRC_PROCEDIMIENTOS ya existe'); 
   
    END IF;

    
       -- ********** CNV_AUX_CCDD_PR_CONV_CIERR_DD - FK A RVC_ID

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CNV_AUX_CCDD_PR_CONV_CIERR_DD'' AND CONSA.CONSTRAINT_TYPE = ''R''
	AND COLSA.COLUMN_NAME = ''DD_RVC_ID'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD  ADD (
			CONSTRAINT FK_CDD_RVC FOREIGN KEY (PRC_ID) 
				 REFERENCES ' || V_ESQUEMA || '.DD_RVC_RES_VALIDACION_CDD (DD_RVC_ID))';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK_CDD_RVC Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD ... FK A DD_RVC_RES_VALIDACION_CD ya existe'); 
   
    END IF;
    
         -- ********** CDD_CRN_RESULTADO_NUSE - FK A CDD

    V_SQL := 'SELECT COUNT(1) FROM (    SELECT consa.CONSTRAINT_NAME FROM ALL_CONSTRAINTS CONSA
	INNER JOIN ALL_CONS_COLUMNS COLSA ON CONSA.CONSTRAINT_NAME = COLSA.CONSTRAINT_NAME AND CONSA.OWNER = COLSA.OWNER
	WHERE COLSA.TABLE_NAME = ''CDD_CRN_RESULTADO_NUSE'' AND CONSA.CONSTRAINT_TYPE = ''R''
	AND COLSA.COLUMN_NAME = ''ID_ACUERDO_CIERRE'' AND CONSA.OWNER ='''|| V_ESQUEMA ||''')';   
    
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	-- Si no existe
    IF V_NUM_TABLAS != 1 THEN 
    
	    V_MSQL := 'ALTER TABLE ' || V_ESQUEMA || '.CDD_CRN_RESULTADO_NUSE ADD (
			CONSTRAINT FK_CRN_CDD FOREIGN KEY (ID_ACUERDO_CIERRE) 
				 REFERENCES ' || V_ESQUEMA || '.CNV_AUX_CCDD_PR_CONV_CIERR_DD (ID_ACUERDO_CIERRE))';
			
		EXECUTE IMMEDIATE V_MSQL;     
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CDD_CRN_RESULTADO_NUSE ... FK_CRN_CDD Creada');
	ELSE
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.CDD_CRN_RESULTADO_NUSE ... FK A CNV_AUX_CCDD_PR_CONV_CIERR_DD ya existe'); 
   
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Código de error obtenido:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
          


END;
/

EXIT