--/*
--##########################################
--## AUTOR=CARLOS PEREZ	
--## FECHA_CREACION=20150914
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.1
--## INCIDENCIA_LINK=PRODUCTO-255
--## PRODUCTO=SI
--## 
--## Finalidad: Creación tabla para historizar la tabla ARR_ARQ_RECUPERACION_PERSONA
--## INSTRUCCIONES:  Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;


DECLARE

 V_SCHEMA_MASTER VARCHAR(25) := '#ESQUEMA_MASTER#';
 V_SCHEMA VARCHAR(25) := '#ESQUEMA#'; 
 TABLA VARCHAR(30) :='H_ARR_ARQ_RECUPERACION_PERSONA'; 
 ITABLE_SPACE VARCHAR(25) :='#TABLESPACE_INDEX#';
 err_num NUMBER;
 err_msg VARCHAR2(2048); 
 V_MSQL1 VARCHAR2(8500 CHAR);
 V_MSQL2 VARCHAR2(8500 CHAR);
 V_MSQL3 VARCHAR2(8500 CHAR);
 V_EXISTE NUMBER (1):=null;


BEGIN 

--Validamos si la tabla existe antes de crearla
  SELECT COUNT(*) INTO V_EXISTE
  FROM ALL_TABLES
  WHERE TABLE_NAME = ''||TABLA||'';


 
  IF V_EXISTE = 1 THEN
     EXECUTE IMMEDIATE ('DROP TABLE '||V_SCHEMA||'.'||TABLA );
     DBMS_OUTPUT.PUT_LINE(''||TABLA||' BORRADA');     
  END IF;   
          


  V_MSQL1 := 'CREATE TABLE '||V_SCHEMA||'.'||TABLA||'   
   (	"ARR_ID" NUMBER(16,0), 
	"PER_ID" NUMBER(16,0), 
	"ARQ_ID" NUMBER(16,0), 
	"ARQ_NAME" VARCHAR2(100 CHAR), 
	"ARQ_PRIO" NUMBER(16,0), 
	"ARQ_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(1,0), 
	"USUARIOCREAR" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"FECHACREAR" TIMESTAMP (6) NOT NULL ENABLE, 
	"USUARIOMODIFICAR" VARCHAR2(10 CHAR), 
	"FECHAMODIFICAR" TIMESTAMP (6), 
	"USUARIOBORRAR" VARCHAR2(10 CHAR), 
	"FECHABORRAR" TIMESTAMP (6), 
	"BORRADO" NUMBER(1,0) NOT NULL ENABLE
   )';

--/* SEGMENT CREATION IMMEDIATE 
--  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE' || TABLE_SPACE|| '';
--  */
          

     EXECUTE IMMEDIATE V_MSQL1;
     DBMS_OUTPUT.PUT_LINE(''||TABLA||' CREADA');


   EXECUTE IMMEDIATE ('grant insert, select, update on '||V_SCHEMA||'.'||TABLA||' to '||V_SCHEMA_MASTER||''); 
     
     
EXCEPTION
WHEN OTHERS THEN  
  err_num := SQLCODE;
  err_msg := SQLERRM;

  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
  
  ROLLBACK;
  RAISE;
END;
/
EXIT;   



