--/*
--###########################################
--## AUTOR=David Gonzalez
--## FECHA_CREACION=20160614
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-581
--## PRODUCTO=NO
--## 
--## Finalidad: Re-asignar gestores de activo a activos asignados por defecto a 'lfabe'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--###########################################
----*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE

  V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
  V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
  V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
  V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
  V_NUM NUMBER(16); -- Vble. para validar la existencia de una tabla.   
  ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
  ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.

BEGIN	

	DBMS_OUTPUT.PUT_LINE('[INICIO] COMIENZA EL PROCESO PARA LA RE-ASIGNACIÓN DE GESTORES PARA ');
	DBMS_OUTPUT.PUT_LINE('         ACTIVOS ASIGNADOS POR DEFECTO A ''lfabe'''||CHR(10));
	
	EXECUTE IMMEDIATE '
	SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME = ''TMP_GEST_ACT'' AND OWNER = '''||V_ESQUEMA||'''
	'
	INTO V_NUM
	;
	
	IF V_NUM > 0 THEN
  
    EXECUTE IMMEDIATE '
		TRUNCATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
		'
		;
	
		EXECUTE IMMEDIATE '
		DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
		'
		;
		
	END IF;

	EXECUTE IMMEDIATE '
	CREATE GLOBAL TEMPORARY TABLE '||V_ESQUEMA||'.TMP_GEST_ACT ON COMMIT PRESERVE ROWS AS (
	
	SELECT
	GEE_ID,
	GESTOR_CORRECTO,
	DD_TGE_ID,
	'||V_ESQUEMA||'.S_GEH_GESTOR_ENTIDAD_HIST.NEXTVAL AS GEH_ID,
	ACT_ID
	FROM (
	
		SELECT DISTINCT
		GEE.GEE_ID,
		GEE.DD_TGE_ID,
		GES.USUARIO_GESTION_ACTIVOS AS GESTOR_CORRECTO,
		GAC.ACT_ID
		FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
		INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
			ON GAC.GEE_ID = GEE.GEE_ID
		INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
			ON ACT.ACT_ID = GAC.ACT_ID
		INNER JOIN '||V_ESQUEMA||'.BIE_BIEN BIE
			ON BIE.BIE_ID = ACT.BIE_ID
		INNER JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC
			ON LOC.BIE_ID = BIE.BIE_ID
		LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV
			ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
		LEFT JOIN '||V_ESQUEMA||'.ACT_GES_DISTRIBUCION GES
			ON GES.COD_PROVINCIA = PRV.DD_PRV_CODIGO
		LEFT JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
			ON USU.USU_ID = GEE.USU_ID
		LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE
			ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
		LEFT JOIN '||V_ESQUEMA_MASTER||'.DD_UPO_UNID_POBLACIONAL UPO
			ON UPO.DD_UPO_CODIGO = GES.COD_MUNICIPIO
		WHERE TGE.DD_TGE_CODIGO = ''GACT''
		AND USU.USU_USERNAME = ''lfabe''
		AND LOC.BIE_LOC_PROVINCIA IS NULL
		AND LOC.DD_PRV_ID IS NOT NULL
		AND GES.PROVINCIA IS NOT NULL
		AND GES.MUNICIPIO IS NULL
		AND GEE.BORRADO = 0
		AND ((GEE.USUARIOMODIFICAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG'')
    OR GEE.USUARIOMODIFICAR IS NULL)
    AND GEE.USUARIOCREAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG''))
	)
	)
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] SE VA A ACTUALIZAR EL GESTOR A '||V_NUM||' ACTIVOS.');
 
	DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZANDO USU_ID EN GEE_GESTOR_ENTIDAD...');
	
	EXECUTE IMMEDIATE '
	MERGE INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE USING
	(
	SELECT 
	TMPGEST.GEE_ID,
	TMPGEST.ACT_ID,
	USU.USU_ID
	FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMPGEST
	LEFT JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU
		ON USU.USU_USERNAME = TMPGEST.GESTOR_CORRECTO
	) TMP
	ON (GEE.GEE_ID = TMP.GEE_ID)
	WHEN MATCHED THEN UPDATE SET
	GEE.USU_ID = TMP.USU_ID,
	GEE.USUARIOMODIFICAR = ''HREOS-581'',
	GEE.FECHAMODIFICAR = SYSDATE
  WHERE ((GEE.USUARIOMODIFICAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG'')
  OR GEE.USUARIOMODIFICAR IS NULL)
  AND GEE.USUARIOCREAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG''))
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] GEE_GESTOR_ENTIDAD ACTUALIZADA...'||V_NUM||' REGISTROS.');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZANDO GEH_FECHA_HASTA EN GEH_GESTOR_ENTIDAD_HIST PARA DAR DE BAJA EL ANTERIOR GESTOR...');
	
	EXECUTE IMMEDIATE '
	MERGE INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH USING
	(
	WITH ACT AS (
    SELECT DISTINCT
    TMP.ACT_ID,
    GAH.GEH_ID,
    TMP.DD_TGE_ID,
    (SELECT USU_ID FROM '||V_ESQUEMA_MASTER||'.USU_USUARIOS WHERE USU_USERNAME = TMP.GESTOR_CORRECTO) AS USU_ID
    FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
    LEFT JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
      ON GAH.ACT_ID = TMP.ACT_ID
    LEFT JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC
      ON GAC.ACT_ID = TMP.ACT_ID
    LEFT JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
      ON GEE.GEE_ID = GAC.GEE_ID
    WHERE GAH.ACT_ID IS NOT NULL
    AND GEE.USUARIOMODIFICAR = ''HREOS-581''
  )
  SELECT GEH.GEH_ID
  FROM ACT
  INNER JOIN '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
    ON GEH.GEH_ID = ACT.GEH_ID
  WHERE GEH.USU_ID != ACT.USU_ID
  AND GEH.DD_TGE_ID = ACT.DD_TGE_ID
	) TMP
	ON (GEH.GEH_ID = TMP.GEH_ID)
	WHEN MATCHED THEN UPDATE SET
	GEH.GEH_FECHA_HASTA = SYSDATE,
	GEH.USUARIOMODIFICAR = ''HREOS-581'',
	GEH.FECHAMODIFICAR = SYSDATE
  WHERE ((GEH.USUARIOMODIFICAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG'')
  OR GEH.USUARIOMODIFICAR IS NULL)
  AND GEH.USUARIOCREAR IN (''ALT_PRINEX'',''ALT_SAREB'',''MIG''))
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] GEH_GESTOR_ENTIDAD_HIST ACTUALIZADA...'||V_NUM||' REGISTROS.');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO NUEVOS REGISTROS EN GEH_GESTOR_ENTIDAD_HIST PARA DAR DE ALTA EL NUEVO GESTOR...');
	
	EXECUTE IMMEDIATE '
	INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
	(GEH_ID,
	USU_ID,
	DD_TGE_ID,
	GEH_FECHA_DESDE,
	USUARIOCREAR,
	FECHACREAR,
	BORRADO
	)
	SELECT
	GEH_ID,
	(SELECT USU_ID FROM '||V_ESQUEMA_MASTER||'.USU_USUARIOS WHERE USU_USERNAME = TMP.GESTOR_CORRECTO) AS USU_ID,
	DD_TGE_ID,
	SYSDATE AS GEH_FECHA_DESDE,
	''HREOS-581'' AS USUARIOCREAR,
	SYSDATE AS FECHACREAR,
	0 AS BORRADO
	FROM '||V_ESQUEMA||'.TMP_GEST_ACT TMP
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTADOS '||V_NUM||' REGISTROS EN GEH_GESTOR_ENTIDAD_HIST.');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO NUEVOS REGISTROS EN GAH_GESTOR_ACTIVO_HISTORICO PARA RELACIONAR LOS REGISTROS DE');
	DBMS_OUTPUT.PUT_LINE('       GEH_GESTOR_ENTIDAD_HIST CON LOS ACTIVOS...');
	
	EXECUTE IMMEDIATE '
	INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH
	(GEH_ID,
	ACT_ID
	)
	SELECT 
	GEH_ID,
	ACT_ID
	FROM '||V_ESQUEMA||'.TMP_GEST_ACT
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTADOS '||V_NUM||' REGISTROS EN GAH_GESTOR_ACTIVO_HISTORICO.');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] GESTORES ACTUALIZADOS CORRECTAMENTE.'||CHR(10));
	
	DBMS_OUTPUT.PUT_LINE('[INFO] SE VAN A RE-ASIGNAR LOS GESTORES PARA LAS TAREAS AFECTADAS...');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZANDO USU_ID EN TAC_TAREAS_ACTIVO...');
	
	EXECUTE IMMEDIATE '
	MERGE INTO '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC USING
	(
	SELECT
	TAC.TAR_ID,
	TAC.ACT_ID,
	TAC.USU_ID,
	GEE.GEE_ID,
	GEE.DD_TGE_ID as GEE_DD_TGE_ID,
	TAP.DD_TGE_ID as TAP_DD_TGE_ID,
	GEE.USU_ID as USU_ID_NEW
	FROM '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC 
	INNER JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR
	  ON TAR.TAR_ID = TAC.TAR_ID
	INNER JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX
	  ON TEX.TAR_ID = TAR.TAR_ID
	INNER JOIN '||V_ESQUEMA||'.TAP_TAREA_PROCEDIMIENTO TAP
	  ON TAP.TAP_ID = TEX.TAP_ID
	INNER JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC 
	  ON GAC.ACT_ID = TAC.ACT_ID
	INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE 
	  ON GEE.GEE_ID = GAC.GEE_ID
	WHERE GEE.DD_TGE_ID = (select dd_tge_id from '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor where dd_tge_codigo = ''GACT'')
	AND TAP.DD_TGE_ID = (select dd_tge_id from '||V_ESQUEMA_MASTER||'.dd_tge_tipo_gestor where dd_tge_codigo = ''GACT'') 
	AND TAC.USU_ID != GEE.USU_ID
	AND TAR.TAR_FECHA_FIN IS NULL
	--AND TAC.BORRADO = 0
	--AND TAR.BORRADO = 0
	--AND TEX.BORRADO = 0
	--AND TAP.BORRADO = 0
	--AND GEE.BORRADO = 0
	--AND GEE.USUARIOMODIFICAR = ''HREOS-581''
	) TMP
	ON (TAC.TAR_ID = TMP.TAR_ID)
	WHEN MATCHED THEN UPDATE SET
	TAC.USU_ID = TMP.USU_ID_NEW,
	TAC.USUARIOMODIFICAR = ''HREOS-581'',
	TAC.FECHAMODIFICAR = SYSDATE
	'
	;
	
	V_NUM := SQL%ROWCOUNT;
	
	DBMS_OUTPUT.PUT_LINE('[INFO] ACTUALIZADOS '||V_NUM||' REGISTROS EN TAC_TAREAS_ACTIVOS.');
	
	DBMS_OUTPUT.PUT_LINE('[INFO] TAREAS ACTUALIZADAS.'||CHR(10));
	 
	EXECUTE IMMEDIATE '
	SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME = ''TMP_GEST_ACT'' AND OWNER = '''||V_ESQUEMA||'''
	'
	INTO V_NUM
	;

	IF V_NUM > 0 THEN
  
    EXECUTE IMMEDIATE '
		TRUNCATE TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
		'
		;
	
		EXECUTE IMMEDIATE '
		DROP TABLE '||V_ESQUEMA||'.TMP_GEST_ACT
		'
		;
		
	END IF;
	
	DBMS_OUTPUT.PUT_LINE('[FIN]  PROCESO FINALIZADO CORRECTAMENTE ');
 
EXCEPTION

   WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SQLERRM;

        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
        DBMS_OUTPUT.put_line(err_msg);

        ROLLBACK;
        RAISE;          

END;

/

EXIT
