--/*
--#########################################
--## AUTOR=DAP
--## FECHA_CREACION=20170620
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=0.1
--## INCIDENCIA_LINK=HREOS-2264
--## PRODUCTO=NO
--## 
--## Finalidad: Proceso de migración 'MIG_ATA_TASACIONES_ACTIVO' -> 'ACT_TAS_TASACION', 'BIE_VALORACIONES'
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

    V_ESQUEMA VARCHAR2(10 CHAR) := 'REM01'; --REM01
    V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := 'REMMASTER'; --REMMASTER
    V_USUARIO VARCHAR2(50 CHAR) := '#USUARIO_MIGRACION#';
    V_TABLA VARCHAR2(40 CHAR) := 'BIE_VALORACIONES';
    V_TABLA_2 VARCHAR2(40 CHAR) := 'ACT_TAS_TASACION';
    V_TABLA_MIG VARCHAR2(40 CHAR) := 'MIG_ATA_TASACIONES_ACTIVO';
    V_SENTENCIA VARCHAR2(2000 CHAR);

BEGIN
    DBMS_OUTPUT.PUT_LINE('[INFO] - '||to_char(sysdate,'HH24:MI:SS')||' comienza el proceso.');
  --REGISTRAMOS TAS_ID Y BIE_VAL_ID
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_MIG||' se actualizará.');
    EXECUTE IMMEDIATE ('
        UPDATE '||V_ESQUEMA||'.'||V_TABLA_MIG||'
        SET
        BIE_VAL_ID = S_BIE_VALORACIONES.NEXTVAL,
        TAS_ID = S_ACT_TAS_TASACION.NEXTVAL
    ');
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_MIG||' actualizada. '||SQL%ROWCOUNT||' Filas.');
  --DAMOS REGISTROS EN ALTA BIE_VALORACIONES PARA LOS ACTIVOS QUE TRATAMOS
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' se cargará.');
  
  EXECUTE IMMEDIATE ('
  INSERT INTO '||V_ESQUEMA||'.'||V_TABLA||' (
  BIE_VAL_ID,
  BIE_ID,
  BIE_IMPORTE_VALOR_TASACION,
  BIE_FECHA_VALOR_TASACION,
  BIE_F_SOL_TASACION,
  VERSION,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO
  )
  WITH ACTIVOS AS (
	SELECT 
	ACT_ID, BIE_VAL_ID, TAS_ID, BIE_ID, MIG.ACT_NUMERO_ACTIVO, MIG.TAS_IMPORTE_VALOR_TASACION, MIG.TAS_FECHA_FIN_TASACION, MIG.TAS_F_SOL_TASACION
	FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
	INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
	ON ACT.ACT_NUM_ACTIVO = MIG.ACT_NUMERO_ACTIVO
	WHERE MIG.VALIDACION = 0
  )
  SELECT
  ACT.BIE_VAL_ID													BIE_VAL_ID,
  ACT.BIE_ID                                                	  	BIE_ID,
  ACT.TAS_IMPORTE_VALOR_TASACION									BIE_IMPORTE_VALOR_TASACION,
  ACT.TAS_FECHA_FIN_TASACION										BIE_FECHA_VALOR_TASACION,
  ACT.TAS_F_SOL_TASACION											BIE_F_SOL_TASACION,
  ''0''                                                             VERSION,
  '''||V_USUARIO||'''                                                           USUARIOCREAR,
  SYSDATE                                                           FECHACREAR,
  0                                                                 BORRADO
  FROM ACTIVOS ACT
  LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA||' BIE ON BIE.BIE_ID = ACT.BIE_ID
  WHERE BIE.BIE_ID IS NULL
  ')
  ;
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' cargada. '||SQL%ROWCOUNT||' Filas.');

    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' se cargará.');
  
	EXECUTE IMMEDIATE ('
	INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_2||' (
	TAS_ID,
	ACT_ID,
	BIE_VAL_ID,
	DD_TTS_ID,
	TAS_FECHA_INI_TASACION,
	TAS_FECHA_RECEPCION_TASACION,
	TAS_CODIGO_FIRMA,
	TAS_NOMBRE_TASADOR,
	TAS_IMPORTE_TAS_FIN,
	TAS_COSTE_REPO_NETO_ACTUAL,
	TAS_COSTE_REPO_NETO_FINALIZADO,
	TAS_COEF_MERCADO_ESTADO,
	TAS_COEF_POND_VALOR_ANYADIDO,
	TAS_VALOR_REPER_SUELO_CONST,
	TAS_COSTE_CONST_CONST,
	TAS_INDICE_DEPRE_FISICA,
	TAS_INDICE_DEPRE_FUNCIONAL,
	TAS_INDICE_TOTAL_DEPRE,
	TAS_COSTE_CONST_DEPRE,
	TAS_COSTE_UNI_REPO_NETO,
	TAS_COSTE_REPOSICION,
	TAS_PORCENTAJE_OBRA,
	TAS_IMPORTE_VALOR_TER,
	TAS_ID_TEXTO_ASOCIADO,
	TAS_IMPORTE_VAL_LEGAL_FINCA,
	TAS_IMPORTE_VAL_SOLAR,
	TAS_OBSERVACIONES,
	VERSION,
	USUARIOCREAR,
	FECHACREAR,
	BORRADO,
	TAS_ID_EXTERNO
	)
	WITH MIG_TASACIONES AS (
		SELECT DISTINCT 
		ACT.ACT_ID,
		MIG.ACT_NUMERO_ACTIVO,
		MIG.BIE_VAL_ID,
		MIG.TAS_ID,
		MIG.TAS_CODIGO_TASA_UVEM,
		MIG.TAS_TIPO_TASACION,
		MIG.TAS_FECHA_INI_TASACION,				
		MIG.TAS_FECHA_RECEPCION_TASACION,	
		MIG.TAS_CODIGO_FIRMA,				
		MIG.TAS_NOMBRE_TASADOR,				
		MIG.TAS_IMPORTE_TAS_FIN,				
		MIG.TAS_COSTE_REPO_NETO_ACTUAL,		
		MIG.TAS_COSTE_REPO_NETO_FINALIZADO,	
		MIG.TAS_COEF_MERCADO_ESTADO,			
		MIG.TAS_COEF_POND_VALOR_ANYADIDO,	
		MIG.TAS_VALOR_REPER_SUELO_CONST,     
		MIG.TAS_COSTE_CONST_CONST,           
		MIG.TAS_INDICE_DEPRE_FISICA ,        
		MIG.TAS_INDICE_DEPRE_FUNCIONAL,      
		MIG.TAS_INDICE_TOTAL_DEPRE,          
		MIG.TAS_COSTE_CONST_DEPRE,           
		MIG.TAS_COSTE_UNI_REPO_NETO,         
		MIG.TAS_COSTE_REPOSICION,            
		MIG.TAS_PORCENTAJE_OBRA,             
		MIG.TAS_IMPORTE_VALOR_TER,           
		MIG.TAS_ID_TEXTO_ASOCIADO,           
		MIG.TAS_IMPORTE_VAL_LEGAL_FINCA ,    
		MIG.TAS_IMPORTE_VAL_SOLAR,           
		MIG.TAS_OBSERVACIONES
		FROM '||V_ESQUEMA||'.'||V_TABLA_MIG||' MIG
		INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT
		ON ACT.ACT_NUM_ACTIVO = MIG.ACT_NUMERO_ACTIVO
		INNER JOIN '||V_ESQUEMA||'.BIE_VALORACIONES BIE
		ON BIE.BIE_ID = ACT.BIE_ID
		WHERE MIG.VALIDACION = 0
	)
	SELECT
	MIG.TAS_ID															TAS_ID,
	MIG.ACT_ID     														ACT_ID,
	MIG.BIE_VAL_ID                                      				BIE_VAL_ID,
	(SELECT DD_TTS_ID
	FROM '||V_ESQUEMA||'.DD_TTS_TIPO_TASACION
	WHERE DD_TTS_CODIGO = MIG.TAS_TIPO_TASACION)						DD_TTS_ID,
	MIG.TAS_FECHA_INI_TASACION											TAS_FECHA_INI_TASACION,
	MIG.TAS_FECHA_RECEPCION_TASACION									TAS_FECHA_RECEPCION_TASACION,
	MIG.TAS_CODIGO_FIRMA												TAS_CODIGO_FIRMA,
	MIG.TAS_NOMBRE_TASADOR												TAS_NOMBRE_TASADOR,
	MIG.TAS_IMPORTE_TAS_FIN												TAS_IMPORTE_TAS_FIN,
	MIG.TAS_COSTE_REPO_NETO_ACTUAL										TAS_COSTE_REPO_NETO_ACTUAL,
	MIG.TAS_COSTE_REPO_NETO_FINALIZADO									TAS_COSTE_REPO_NETO_FINALIZADO,
	MIG.TAS_COEF_MERCADO_ESTADO											TAS_COEF_MERCADO_ESTADO,
	MIG.TAS_COEF_POND_VALOR_ANYADIDO									TAS_COEF_POND_VALOR_ANYADIDO,
	MIG.TAS_VALOR_REPER_SUELO_CONST                         			TAS_VALOR_REPER_SUELO_CONST,
	MIG.TAS_COSTE_CONST_CONST                               			TAS_COSTE_CONST_CONST,
	MIG.TAS_INDICE_DEPRE_FISICA                             			TAS_INDICE_DEPRE_FISICA,
	MIG.TAS_INDICE_DEPRE_FUNCIONAL                          			TAS_INDICE_DEPRE_FUNCIONAL,
	MIG.TAS_INDICE_TOTAL_DEPRE                              			TAS_INDICE_TOTAL_DEPRE,
	MIG.TAS_COSTE_CONST_DEPRE                               			TAS_COSTE_CONST_DEPRE,
	MIG.TAS_COSTE_UNI_REPO_NETO                             			TAS_COSTE_UNI_REPO_NETO,
	MIG.TAS_COSTE_REPOSICION                                			TAS_COSTE_REPOSICION,
	MIG.TAS_PORCENTAJE_OBRA                                 			TAS_PORCENTAJE_OBRA,
	MIG.TAS_IMPORTE_VALOR_TER                               			TAS_IMPORTE_VALOR_TER,
	MIG.TAS_ID_TEXTO_ASOCIADO                               			TAS_ID_TEXTO_ASOCIADO,
	MIG.TAS_IMPORTE_VAL_LEGAL_FINCA                         			TAS_IMPORTE_VAL_LEGAL_FINCA,
	MIG.TAS_IMPORTE_VAL_SOLAR                               			TAS_IMPORTE_VAL_SOLAR,
	MIG.TAS_OBSERVACIONES                                   			TAS_OBSERVACIONES,
	''0''                                                 				VERSION,
	'''||V_USUARIO||'''                                               	USUARIOCREAR,
	SYSDATE                                               				FECHACREAR,
	0                                                     				BORRADO,
	MIG.TAS_CODIGO_TASA_UVEM											TAS_ID_EXTERNO	
	FROM MIG_TASACIONES MIG
    JOIN '||V_ESQUEMA||'.'||V_TABLA||' BIE_VAL ON BIE_VAL.BIE_VAL_ID = MIG.BIE_VAL_ID
    LEFT JOIN '||V_ESQUEMA||'.'||V_TABLA_2||' CRG ON CRG.BIE_VAL_ID = BIE_VAL.BIE_VAL_ID
    WHERE CRG.BIE_VAL_ID IS NULL
	')
	;
	
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' cargada. '||SQL%ROWCOUNT||' Filas.');
  
  -- ACTUALIZAMOS EL CAMPO TAS_ID_EXTERNO CON LOS DATOS DE FASE 1
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' se actualizará.');
  
	EXECUTE IMMEDIATE ('
	MERGE INTO '||V_ESQUEMA||'.'||V_TABLA_2||' TAS
	USING
	(
		SELECT ATA.BIE_VAL_ID, ATA.TAS_CODIGO_TASA_UVEM 
        FROM '||V_ESQUEMA||'.MIG_ATA_TASACIONES_ACTIVO ATA
		WHERE ATA.VALIDACION = 0
	) AUX
	ON (AUX.BIE_VAL_ID = TAS.BIE_VAL_ID)
	WHEN MATCHED THEN UPDATE SET
	  TAS.TAS_ID_EXTERNO = AUX.TAS_CODIGO_TASA_UVEM,
	  TAS.USUARIOMODIFICAR = '''||V_USUARIO||''',
	  TAS.FECHAMODIFICAR = SYSDATE
	')
	;
  
	COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' actualizada. '||SQL%ROWCOUNT||' Filas.');
  
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' se analizará.');
      V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA||''',''10''); END;';
      EXECUTE IMMEDIATE V_SENTENCIA;
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA||' analizada.');
    
    DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' se analizará.');
      V_SENTENCIA := 'BEGIN '||V_ESQUEMA||'.OPERACION_DDL.DDL_TABLE(''ANALYZE'','''||V_TABLA_2||''',''10''); END;';
      EXECUTE IMMEDIATE V_SENTENCIA;
	DBMS_OUTPUT.PUT_LINE('  [INFO] - '||to_char(sysdate,'HH24:MI:SS')||'  '||V_ESQUEMA||'.'||V_TABLA_2||' analizada.');

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

EXIT;
