DELETE
FROM BANK01.dd_ptp_plazos_tareas_plazas
WHERE TAP_ID IN
  (SELECT tap_id
  FROM BANK01.tap_tarea_procedimiento
  WHERE DD_TPO_ID=
    (SELECT DD_TPO_ID
    FROM BANK01.DD_TPO_TIPO_PROCEDIMIENTO
    WHERE dd_tpo_codigo='P411'
    )
  );
DELETE
FROM BANK01.TFI_TAREAS_FORM_ITEMS
WHERE TAP_ID IN
  (SELECT tap_id
  FROM BANK01.tap_tarea_procedimiento
  WHERE DD_TPO_ID=
    (SELECT DD_TPO_ID
    FROM BANK01.DD_TPO_TIPO_PROCEDIMIENTO
    WHERE dd_tpo_codigo='P411'
    )
  );
DELETE
FROM BANK01.TAP_TAREA_PROCEDIMIENTO
WHERE DD_TPO_ID=
  (SELECT DD_TPO_ID
  FROM BANK01.DD_TPO_TIPO_PROCEDIMIENTO
  WHERE dd_tpo_codigo='P411'
  );
DELETE FROM BANK01.DD_TPO_TIPO_PROCEDIMIENTO WHERE dd_tpo_codigo='P411';
