whenever sqlerror exit sql.sqlcode;

DECLARE
  V_COUNT NUMBER(16);
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES WHERE OWNER = 'BANK01' AND TABLE_NAME = 'REC_FIC_RECHAZOS_CONTRATOS';
  IF (V_COUNT = 0) THEN 
    EXECUTE IMMEDIATE 'CREATE TABLE "BANK01"."REC_FIC_RECHAZOS_CONTRATOS" 
    (	"FECHA_RECHAZO" TIMESTAMP (6) NOT NULL ENABLE, 
    "DD_MRE_ID" NUMBER(16,0) NOT NULL ENABLE, 
    "RCF_AGE_ID" NUMBER(16,0) NOT NULL ENABLE, 
    "RCF_SCA_ID" NUMBER(16,0) NOT NULL ENABLE, 
    "ID_ENVIO" NUMBER(24,0) NOT NULL ENABLE, 
    "ID_EXPEDIENTE" NUMBER(16,0) NOT NULL ENABLE, 
    "ID_CARTERA" NUMBER(16,0) NOT NULL ENABLE, 
    "CARTERA_EXPEDIENTE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    "CODIGO_ENTIDAD" NUMBER(4,0) NOT NULL ENABLE, 
    "COD_ENTIDAD_OFI_ADMIN" NUMBER(5,0) NOT NULL ENABLE, 
    "COD_OFI_ADMIN" NUMBER(5,0) NOT NULL ENABLE, 
    "DIR_OFI_ADMIN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    "CODIGO_PROPIETARIO" NUMBER(5,0) NOT NULL ENABLE, 
    "TIPO_PRODUCTO" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
    "NUMERO_CONTRATO" NUMBER(17,0) NOT NULL ENABLE, 
    "NUMERO_ESPEC" NUMBER(15,0) NOT NULL ENABLE, 
    "IBAN_CONTRATO" VARCHAR2(24 CHAR), 
    "CNT_DOMICILIACION" VARCHAR2(20 CHAR), 
    "IBAN_CNT_DOMICILIACION" VARCHAR2(24 CHAR), 
    "CD_SITUACION_CONTABLE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
    "SITUACION_CONTABLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "POS_VIVA_NO_VENCIDA" NUMBER(16,2) NOT NULL ENABLE, 
    "POS_VIVA_VENCIDA" NUMBER(16,2) NOT NULL ENABLE, 
    "INT_ORDIN_DEVEN" NUMBER(16,2) NOT NULL ENABLE, 
    "INT_MORAT_DEVEN" NUMBER(16,2) NOT NULL ENABLE, 
    "COMISIONES" NUMBER(16,2) NOT NULL ENABLE, 
    "GASTOS" NUMBER(16,2) NOT NULL ENABLE, 
    "IMPUESTOS" NUMBER(16,2), 
    "ENTREGAS" NUMBER(16,2) NOT NULL ENABLE, 
    "INT_ENTREGAS" NUMBER(16,2) NOT NULL ENABLE, 
    "DEUDA_IRREGULAR" NUMBER(16,2) NOT NULL ENABLE, 
    "LIMITE_INICIAL" NUMBER(16,2) NOT NULL ENABLE, 
    "LIMITE_ACTUAL" NUMBER(16,2) NOT NULL ENABLE, 
    "FECHA_CREACION" TIMESTAMP (6) NOT NULL ENABLE, 
    "FECHA_INI_IRREGU" TIMESTAMP (6), 
    "FECHA_POS_VENCIDA" TIMESTAMP (6) NOT NULL ENABLE, 
    "CD_PRODUCTO_COMERCIAL" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
    "CATALOGO1" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
    "CATALOGO2" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
    "CD_GARANTIA1" NUMBER(4,0), 
    "GARANTIA1" VARCHAR2(255 CHAR), 
    "CD_GARANTIA2" NUMBER(4,0), 
    "GARANTIA2" VARCHAR2(255 CHAR), 
    "CONTACTO_ENTIDAD_NOMBRE" VARCHAR2(255 CHAR), 
    "CONTACTO_ENTIDAD_TEL" VARCHAR2(25 CHAR), 
    "CONTACTO_ENTIDAD_EMAIL" VARCHAR2(255 CHAR), 
    "SITUACION_GESTION" VARCHAR2(3 CHAR), 
    "CUOTA_IMPORTE" NUMBER(16,2), 
    "CUOTA_PERIODICIDAD" NUMBER(3,0), 
    "CD_FINALIDAD" VARCHAR2(5 CHAR), 
    "DESC_OFICIAL_FINALIDAD" VARCHAR2(255 CHAR), 
    "FECHA_VENCIMIENTO" TIMESTAMP (6) NOT NULL ENABLE, 
    "CD_SISTEMA_AMORTIZACION" VARCHAR2(8 CHAR), 
    "SISTEMA_AMORTIZACION" VARCHAR2(255 CHAR), 
    "TIPO_INTERES" NUMBER(7,5) NOT NULL ENABLE, 
    "FECHA_PLAZO_MINIMO_GESTION" TIMESTAMP (6) NOT NULL ENABLE, 
    "FECHA_MAX_COBRO_PARCIAL" TIMESTAMP (6), 
    "FECHA_MAX_REGULARIZACION" TIMESTAMP (6) NOT NULL ENABLE, 
    "FECHA_EXTRA1" TIMESTAMP (6), 
    "FECHA_EXTRA2" TIMESTAMP (6), 
    "FECHA_EXTRA3" TIMESTAMP (6), 
    "FECHA_EXTRA4" TIMESTAMP (6), 
    "FECHA_EXTRA5" TIMESTAMP (6), 
    "FECHA_EXTRA6" TIMESTAMP (6), 
    "FECHA_EXTRA7" TIMESTAMP (6), 
    "FECHA_EXTRA8" TIMESTAMP (6), 
    "FECHA_EXTRA9" TIMESTAMP (6), 
    "FECHA_EXTRA10" TIMESTAMP (6), 
    "NUMERO_EXTRA1" NUMBER(16,2), 
    "NUMERO_EXTRA2" NUMBER(16,2), 
    "NUMERO_EXTRA3" NUMBER(16,2), 
    "NUMERO_EXTRA4" NUMBER(16,2), 
    "NUMERO_EXTRA5" NUMBER(16,2), 
    "NUMERO_EXTRA6" NUMBER(16,2), 
    "NUMERO_EXTRA7" NUMBER(16,2), 
    "NUMERO_EXTRA8" NUMBER(16,2), 
    "NUMERO_EXTRA9" NUMBER(16,2), 
    "NUMERO_EXTRA10" NUMBER(16,2), 
    "LCHAR_EXTRA1" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA2" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA3" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA4" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA5" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA6" VARCHAR2(250 CHAR), 
    "LCHAR_EXTRA7" VARCHAR2(250 CHAR), 
  	"LCHAR_EXTRA8" VARCHAR2(250 CHAR), 
  	"LCHAR_EXTRA9" VARCHAR2(250 CHAR), 
  	"LCHAR_EXTRA10" VARCHAR2(250 CHAR)
   )';
  END IF;
  
  SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES WHERE OWNER = 'BANK01' AND TABLE_NAME = 'REC_FIC_RECHAZOS_PERSONAS';
  IF (V_COUNT = 0) THEN 
  EXECUTE IMMEDIATE 'CREATE TABLE "BANK01"."REC_FIC_RECHAZOS_PERSONAS" 
   (	"FECHA_RECHAZO" TIMESTAMP (6) NOT NULL ENABLE, 
  "DD_MRE_ID" NUMBER(16,0) NOT NULL ENABLE,  
	"RCF_AGE_ID" NUMBER(16,0) NOT NULL ENABLE, 
	"CODIGO_PROPIETARIO" NUMBER(5,0) NOT NULL ENABLE, 
	"CODIGO_PERSONA" NUMBER(16,0) NOT NULL ENABLE, 
	"TIPO_PERSONA" NUMBER(1,0) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DS_TIPO_DOCUMENTO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"NIF_CIF_PASAP_NIE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"APELLIDO1" VARCHAR2(100 CHAR), 
	"APELLIDO2" VARCHAR2(100 CHAR), 
	"CD_SEGMENTO_CLIENTE_1" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"SEGMENTO_CLIENTE_1" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FECHA_CONSTITUCION" TIMESTAMP (6), 
	"FECHA_NACIMIENTO" TIMESTAMP (6), 
	"CD_NACIONALIDAD" VARCHAR2(3 CHAR), 
	"NACIONALIDAD" VARCHAR2(255 CHAR), 
	"SEXO" VARCHAR2(255 CHAR), 
	"CORREO_ELECTRONICO" VARCHAR2(255 CHAR), 
	"SALDO_PASIVO" NUMBER(16,2) NOT NULL ENABLE, 
	"RIESGO_DIRECTO_CLIENTE" NUMBER(16,2) NOT NULL ENABLE, 
	"RIESGO_INDIRECTO_CLIENTE" NUMBER(16,2) NOT NULL ENABLE, 
	"RIESGO_DIRECTO_IRREGULAR_CLI" NUMBER(16,2) NOT NULL ENABLE, 
	"RIESGO_INDIRECTO_IRREGULAR_CLI" NUMBER(16,2) NOT NULL ENABLE, 
	"RIESG_DIRECT_IRREG_GRUPO" NUMBER(16,2), 
	"RIESG_INDIRECT_IRREG_GRUPO" NUMBER(16,2), 
	"ULTIMA_ACTUACION" VARCHAR2(1024 CHAR), 
	"GESTION_COMPARTIDA" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"FECHA_EXTRA1" TIMESTAMP (6), 
	"FECHA_EXTRA2" TIMESTAMP (6), 
	"FECHA_EXTRA3" TIMESTAMP (6), 
	"FECHA_EXTRA4" TIMESTAMP (6), 
	"FECHA_EXTRA5" TIMESTAMP (6), 
	"NUMERO_EXTRA1" NUMBER(16,2), 
	"NUMERO_EXTRA2" NUMBER(16,2), 
	"NUMERO_EXTRA3" NUMBER(16,2), 
	"NUMERO_EXTRA4" NUMBER(16,2), 
	"NUMERO_EXTRA5" NUMBER(16,2), 
	"LCHAR_EXTRA1" VARCHAR2(250 CHAR), 
	"LCHAR_EXTRA2" VARCHAR2(250 CHAR), 
	"LCHAR_EXTRA3" VARCHAR2(250 CHAR), 
	"LCHAR_EXTRA4" VARCHAR2(250 CHAR), 
	"LCHAR_EXTRA5" VARCHAR2(250 CHAR)
   )';
  END IF;
  
  SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES WHERE OWNER = 'BANK01' AND TABLE_NAME = 'DD_MRE_MOB_RECHAZO_REC_FIC';
  IF (V_COUNT = 0) THEN 
    EXECUTE IMMEDIATE 'CREATE TABLE "BANK01"."DD_MRE_MOB_RECHAZO_REC_FIC" 
   (	"DD_MRE_ID" NUMBER(16,0) NOT NULL ENABLE, 
	"DD_MRE_CODIGO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DD_MRE_DESCRIPCION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DD_MRE_DESCRIPCION_LARGA" VARCHAR2(250 BYTE), 
	"VERSION" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"USUARIOCREAR" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FECHACREAR" TIMESTAMP (6) NOT NULL ENABLE, 
	"USUARIOMODIFICAR" VARCHAR2(10 BYTE), 
	"FECHAMODIFICAR" TIMESTAMP (6), 
	"USUARIOBORRAR" VARCHAR2(10 BYTE), 
	"FECHABORRAR" TIMESTAMP (6), 
	"BORRADO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_DD_MRE_MOB_RECHAZO_REC_FIC" PRIMARY KEY ("DD_MRE_ID")
  )';
  END IF;

  SELECT COUNT(1) INTO V_COUNT FROM BANK01.DD_MRE_MOB_RECHAZO_REC_FIC WHERE DD_MRE_CODIGO = 'REL';
  IF (V_COUNT <= 0) THEN
    Insert into BANK01.DD_MRE_MOB_RECHAZO_REC_FIC (DD_MRE_ID,DD_MRE_CODIGO,DD_MRE_DESCRIPCION,DD_MRE_DESCRIPCION_LARGA,VERSION,USUARIOCREAR,FECHACREAR,USUARIOMODIFICAR,FECHAMODIFICAR,USUARIOBORRAR,FECHABORRAR,BORRADO) 
    values (1
      ,'REL'
      ,'Faltan relaciones'
      ,'Faltan relaciones'
      ,'0','DD ',SYSDATE,null,null,null,null,'0');
  END IF;
  
  COMMIT;
  
END;
/
EXIT