-- diccionario de tipos de operación
--DROP SEQUENCE S_DD_ECR_ESPERAR_CONTINUAR;
CREATE SEQUENCE S_DD_ECR_ESPERAR_CONTINUAR;

--DROP TABLE DD_ECR_ESPERAR_CONTINUAR;
CREATE TABLE DD_ECR_ESPERAR_CONTINUAR  (
   DD_ECR_ID		 			NUMBER(16)			NOT NULL,
   DD_ECR_CODIGO           		VARCHAR2(20 BYTE)   NOT NULL,
   DD_ECR_DESCRIPCION       	VARCHAR2(50 BYTE),
   DD_ECR_DESCRIPCION_LARGA     VARCHAR2(250 BYTE),
   VERSION                  	INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             	VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               	TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         	VARCHAR2(10 BYTE),
   FECHAMODIFICAR           	TIMESTAMP(6),
   USUARIOBORRAR            	VARCHAR2(10 BYTE),
   FECHABORRAR              	TIMESTAMP(6),
   BORRADO                 		 NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_DD_ECR_ESPERAR_CONTINUAR PRIMARY KEY (DD_ECR_ID)
  -- CONSTRAINT UK_DD_ECR_ESPERAR_CONTINUAR UNIQUE KEY (DD_OPM_CODIGO),
);

INSERT INTO DD_ECR_ESPERAR_CONTINUAR (DD_ECR_ID,DD_ECR_CODIGO,DD_ECR_DESCRIPCION,DD_ECR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_ECR_ESPERAR_CONTINUAR.nextVal,'01','Esperar','Esperar','DD',SYSDATE);
	
INSERT INTO DD_ECR_ESPERAR_CONTINUAR (DD_ECR_ID,DD_ECR_CODIGO,DD_ECR_DESCRIPCION,DD_ECR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_ECR_ESPERAR_CONTINUAR.nextVal,'02','Continuar','Continuar','DD',SYSDATE);	


-- DICCIONARIO DE DATOS DE REQUERIMIENTOS PREVIOS
-- DROP SEQUENCE S_DD_RPR_REQUERIMIENTO_PREVIO
CREATE SEQUENCE S_DD_RPR_REQUERIMIENTO_PREVIO;

--DROP TABLE DD_ECR_ESPERAR_CONTINUAR;
CREATE TABLE DD_RPR_REQUERIMIENTO_PREVIO  (
   DD_RPR_ID		 			NUMBER(16)			NOT NULL,
   DD_RPR_CODIGO           		VARCHAR2(20 BYTE)   NOT NULL,
   DD_RPR_DESCRIPCION       	VARCHAR2(50 BYTE),
   DD_RPR_DESCRIPCION_LARGA     VARCHAR2(250 BYTE),
   VERSION                  	INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             	VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               	TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         	VARCHAR2(10 BYTE),
   FECHAMODIFICAR           	TIMESTAMP(6),
   USUARIOBORRAR            	VARCHAR2(10 BYTE),
   FECHABORRAR              	TIMESTAMP(6),
   BORRADO                 		 NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_DD_RPR_REQUERIMIENTO_PREVIO PRIMARY KEY (DD_RPR_ID)
  -- CONSTRAINT UK_DD_ECR_ESPERAR_CONTINUAR UNIQUE KEY (DD_OPM_CODIGO),
);

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'ACNT','Aportación Contrato','Aportación Contrato','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'APCP','Aportación Poder con procurador','Aportación Poder con procurador','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'APSP','Aportación Poder sin procurador','Aportación Poder sin procurador','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'FDM','Firma Demanda','Firma Demanda','DD',SYSDATE);
	
INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'RDM','Ratificación Demanda','Ratificación Demanda','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'ACDM','Aportación copia de demanda','Aportación copia de demanda','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'SCDM','Subsanación cuantía de demanda','Subsanación cuantía de demanda','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'SDD','Subsanación datos demandado/s','Subsanación datos demandado/s','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'CSC','Cesión de Crédito','Cesión de Crédito','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'ATJ','Aportación de Tasas Judiciales','Aportación de Tasas Judiciales','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'ACD','Aportación de Certificado de deuda','Aportación de Certificado de deuda','DD',SYSDATE);	

INSERT INTO DD_RPR_REQUERIMIENTO_PREVIO (DD_RPR_ID,DD_RPR_CODIGO,DD_RPR_DESCRIPCION,DD_RPR_DESCRIPCION_LARGA,USUARIOCREAR,FECHACREAR) 
	VALUES (S_DD_RPR_REQUERIMIENTO_PREVIO.nextVal,'ADD',' Aclaración de deuda con desglose',' Aclaración de deuda con desglose','DD',SYSDATE);	
	