  --/*
--##########################################
--## AUTOR=Juan Bautista Alfonso
--## FECHA_CREACION=20210630
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-9781
--## PRODUCTO=NO
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--## HREOS-4107 Se añade el campo ACT_COD_PROMOCION_PRINEX para el cod.Promo al crear trabajos con activos liberbank.
--##	    0.3 REMVIP-9781 Juan Bautista Alfonso Añadido campo ACT_EN_TRAMITE para bankia
--##
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    seq_count number(3); -- Vble. para validar la existencia de las Secuencias.
    table_count number(3); -- Vble. para validar la existencia de las Tablas.
    v_column_count number(3); -- Vble. para validar la existencia de las Columnas.    
    v_constraint_count number(3); -- Vble. para validar la existencia de las Constraints.
    err_num NUMBER; -- N?mero de errores
    err_msg VARCHAR2(2048); -- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas
    V_MSQL VARCHAR2(4000 CHAR); 

    CUENTA NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_ACTIVOS_CREAR_TBJ' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ...');
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_ACTIVOS_CREAR_TBJ';  
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ... borrada OK');
  END IF;

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_ACTIVOS_CREAR_TBJ' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ...');
    EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_ACTIVOS_CREAR_TBJ';  
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ...');
  EXECUTE IMMEDIATE 'CREATE VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_ACTIVOS_CREAR_TBJ 
		
	AS	
    SELECT
      act.ACT_ID,
      ACT.ACT_NUM_ACTIVO,
      ACT.ACT_NUM_ACTIVO_REM,
      CRA.DD_CRA_DESCRIPCION AS CARTERA,
      TPA.DD_TPA_DESCRIPCION AS TIPO_ACTIVO,
      STA.DD_SAC_DESCRIPCION AS SUBTIPO_ACTIVO,
      SCM.DD_SCM_DESCRIPCION AS SITUACION_COMERCIAL,
      BDR.BIE_DREG_NUM_FINCA AS NUM_FINCA_REGISTRAL,
      PAC.PAC_CHECK_GESTIONAR AS PER_GESTION,
      PAC2.PRO_ID,
	  (SELECT CASE WHEN (COUNT(1) > 0) THEN 1 ELSE 0 END
		FROM ' || V_ESQUEMA || '.PRP_PROPUESTAS_PRECIOS prp
		INNER JOIN ' || V_ESQUEMA || '.ACT_PRP ACP ON prp.PRP_ID = ACP.PRP_ID
		INNER JOIN ' || V_ESQUEMA || '.DD_EPP_ESTADO_PROP_PRECIO epp ON prp.DD_EPP_ID = epp.DD_EPP_ID
		WHERE epp.DD_EPP_CODIGO NOT IN (''03'',''04'',''05'')
			AND acp.ACT_ID = act.ACT_ID ) AS IN_PRP_TRAMITACION,
	  ACT.ACT_COD_PROMOCION_PRINEX,
	  CRA.DD_CRA_CODIGO AS CODIGO_CARTERA,
	ACT.ACT_EN_TRAMITE
    
    FROM ' ||V_ESQUEMA|| '.ACT_ACTIVO ACT
      LEFT JOIN ' ||V_ESQUEMA|| '.DD_SAC_SUBTIPO_ACTIVO STA ON STA.DD_SAC_ID = ACT.DD_SAC_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.DD_TPA_TIPO_ACTIVO TPA ON TPA.DD_TPA_ID = STA.DD_TPA_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.DD_SCM_SITUACION_COMERCIAL SCM ON SCM.DD_SCM_ID = ACT.DD_SCM_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.ACT_REG_INFO_REGISTRAL ARIR ON ACT.ACT_ID = ARIR.ACT_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.BIE_DATOS_REGISTRALES BDR ON ARIR.BIE_DREG_ID = BDR.BIE_DREG_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.ACT_PAC_PERIMETRO_ACTIVO PAC ON ACT.ACT_ID = PAC.ACT_ID
      LEFT JOIN ' ||V_ESQUEMA|| '.ACT_PAC_PROPIETARIO_ACTIVO PAC2 ON PAC2.ACT_ID = ACT.ACT_ID
    where act.borrado = 0
';

      	
  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_ACTIVOS_CREAR_TBJ...Creada OK');
  
END;
/

EXIT;
