--/*
--##########################################
--## AUTOR=IVAN REPISO
--## FECHA_CREACION=20220111
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-16881
--## PRODUCTO=NO
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial 
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    ERR_NUM NUMBER; -- N?mero de errores
    ERR_MSG VARCHAR2(2048); -- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas
    V_MSQL VARCHAR2(4000 CHAR); 
	V_TABLA VARCHAR2(100 CHAR) := 'V_GRID_INTERVINIENTES';

    V_COUNT NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO V_COUNT FROM ALL_OBJECTS WHERE OBJECT_NAME = V_TABLA AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF V_COUNT>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'...');
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.'||V_TABLA||'';  
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'... borrada OK');
  END IF;

  SELECT COUNT(*) INTO V_COUNT FROM ALL_OBJECTS WHERE OBJECT_NAME = V_TABLA AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF V_COUNT>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'...');
    EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.'||V_TABLA||'';  
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATING VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'...');
  EXECUTE IMMEDIATE 'CREATE VIEW ' || V_ESQUEMA || '.'||V_TABLA||' 
	AS
		SELECT DISTINCT
      COM.COM_ID AS ID,
			OFR.OFR_NUM_OFERTA AS NUM_OFERTA,
			NVL2(COM.COM_NOMBRE, COM.COM_NOMBRE,NULL) AS NOMBRE,
			NVL2(COM.COM_APELLIDOS,COM.COM_APELLIDOS, NULL) AS APELLIDOS,
			TDI.DD_TDI_DESCRIPCION AS TIPO_DOCUMENTO,
			COM.COM_DOCUMENTO AS NUM_DOCUMENTO,
			FIO.DD_FIO_DESCRIPCION AS ROL_OFERTA
		FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
		JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL         	ECO ON ECO.OFR_ID = OFR.OFR_ID AND ECO.BORRADO = 0
		LEFT JOIN '||V_ESQUEMA||'.CEX_COMPRADOR_EXPEDIENTE         	CEX ON CEX.ECO_ID = ECO.ECO_ID AND CEX.BORRADO = 0
    LEFT JOIN '||V_ESQUEMA||'.COM_COMPRADOR                       COM ON COM.COM_ID = CEX.COM_ID AND COM.BORRADO = 0
		LEFT JOIN '||V_ESQUEMA||'.DD_FIO_FUN_INTERLOCUTOR_OFERTA 		FIO ON FIO.DD_FIO_ID = CEX.DD_FIO_ID AND FIO.BORRADO = 0
		LEFT JOIN '||V_ESQUEMA||'.DD_TDI_TIPO_DOCUMENTO_ID 			TDI ON TDI.DD_TDI_ID = COM.DD_TDI_ID AND TDI.BORRADO = 0
		WHERE OFR.BORRADO = 0';



  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.'||V_TABLA||'...Creada OK');
  
  EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;

          DBMS_OUTPUT.PUT_LINE('KO no modificada');
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(ERR_MSG);

          ROLLBACK;
          RAISE;     
  
END;
/

EXIT;
