--/*
--##########################################
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20220630
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=HREOS-18226
--## PRODUCTO=NO
--## Finalidad: 
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;

CREATE OR REPLACE PROCEDURE #ESQUEMA#.SP_EAS_01_DATOS_GENERALES (
      PL_OUTPUT       OUT VARCHAR2
)
AS

  V_ESQUEMA VARCHAR2(15 CHAR) := '#ESQUEMA#';
  V_ESQUEMA_MASTER VARCHAR2(15 CHAR) := '#ESQUEMA_MASTER#';
  V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.  

  V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.

BEGIN

    DBMS_OUTPUT.PUT_LINE('[INICIO]');
    
        V_SQL := 'TRUNCATE TABLE ' || V_ESQUEMA || '.AUX_APR_DATOS_GENERALES';
   	
   	EXECUTE IMMEDIATE V_SQL;

        V_SQL := 'MERGE INTO ' || V_ESQUEMA || '.AUX_APR_DATOS_GENERALES APR USING(
			WITH ACTIVO_MATRIZ AS (
			SELECT AGA.AGR_ID, ACT.ACT_NUM_ACTIVO, ACT.ACT_ID, ACT.DD_SAC_ID
			FROM ' || V_ESQUEMA || '.ACT_AGR_AGRUPACION AGR 
			JOIN ' || V_ESQUEMA || '.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGR.AGR_ID = AGA.AGR_ID AND AGA.BORRADO = 0
			JOIN ' || V_ESQUEMA || '.ACT_ACTIVO ACT ON ACT.ACT_ID = AGA.ACT_ID AND ACT.BORRADO = 0 
			WHERE AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL AND 
			AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM ' || V_ESQUEMA || '.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''16'') AND AGA.AGA_PRINCIPAL = 1)
			
			SELECT 1 AS TREGISTRO, 
			ACT.ACT_NUM_ACTIVO AS ZZEXTERNALID, 
			''RS'' AS ROTYPE, 
			EQV2.DD_CODIGO_CAIXA AS BUKRS, 
			MAT.ACT_NUM_ACTIVO AS SMENR, 
			REG.REG_SUPERFICIE_UTIL AS XMMEAS, 
			EQV4.DD_CODIGO_CAIXA AS SNUNR, 
			SUBSTR(ACT.ACT_DESCRIPCION, 1, 60) AS XMETXT, 
			ACT.ACT_NUM_ACTIVO AS SALTNR, 
			NULL AS VALIDFROM, 
			NULL AS VALIDTO, 
			EQV3.DD_CODIGO_CAIXA AS SGEBT, 
			EQV.DD_CODIGO_CAIXA AS SSTOCKW, 
			LOC.BIE_LOC_PORTAL AS XSTANDNR, 
			ICO.ICO_LONGITUD AS ZZ_XGOOGLE, 
			ICO.ICO_LATITUD AS ZZ_YGOOGLE 
			FROM ' || V_ESQUEMA || '.ACT_AGR_AGRUPACION AGR 
			JOIN ' || V_ESQUEMA || '.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGR.AGR_ID = AGA.AGR_ID AND AGA.BORRADO = 0
			JOIN ' || V_ESQUEMA || '.ACT_ACTIVO ACT ON ACT.ACT_ID = AGA.ACT_ID AND ACT.BORRADO = 0 
			JOIN ACTIVO_MATRIZ MAT ON MAT.AGR_ID = AGR.AGR_ID
			JOIN ' || V_ESQUEMA || '.ACT_LOC_LOCALIZACION LOC ON LOC.ACT_ID = ACT.ACT_ID
			JOIN ' || V_ESQUEMA || '.ACT_PAC_PROPIETARIO_ACTIVO PAC ON PAC.ACT_ID = MAT.ACT_ID
			JOIN ' || V_ESQUEMA || '.ACT_PRO_PROPIETARIO PRO ON PRO.PRO_ID = PAC.PRO_ID
			LEFT JOIN ' || V_ESQUEMA || '.DD_EQV_CAIXA_REM EQV2 ON EQV2.DD_NOMBRE_CAIXA = ''SOCIEDAD_PATRIMONIAL'' AND EQV2.DD_CODIGO_REM =PRO.PRO_DOCIDENTIF  AND EQV2.BORRADO=0  
			LEFT JOIN ' || V_ESQUEMA || '.DD_PLN_PLANTA_EDIFICIO PLN ON LOC.DD_PLN_ID = PLN.DD_PLN_ID
			LEFT JOIN ' || V_ESQUEMA || '.DD_EQV_CAIXA_REM EQV ON EQV.DD_NOMBRE_CAIXA = ''DD_PLN_PLANTA_EDIFICIO'' AND EQV.DD_CODIGO_REM =PLN.DD_PLN_CODIGO  AND EQV.BORRADO=0  
			LEFT JOIN ' || V_ESQUEMA || '.DD_ESE_ESCALERA_EDIFICIO ESE ON ESE.DD_ESE_ID = LOC.DD_ESE_ID
			LEFT JOIN ' || V_ESQUEMA || '.DD_EQV_CAIXA_REM EQV3 ON EQV3.DD_NOMBRE_CAIXA = ''ALA_EDIFICIO'' AND EQV3.DD_CODIGO_REM =ESE.DD_ESE_CODIGO  AND EQV3.BORRADO=0  
			LEFT JOIN ' || V_ESQUEMA || '.DD_SAC_SUBTIPO_ACTIVO SAC ON SAC.DD_SAC_ID = MAT.DD_SAC_ID
			LEFT JOIN ' || V_ESQUEMA || '.DD_EQV_CAIXA_REM EQV4 ON EQV4.DD_NOMBRE_CAIXA = ''CLASE_USO_REGISTRAL'' AND EQV4.DD_CODIGO_REM =SAC.DD_SAC_CODIGO  AND EQV4.BORRADO=0  
			JOIN ' || V_ESQUEMA || '.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
			JOIN ' || V_ESQUEMA || '.ACT_REG_INFO_REGISTRAL REG ON REG.ACT_ID = ACT.ACT_ID
			JOIN ' || V_ESQUEMA || '.DD_TPA_TIPO_ACTIVO TPA ON TPA.DD_TPA_ID = ACT.DD_TPA_ID
			JOIN ' || V_ESQUEMA || '.ACT_ICO_INFO_COMERCIAL ICO ON ICO.ACT_ID = ACT.ACT_ID
			JOIN ' || V_ESQUEMA || '.BIE_BIEN BIE ON BIE.BIE_ID = ACT.BIE_ID
			JOIN ' || V_ESQUEMA || '.BIE_LOCALIZACION LOC ON LOC.BIE_ID = BIE.BIE_ID
			WHERE AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL AND 
			AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM ' || V_ESQUEMA || '.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''16'') AND AGA.AGA_PRINCIPAL = 0
			) AUX ON (AUX.ZZEXTERNALID = APR.ZZEXTERNALID) 
			WHEN NOT MATCHED THEN INSERT
			(
			APR.TREGISTRO,
			APR.ZZEXTERNALID,
			APR.ROTYPE,
			APR.BUKRS,
			APR.SMENR,
			APR.XMMEAS,
			APR.SNUNR,
			APR.XMETXT,
			APR.SALTNR,
			APR.VALIDFROM,
			APR.VALIDTO,
			APR.SGEBT,
			APR.SSTOCKW,
			APR.XSTANDNR,
			APR.ZZ_XGOOGLE,
			APR.ZZ_YGOOGLE
			) VALUES(
			AUX.TREGISTRO,
			AUX.ZZEXTERNALID,
			AUX.ROTYPE,
			AUX.BUKRS,
			AUX.SMENR,
			AUX.XMMEAS,
			AUX.SNUNR,
			AUX.XMETXT,
			AUX.SALTNR,
			AUX.VALIDFROM,
			AUX.VALIDTO,
			AUX.SGEBT,
			AUX.SSTOCKW,
			AUX.XSTANDNR,
			AUX.ZZ_XGOOGLE,
			AUX.ZZ_YGOOGLE)';

        EXECUTE IMMEDIATE V_SQL;

    DBMS_OUTPUT.PUT_LINE('[INFO] FIN UPDATE / INSERT');
    COMMIT;

EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR: ' || TO_CHAR (SQLCODE));
      DBMS_OUTPUT.put_line (SQLERRM);
      ROLLBACK;
      RAISE;
END SP_EAS_01_DATOS_GENERALES;
/
EXIT;
