--/*
--##########################################
--## AUTOR=Daniel Algaba
--## FECHA_CREACION=20210819
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=HREOS-14893
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##	      0.2 Se añade el FLAG EN REM en la insercción de la AUX_BC_AGRUPACIONES - HREOS-14837
--##	      0.3 Correcciones - HREOS-14820
--##	      0.4 Validación OBREM para comprobar que todos sus activos no están parcialmente dentro de agrupaciones restringidas venta o alquiler - HREOS-14893
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;						

CREATE OR REPLACE PROCEDURE SP_BCR_11_AGRUPACIONES
   (     
      FLAG_EN_REM IN NUMBER
      , SALIDA OUT VARCHAR2
      , COD_RETORNO OUT NUMBER
   )

   AS

   V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar
   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
   ERR_NUM NUMBER(25); -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(10024 CHAR); -- Vble. auxiliar para registrar errores en el script.
   V_AUX NUMBER(10); -- Variable auxiliar

   V_FECHA_INICIO VARCHAR2(100 CHAR);
   V_FECHA_FIN VARCHAR2(100 CHAR);

BEGIN
      SALIDA := '[INICIO]'||CHR(10);

      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGR_SACAR_ACT');
      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGRUPACIONES_NUEVAS');
      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGRUPACIONES');
      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGRUPACIONES_REJECTS');
      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGRUPACIONES_ANYADIR');
      #ESQUEMA#.OPERACION_DDL.DDL_TABLE('TRUNCATE','AUX_BC_AGR_OBREM_PARCIALES');

      SALIDA := SALIDA || '[INFO] SE VA A PROCEDER A ACTUALIZAR/INSERTAR ACTIVOS EN AGRUPACIONES.'|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 0 - CARGAMOS ACTIVOS EN AUXILIAR'||CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  SELECT 
                  APR.NUM_IDENTIFICATIVO ACTIVO
                  , APR.PROMO_CONJUNTA_OB_REM
                  , APR.PROMO_CONJUNTA_VENTA
                  , APR.PROMO_CONJUNTA_ALQUILER
                  , APR.PROMO_COMERCIAL
                  FROM '|| V_ESQUEMA ||'.AUX_APR_BCR_STOCK APR
                  WHERE APR.FLAG_EN_REM = '||FLAG_EN_REM||'';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      INSERTADOS '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 1 - VALIDAMOS LAS AGRUPACIONES'||CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PRO.PRO_ID
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_VENTA = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , AUX.PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas venta - Diferente propietario que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND PRO.PRO_ID <> PRI.PRO_ID';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS VENTA, RECHAZADOS POR PROPIETARIO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PAC.PAC_INCLUIDO
                  , PAC.PAC_CHECK_ADMISION
                  , PAC.PAC_CHECK_COMERCIALIZAR
                  , PAC.PAC_CHECK_FORMALIZAR
                  , PAC.PAC_CHECK_GESTIONAR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_VENTA = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , AUX.PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas venta - Diferente perímetro que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND (PAC.PAC_INCLUIDO <> PRI.PAC_INCLUIDO
                  OR PAC.PAC_CHECK_ADMISION <> PRI.PAC_CHECK_ADMISION
                  OR PAC.PAC_CHECK_COMERCIALIZAR <> PRI.PAC_CHECK_COMERCIALIZAR
                  OR PAC.PAC_CHECK_FORMALIZAR <> PRI.PAC_CHECK_FORMALIZAR
                  OR PAC.PAC_CHECK_GESTIONAR <> PRI.PAC_CHECK_GESTIONAR)';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS VENTA, RECHAZADOS POR PERÍMETRO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , AUX.PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas venta - Tipo de comercialización diferente a venta'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_APU_ACTIVO_PUBLICACION APU ON APU.ACT_ID = ACT.ACT_ID AND APU.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_TCO_TIPO_COMERCIALIZACION TCO ON TCO.DD_TCO_ID = APU.DD_TCO_ID AND TCO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND TCO.DD_TCO_CODIGO NOT IN (''01'',''02'')';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS VENTA, RECHAZADOS POR TIPO DE COMERCIALIZACIÓN DIFERENTE A VENTA '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES
                WITH OBREM AS (SELECT AUX.PROMO_CONJUNTA_OB_REM
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                GROUP BY AUX.PROMO_CONJUNTA_OB_REM)
                SELECT
                DISTINCT AUX.PROMO_CONJUNTA_OB_REM
                , 1 PROMO_CONJUNTA_VENTA
                , 0 PROMO_CONJUNTA_ALQUILER
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                LEFT JOIN OBREM OBREM_V ON AUX.PROMO_CONJUNTA_VENTA = OBREM_V.PROMO_CONJUNTA_OB_REM
                WHERE OBREM_V.PROMO_CONJUNTA_OB_REM IS NULL';

      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM SIN TODOS SUS ACTIVOS EN AGRUPACIONES RESTRINGIDAS VENTA '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                SELECT
                AUX.NUM_IDENTIFICATIVO
                , NULL PROMO_CONJUNTA_OB_REM
                , AUX.PROMO_CONJUNTA_VENTA
                , NULL PROMO_CONJUNTA_ALQUILER
                , NULL PROMO_COMERCIAL
                , ''Restringidas venta - Los activos que componen una agrupación restringida OBREM no son divisibles en agrupaciones restringidas de venta'' ERROR
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                JOIN '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES PAR ON PAR.PROMO_CONJUNTA_OB_REM = AUX.PROMO_CONJUNTA_OB_REM AND PAR.PROMO_CONJUNTA_VENTA = 1
                WHERE AUX.PROMO_CONJUNTA_VENTA IS NOT NULL';

      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS VENTA, RECHAZADOS POR NO TENER TODOS LOS ACTIVOS DE SU OBREM '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PRO.PRO_ID
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_ALQUILER = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , AUX.PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas alquiler - Diferente propietario que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND PRO.PRO_ID <> PRI.PRO_ID';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS ALQUILER, RECHAZADOS POR PROPIETARIO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PAC.PAC_INCLUIDO
                  , PAC.PAC_CHECK_ADMISION
                  , PAC.PAC_CHECK_COMERCIALIZAR
                  , PAC.PAC_CHECK_FORMALIZAR
                  , PAC.PAC_CHECK_GESTIONAR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_ALQUILER = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , AUX.PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas alquiler - Diferente perímetro que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND (PAC.PAC_INCLUIDO <> PRI.PAC_INCLUIDO
                  OR PAC.PAC_CHECK_ADMISION <> PRI.PAC_CHECK_ADMISION
                  OR PAC.PAC_CHECK_COMERCIALIZAR <> PRI.PAC_CHECK_COMERCIALIZAR
                  OR PAC.PAC_CHECK_FORMALIZAR <> PRI.PAC_CHECK_FORMALIZAR
                  OR PAC.PAC_CHECK_GESTIONAR <> PRI.PAC_CHECK_GESTIONAR)';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS ALQUILER, RECHAZADOS POR PERÍMETRO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , AUX.PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas alquiler - Tipo de comercialización diferente a alquiler'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_APU_ACTIVO_PUBLICACION APU ON APU.ACT_ID = ACT.ACT_ID AND APU.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_TCO_TIPO_COMERCIALIZACION TCO ON TCO.DD_TCO_ID = APU.DD_TCO_ID AND TCO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND TCO.DD_TCO_CODIGO NOT IN (''02'',''03'')';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS ALQUILER, RECHAZADOS POR TIPO DE COMERCIALIZACIÓN DIFERENTE A ALQUILER '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'MERGE INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES AUX
                USING (
                WITH OBREM AS (SELECT AUX.PROMO_CONJUNTA_OB_REM
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                GROUP BY AUX.PROMO_CONJUNTA_OB_REM)
                SELECT
                DISTINCT AUX.PROMO_CONJUNTA_OB_REM
                , 1 PROMO_CONJUNTA_ALQUILER
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                LEFT JOIN OBREM OBREM_A ON AUX.PROMO_CONJUNTA_ALQUILER = OBREM_A.PROMO_CONJUNTA_OB_REM
                WHERE OBREM_A.PROMO_CONJUNTA_OB_REM IS NULL
                ) AUX_A ON (AUX.PROMO_CONJUNTA_OB_REM = AUX_A.PROMO_CONJUNTA_OB_REM)
                 WHEN MATCHED THEN
                     UPDATE SET
                        AUX.PROMO_CONJUNTA_ALQUILER = AUX_A.PROMO_CONJUNTA_ALQUILER
                WHEN NOT MATCHED THEN
                    INSERT (PROMO_CONJUNTA_OB_REM, PROMO_CONJUNTA_VENTA , PROMO_CONJUNTA_ALQUILER)
                        VALUES (AUX_A.PROMO_CONJUNTA_OB_REM, 0, AUX_A.PROMO_CONJUNTA_ALQUILER)';    

      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM SIN TODOS SUS ACTIVOS EN AGRUPACIONES RESTRINGIDAS ALQUILER '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                SELECT
                AUX.NUM_IDENTIFICATIVO
                , NULL PROMO_CONJUNTA_OB_REM
                , NULL PROMO_CONJUNTA_VENTA
                , AUX.PROMO_CONJUNTA_ALQUILER
                , NULL PROMO_COMERCIAL
                , ''Restringidas alquiler - Los activos que componen una agrupación restringida OBREM no son divisibles en agrupaciones restringidas de alquiler'' ERROR
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                JOIN '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES PAR ON PAR.PROMO_CONJUNTA_OB_REM = AUX.PROMO_CONJUNTA_OB_REM AND PAR.PROMO_CONJUNTA_ALQUILER = 1
                WHERE AUX.PROMO_CONJUNTA_ALQUILER IS NOT NULL';

      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS ALQUILER, RECHAZADOS POR NO TENER TODOS LOS ACTIVOS DE SU OBREM '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , TCO.DD_TCO_CODIGO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_OB_REM = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_APU_ACTIVO_PUBLICACION APU ON APU.ACT_ID = ACT.ACT_ID AND APU.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.DD_TCO_TIPO_COMERCIALIZACION TCO ON TCO.DD_TCO_ID = APU.DD_TCO_ID AND TCO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , AUX.PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas obrem - Tipo de comercialización diferente al principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_APU_ACTIVO_PUBLICACION APU ON APU.ACT_ID = ACT.ACT_ID AND APU.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.DD_TCO_TIPO_COMERCIALIZACION TCO ON TCO.DD_TCO_ID = APU.DD_TCO_ID AND TCO.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND 1 = CASE WHEN TCO.DD_TCO_CODIGO = ''01'' AND PRI.DD_TCO_CODIGO = ''03'' THEN 1 
                  WHEN TCO.DD_TCO_CODIGO = ''03'' AND PRI.DD_TCO_CODIGO = ''01'' THEN 1 
                  ELSE 0 END';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM, RECHAZADOS POR TIPO DE COMERCIALIZACIÓN DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PRO.PRO_ID
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_OB_REM = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , AUX.PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas obrem - Diferente propietario que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PROPIETARIO_ACTIVO PRO ON PRO.ACT_ID = ACT.ACT_ID AND PRO.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND PRO.PRO_ID <> PRI.PRO_ID';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM, RECHAZADOS POR PROPIETARIO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  WITH PRINCIPAL AS (
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , PAC.PAC_INCLUIDO
                  , PAC.PAC_CHECK_ADMISION
                  , PAC.PAC_CHECK_COMERCIALIZAR
                  , PAC.PAC_CHECK_FORMALIZAR
                  , PAC.PAC_CHECK_GESTIONAR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.PROMO_CONJUNTA_OB_REM = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  )
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , AUX.PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , NULL PROMO_COMERCIAL
                  , ''Restringidas obrem - Diferente perímetro que el principal'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_PAC_PERIMETRO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID AND PAC.BORRADO = 0
                  JOIN PRINCIPAL PRI ON PRI.NUM_IDENTIFICATIVO = AUX.NUM_IDENTIFICATIVO
                  WHERE AUX.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND (PAC.PAC_INCLUIDO <> PRI.PAC_INCLUIDO
                  OR PAC.PAC_CHECK_ADMISION <> PRI.PAC_CHECK_ADMISION
                  OR PAC.PAC_CHECK_COMERCIALIZAR <> PRI.PAC_CHECK_COMERCIALIZAR
                  OR PAC.PAC_CHECK_FORMALIZAR <> PRI.PAC_CHECK_FORMALIZAR
                  OR PAC.PAC_CHECK_GESTIONAR <> PRI.PAC_CHECK_GESTIONAR)';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM, RECHAZADOS POR PERÍMETRO DIFERENTE AL PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS
                  SELECT 
                  AUX.NUM_IDENTIFICATIVO
                  , NULL PROMO_CONJUNTA_OB_REM
                  , NULL PROMO_CONJUNTA_VENTA
                  , NULL PROMO_CONJUNTA_ALQUILER
                  , AUX.PROMO_COMERCIAL
                  , ''Obra nueva - Ya existe el activo en otra agrupación de Obra Nueva'' ERROR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  WHERE AUX.PROMO_COMERCIAL IS NOT NULL
                  AND EXISTS (SELECT 1 FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR
                  JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGA.AGR_ID = AGR.AGR_ID AND AGA.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION TAG ON AGR.DD_TAG_ID = TAG.DD_TAG_ID AND TAG.BORRADO = 0 AND TAG.DD_TAG_CODIGO = ''01''
                  WHERE AGR.AGR_FECHA_BAJA IS NULL
                  AND AGA.ACT_ID = ACT.ACT_ID)';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      OBRA NUEVA, RECHAZADOS POR ESTAR YA EN OTRA AGRUPACIÓN DE OBRA NUEVA '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 2 - ACTIVOS QUE CAMBIAN DE AGRUPACIÓN'||CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT AUX
                  SELECT 
                  AGR.AGR_UVEM_COAGIW COD_AGRUPACION
                  , ''02'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON APR.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGA.ACT_ID = ACT.ACT_ID AND AGA.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ID = AGA.AGR_ID AND AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.AGR_UVEM_COAGIW IS NOT NULL
                  JOIN '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION TAG ON AGR.DD_TAG_ID = TAG.DD_TAG_ID AND TAG.BORRADO = 0 AND TAG.DD_TAG_CODIGO = ''02''
                  WHERE NVL(APR.PROMO_CONJUNTA_VENTA,-1) <> AGR.AGR_UVEM_COAGIW
                  AND NOT EXISTS (SELECT 1
                  FROM '|| V_ESQUEMA ||'.OFR_OFERTAS OFR
                  JOIN '|| V_ESQUEMA ||'.ACT_OFR ACO ON OFR.OFR_ID = ACO.OFR_ID
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO AUX_ACT ON AUX_ACT.ACT_ID = ACO.ACT_ID AND AUX_ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_EOF_ESTADOS_OFERTA EOF ON OFR.DD_EOF_ID = EOF.DD_EOF_ID AND EOF.DD_EOF_CODIGO = ''01''
                  WHERE OFR.BORRADO = 0 AND AUX_ACT.ACT_NUM_ACTIVO = AGR.AGR_UVEM_COAGIW)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT AUX
                  SELECT 
                  AGR.AGR_UVEM_COAGIW COD_AGRUPACION
                  , ''17'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON APR.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGA.ACT_ID = ACT.ACT_ID AND AGA.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ID = AGA.AGR_ID AND AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.AGR_UVEM_COAGIW IS NOT NULL
                  JOIN '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION TAG ON AGR.DD_TAG_ID = TAG.DD_TAG_ID AND TAG.BORRADO = 0 AND TAG.DD_TAG_CODIGO = ''17''
                  WHERE NVL(APR.PROMO_CONJUNTA_ALQUILER,-1) <> AGR.AGR_UVEM_COAGIW
                  AND NOT EXISTS (SELECT 1
                  FROM '|| V_ESQUEMA ||'.OFR_OFERTAS OFR
                  JOIN '|| V_ESQUEMA ||'.ACT_OFR ACO ON OFR.OFR_ID = ACO.OFR_ID
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO AUX_ACT ON AUX_ACT.ACT_ID = ACO.ACT_ID AND AUX_ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_EOF_ESTADOS_OFERTA EOF ON OFR.DD_EOF_ID = EOF.DD_EOF_ID AND EOF.DD_EOF_CODIGO = ''01''
                  WHERE OFR.BORRADO = 0 AND AUX_ACT.ACT_NUM_ACTIVO = AGR.AGR_UVEM_COAGIW)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT AUX
                  SELECT 
                  AGR.AGR_UVEM_COAGIW COD_AGRUPACION
                  , ''18'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON APR.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGA.ACT_ID = ACT.ACT_ID AND AGA.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ID = AGA.AGR_ID AND AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.AGR_UVEM_COAGIW IS NOT NULL
                  JOIN '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION TAG ON AGR.DD_TAG_ID = TAG.DD_TAG_ID AND TAG.BORRADO = 0 AND TAG.DD_TAG_CODIGO = ''18''
                  WHERE NVL(APR.PROMO_CONJUNTA_OB_REM,-1) <> AGR.AGR_UVEM_COAGIW
                  AND NOT EXISTS (SELECT 1
                  FROM '|| V_ESQUEMA ||'.OFR_OFERTAS OFR
                  JOIN '|| V_ESQUEMA ||'.ACT_OFR ACO ON OFR.OFR_ID = ACO.OFR_ID
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO AUX_ACT ON AUX_ACT.ACT_ID = ACO.ACT_ID AND AUX_ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.DD_EOF_ESTADOS_OFERTA EOF ON OFR.DD_EOF_ID = EOF.DD_EOF_ID AND EOF.DD_EOF_CODIGO = ''01''
                  WHERE OFR.BORRADO = 0 AND AUX_ACT.ACT_NUM_ACTIVO = AGR.AGR_UVEM_COAGIW)';
   
      EXECUTE IMMEDIATE V_MSQL;

     V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT AUX
                SELECT 
                PCV.PROMO_CONJUNTA_VENTA COD_AGRUPACION
                , ''02'' TIPO
                , AUX.NUM_IDENTIFICATIVO ACTIVO
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                JOIN '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES PAR ON PAR.PROMO_CONJUNTA_OB_REM = AUX.PROMO_CONJUNTA_OB_REM AND PAR.PROMO_CONJUNTA_VENTA = 1
                JOIN (SELECT SAC.COD_AGRUPACION PROMO_CONJUNTA_VENTA FROM '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT SAC WHERE SAC.TIPO = ''02'' GROUP BY SAC.COD_AGRUPACION) PCV ON PCV.PROMO_CONJUNTA_VENTA = AUX.PROMO_CONJUNTA_VENTA
                WHERE NOT EXISTS (SELECT 1 
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT ACT
                WHERE ACT.TIPO = ''02'' AND ACT.ACTIVO = AUX.NUM_IDENTIFICATIVO)
                UNION ALL
                SELECT 
                PCA.PROMO_CONJUNTA_ALQUILER COD_AGRUPACION
                , ''17'' TIPO
                , AUX.NUM_IDENTIFICATIVO ACTIVO
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES AUX
                JOIN '|| V_ESQUEMA ||'.AUX_BC_AGR_OBREM_PARCIALES PAR ON PAR.PROMO_CONJUNTA_OB_REM = AUX.PROMO_CONJUNTA_OB_REM AND PAR.PROMO_CONJUNTA_ALQUILER = 1
                JOIN (SELECT SAC.COD_AGRUPACION PROMO_CONJUNTA_ALQUILER FROM '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT SAC WHERE SAC.TIPO = ''17'' GROUP BY SAC.COD_AGRUPACION) PCA ON PCA.PROMO_CONJUNTA_ALQUILER = AUX.PROMO_CONJUNTA_ALQUILER
                WHERE NOT EXISTS (SELECT 1 
                FROM '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT ACT
                WHERE ACT.TIPO = ''17'' AND ACT.ACTIVO = AUX.NUM_IDENTIFICATIVO)';

      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'MERGE INTO '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA
                  USING (
                  SELECT 
                  AGA.AGA_ID
                  , ACT.ACT_ID
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGR_SACAR_ACT AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.BORRADO = 0 AND AGR.AGR_FECHA_BAJA IS NULL
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.ACTIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGR.AGR_ID = AGA.AGR_ID AND AGA.ACT_ID = ACT.ACT_ID AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGA.BORRADO = 0
                  ) AUX
                  ON (AGA.AGA_ID = AUX.AGA_ID)
                  WHEN MATCHED THEN
                     UPDATE SET AGA.BORRADO = 1
                     , AGA.USUARIOBORRAR = ''STOCK_BC''
                     , AGA.FECHABORRAR = SYSDATE';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RELACIONADOS '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 3 - AÑADIR ACTIVOS A AGRUPACIONES EXISTENTES'||CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_ANYADIR AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_VENTA COD_AGRUPACION
                  , ''02'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_VENTA)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_VENTA = APR.PROMO_CONJUNTA_VENTA)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_ANYADIR AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_ALQUILER COD_AGRUPACION
                  , ''17'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_ALQUILER)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_ALQUILER = APR.PROMO_CONJUNTA_ALQUILER)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_ANYADIR AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_OB_REM COD_AGRUPACION
                  , ''18'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_OB_REM)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_OB_REM = APR.PROMO_CONJUNTA_OB_REM)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_ANYADIR AUX
                  SELECT 
                  APR.PROMO_COMERCIAL COD_AGRUPACION
                  , ''01'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_COMERCIAL IS NOT NULL
                  AND EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_COMERCIAL)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_COMERCIAL IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_COMERCIAL = APR.PROMO_COMERCIAL)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO
                  (AGA_ID
                  , AGR_ID
                  , ACT_ID
                  , AGA_FECHA_INCLUSION
                  , ACT_AGA_PARTICIPACION_UA
                  , USUARIOCREAR
                  , FECHACREAR)
                  SELECT 
                  '|| V_ESQUEMA ||'.S_ACT_AGA_AGRUPACION_ACTIVO.NEXTVAL AGA_ID
                  , AGR.AGR_ID
                  , ACT.ACT_ID
                  , SYSDATE AGA_FECHA_INCLUSION
                  , NULL ACT_AGA_PARTICIPACION_UA
                  , ''STOCK_BC'' USUARIOCREAR
                  , SYSDATE FECHACREAR
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_ANYADIR AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX.ACTIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0 
                  WHERE AGR.AGR_FECHA_BAJA IS NULL
                  AND NOT EXISTS (SELECT 1 FROM '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA WHERE AGA.BORRADO = 0 AND AGR.AGR_ID = AGA.AGR_ID AND ACT.ACT_ID = AGA.ACT_ID)';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RELACIONADOS '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 4 - AGRUPACIONES NUEVAS'||CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_VENTA COD_AGRUPACION
                  , ''02'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''02'')
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_VENTA)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_VENTA = APR.PROMO_CONJUNTA_VENTA)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_VENTA IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.PROMO_CONJUNTA_VENTA)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_ALQUILER COD_AGRUPACION
                  , ''17'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''17'')
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_ALQUILER)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_ALQUILER = APR.PROMO_CONJUNTA_ALQUILER)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_ALQUILER IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.PROMO_CONJUNTA_ALQUILER)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS AUX
                  SELECT 
                  APR.PROMO_CONJUNTA_OB_REM COD_AGRUPACION
                  , ''18'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''18'')
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_CONJUNTA_OB_REM)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_CONJUNTA_OB_REM = APR.PROMO_CONJUNTA_OB_REM)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_CONJUNTA_OB_REM IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.PROMO_CONJUNTA_OB_REM)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS AUX
                  SELECT 
                  APR.PROMO_COMERCIAL COD_AGRUPACION
                  , ''01'' TIPO
                  , APR.NUM_IDENTIFICATIVO ACTIVO
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES APR
                  WHERE APR.PROMO_COMERCIAL IS NOT NULL
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR 
                  WHERE AGR.BORRADO = 0 
                  AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = ''01'')
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND AGR.AGR_UVEM_COAGIW = APR.PROMO_COMERCIAL)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_COMERCIAL IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.NUM_IDENTIFICATIVO
                  AND REJ.PROMO_COMERCIAL = APR.PROMO_COMERCIAL)
                  AND NOT EXISTS (SELECT 1 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_REJECTS REJ
                  WHERE REJ.PROMO_COMERCIAL IS NOT NULL
                  AND REJ.NUM_IDENTIFICATIVO = APR.PROMO_COMERCIAL)';
   
      EXECUTE IMMEDIATE V_MSQL;

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION
                  (AGR_ID
                  , DD_TAG_ID
                  , AGR_NOMBRE
                  , AGR_NUM_AGRUP_REM
                  , AGR_NUM_AGRUP_UVEM
                  , AGR_FECHA_ALTA
                  , AGR_ACT_PRINCIPAL
                  , AGR_SEG_VISITAS
                  , USUARIOCREAR
                  , FECHACREAR
                  , AGR_IS_FORMALIZACION
                  , AGR_UVEM_COAGIW)
                  SELECT 
                  '|| V_ESQUEMA ||'.S_ACT_AGR_AGRUPACION.NEXTVAL AGR_ID
                  , (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) DD_TAG_ID
                  , BIE_LOC.BIE_LOC_NOMBRE_VIA || '' '' || BIE_LOC.BIE_LOC_PORTAL AGR_NOMBRE
                  , '|| V_ESQUEMA ||'.S_AGR_NUM_AGRUP_REM.NEXTVAL AGR_NUM_AGRUP_REM
                  , AUX.COD_AGRUPACION AGR_NUM_AGRUP_UVEM
                  , SYSDATE AGR_FECHA_ALTA
                  , CASE WHEN AUX.TIPO IN (''02'',''17'',''18'') THEN ACT.ACT_ID ELSE NULL END AGR_ACT_PRINCIPAL
                  , 0 AGR_SEG_VISITAS
                  , ''STOCK_BC'' USUARIOCREAR
                  , SYSDATE FECHACREAR
                  , 1 AGR_IS_FORMALIZACION
                  , AUX.COD_AGRUPACION AGR_UVEM_COAGIW
                  FROM (SELECT BCAN.COD_AGRUPACION, BCAN.ACTIVO, BCAN.TIPO 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS BCAN
                  WHERE BCAN.COD_AGRUPACION = BCAN.ACTIVO) AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.ACTIVO AND ACT.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.BIE_LOCALIZACION BIE_LOC ON ACT.BIE_ID = BIE_LOC.BIE_ID AND BIE_LOC.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      AGRUPACIONES NUEVAS '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_RES_RESTRINGIDA
                  (AGR_ID
                  , DD_PRV_ID
                  , DD_LOC_ID
                  , RES_DIRECCION
                  , RES_CP)
                  SELECT 
                  AGR_ID
                  , BIE_LOC.DD_PRV_ID
                  , BIE_LOC.DD_LOC_ID
                  , BIE_LOC.BIE_LOC_NOMBRE_VIA || '' '' || BIE_LOC.BIE_LOC_PORTAL RES_DIRECCION
                  , BIE_LOC.BIE_LOC_COD_POST RES_CP
                  FROM (SELECT BCAN.COD_AGRUPACION, BCAN.ACTIVO, BCAN.TIPO 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS BCAN
                  WHERE BCAN.COD_AGRUPACION = BCAN.ACTIVO
                  AND BCAN.TIPO = ''02'') AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.ACTIVO AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ACT_PRINCIPAL = ACT.ACT_ID AND AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.BIE_LOCALIZACION BIE_LOC ON ACT.BIE_ID = BIE_LOC.BIE_ID AND BIE_LOC.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS VENTA '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_RAL_RESTRINGIDA_ALQUILER
                  (AGR_ID
                  , DD_PRV_ID
                  , DD_LOC_ID
                  , RAL_DIRECCION
                  , RAL_CP)
                  SELECT 
                  AGR_ID
                  , BIE_LOC.DD_PRV_ID
                  , BIE_LOC.DD_LOC_ID
                  , BIE_LOC.BIE_LOC_NOMBRE_VIA || '' '' || BIE_LOC.BIE_LOC_PORTAL RAL_DIRECCION
                  , BIE_LOC.BIE_LOC_COD_POST RAL_CP
                  FROM (SELECT BCAN.COD_AGRUPACION, BCAN.ACTIVO, BCAN.TIPO 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS BCAN
                  WHERE BCAN.COD_AGRUPACION = BCAN.ACTIVO
                  AND BCAN.TIPO = ''17'') AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.ACTIVO AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ACT_PRINCIPAL = ACT.ACT_ID AND AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.BIE_LOCALIZACION BIE_LOC ON ACT.BIE_ID = BIE_LOC.BIE_ID AND BIE_LOC.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS ALQUILER '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_ROB_RESTRINGIDA_OBREM
                  (AGR_ID
                  , DD_PRV_ID
                  , DD_LOC_ID
                  , ROB_DIRECCION
                  , ROB_CP)
                  SELECT 
                  AGR_ID
                  , BIE_LOC.DD_PRV_ID
                  , BIE_LOC.DD_LOC_ID
                  , BIE_LOC.BIE_LOC_NOMBRE_VIA || '' '' || BIE_LOC.BIE_LOC_PORTAL ROB_DIRECCION
                  , BIE_LOC.BIE_LOC_COD_POST ROB_CP
                  FROM (SELECT BCAN.COD_AGRUPACION, BCAN.ACTIVO, BCAN.TIPO 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS BCAN
                  WHERE BCAN.COD_AGRUPACION = BCAN.ACTIVO
                  AND BCAN.TIPO = ''18'') AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.ACTIVO AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_ACT_PRINCIPAL = ACT.ACT_ID AND AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.BIE_LOCALIZACION BIE_LOC ON ACT.BIE_ID = BIE_LOC.BIE_ID AND BIE_LOC.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      RESTRINGIDAS OBREM '|| SQL%ROWCOUNT|| CHR(10);


      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_ONV_OBRA_NUEVA
                  (AGR_ID
                  , DD_PRV_ID
                  , DD_LOC_ID
                  , ONV_DIRECCION
                  , ONV_CP)
                  SELECT 
                  AGR_ID
                  , BIE_LOC.DD_PRV_ID
                  , BIE_LOC.DD_LOC_ID
                  , BIE_LOC.BIE_LOC_NOMBRE_VIA || '' '' || BIE_LOC.BIE_LOC_PORTAL ONV_DIRECCION
                  , BIE_LOC.BIE_LOC_COD_POST ONV_CP
                  FROM (SELECT BCAN.COD_AGRUPACION, BCAN.TIPO 
                  FROM '|| V_ESQUEMA ||'.AUX_BC_AGRUPACIONES_NUEVAS BCAN
                  WHERE BCAN.TIPO = ''01''
                  GROUP BY BCAN.COD_AGRUPACION, BCAN.TIPO) AUX
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.COD_AGRUPACION AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0
                  LEFT JOIN '|| V_ESQUEMA ||'.BIE_LOCALIZACION BIE_LOC ON ACT.BIE_ID = BIE_LOC.BIE_ID AND BIE_LOC.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      OBRA NUEVA '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO
               (AGA_ID
               , AGR_ID
               , ACT_ID
               , AGA_FECHA_INCLUSION
               , AGA_PRINCIPAL
               , ACT_AGA_PARTICIPACION_UA
               , USUARIOCREAR
               , FECHACREAR)
               SELECT 
               '|| V_ESQUEMA ||'.S_ACT_AGA_AGRUPACION_ACTIVO.NEXTVAL AGA_ID
               , AGR.AGR_ID
               , ACT.ACT_ID
               , SYSDATE AGA_FECHA_INCLUSION
               , CASE WHEN AUX.TIPO  IN (''02'',''17'',''18'') AND AUX.COD_AGRUPACION = AUX.ACTIVO THEN 1 
                  WHEN AUX.TIPO  IN (''02'',''17'',''18'') THEN 0
                  ELSE NULL END AGA_PRINCIPAL
               , NULL ACT_AGA_PARTICIPACION_UA
               , ''STOCK_BC'' USUARIOCREAR
               , SYSDATE FECHACREAR
               FROM AUX_BC_AGRUPACIONES_NUEVAS AUX
               JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO_CAIXA = AUX.ACTIVO AND ACT.BORRADO = 0
               JOIN '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR ON AGR.AGR_UVEM_COAGIW = AUX.COD_AGRUPACION AND AGR.AGR_FECHA_BAJA IS NULL AND AGR.DD_TAG_ID = (SELECT DD_TAG_ID FROM '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION WHERE DD_TAG_CODIGO = AUX.TIPO) AND AGR.BORRADO = 0';
   
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      ACTIVOS RELACIONADOS '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 5 - AGRUPACIONES SIN ACTIVOS'||CHR(10);

      V_MSQL := 'MERGE INTO '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR
                  USING (
                  SELECT 
                  AGR.AGR_ID, AGR.AGR_NUM_AGRUP_REM
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR
                  WHERE AGR.BORRADO = 0 
                  AND AGR.AGR_UVEM_COAGIW IS NOT NULL
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND 0 = (SELECT COUNT(AGA.ACT_ID)
                  FROM '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA
                  WHERE AGA.BORRADO = 0 
                  AND AGA.AGR_ID = AGR.AGR_ID)
                  ) AUX
                  ON (AGR.AGR_ID = AUX.AGR_ID)
                  WHEN MATCHED THEN
                     UPDATE SET AGR.AGR_FECHA_BAJA = SYSDATE
                     , AGR.USUARIOMODIFICAR = ''STOCK_BC''
                     , AGR.FECHAMODIFICAR = SYSDATE';
                     
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      AGRUPACIONES DADAS DE BAJA '|| SQL%ROWCOUNT|| CHR(10);

      V_MSQL := 'MERGE INTO '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR
                  USING (
                  SELECT
                  AGR.AGR_ID
                  FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AGR
                  JOIN '|| V_ESQUEMA ||'.DD_TAG_TIPO_AGRUPACION TAG ON AGR.DD_TAG_ID = TAG.DD_TAG_ID AND TAG.BORRADO = 0 AND TAG.DD_TAG_CODIGO IN (''02'',''17'',''18'')
                  WHERE AGR.BORRADO = 0
                  AND AGR.AGR_UVEM_COAGIW IS NOT NULL
                  AND AGR.AGR_FECHA_BAJA IS NULL
                  AND NOT EXISTS (SELECT 1 FROM '|| V_ESQUEMA ||'.ACT_AGR_AGRUPACION AUX_AGR
                     JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON AUX_AGR.AGR_UVEM_COAGIW = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                     JOIN '|| V_ESQUEMA ||'.ACT_AGA_AGRUPACION_ACTIVO AGA ON AUX_AGR.AGR_ID = AGA.AGR_ID AND AGA.ACT_ID = ACT.ACT_ID AND AGA.BORRADO = 0
                     WHERE AUX_AGR.AGR_FECHA_BAJA IS NULL AND AGA.AGA_PRINCIPAL = 1 AND AGR.AGR_ID = AUX_AGR.AGR_ID AND AGR.DD_TAG_ID = AUX_AGR.DD_TAG_ID)
                  ) AUX
                  ON (AGR.AGR_ID = AUX.AGR_ID)
                  WHEN MATCHED THEN
                     UPDATE SET AGR.AGR_FECHA_BAJA = SYSDATE
                     , AGR.USUARIOMODIFICAR = ''STOCK_BC''
                     , AGR.FECHAMODIFICAR = SYSDATE';
                     
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      AGRUPACIONES DADAS DE BAJA POR SACAR EL ACTIVO PRINCIPAL '|| SQL%ROWCOUNT|| CHR(10);

      SALIDA := SALIDA || '   [INFO] 6 - INFORMAR UNIDAD ECÓNOMICA'||CHR(10);

      V_MSQL := 'MERGE INTO '|| V_ESQUEMA ||'.ACT_ACTIVO_CAIXA CBX
                  USING (
                  SELECT 
                  APR.PROMO_COMERCIAL CBX_UNIDAD_ECONOMICA
                  , CBX.CBX_ID
                  FROM '|| V_ESQUEMA ||'.AUX_APR_BCR_STOCK APR
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO ACT ON APR.NUM_IDENTIFICATIVO = ACT.ACT_NUM_ACTIVO_CAIXA AND ACT.BORRADO = 0
                  JOIN '|| V_ESQUEMA ||'.ACT_ACTIVO_CAIXA CBX ON ACT.ACT_ID = CBX.ACT_ID AND CBX.BORRADO = 0
                  WHERE NVL(APR.PROMO_COMERCIAL,-1) <> NVL(CBX.CBX_UNIDAD_ECONOMICA,-1)
                  ) AUX
                  ON (CBX.CBX_ID = AUX.CBX_ID)
                  WHEN MATCHED THEN
                     UPDATE SET CBX.CBX_UNIDAD_ECONOMICA = AUX.CBX_UNIDAD_ECONOMICA
                     , CBX.USUARIOMODIFICAR = ''STOCK_BC''
                     , CBX.FECHAMODIFICAR = SYSDATE';
                     
      EXECUTE IMMEDIATE V_MSQL;

      SALIDA := SALIDA || '   [INFO]      SE INFORMAN UNIDADES ECÓNOMICAS PARA '|| SQL%ROWCOUNT|| CHR(10);

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ERR_NUM := SQLCODE;
      ERR_MSG := SQLERRM;
      SALIDA := SALIDA || CHR(10) ||'    [ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM);
      SALIDA := SALIDA || CHR(10) ||'    '||ERR_MSG;
      ROLLBACK;
      RAISE;
END SP_BCR_11_AGRUPACIONES;
/
EXIT;
