
--/*
--##########################################
--## AUTOR=JORGE ROS
--## FECHA_CREACION=20161201
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=0
--## PRODUCTO=NO
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    seq_count number(3); -- Vble. para validar la existencia de las Secuencias.
    table_count number(3); -- Vble. para validar la existencia de las Tablas.
    v_column_count number(3); -- Vble. para validar la existencia de las Columnas.    
    v_constraint_count number(3); -- Vble. para validar la existencia de las Constraints.
    err_num NUMBER; -- N?mero de errores
    err_msg VARCHAR2(2048); -- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas
    V_MSQL VARCHAR2(4000 CHAR); 

    CUENTA NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_PROPUESTAS_PRECIO' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO...');
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_PROPUESTAS_PRECIO';  
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO... borrada OK');
  END IF;

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_PROPUESTAS_PRECIO' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO...');
    EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_PROPUESTAS_PRECIO';  
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATING VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO...');
  EXECUTE IMMEDIATE 'CREATE VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_PROPUESTAS_PRECIO 
	AS
		SELECT
		  	PRP.PRP_ID,
			PRP.PRP_NUM_PROPUESTA,
			PRP.PRP_NOMBRE_PROPUESTA,
			PRP.PRP_FECHA_EMISION,
			PRP.PRP_FECHA_ENVIO,
			PRP.PRP_FECHA_SANCION,
			PRP.PRP_FECHA_CARGA,
			PRP.PRP_OBSERVACIONES,
			TBJ.TBJ_ID,
			TBJ.TBJ_NUM_TRABAJO,
			CRA.DD_CRA_CODIGO AS ENTIDAD_CODIGO,
			CRA.DD_CRA_DESCRIPCION AS ENTIDAD_DESCRIPCION,
			EPP.DD_EPP_CODIGO AS ESTADO_CODIGO,
			EPP.DD_EPP_DESCRIPCION AS ESTADO_DESCRIPCION,
      		TRA.TRA_ID,
      		TPO.DD_TPO_ID,
      		TPO.DD_TPO_DESCRIPCION,
			TPP.DD_TPP_CODIGO AS TIPO_CODIGO,
			TPP.DD_TPP_DESCRIPCION AS TIPO_DESCRIPCION,
			NVL2(GESTOR.USU_APELLIDO1, NVL2(GESTOR.USU_APELLIDO2,INITCAP(GESTOR.USU_APELLIDO1) || '' '' || INITCAP(GESTOR.USU_APELLIDO2) || '', '', INITCAP(GESTOR.USU_APELLIDO1) || '', ''), '''') || INITCAP(GESTOR.USU_NOMBRE) AS GESTOR_PRECIOS,
			(SELECT ADT_ID FROM 
				(SELECT ADT.ADT_ID, ADT.TBJ_ID FROM ACT_ADT_ADJUNTO_TRABAJO ADT 
					LEFT JOIN DD_TPD_TIPO_DOCUMENTO TPD ON TPD.DD_TPD_ID=ADT.DD_TPD_ID
					WHERE TPD.DD_TPD_CODIGO IN (''21'',''22'',''23'')
					ORDER BY TPD.DD_TPD_CODIGO DESC, ADT.ADT_FECHA_DOCUMENTO DESC) ADJUNTO
			WHERE ADJUNTO.TBJ_ID = TBJ.TBJ_ID AND ROWNUM = 1
			) AS ADJ_ID
			
		FROM '|| V_ESQUEMA ||'.PRP_PROPUESTAS_PRECIOS PRP
		INNER JOIN '|| V_ESQUEMA ||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = PRP.DD_CRA_ID
		LEFT JOIN '|| V_ESQUEMA ||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = PRP.TBJ_ID
    	LEFT JOIN '|| V_ESQUEMA ||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID=TBJ.TBJ_ID
    	LEFT JOIN '|| V_ESQUEMA ||'.DD_TPO_TIPO_PROCEDIMIENTO TPO ON TPO.DD_TPO_ID=TRA.DD_TPO_ID
		LEFT JOIN '|| V_ESQUEMA_MASTER ||'.USU_USUARIOS GESTOR ON GESTOR.USU_ID = PRP.USU_ID
		LEFT JOIN '|| V_ESQUEMA ||'.DD_EPP_ESTADO_PROP_PRECIO EPP ON EPP.DD_EPP_ID = PRP.DD_EPP_ID
		LEFT JOIN '|| V_ESQUEMA ||'.DD_TPP_TIPO_PROP_PRECIO TPP ON TPP.DD_TPP_ID = PRP.DD_TPP_ID';

  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_PROPUESTAS_PRECIO...Creada OK');
  
END;
/

EXIT;