--/*
--##########################################
--## AUTOR=DAP
--## FECHA_CREACION=20180417
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=2.0.16
--## INCIDENCIA_LINK=REMVIP-518
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

create or replace PROCEDURE #ESQUEMA#.CARGA_TASACIONES 
    (TAS_ID IN #ESQUEMA#.ACT_TAS_TASACION.TAS_ID%TYPE
    , ACT_ID IN #ESQUEMA#.ACT_TAS_TASACION.ACT_ID%TYPE
	, DD_TTS_ID IN #ESQUEMA#.ACT_TAS_TASACION.DD_TTS_ID%TYPE
	, TAS_FECHA_INI_TASACION IN #ESQUEMA#.ACT_TAS_TASACION.TAS_FECHA_INI_TASACION%TYPE
	, TAS_FECHA_RECEPCION_TASACION IN #ESQUEMA#.ACT_TAS_TASACION.TAS_FECHA_RECEPCION_TASACION%TYPE
	, TAS_CODIGO_FIRMA IN #ESQUEMA#.ACT_TAS_TASACION.TAS_CODIGO_FIRMA%TYPE
	, TAS_NOMBRE_TASADOR IN #ESQUEMA#.ACT_TAS_TASACION.TAS_NOMBRE_TASADOR%TYPE
	, TAS_IMPORTE_TAS_FIN IN #ESQUEMA#.ACT_TAS_TASACION.TAS_IMPORTE_TAS_FIN%TYPE
	, TAS_COSTE_REPO_NETO_ACTUAL IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_REPO_NETO_ACTUAL%TYPE
	, TAS_COSTE_REPO_NETO_FINALIZADO IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_REPO_NETO_FINALIZADO%TYPE
	, TAS_COEF_MERCADO_ESTADO IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COEF_MERCADO_ESTADO%TYPE
	, TAS_COEF_POND_VALOR_ANYADIDO IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COEF_POND_VALOR_ANYADIDO%TYPE
	, TAS_VALOR_REPER_SUELO_CONST IN #ESQUEMA#.ACT_TAS_TASACION.TAS_VALOR_REPER_SUELO_CONST%TYPE
	, TAS_COSTE_CONST_CONST IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_CONST_CONST%TYPE
	, TAS_INDICE_DEPRE_FISICA IN #ESQUEMA#.ACT_TAS_TASACION.TAS_INDICE_DEPRE_FISICA%TYPE
	, TAS_INDICE_DEPRE_FUNCIONAL IN #ESQUEMA#.ACT_TAS_TASACION.TAS_INDICE_DEPRE_FUNCIONAL%TYPE
	, TAS_INDICE_TOTAL_DEPRE IN #ESQUEMA#.ACT_TAS_TASACION.TAS_INDICE_TOTAL_DEPRE%TYPE
	, TAS_COSTE_CONST_DEPRE IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_CONST_DEPRE%TYPE
	, TAS_COSTE_UNI_REPO_NETO IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_UNI_REPO_NETO%TYPE
	, TAS_COSTE_REPOSICION IN #ESQUEMA#.ACT_TAS_TASACION.TAS_COSTE_REPOSICION%TYPE
	, TAS_PORCENTAJE_OBRA IN #ESQUEMA#.ACT_TAS_TASACION.TAS_PORCENTAJE_OBRA%TYPE
	, TAS_IMPORTE_VALOR_TER IN #ESQUEMA#.ACT_TAS_TASACION.TAS_IMPORTE_VALOR_TER%TYPE
	, TAS_ID_TEXTO_ASOCIADO IN #ESQUEMA#.ACT_TAS_TASACION.TAS_ID_TEXTO_ASOCIADO%TYPE
	, TAS_IMPORTE_VAL_LEGAL_FINCA IN #ESQUEMA#.ACT_TAS_TASACION.TAS_IMPORTE_VAL_LEGAL_FINCA%TYPE
	, TAS_IMPORTE_VAL_SOLAR IN #ESQUEMA#.ACT_TAS_TASACION.TAS_IMPORTE_VAL_SOLAR%TYPE
	, TAS_OBSERVACIONES IN #ESQUEMA#.ACT_TAS_TASACION.TAS_OBSERVACIONES%TYPE
    , PL_OUTPUT OUT VARCHAR2)
    AUTHID CURRENT_USER IS

   V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar        
   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
   ERR_NUM NUMBER(25); -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
   V_USUARIO VARCHAR2 (50 CHAR) := 'EXT_CARGA_TAS';
   V_COUNT NUMBER(1);
   V_RESULTADO VARCHAR2(50 CHAR);

BEGIN

    PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INICIO]';
    
    IF TAS_ID IS NOT NULL THEN
        V_MSQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.ACT_TAS_TASACION WHERE TAS_ID = '||TAS_ID;
        EXECUTE IMMEDIATE V_MSQL INTO V_COUNT;
    END IF;
    
    IF V_COUNT = 0 AND TAS_ID IS NOT NULL THEN
        PL_OUTPUT := PL_OUTPUT || CHR(10) ||'  [INFO] No existe la tasación que se quiere actualizar.';
    ELSIF TAS_ID IS NULL THEN
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.BIE_VALORACIONES (BIE_VAL_ID, BIE_ID, BIE_IMPORTE_VALOR_TASACION, USUARIOCREAR 
                ,FECHACREAR)
            SELECT '||V_ESQUEMA||'.S_BIE_VALORACIONES.NEXTVAL, ACT.BIE_ID, 0, '''||V_USUARIO||''', SYSDATE
            FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
            WHERE ACT.ACT_ID = '||ACT_ID;
        EXECUTE IMMEDIATE V_MSQL;
        PL_OUTPUT := PL_OUTPUT || CHR(10) ||'  [INFO] Insertada '||SQL%ROWCOUNT||' fila en BIE_VALORACIONES';
        
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.ACT_TAS_TASACION (TAS_ID, ACT_ID, DD_TTS_ID, BIE_VAL_ID, TAS_FECHA_INI_TASACION
                , TAS_FECHA_RECEPCION_TASACION, TAS_CODIGO_FIRMA, TAS_NOMBRE_TASADOR, TAS_IMPORTE_TAS_FIN
                , TAS_COSTE_REPO_NETO_ACTUAL, TAS_COSTE_REPO_NETO_FINALIZADO, TAS_COEF_MERCADO_ESTADO
                , TAS_COEF_POND_VALOR_ANYADIDO, TAS_VALOR_REPER_SUELO_CONST, TAS_COSTE_CONST_CONST
                , TAS_INDICE_DEPRE_FISICA, TAS_INDICE_DEPRE_FUNCIONAL, TAS_INDICE_TOTAL_DEPRE
                , TAS_COSTE_CONST_DEPRE, TAS_COSTE_UNI_REPO_NETO, TAS_COSTE_REPOSICION, TAS_PORCENTAJE_OBRA
                , TAS_IMPORTE_VALOR_TER, TAS_ID_TEXTO_ASOCIADO, TAS_IMPORTE_VAL_LEGAL_FINCA, TAS_IMPORTE_VAL_SOLAR
                , TAS_OBSERVACIONES, USUARIOCREAR, FECHACREAR)
            SELECT '||V_ESQUEMA||'.S_ACT_TAS_TASACION.NEXTVAL TAS_ID
                , '||ACT_ID||' ACT_ID
                , '||DD_TTS_ID||' DD_TTS_ID
                , VAL.BIE_VAL_ID
                , CASE WHEN '''||TAS_FECHA_INI_TASACION||''' IS NULL THEN NULL ELSE TO_DATE('''||TAS_FECHA_INI_TASACION||''', ''DD/MM/RR'') END TAS_FECHA_INI_TASACION
                , CASE WHEN '''||TAS_FECHA_RECEPCION_TASACION||''' IS NULL THEN NULL ELSE TO_DATE('''||TAS_FECHA_RECEPCION_TASACION||''',''DD/MM/RR'') END TAS_FECHA_RECEPCION_TASACION
                , '||TAS_CODIGO_FIRMA||' TAS_CODIGO_FIRMA
                , '''||TAS_NOMBRE_TASADOR||''' TAS_NOMBRE_TASADOR
                , '||TAS_IMPORTE_TAS_FIN||' TAS_IMPORTE_TAS_FIN
                , '||TAS_COSTE_REPO_NETO_ACTUAL||' TAS_COSTE_REPO_NETO_ACTUAL
                , '||TAS_COSTE_REPO_NETO_FINALIZADO||' TAS_COSTE_REPO_NETO_FINALIZADO
                , '||TAS_COEF_MERCADO_ESTADO||' TAS_COEF_MERCADO_ESTADO
                , '||TAS_COEF_POND_VALOR_ANYADIDO||' TAS_COEF_POND_VALOR_ANYADIDO
                , '||TAS_VALOR_REPER_SUELO_CONST||' TAS_VALOR_REPER_SUELO_CONST
                , '||TAS_COSTE_CONST_CONST||' TAS_COSTE_CONST_CONST
                , '||TAS_INDICE_DEPRE_FISICA||' TAS_INDICE_DEPRE_FISICA
                , '||TAS_INDICE_DEPRE_FUNCIONAL||' TAS_INDICE_DEPRE_FUNCIONAL
                , '||TAS_INDICE_TOTAL_DEPRE||' TAS_INDICE_TOTAL_DEPRE
                , '||TAS_COSTE_CONST_DEPRE||' TAS_COSTE_CONST_DEPRE
                , '||TAS_COSTE_UNI_REPO_NETO||' TAS_COSTE_UNI_REPO_NETO
                , '||TAS_COSTE_REPOSICION||' TAS_COSTE_REPOSICION
                , '||TAS_PORCENTAJE_OBRA||' TAS_PORCENTAJE_OBRA
                , '||TAS_IMPORTE_VALOR_TER||' TAS_IMPORTE_VALOR_TER
                , '||TAS_ID_TEXTO_ASOCIADO||' TAS_ID_TEXTO_ASOCIADO
                , '||TAS_IMPORTE_VAL_LEGAL_FINCA||' TAS_IMPORTE_VAL_LEGAL_FINCA
                , '||TAS_IMPORTE_VAL_SOLAR||' TAS_IMPORTE_VAL_SOLAR
                , '''||TAS_OBSERVACIONES||''' TAS_OBSERVACIONES
                , '''||V_USUARIO||''' USUARIOCREAR
                , SYSDATE FECHACREAR
            FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
            JOIN '||V_ESQUEMA||'.BIE_VALORACIONES VAL ON VAL.BIE_ID = ACT.BIE_ID
            LEFT JOIN '||V_ESQUEMA||'.ACT_TAS_TASACION TAS ON TAS.BIE_VAL_ID = VAL.BIE_VAL_ID
            WHERE ACT.ACT_ID = '||ACT_ID||' AND TAS.TAS_ID IS NULL';
        EXECUTE IMMEDIATE V_MSQL;
        
        IF SQL%ROWCOUNT = 0 THEN
            PL_OUTPUT := PL_OUTPUT || CHR(10) ||'  [ERROR] No existe el activo para el cual se está intentando insertar una tasación';
        ELSIF SQL%ROWCOUNT = 1 THEN
            PL_OUTPUT := PL_OUTPUT || CHR(10) ||'  [INFO] Insertada '||SQL%ROWCOUNT||' fila en ACT_TAS_TASACION';
        ELSE
            PL_OUTPUT := PL_OUTPUT || CHR(10) ||'  [ERROR] Insertadas más de una fila en ACT_TAS_TASACION';
        END IF;
    ELSIF V_COUNT = 1 AND TAS_ID IS NOT NULL THEN
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_TAS_TASACION T1
            USING (
                SELECT '||TAS_ID||' TAS_ID
                    , '||ACT_ID||' ACT_ID
                    , '||DD_TTS_ID||' DD_TTS_ID
                    , CASE WHEN '''||TAS_FECHA_INI_TASACION||''' IS NULL THEN NULL ELSE TO_DATE('''||TAS_FECHA_INI_TASACION||''', ''DD/MM/RR'') END TAS_FECHA_INI_TASACION
                    , CASE WHEN '''||TAS_FECHA_RECEPCION_TASACION||''' IS NULL THEN NULL ELSE TO_DATE('''||TAS_FECHA_RECEPCION_TASACION||''',''DD/MM/RR'') END TAS_FECHA_RECEPCION_TASACION
                    , '||TAS_CODIGO_FIRMA||' TAS_CODIGO_FIRMA
                    , '''||TAS_NOMBRE_TASADOR||''' TAS_NOMBRE_TASADOR
                    , '''||TAS_IMPORTE_TAS_FIN||''' TAS_IMPORTE_TAS_FIN
                    , '''||TAS_COSTE_REPO_NETO_ACTUAL||''' TAS_COSTE_REPO_NETO_ACTUAL
                    , '''||TAS_COSTE_REPO_NETO_FINALIZADO||''' TAS_COSTE_REPO_NETO_FINALIZADO
                    , '''||TAS_COEF_MERCADO_ESTADO||''' TAS_COEF_MERCADO_ESTADO
                    , '''||TAS_COEF_POND_VALOR_ANYADIDO||''' TAS_COEF_POND_VALOR_ANYADIDO
                    , '''||TAS_VALOR_REPER_SUELO_CONST||''' TAS_VALOR_REPER_SUELO_CONST
                    , '''||TAS_COSTE_CONST_CONST||''' TAS_COSTE_CONST_CONST
                    , '''||TAS_INDICE_DEPRE_FISICA||''' TAS_INDICE_DEPRE_FISICA
                    , '''||TAS_INDICE_DEPRE_FUNCIONAL||''' TAS_INDICE_DEPRE_FUNCIONAL
                    , '''||TAS_INDICE_TOTAL_DEPRE||''' TAS_INDICE_TOTAL_DEPRE
                    , '''||TAS_COSTE_CONST_DEPRE||''' TAS_COSTE_CONST_DEPRE
                    , '''||TAS_COSTE_UNI_REPO_NETO||''' TAS_COSTE_UNI_REPO_NETO
                    , '''||TAS_COSTE_REPOSICION||''' TAS_COSTE_REPOSICION
                    , '''||TAS_PORCENTAJE_OBRA||''' TAS_PORCENTAJE_OBRA
                    , '''||TAS_IMPORTE_VALOR_TER||''' TAS_IMPORTE_VALOR_TER
                    , '''||TAS_ID_TEXTO_ASOCIADO||''' TAS_ID_TEXTO_ASOCIADO
                    , '''||TAS_IMPORTE_VAL_LEGAL_FINCA||''' TAS_IMPORTE_VAL_LEGAL_FINCA
                    , '''||TAS_IMPORTE_VAL_SOLAR||''' TAS_IMPORTE_VAL_SOLAR
                    , '''||TAS_OBSERVACIONES||''' TAS_OBSERVACIONES
                FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
                JOIN '||V_ESQUEMA||'.BIE_VALORACIONES VAL ON VAL.BIE_ID = ACT.BIE_ID
                JOIN '||V_ESQUEMA||'.ACT_TAS_TASACION TAS ON TAS.BIE_VAL_ID = VAL.BIE_VAL_ID
                WHERE ACT.ACT_ID = '||ACT_ID||' AND TAS.TAS_ID = '||TAS_ID||') T2
            ON (T1.TAS_ID = T2.TAS_ID)
            WHEN MATCHED THEN UPDATE SET
                T1.DD_TTS_ID = T2.DD_TTS_ID, T1.TAS_FECHA_INI_TASACION = T2.TAS_FECHA_INI_TASACION
                , T1.TAS_FECHA_RECEPCION_TASACION = T2.TAS_FECHA_RECEPCION_TASACION, T1.TAS_CODIGO_FIRMA = T2.TAS_CODIGO_FIRMA
                , T1.TAS_NOMBRE_TASADOR = T2.TAS_NOMBRE_TASADOR, T1.TAS_IMPORTE_TAS_FIN = T2.TAS_IMPORTE_TAS_FIN
                , T1.TAS_COSTE_REPO_NETO_ACTUAL = T2.TAS_COSTE_REPO_NETO_ACTUAL, T1.TAS_COSTE_REPO_NETO_FINALIZADO = T2.TAS_COSTE_REPO_NETO_FINALIZADO
                , T1.TAS_COEF_MERCADO_ESTADO = T2.TAS_COEF_MERCADO_ESTADO, T1.TAS_COEF_POND_VALOR_ANYADIDO = T2.TAS_COEF_POND_VALOR_ANYADIDO
                , T1.TAS_VALOR_REPER_SUELO_CONST = T2.TAS_VALOR_REPER_SUELO_CONST, T1.TAS_COSTE_CONST_CONST = T2.TAS_COSTE_CONST_CONST
                , T1.TAS_INDICE_DEPRE_FISICA = T2.TAS_INDICE_DEPRE_FISICA, T1.TAS_INDICE_DEPRE_FUNCIONAL = T2.TAS_INDICE_DEPRE_FUNCIONAL
                , T1.TAS_INDICE_TOTAL_DEPRE = T2.TAS_INDICE_TOTAL_DEPRE, T1.TAS_COSTE_CONST_DEPRE = T2.TAS_COSTE_CONST_DEPRE
                , T1.TAS_COSTE_UNI_REPO_NETO = T2.TAS_COSTE_UNI_REPO_NETO, T1.TAS_COSTE_REPOSICION = T2.TAS_COSTE_REPOSICION
                , T1.TAS_PORCENTAJE_OBRA = T2.TAS_PORCENTAJE_OBRA, T1.TAS_IMPORTE_VALOR_TER = T2.TAS_IMPORTE_VALOR_TER
                , T1.TAS_ID_TEXTO_ASOCIADO = T2.TAS_ID_TEXTO_ASOCIADO, T1.TAS_IMPORTE_VAL_LEGAL_FINCA = T2.TAS_IMPORTE_VAL_LEGAL_FINCA
                , T1.TAS_IMPORTE_VAL_SOLAR = T2.TAS_IMPORTE_VAL_SOLAR, T1.TAS_OBSERVACIONES = T2.TAS_OBSERVACIONES, T1.VERSION = T1.VERSION + 1
                , T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE
            WHERE T2.TAS_ID IS NOT NULL';
        EXECUTE IMMEDIATE V_MSQL;
        PL_OUTPUT := PL_OUTPUT || CHR(10) ||' [INFO] Actualizada '||SQL%ROWCOUNT||' fila en ACT_TAS_TASACION';
    END IF;
    
    COMMIT;
    PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[FIN]';
    
EXCEPTION
   WHEN OTHERS THEN
      ERR_NUM := SQLCODE;
      ERR_MSG := SQLERRM;
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    [ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM);
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    '||ERR_MSG;
      ROLLBACK;
      RAISE;
END CARGA_TASACIONES;
/
EXIT;