ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION
 DROP CONSTRAINT FK_BIE_ADJ_RMO;

ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION
RENAME COLUMN DD_RMO_ID TO DD_FAV_ID;

ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION
 ADD CONSTRAINT BIE_ADJ_FAV_FK 
 FOREIGN KEY (DD_FAV_ID) 
 REFERENCES BANKMASTER.DD_FAV_FAVORABLE (DD_FAV_ID);
