# TEMPLATE
# Reemplazar los valores entre corchetes

#ESQUEMA es donde se va a gestionar la tabla de registro de ejecución

export VARIABLES_SUSTITUCION='#ESQUEMA#;CM01,#ESQUEMA_MASTER#;CMMASTER,#ESQUEMA_DWH#;RECOVERY_CM_DWH,#ESQUEMA_DATASTAGE#;RECOVERY_CM_DATASTAGE,#AUTOR#;[NOMBRE_APELLIDOS],#TABLESPACE_INDEX#;IRECOVERYONL8M,#TABLESPACE_INDEX_BI#;IRECOVERYDWH8M,#ESQUEMA02#;CM01,#TABLESPACE_INDEX_M#;IRECOVERYONL8M'

export MD='RECOVERY_MD'
export DWH='RECOVERY_CM_DWH'
export DS='RECOVERY_CM_DATASTAGE'

export GENERATE_BAT='false'

export UNIFIED_PACKAGE='true'
