DELETE FROM ${master.schema}.BATCH_STEP_EXECUTION_CONTEXT ;
DELETE FROM ${master.schema}.BATCH_STEP_EXECUTION ;
DELETE FROM ${master.schema}.BATCH_JOB_EXECUTION ;
DELETE FROM ${master.schema}.BATCH_JOB_PARAMS ;
DELETE FROM ${master.schema}.BATCH_JOB_INSTANCE ;