OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_BORRADO_GASTOS_REMVIP_642
TRUNCATE
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
	GASTO	INTEGER EXTERNAL NULLIF(GASTO=BLANKS)	"TO_NUMBER(SUBSTR(REPLACE(REPLACE(REPLACE(TRIM(:GASTO),';',' '), '\"',''),'''',''),1,16))"
)