OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET AL32UTF8
INTO TABLE REM01.AUX_REMVIP_8880_2
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(	
	PROVEEDOR						NULLIF(PROVEEDOR=BLANKS)					"TRIM(:PROVEEDOR)",
	COD_PROVEEDOR						NULLIF(COD_PROVEEDOR=BLANKS)					"TRIM(:COD_PROVEEDOR)",
	PROVINCIA						NULLIF(PROVINCIA=BLANKS)					"TRIM(:PROVINCIA)"
)

