--/*
--##########################################
--## AUTOR=SIMEON SHOPOV
--## FECHA_CREACION=201803
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=2.0.17
--## INCIDENCIA_LINK=REMVIP-643
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

CREATE OR REPLACE PROCEDURE #ESQUEMA#.UPDATE_ECO
   (  ECO_NUM_EXPEDIENTE IN NUMBER
	, DD_EEC_ID IN NUMBER
	, ECO_FECHA_VENTA IN VARCHAR2
	, ECO_FECHA_CONT_PROPIETARIO IN VARCHAR2
	, ECO_BLOQUEADO IN NUMBER
	, PL_OUTPUT OUT VARCHAR2
   )
   
   AS

   V_SQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar        
   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
   ERR_NUM NUMBER(25); -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
   DESCRIPCION VARCHAR2(64 CHAR);

BEGIN

	IF DD_EEC_ID IS NOT NULL THEN
		EXECUTE IMMEDIATE 'SELECT DD_EEC_DESCRIPCION FROM '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL WHERE DD_EEC_ID = '||DD_EEC_ID INTO DESCRIPCION;
		V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET DD_EEC_ID = '||DD_EEC_ID||' WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
		EXECUTE IMMEDIATE V_SQL;
		PL_OUTPUT := '[INFO] actualizado el estado del expediente  '||ECO_NUM_EXPEDIENTE||' a '||DESCRIPCION;
	END IF;
	

	IF ECO_FECHA_VENTA IS NULL THEN
		V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET ECO_FECHA_VENTA = NULL WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
		EXECUTE IMMEDIATE V_SQL;
		PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INFO] Borrada la fecha de venta del expediente  '||ECO_NUM_EXPEDIENTE;
	ELSE
		V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET ECO_FECHA_VENTA = TO_DATE('''||ECO_FECHA_VENTA||''', ''DD/MM/YYYY'') WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
		EXECUTE IMMEDIATE V_SQL;
		PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INFO] actualizada la fecha de venta del expediente  '||ECO_NUM_EXPEDIENTE||' a '||ECO_FECHA_VENTA;
	END IF;

	IF ECO_FECHA_CONT_PROPIETARIO IS NULL THEN
		V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET ECO_FECHA_CONT_PROPIETARIO = NULL WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
		EXECUTE IMMEDIATE V_SQL;
		PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INFO] Borrada la fecha de ingreso cheque del expediente  '||ECO_NUM_EXPEDIENTE;
	ELSE
		V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET ECO_FECHA_CONT_PROPIETARIO = TO_DATE('''||ECO_FECHA_CONT_PROPIETARIO||''', ''DD/MM/YYYY'') WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
		EXECUTE IMMEDIATE V_SQL;
		PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INFO] actualizada la fecha de ingreso cheque del expediente  '||ECO_NUM_EXPEDIENTE||' a '||ECO_FECHA_CONT_PROPIETARIO;
	END IF;
	
	V_SQL := 'UPDATE '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL SET ECO_BLOQUEADO = '||ECO_BLOQUEADO||' WHERE ECO_NUM_EXPEDIENTE = '||ECO_NUM_EXPEDIENTE;
	EXECUTE IMMEDIATE V_SQL;
	PL_OUTPUT := PL_OUTPUT || CHR(10) ||'[INFO] actualizado el indicador de bloqueado del expediente  '||ECO_NUM_EXPEDIENTE||' a '||ECO_BLOQUEADO;


COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ERR_NUM := SQLCODE;
      ERR_MSG := SQLERRM;
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    [ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM);
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    '||ERR_MSG;
      ROLLBACK;
      RAISE;
END UPDATE_ECO;
/
EXIT;
