--/*
--##########################################
--## AUTOR=Carles Molins
--## FECHA_CREACION=20181128
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-2629
--## PRODUCTO=NO
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    
    err_num NUMBER; 							-- N?mero de errores
    err_msg VARCHAR2(2048); 					-- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; 	-- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; 		-- Configuracion Esquemas
    V_MSQL VARCHAR2(32000 CHAR); 

    CUENTA NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_COND_PUBLICACION' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF CUENTA>0 THEN
		DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION...');
		EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.V_COND_PUBLICACION';  
		DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION... borrada OK');
  END IF;

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_COND_PUBLICACION' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF CUENTA>0 THEN
		DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION...');
		EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.V_COND_PUBLICACION';  
		DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATING VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION...');
  V_MSQL := 'CREATE OR REPLACE VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION AS
    SELECT DISTINCT ACT.ACT_ID,
    CASE WHEN TCO.DD_TCO_CODIGO = ''01'' OR TCO.DD_TCO_CODIGO = ''02'' OR TCO.DD_TCO_CODIGO = ''04'' THEN
            CASE WHEN ACT.ACT_ADMISION = 1 AND ACT.ACT_GESTION = 1 AND V_COND.SIN_INFORME_APROBADO_REM = 0 AND (TPC.DD_TPC_ID IS NOT NULL OR ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 1) THEN 1
                 WHEN ACT.ACT_ADMISION = 0 AND ACT.ACT_GESTION = 0 AND V_COND.SIN_INFORME_APROBADO_REM = 1 AND (TPC.DD_TPC_ID IS NULL AND ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 0) THEN 0
                 ELSE 2
            END
    END AS COND_PUBL_VENTA,
    CASE WHEN TCO.DD_TCO_CODIGO = ''02'' OR TCO.DD_TCO_CODIGO = ''03'' OR TCO.DD_TCO_CODIGO = ''04'' THEN
            CASE TPA.DD_TPA_CODIGO WHEN ''02'' THEN
                CASE WHEN ACT.ACT_ADMISION = 1 AND ACT.ACT_GESTION = 1 AND V_COND.SIN_INFORME_APROBADO_REM = 0 AND (ADA.DD_ADA_CODIGO = ''01'' OR ADA.DD_ADA_CODIGO = ''03'')
                          AND TPD.DD_TPD_CODIGO = ''11'' AND (TPC.DD_TPC_ID IS NOT NULL OR ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 1)
                     THEN 1
                     WHEN ACT.ACT_ADMISION = 0 AND ACT.ACT_GESTION = 0 AND V_COND.SIN_INFORME_APROBADO_REM = 1 AND (ADA.DD_ADA_CODIGO <> ''01'' AND ADA.DD_ADA_CODIGO <> ''03'')
                          AND TPD.DD_TPD_CODIGO <> ''11'' AND (TPC.DD_TPC_ID IS NOT NULL OR ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 0)
                     THEN 0
                     ELSE 2
                END
            ELSE
                CASE WHEN ACT.ACT_ADMISION = 1 AND ACT.ACT_GESTION = 1 AND V_COND.SIN_INFORME_APROBADO_REM = 0 AND (ADA.DD_ADA_CODIGO = ''01'' OR ADA.DD_ADA_CODIGO = ''03'')
                          AND (TPC.DD_TPC_ID IS NOT NULL OR ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 1)
                     THEN 1
                     WHEN ACT.ACT_ADMISION = 0 AND ACT.ACT_GESTION = 0 AND V_COND.SIN_INFORME_APROBADO_REM = 1 AND (ADA.DD_ADA_CODIGO <> ''01'' AND ADA.DD_ADA_CODIGO <> ''03'')
                          AND (TPC.DD_TPC_ID IS NOT NULL OR ACT_APU.APU_CHECK_PUB_SIN_PRECIO_V = 0)
                     THEN 0
                     ELSE 2
                END
            END
    END AS COND_PUBL_ALQUILER
    FROM '|| V_ESQUEMA ||'.ACT_ACTIVO ACT
    INNER JOIN '|| V_ESQUEMA ||'.ACT_APU_ACTIVO_PUBLICACION 		ACT_APU ON ACT_APU.ACT_ID = ACT.ACT_ID 		 AND ACT_APU.BORRADO = 0
    INNER JOIN '|| V_ESQUEMA ||'.DD_TCO_TIPO_COMERCIALIZACION 	TCO 	ON TCO.DD_TCO_ID = ACT_APU.DD_TCO_ID AND TCO.BORRADO = 0
    INNER JOIN '|| V_ESQUEMA ||'.V_COND_DISPONIBILIDAD          V_COND  ON ACT.ACT_ID = V_COND.ACT_ID        AND V_COND.BORRADO = 0
    INNER JOIN '|| V_ESQUEMA ||'.ACT_VAL_VALORACIONES           VAL     ON VAL.ACT_ID = ACT.ACT_ID           AND VAL.BORRADO = 0
    INNER JOIN '|| V_ESQUEMA ||'.DD_TPC_TIPO_PRECIO             TPC     ON VAL.DD_TPC_ID = TPC.DD_TPC_ID     AND (TPC.DD_TPC_CODIGO = ''02'' OR TPC.DD_TPC_CODIGO = ''03'')
    LEFT JOIN '|| V_ESQUEMA ||'.ACT_ADO_ADMISION_DOCUMENTO      ADO     ON ACT.ACT_ID = ADO.ACT_ID           AND ADO.BORRADO = 0
    LEFT JOIN '|| V_ESQUEMA ||'.ACT_CFD_CONFIG_DOCUMENTO        CFD     ON CFD.CFD_ID = ADO.CFD_ID           AND CFD.BORRADO = 0
    LEFT JOIN '|| V_ESQUEMA ||'.DD_TPD_TIPO_DOCUMENTO           TPD     ON TPD.DD_TPD_ID = CFD.DD_TPD_ID     AND TPD.BORRADO = 0
    LEFT JOIN '|| V_ESQUEMA ||'.ACT_PTA_PATRIMONIO_ACTIVO       PTA     ON PTA.ACT_ID = ACT.ACT_ID           AND PTA.BORRADO = 0
    INNER JOIN '|| V_ESQUEMA ||'.DD_ADA_ADECUACION_ALQUILER     ADA     ON PTA.DD_ADA_ID = ADA.DD_ADA_ID     AND ADA.BORRADO = 0
	INNER JOIN '|| V_ESQUEMA ||'.DD_TPA_TIPO_ACTIVO             TPA     ON TPA.DD_TPA_ID = ACT.DD_TPA_ID     AND TPA.BORRADO = 0
	';

    EXECUTE IMMEDIATE V_MSQL;
    DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_COND_PUBLICACION...Creada OK');
  
END;
/
EXIT;

