--/*
--##########################################
--## AUTOR=JOSE VILLEL
--## FECHA_CREACION=20160510
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.1
--## INCIDENCIA_LINK=0
--## PRODUCTO=NO
--## Finalidad: DDL VISTA PARA LAS SUBDIVISIONES DE AGRUPACION
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    seq_count number(3); -- Vble. para validar la existencia de las Secuencias.
    table_count number(3); -- Vble. para validar la existencia de las Tablas.
    v_column_count number(3); -- Vble. para validar la existencia de las Columnas.    
    v_constraint_count number(3); -- Vble. para validar la existencia de las Constraints.
    err_num NUMBER; -- N?mero de errores
    err_msg VARCHAR2(2048); -- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas
    V_MSQL VARCHAR2(4000 CHAR);
    CUENTA NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_SUBDIVISIONES_AGRUPACION' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION...');
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.V_SUBDIVISIONES_AGRUPACION';  
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION... borrada OK');
  END IF;

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_SUBDIVISIONES_AGRUPACION' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION...');
    EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.V_SUBDIVISIONES_AGRUPACION';  
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION...');
  EXECUTE IMMEDIATE 'CREATE VIEW ' || V_ESQUEMA || '.V_SUBDIVISIONES_AGRUPACION 

	AS
		SELECT 
			ACT_SD.ID, 
			AGA.AGR_ID, 
			ACT_SD.DESCRIPCION,
			NVL(ACT_SD.DORMITORIOS,0) DORMITORIOS,
			NVL(ACT_SD.PLANTAS,0) PLANTAS,
			COUNT(*) AS NUM_ACTIVOS FROM(
							SELECT SUBD.ID, SUBD.ACT_ID,
							CASE TPA.DD_TPA_CODIGO
								WHEN ''02''	THEN TPA.DD_TPA_DESCRIPCION || '' - '' || 
								SAC.DD_SAC_DESCRIPCION || 
								NVL2(SUBD.PLANTAS,'' - '' || SUBD.PLANTAS ||'' PLANTA'' || DECODE(SUBD.PLANTAS,1,'''',''S''),NULL) || 
								NVL2(SUBD.DORMITORIOS,'' - '' || SUBD.DORMITORIOS ||'' DORMITORIO''|| DECODE(SUBD.DORMITORIOS,1,'''',''S'')  ,NULL) ||
								NVL2(SUBD.BANYOS, '' - '' || SUBD.BANYOS || '' BAÑO'' || DECODE (SUBD.BANYOS, 1, '''', ''S''), NULL)
  								ELSE TPA.DD_TPA_DESCRIPCION || '' - '' || SAC.DD_SAC_DESCRIPCION
							END DESCRIPCION,
              SUBD.DORMITORIOS,
              SUBD.BANYOS,
              SUBD.PLANTAS
							FROM (
									SELECT ACT.ACT_ID, ACT.DD_TPA_ID, ACT.DD_SAC_ID, NVL(VIV.VIV_NUM_PLANTAS_INTERIOR,0) PLANTAS, SUM (DECODE (DIS.DD_TPH_ID, 1, DIS.DIS_CANTIDAD, NULL)) DORMITORIOS, 
									SUM (DECODE (DIS.DD_TPH_ID, 2, DIS.DIS_CANTIDAD, NULL)) BANYOS,
									ORA_HASH(ACT.DD_TPA_ID||ACT.DD_SAC_ID||NVL(VIV.VIV_NUM_PLANTAS_INTERIOR,0)||NVL(SUM(DECODE (DIS.DD_TPH_ID, 1, DIS.DIS_CANTIDAD, NULL)),0) || NVL (SUM (DECODE (DIS.DD_TPH_ID, 2, DIS.DIS_CANTIDAD, NULL)), 0)) ID
									FROM ' || V_ESQUEMA || '.ACT_ICO_INFO_COMERCIAL ICO 
									JOIN ' || V_ESQUEMA || '.ACT_ACTIVO ACT ON ACT.ACT_ID = ICO.ACT_ID
									LEFT JOIN ' || V_ESQUEMA || '.ACT_VIV_VIVIENDA VIV ON VIV.ICO_ID = ICO.ICO_ID
									LEFT JOIN ' || V_ESQUEMA || '.ACT_DIS_DISTRIBUCION DIS ON DIS.ICO_ID = VIV.ICO_ID AND DIS.BORRADO = 0
									where act.borrado = 0
									GROUP BY ACT.ACT_ID, ACT.DD_TPA_ID, ACT.DD_SAC_ID, NVL(VIV.VIV_NUM_PLANTAS_INTERIOR,0)
							) SUBD
							JOIN ' || V_ESQUEMA || '.DD_TPA_TIPO_ACTIVO TPA ON TPA.DD_TPA_ID = SUBD.DD_TPA_ID
							JOIN ' || V_ESQUEMA || '.DD_SAC_SUBTIPO_ACTIVO SAC ON SAC.DD_SAC_ID = SUBD.DD_SAC_ID
			) ACT_SD
		JOIN ' || V_ESQUEMA || '.ACT_AGA_AGRUPACION_ACTIVO AGA ON AGA.ACT_ID = ACT_SD.ACT_ID
		GROUP BY ACT_SD.ID, AGA.AGR_ID, ACT_SD.DESCRIPCION,NVL(ACT_SD.DORMITORIOS,0), NVL(ACT_SD.PLANTAS,0), NVL (ACT_SD.BANYOS, 0)';

  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_SUBDIVISIONES_AGRUPACION...Creada OK');
  
END;
/

EXIT;  
