--/*
--#########################################
--## AUTOR=Pier Gotta 
--## FECHA_CREACION=20180724
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-1351
--## PRODUCTO=NO
--## 
--## Finalidad:  Creación del SP SP_EXT_ACTUALIZA_PROVEEDOR_ENV
--##            
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1-Pier Gotta-Versión inicial (20180720)
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

create or replace PROCEDURE SP_EXT_ACTUALIZA_PROVEEDOR_ENV (
	PVE_COD_IDENTIF IN #ESQUEMA#.ACT_PVE_PROVEEDOR.PVE_DOCIDENTIF%TYPE,
	ENVIADO IN NUMBER,
	COD_RETORNO OUT NUMBER
)
AS

	V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; 	-- '#ESQUEMA#'; -- Configuracion Esquema
	V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; 	-- '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	err_num NUMBER; 								-- Numero de errores
	err_msg VARCHAR2(2048);
	V_NUM NUMBER(16);
	V_COUNT NUMBER(16) := 0;	
	V_MSQL VARCHAR2(4000 CHAR);
	
	V_SEC VARCHAR2(30 CHAR) := '';
	V_TABLA_HLP VARCHAR2(30 CHAR) := 'HLP_HISTORICO_LANZA_PERIODICO';
	V_TABLA_HLD VARCHAR2(30 CHAR) := 'HLD_HISTORICO_LANZA_PER_DETA';
	V_TABLA_PVE VARCHAR2(30 CHAR) := 'ACT_PVE_PROVEEDOR';
BEGIN
	--v0.1
	 DBMS_OUTPUT.PUT_LINE('[INICIO] Inicio del proceso');
	 	 
	 IF ENVIADO = 1 THEN

		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_HLD||' (
			HLD_SP_CARGA,
			HLD_FECHA_EJEC,	
			HLD_CODIGO_REG,
			HLD_TABLA_MODIFICAR,	
			HLD_TABLA_MODIFICAR_CLAVE,	
			HLD_TABLA_MODIFICAR_CLAVE_ID,	
			HLD_CAMPO_MODIFICAR,	
			HLD_VALOR_ORIGINAL,	
			HLD_VALOR_ACTUALIZADO
		 )
		 SELECT ''SP_EXT_ACTUALIZA_PROVEEDOR_ENV'',
		 SYSDATE,
		 PVE.PVE_ID,
		 '''||V_TABLA_PVE||''',
		 ''PVE_ID'',
		 PVE.PVE_ID,
		 ''PVE_ENVIADO'',
		 PVE.PVE_ENVIADO,
		 SYSDATE
		 FROM '||V_ESQUEMA||'.'||V_TABLA_PVE||' PVE WHERE PVE.PVE_DOCIDENTIF = '''||PVE_COD_IDENTIF||''' AND PVE.BORRADO = 0
		 ';
		 EXECUTE IMMEDIATE V_MSQL;
		 V_MSQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_PVE||' PVE 
				SET PVE.PVE_ENVIADO = SYSDATE, USUARIOMODIFICAR = ''REMVIP-1351'', FECHAMODIFICAR = SYSDATE 
				WHERE PVE.PVE_DOCIDENTIF = '''||PVE_COD_IDENTIF||''' AND PVE.BORRADO = 0';
		 EXECUTE IMMEDIATE V_MSQL;
		 
		 V_COUNT := SQL%ROWCOUNT;
	 
	 
	 ELSE 
		IF ENVIADO = 0 THEN

		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_HLD||' (
			HLD_SP_CARGA,
			HLD_FECHA_EJEC,	
			HLD_CODIGO_REG,
			HLD_TABLA_MODIFICAR,	
			HLD_TABLA_MODIFICAR_CLAVE,	
			HLD_TABLA_MODIFICAR_CLAVE_ID,	
			HLD_CAMPO_MODIFICAR,	
			HLD_VALOR_ORIGINAL,	
			HLD_VALOR_ACTUALIZADO
		 )
		 SELECT ''SP_EXT_ACTUALIZA_PROVEEDOR_ENV'',
		 SYSDATE,
		 PVE.PVE_ID,
		 '''||V_TABLA_PVE||''',
		 ''PVE_ID'',
		 PVE.PVE_ID,
		 ''PVE_ENVIADO'',
		 PVE.PVE_ENVIADO,
		 NULL
		 FROM '||V_ESQUEMA||'.'||V_TABLA_PVE||' PVE WHERE PVE.PVE_DOCIDENTIF = '''||PVE_COD_IDENTIF||''' AND PVE.BORRADO = 0
		 ';
		 EXECUTE IMMEDIATE V_MSQL;
		 
		 V_MSQL := 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_PVE||' PVE 
				SET PVE.PVE_ENVIADO = null, USUARIOMODIFICAR = ''REMVIP-1351'', FECHAMODIFICAR = SYSDATE 
				WHERE PVE.PVE_DOCIDENTIF = '''||PVE_COD_IDENTIF||''' AND PVE.BORRADO = 0';
		 EXECUTE IMMEDIATE V_MSQL;
		 
		 V_COUNT := SQL%ROWCOUNT;
	
		END IF;
	END IF;
	 
	 
	V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_HLP||' (
		HLP_SP_CARGA,
		HLP_FECHA_EJEC,
		HLP_RESULTADO_EJEC,
		HLP_CODIGO_REG,
		HLP_REGISTRO_EJEC
	)VALUES(
	''SP_EXT_ACTUALIZA_PROVEEDOR_ENV'',
	 SYSDATE,
	 0,
	 '''||PVE_COD_IDENTIF||''',
	 '||to_char(V_COUNT)||'
	 )';
	  EXECUTE IMMEDIATE V_MSQL;
	  
	  COD_RETORNO := 0;
COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(SQLCODE));
    DBMS_OUTPUT.put_line('-----------------------------------------------------------');
    DBMS_OUTPUT.put_line(SQLERRM);
    ROLLBACK;
    
    V_MSQL := 'SELECT COUNT(1) FROM ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_HLP||'''';
    EXECUTE IMMEDIATE V_MSQL INTO V_COUNT;
    
    IF V_COUNT > 0 THEN
		
		V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.'||V_TABLA_HLP||' (
			HLP_SP_CARGA,
			HLP_FECHA_EJEC,
			HLP_RESULTADO_EJEC,
			HLP_CODIGO_REG,
			HLP_REGISTRO_EJEC
		)VALUES(
		''SP_EXT_ACTUALIZA_PROVEEDOR_ENV'',
		 SYSDATE,
		 1,
		 '''||PVE_COD_IDENTIF||''',
		 '''||SQLERRM||'''
		 )';
		  EXECUTE IMMEDIATE V_MSQL;
		  
		COMMIT;
	END IF;
    COD_RETORNO := 1;
    RAISE;

END SP_EXT_ACTUALIZA_PROVEEDOR_ENV;
/
EXIT
