--/*
--##########################################
--## AUTOR=DAP
--## FECHA_CREACION=20180315
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=2.0.16
--## INCIDENCIA_LINK=REMVIP-312
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

create or replace PROCEDURE #ESQUEMA#.ANULACION_OFERTA_CAMBIO_SCM (V_USUARIO IN #ESQUEMA#.ACT_ACTIVO.USUARIOMODIFICAR%TYPE, V_NUM_OFERTA IN VARCHAR2, V_SCM_CODIGO IN #ESQUEMA#.DD_SCM_SITUACION_COMERCIAL.DD_SCM_CODIGO%TYPE DEFAULT NULL) AUTHID CURRENT_USER IS

   V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar        
   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
   ERR_NUM NUMBER(25); -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
   /*V_NUM_OFERTA  es la oferta a anular
   V_NUM_ACTIVO es el activo a cambiar el estado de su situación comercial
   V_SCM_CODIGO es la situación comercial*/

BEGIN

  DBMS_OUTPUT.PUT_LINE('[INICIO]');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.OFR_OFERTAS T1
    USING (SELECT DISTINCT OFR.OFR_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.OFR_ID = T2.OFR_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.DD_EOF_ID = (SELECT DD_EOF_ID FROM '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA WHERE DD_EOF_CODIGO = ''02'')
        , T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' ofertas anuladas');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL T1
    USING (SELECT DISTINCT ECO.ECO_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.ECO_ID = T2.ECO_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.DD_EEC_ID = (SELECT DD_EEC_ID FROM '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL WHERE DD_EEC_CODIGO = ''02'')
        , T1.ECO_FECHA_ANULACION = SYSDATE, T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' expedientes anulados');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_TBJ_TRABAJO T1
    USING (SELECT DISTINCT TBJ.TBJ_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.TBJ_ID = T2.TBJ_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.DD_EST_ID = (SELECT DD_EST_ID FROM '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO WHERE DD_EST_CODIGO = ''02'')
        , T1.TBJ_FECHA_FIN = SYSDATE, T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' trabajos anulados');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_TRA_TRAMITE T1
    USING (SELECT DISTINCT TRA.TRA_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.TRA_ID = T2.TRA_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.DD_EPR_ID = (SELECT DD_EPR_ID FROM '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO WHERE DD_EPR_CODIGO = ''05'')
        , T1.TRA_FECHA_FIN = SYSDATE, T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' trámites cerrados');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES T1
    USING (SELECT TAR.TAR_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.TAR_ID = T2.TAR_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.TAR_FECHA_FIN = SYSDATE, T1.TAR_TAREA_FINALIZADA = 1, T1.BORRADO = 1
        , T1.USUARIOBORRAR = '''||V_USUARIO||''', T1.FECHABORRAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' tareas finalizadas');

  V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TEX_TAREA_EXTERNA T1
    USING (SELECT TEX.TEX_ID
        FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
        JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.OFR_ID = OFR.OFR_ID
        JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TBJ ON TBJ.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TBJ_ID = ECO.TBJ_ID
        JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON TAC.TRA_ID = TRA.TRA_ID
        JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
        JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX ON TEX.TAR_ID = TAR.TAR_ID
        JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_ID = OFR.DD_EOF_ID
        JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_ID = ECO.DD_EEC_ID
        JOIN '||V_ESQUEMA||'.DD_EST_ESTADO_TRABAJO EST ON EST.DD_EST_ID = TBJ.DD_EST_ID
        JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
        WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND (EOF.DD_EOF_CODIGO <> ''02'' OR EEC.DD_EEC_CODIGO <> ''02''
            OR EST.DD_EST_CODIGO <> ''02'' OR EPR.DD_EPR_CODIGO <> ''05'' OR ECO.ECO_FECHA_ANULACION IS NULL
            OR TBJ.TBJ_FECHA_FIN IS NULL OR TRA.TRA_FECHA_FIN IS NULL OR TAR.TAR_FECHA_FIN IS NULL
            OR TAR.BORRADO = 0 OR NVL(TAR.TAR_TAREA_FINALIZADA,0) = 0 OR TEX.BORRADO = 0)) T2
    ON (T1.TEX_ID = T2.TEX_ID)
    WHEN MATCHED THEN UPDATE SET
        T1.BORRADO = 1, T1.USUARIOBORRAR = '''||V_USUARIO||''', T1.FECHABORRAR = SYSDATE';
  EXECUTE IMMEDIATE V_MSQL;
    
    IF V_SCM_CODIGO IS NOT NULL THEN 
      V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_ACTIVO T1
            USING (SELECT ACT.ACT_ID
                FROM '||V_ESQUEMA||'.OFR_OFERTAS OFR
                JOIN '||V_ESQUEMA||'.ACT_OFR AO ON AO.OFR_ID = OFR.OFR_ID
                JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = AO.ACT_ID AND ACT.BORRADO = 0
                JOIN '||V_ESQUEMA||'.DD_SCM_SITUACION_COMERCIAL SCM ON SCM.DD_SCM_ID = ACT.DD_SCM_ID
                WHERE OFR.OFR_NUM_OFERTA IN ('||V_NUM_OFERTA||') AND SCM.DD_SCM_CODIGO <> '''||V_SCM_CODIGO||'''
                  AND OFR.BORRADO = 0) T2
            ON (T1.ACT_ID = T2.ACT_ID)
            WHEN MATCHED THEN UPDATE SET
                T1.DD_SCM_ID = (SELECT DD_SCM_ID FROM '||V_ESQUEMA||'.DD_SCM_SITUACION_COMERCIAL WHERE DD_SCM_CODIGO = '''||V_SCM_CODIGO||''')
                , T1.USUARIOMODIFICAR = '''||V_USUARIO||''', T1.FECHAMODIFICAR = SYSDATE';
        EXECUTE IMMEDIATE V_MSQL;
        DBMS_OUTPUT.PUT_LINE('  [INFO] '||SQL%ROWCOUNT||' situación comercial actualizadas');
    END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
   WHEN OTHERS THEN
      ERR_NUM := SQLCODE;
      ERR_MSG := SQLERRM;
      DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
      DBMS_OUTPUT.PUT_LINE(ERR_MSG);
      ROLLBACK;
      RAISE;
END ANULACION_OFERTA_CAMBIO_SCM;
/
EXIT;