  --/*
--##########################################
--## AUTOR=JORGE ROS
--## FECHA_CREACION=20161027
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=HREOS-1075
--## PRODUCTO=NO
--## Finalidad: DDL
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    seq_count number(3); -- Vble. para validar la existencia de las Secuencias.
    table_count number(3); -- Vble. para validar la existencia de las Tablas.
    v_column_count number(3); -- Vble. para validar la existencia de las Columnas.    
    v_constraint_count number(3); -- Vble. para validar la existencia de las Constraints.
    err_num NUMBER; -- N?mero de errores
    err_msg VARCHAR2(2048); -- Mensaje de error
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas
    V_MSQL VARCHAR2(4000 CHAR); 

    CUENTA NUMBER;
    
BEGIN

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_TRAMITES_ACTIVO' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='MATERIALIZED VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO...');
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_TRAMITES_ACTIVO';  
    DBMS_OUTPUT.PUT_LINE('DROP MATERIALIZED VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO... borrada OK');
  END IF;

  SELECT COUNT(*) INTO CUENTA FROM ALL_OBJECTS WHERE OBJECT_NAME = 'V_BUSQUEDA_TRAMITES_ACTIVO' AND OWNER=V_ESQUEMA AND OBJECT_TYPE='VIEW';  
  IF CUENTA>0 THEN
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO...');
    EXECUTE IMMEDIATE 'DROP VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_TRAMITES_ACTIVO';  
    DBMS_OUTPUT.PUT_LINE('DROP VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO... borrada OK');
  END IF;

  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO...');
  EXECUTE IMMEDIATE 'CREATE VIEW ' || V_ESQUEMA || '.V_BUSQUEDA_TRAMITES_ACTIVO 
		
	AS	
		SELECT
			TRAMITES.TRA_ID,
			TRA.DD_TPO_ID AS TIPO_TRAMITE_ID,
			TPO.DD_TPO_CODIGO AS TIPO_TRAMITE_CODIGO,
			TPO.DD_TPO_DESCRIPCION AS TIPO_TRAMITE_DESCRIPCION,
			TRA.TRA_TRA_ID AS TRAMITE_PADRE_ID,
			TRAMITES.ACT_ID,
			(SELECT ACT_NUM_ACTIVO FROM ACT_ACTIVO ACT WHERE ACT.ACT_ID = TRAMITES.ACT_ID) AS NUM_ACTIVO,
			TPO.DD_TPO_DESCRIPCION AS NOMBRE,
			EPR.DD_EPR_CODIGO AS ESTADO_CODIGO,
			EPR.DD_EPR_DESCRIPCION AS ESTADO_DESCRIPCION,
			DD.DD_STR_CODIGO AS SUBTIPO_TBJ_CODIGO,
			DD.DD_STR_DESCRIPCION AS SUBTIPO_TBJ_DESCRIPCION,
			TRA.TRA_FECHA_INICIO AS FECHA_INICIO,
			TRA.TRA_FECHA_FIN AS FECHA_FIN
			
	    FROM '|| V_ESQUEMA ||'.ACT_TRA_TRAMITE TRA
			LEFT JOIN '|| V_ESQUEMA ||'.DD_TPO_TIPO_PROCEDIMIENTO TPO ON TRA.DD_TPO_ID = TPO.DD_TPO_ID
			LEFT JOIN '|| V_ESQUEMA_MASTER ||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_ID = TRA.DD_EPR_ID
			LEFT JOIN 
				(SELECT TBJ.TBJ_ID, DD_STR_CODIGO, DD_STR_DESCRIPCION 
						FROM '|| V_ESQUEMA ||'.DD_STR_SUBTIPO_TRABAJO STR 
						LEFT JOIN '|| V_ESQUEMA ||'.ACT_TBJ_TRABAJO TBJ ON TBJ.DD_STR_ID=STR.DD_STR_ID
				) DD ON DD.TBJ_ID=TRA.TBJ_ID
			INNER JOIN 
			(
				SELECT TRA_ID,ACT_ID FROM '|| V_ESQUEMA ||'.ACT_TRA_TRAMITE 
				UNION
				SELECT TRA.TRA_ID,TBJ.ACT_ID FROM '|| V_ESQUEMA ||'.ACT_TRA_TRAMITE TRA
					LEFT JOIN '|| V_ESQUEMA ||'.ACT_TBJ TBJ ON TRA.TBJ_ID=TBJ.TBJ_ID
					WHERE TBJ.ACT_ID IS NOT NULL
			) TRAMITES ON TRAMITES.TRA_ID = TRA.TRA_ID
';

      	
  DBMS_OUTPUT.PUT_LINE('CREATE VIEW '|| V_ESQUEMA ||'.V_BUSQUEDA_TRAMITES_ACTIVO...Creada OK');
  
END;
/

EXIT;