#!/bin/bash
export NOMBRE_SCRIPT=DML_001_BANK01_DD_RULE_DEFINITION.sql
export ESQUEMA_EJECUCION=BANK01
export VARIABLES_SUSTITUCION='#ESQUEMA#;BANK01,#ESQUEMA_MASTER#;BANKMASTER'
export AUTOR='LUIS RUIZ'
export ARTEFACTO=batch
export VERSION_ARTEFACTO=2.10.13
export FECHA_CREACION=20150514
export INCIDENCIA_LINK=BCFI613
export PRODUCTO=SI
