INSERT INTO GEE_GESTOR_ENTIDAD (GEE_ID,USU_ID,DD_TGE_ID,VERSION,USUARIOCREAR,FECHACREAR,BORRADO)
VALUES (S_GEE_GESTOR_ENTIDAD.NEXTVAL, (SELECT USU_ID FROM BANKMASTER.USU_USUARIOS WHERE USU_USERNAME = 'AGE3'),
(SELECT DD_TGE_ID FROM BANKMASTER.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = 'SAGER'),0,'DD',SYSDATE,0);

INSERT INTO GEE_GESTOR_ENTIDAD (GEE_ID,USU_ID,DD_TGE_ID,VERSION,USUARIOCREAR,FECHACREAR,BORRADO)
VALUES (S_GEE_GESTOR_ENTIDAD.NEXTVAL, (SELECT USU_ID FROM BANKMASTER.USU_USUARIOS WHERE USU_USERNAME = 'AGE2'),
(SELECT DD_TGE_ID FROM BANKMASTER.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = 'GAGER'),0,'DD',SYSDATE,0);

INSERT INTO GEE_GESTOR_ENTIDAD (GEE_ID,USU_ID,DD_TGE_ID,VERSION,USUARIOCREAR,FECHACREAR,BORRADO)
VALUES (S_GEE_GESTOR_ENTIDAD.NEXTVAL, (SELECT USU_ID FROM BANKMASTER.USU_USUARIOS WHERE USU_USERNAME = 'AGE1'),
(SELECT DD_TGE_ID FROM BANKMASTER.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = 'GAGER'),0,'DD',SYSDATE,0);


Insert into GAE_GESTOR_ADD_EXPEDIENTE
   (GEE_ID, EXP_ID)
 Values
   ((select gee_id from gee_gestor_entidad gee inner join
		bankmaster.dd_tge_tipo_gestor tge on tge.dd_tge_id = gee.dd_tge_id
		where TGE.DD_TGE_CODIGO = 'SAGER' and rownum=1)	, 378133);

   COMMIT;
