--/*
--#########################################
--## AUTOR=IVAN REPISO
--## FECHA_CREACION=20220721
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-11706
--## PRODUCTO=NO
--## 
--## Finalidad: 
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
	
	V_TABLA_TMP VARCHAR2(50 CHAR) := 'AUX_REMVIP_11706'; -- Variable para tabla 	
	V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01';-- '#ESQUEMA#'; -- Configuracion Esquema
	V_ESQUEMA_M VARCHAR2(25 CHAR):= 'REMMASTER';-- '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
	ERR_NUM NUMBER;-- Numero de errores
	ERR_MSG VARCHAR2(2048);-- Mensaje de error
	V_MSQL VARCHAR2(4000 CHAR);--Variable para consultar la existencia de registros en la tabla
	V_SQL VARCHAR2(4000 CHAR);--Sentencia a ejecutar
	V_NUM NUMBER(16); --Variable para comprobar si existen registros
	PL_OUTPUT VARCHAR2(32000 CHAR);
	V_USUARIO VARCHAR2(50 CHAR) := 'REMVIP-11706';
	V_NUM_ACTIVO VARCHAR2(32000 CHAR);
	

BEGIN

	DBMS_OUTPUT.PUT_LINE('[INICIO]'||CHR(10));

	EXECUTE IMMEDIATE 'UPDATE '||V_ESQUEMA||'.'||V_TABLA_TMP||' SET ESTADO = NULL WHERE ESTADO = 0';
	 
	COMMIT;			

	EXECUTE IMMEDIATE 'MERGE INTO '||V_ESQUEMA||'.'||V_TABLA_TMP||' T1 USING (
						SELECT DISTINCT AUX.ID_HAYA, PTA.DD_EAL_ID
						FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
						INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_TMP||' AUX ON ACT.ACT_NUM_ACTIVO = AUX.ID_HAYA 
						INNER JOIN '||V_ESQUEMA||'.ACT_PTA_PATRIMONIO_ACTIVO PTA ON ACT.ACT_ID = PTA.ACT_ID AND PTA.BORRADO = 0
						WHERE ACT.BORRADO = 0) T2
						ON (T1.ID_HAYA = T2.ID_HAYA)
						WHEN MATCHED THEN UPDATE SET
						T1.ESTADO_BACKUP = T2.DD_EAL_ID';
	 
	COMMIT;	
	
	EXECUTE IMMEDIATE 'MERGE INTO '||V_ESQUEMA||'.ACT_PTA_PATRIMONIO_ACTIVO T1 USING (
						SELECT DISTINCT PTA.ACT_PTA_ID, AUX.ESTADO
						FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
						INNER JOIN '||V_ESQUEMA||'.'||V_TABLA_TMP||' AUX ON ACT.ACT_NUM_ACTIVO = AUX.ID_HAYA 
						INNER JOIN '||V_ESQUEMA||'.ACT_PTA_PATRIMONIO_ACTIVO PTA ON ACT.ACT_ID = PTA.ACT_ID AND PTA.BORRADO = 0
						WHERE ACT.BORRADO = 0) T2
						ON (T1.ACT_PTA_ID = T2.ACT_PTA_ID)
						WHEN MATCHED THEN UPDATE SET
						T1.DD_EAL_ID = T2.ESTADO, 
						T1.USUARIOMODIFICAR = '''||V_USUARIO||''', 
						T1.FECHAMODIFICAR = SYSDATE ';

	DBMS_OUTPUT.PUT_LINE('[INFO] Se han modificado '||SQL%ROWCOUNT||' registros');  
	COMMIT;

	PL_OUTPUT := PL_OUTPUT || '[FIN]'||CHR(10);
	DBMS_OUTPUT.PUT_LINE(PL_OUTPUT);

EXCEPTION
    WHEN OTHERS THEN
      PL_OUTPUT := PL_OUTPUT ||'[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(SQLCODE)||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||'-----------------------------------------------------------'||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||SQLERRM||CHR(10);
      PL_OUTPUT := PL_OUTPUT ||V_SQL||CHR(10);
      DBMS_OUTPUT.PUT_LINE(PL_OUTPUT);
      ROLLBACK;
      RAISE;
END;
/
EXIT;
