prompt Cambiando los NLS_PARAMETERS a SPANISH

set linesize 300
set pagesize 50000

ALTER SYSTEM SET NLS_LANGUAGE=SPANISH SCOPE=SPFILE;
ALTER SYSTEM SET NLS_TERRITORY=SPAIN SCOPE=SPFILE;
ALTER SYSTEM SET NLS_CURRENCY='€' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_ISO_CURRENCY=SPAIN SCOPE=SPFILE;
ALTER SYSTEM SET NLS_NUMERIC_CHARACTERS=',.' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_DATE_FORMAT='DD/MM/RR' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_DATE_LANGUAGE=SPANISH SCOPE=SPFILE;
ALTER SYSTEM SET NLS_SORT=SPANISH SCOPE=SPFILE;
ALTER SYSTEM SET NLS_TIME_FORMAT='HH24:MI:SSXFF' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_TIMESTAMP_FORMAT='DD/MM/RR HH24:MI:SSXFF' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_TIME_TZ_FORMAT='HH24:MI:SSXFF TZR' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_TIMESTAMP_TZ_FORMAT='DD/MM/RR HH24:MI:SSXFF TZR' SCOPE=SPFILE;
ALTER SYSTEM SET NLS_DUAL_CURRENCY='€' SCOPE=SPFILE;

prompt Reiniciando la BD

shutdown immediate;
startup;

exit;
