DELETE FROM ACT_PAC_PERIMETRO_ACTIVO WHERE USUARIOCREAR = 'MIG2';

UPDATE REM01.ACT_ACTIVO ACT SET
    ACT.ACT_BLOQUEO_PRECIO_FECHA_INI = NULL
    ,ACT.ACT_BLOQUEO_PRECIO_USU_ID = NULL
    ,ACT.DD_TPU_ID = NULL
    ,ACT.DD_EPU_ID = NULL
    ,ACT.DD_TCO_ID = NULL
    ,ACT.ACT_FECHA_IND_PRECIAR = NULL
    ,ACT.ACT_FECHA_IND_REPRECIAR = NULL
    ,ACT.ACT_FECHA_IND_DESCUENTO = NULL
    ,ACT.USUARIOMODIFICAR = NULL
    ,ACT.FECHAMODIFICAR = NULL
WHERE ACT.USUARIOMODIFICAR = 'MIG2'
;

DELETE FROM ACT_OFR;

DELETE FROM CLC_CLIENTE_COMERCIAL WHERE USUARIOCREAR = 'MIG2';

COMMIT;
