DECLARE
    -- Vble. para validar la existencia de las Tablas.
    table_count number(3);
    -- Querys
    query_body varchar (30048);
BEGIN

 	select count(1) into table_count from all_tables WHERE table_name='DATA_RULE_ENGINE_ANTERIOR';
	if table_count = 1 then
 		query_body := 'DROP TABLE BANK01.DATA_RULE_ENGINE_ANTERIOR';  EXECUTE IMMEDIATE query_body;
	end if;

	query_body := 'CREATE TABLE BANK01.DATA_RULE_ENGINE_ANTERIOR 
	AS SELECT * from BANK01.DATA_RULE_ENGINE WHERE rownum < 1'; EXECUTE IMMEDIATE query_body;

	select count(1) into table_count from all_tables WHERE table_name='TMP_REC_DATA_RULE_ENGINE';
	if table_count = 1 then
 		query_body := 'DROP TABLE BANK01.TMP_REC_DATA_RULE_ENGINE';  EXECUTE IMMEDIATE query_body;
	end if;
	
	query_body := 'CREATE table BANK01.tmp_rec_data_rule_engine 
	   AS
	  SELECT "PER_ID", "PER_RIESGO", "PER_RIESGO_AUTORIZADO", "PER_RIESGO_IND", "PER_RIESGO_DIR_VENCIDO",
	  "PER_SEXO", "PER_EMPLEADO", "DD_COS_ID", "DD_PNV_ID", "PER_TITULAR", "PER_RIESGO_DISPUESTO",
	  "PER_NACIONALIDAD", "PER_ECV", "DD_SCE_ID", "ANT_REINCIDENCIA_INTERNOS", "DD_TPE_ID",
	  "PER_PAIS_NACIMIENTO", "DD_POL_ID", "PER_FECHA_NACIMIENTO", "SERV_NOMINA_PENSION", "DD_REX_ID",
	  "PER_FECHA_CONSTITUCION", "OFI_ID", "MOV_INT_MORATORIOS", "DD_APO_ID", 
	  "DD_GC1_ID", "CNT_FECHA_ESC", "CNT_FECHA_CONSTITUCION", "DIAS_IRREGULAR", "MOV_DEUDA_IRREGULAR",
	  "MOV_SALDO_DUDOSO", "MOV_PROVISION", "MOV_PROVISION_PORCENTAJE", "MOV_RIESGO_GARANT", "CNT_FECHA_EFC_ANT",
	  "MOV_LTV_INI", "CNT_FECHA_EFC", "MOV_COMISIONES", "MOV_DISPUESTO", "DD_FNO_ID", "DD_EFC_ID", "DD_MON_ID",
	  "DD_CT1_ID", "CNT_DOMICI_EXT", "DD_ESC_ID", "DD_ECE_ID", "MOV_LTV_FIN", "CNT_LIMITE_INI", "MOV_SALDO_PASIVO",
	  "MOV_FECHA_POS_VENCIDA", "MOV_LIMITE_DESC", "CNT_FECHA_VENC", "CNT_FECHA_CREACION", "MOV_SALDO_EXCE",
	  "CNT_LIMITE_FIN", "DD_EFC_ID_ANT", "MOV_GASTOS", "CENTRONIVEL0", "CENTRONIVEL1", "CENTRONIVEL2", "CENTRONIVEL3",
	  "CENTRONIVEL4", "CENTRONIVEL5", "CENTRONIVEL6", "CENTRONIVEL7", "CENTRONIVEL8", "CENTRONIVEL9", 
	  "CENTRONIVELPER0", "CENTRONIVELPER1", "CENTRONIVELPER2", "CENTRONIVELPER3", "CENTRONIVELPER4", "CENTRONIVELPER5", 
	  "CENTRONIVELPER6", "CENTRONIVELPER7", "CENTRONIVELPER8", "CENTRONIVELPER9"
	 FROM ((select * from BANK01.data_rule_engine) minus (select * from BANK01.data_rule_engine_anterior))
	 WHERE per_id IN (SELECT DISTINCT (per_id) FROM BANK01.tmp_rec_cnt_libres)'; EXECUTE IMMEDIATE query_body;

	select count(1) into table_count from all_views WHERE view_name='TMP_REC_PER_DATA_RULE_ENGINE';
	if table_count = 1 then
 		query_body := 'DROP VIEW BANK01.TMP_REC_PER_DATA_RULE_ENGINE';  EXECUTE IMMEDIATE query_body;
	end if;
	 
	query_body := 'CREATE OR REPLACE FORCE VIEW BANK01.tmp_rec_per_data_rule_engine 
	AS
	 SELECT "PER_ID", "PER_RIESGO", "PER_RIESGO_AUTORIZADO", "PER_RIESGO_IND", "PER_RIESGO_DIR_VENCIDO",
	  "PER_SEXO", "PER_EMPLEADO", "DD_COS_ID", "DD_PNV_ID", "PER_TITULAR", "PER_RIESGO_DISPUESTO",
	  "PER_NACIONALIDAD", "PER_ECV", "DD_SCE_ID", "ANT_REINCIDENCIA_INTERNOS", "DD_TPE_ID",
	  "PER_PAIS_NACIMIENTO", "DD_POL_ID", "PER_FECHA_NACIMIENTO", "SERV_NOMINA_PENSION", "DD_REX_ID",
	  "PER_FECHA_CONSTITUCION", "OFI_ID", "MOV_INT_MORATORIOS", "DD_APO_ID", 
	  "DD_GC1_ID", "CNT_FECHA_ESC", "CNT_FECHA_CONSTITUCION", "DIAS_IRREGULAR", "MOV_DEUDA_IRREGULAR",
	  "MOV_SALDO_DUDOSO", "MOV_PROVISION", "MOV_PROVISION_PORCENTAJE", "MOV_RIESGO_GARANT", "CNT_FECHA_EFC_ANT",
	  "MOV_LTV_INI", "CNT_FECHA_EFC", "MOV_COMISIONES", "MOV_DISPUESTO", "DD_FNO_ID", "DD_EFC_ID", "DD_MON_ID",
	  "DD_CT1_ID", "CNT_DOMICI_EXT", "DD_ESC_ID", "DD_ECE_ID", "MOV_LTV_FIN", "CNT_LIMITE_INI", "MOV_SALDO_PASIVO",
	  "MOV_FECHA_POS_VENCIDA", "MOV_LIMITE_DESC", "CNT_FECHA_VENC", "CNT_FECHA_CREACION", "MOV_SALDO_EXCE",
	  "CNT_LIMITE_FIN", "DD_EFC_ID_ANT", "MOV_GASTOS", "CENTRONIVEL0", "CENTRONIVEL1", "CENTRONIVEL2", "CENTRONIVEL3",
	  "CENTRONIVEL4", "CENTRONIVEL5", "CENTRONIVEL6", "CENTRONIVEL7", "CENTRONIVEL8", "CENTRONIVEL9", 
	  "CENTRONIVELPER0", "CENTRONIVELPER1", "CENTRONIVELPER2", "CENTRONIVELPER3", "CENTRONIVELPER4", "CENTRONIVELPER5", 
	  "CENTRONIVELPER6", "CENTRONIVELPER7", "CENTRONIVELPER8", "CENTRONIVELPER9"
	FROM BANK01.data_rule_engine
	WHERE per_id IN (SELECT DISTINCT (per_id) FROM BANK01.tmp_rec_exp_desnormalizado)'; EXECUTE IMMEDIATE query_body;

END;
/
