--###########################################
--## AUTOR=Viorel Remus Ovidiu
--## FECHA_CREACION=20191030
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.3
--## INCIDENCIA_LINK=REMVIP-5603
--## PRODUCTO=NO
--## 
--## Finalidad: INSERTAR GPL-PRINEX
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--###########################################
----*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;
alter session set NLS_NUMERIC_CHARACTERS = '.,';

DECLARE
  V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
  V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01'; -- Configuracion Esquema
  V_ESQUEMA_M VARCHAR2(25 CHAR):= 'REMMASTER'; -- Configuracion Esquema Master
  V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
  V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.   
  ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
  ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
  V_USUARIO VARCHAR2(100 CHAR) := 'REMVIP-5603';
    
BEGIN	
	
    V_NUM_TABLAS := 0;
	DBMS_OUTPUT.PUT_LINE('[INICIO]');
	EXECUTE IMMEDIATE 'DELETE FROM '||V_ESQUEMA||'.GPL_GASTOS_PRINEX_LBK WHERE GPV_ID IN (SELECT GPV_ID FROM '||V_ESQUEMA||'.GPV_GASTOS_PROVEEDOR WHERE GPV_NUM_GASTO_HAYA IN (SELECT DISTINCT NUM_GASTO FROM REM01.AUX_REMVIP_5603))';
    DBMS_OUTPUT.PUT_LINE('	[INFO]: ACTUALIZAR GASTOS');


V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GPL_GASTOS_PRINEX_LBK(
GPV_ID,
ACT_ID,
GPL_PROYECTO,	 
GPL_TIPO_INMUEBLE, 
GPL_CLAVE_1,
GPL_CLAVE_2,	 
GPL_CLAVE_3,	 
GPL_CLAVE_4,	 
GPL_IMPORTE_GASTO, 	
GPL_FECHA_CONTABLE,	
GPL_DIARIO_CONTB,	 
GPL_D347,	 
GPL_DELEGACION,	 
GPL_BASE_RETENCION,	 
GPL_PROCENTAJE_RETEN,	 
GPL_IMPORTE_RENTE,	 
GPL_APLICAR_RETENCION,	 
GPL_BASE_IRPF,	 
GPL_PROCENTAJE_IRPF,	 
GPL_IMPORTE_IRPF,	 
GPL_CLAVE_IRPF,	 
GPL_SUBCLAVE_IRPF,	 
GPL_CEUTA,	 
GPL_CTA_IVAD,	 
GPL_SCTA_IVAD,	 
GPL_CONDICIONES,	 
GPL_CTA_BANCO,	 
GPL_SCTA_BANCO,	 
GPL_CTA_EFECTOS,	 
GPL_SCTA_EFECTOS, 	
GPL_APUNTE,	 
GPL_CENTRODESTINO,	 
GPL_TIPO_FRA_SII,	 
GPL_CLAVE_RE,	 
GPL_CLAVE_RE_AD1, 	
GPL_CLAVE_RE_AD2, 	
GPL_TIPO_OP_INTRA, 	
GPL_DESC_BIENES,	 
GPL_DESCRIPCION_OP,	 
GPL_SIMPLIFICADA,	 
GPL_FRA_SIMPLI_IDEN,	 
GPL_DIARIO1,	 
GPL_DIARIO1_BASE,	 
GPL_DIARIO1_TIPO,	 
GPL_DIARIO1_CUOTA,	 
GPL_DIARIO2,	 
GPL_DIARIO2_BASE,	 
GPL_DIARIO2_TIPO,	 
GPL_DIARIO2_CUOTA,	 
GPL_TIPO_PARTIDA, 	
GPL_APARTADO,	 
GPL_CAPITULO,	 
GPL_PARTIDA,	 
GPL_CTA_GASTO,	 
GPL_SCTA_GASTO,	 
GPL_REPERCUTIR,	 
GPL_CONCEPTO_FAC,	 
GPL_FECHA_FAC,	 
GPL_COD_COEF,	 
GPL_CODI_DIAR_IVA_V,	 
GPL_PCTJE_IVA_V,	
GPL_NOMBRE,	 
GPL_CARACTERISTICA, 
VERSION,
USUARIOCREAR,
FECHACREAR,
BORRADO,
GPL_ID
)
SELECT 
gpv.GPV_ID,
act.ACT_ID,
to_number(GPL_PROYECTO),	 
GPL_TIPO_INMUEBLE, 
GPL_CLAVE1,
GPL_CLAVE2,	 
GPL_CLAVE3,	 
GPL_CLAVE4,	 
to_number(GPL_IMPORTE_GASTO), 	
GPL_FECHA_CONTABLE,	
to_number(GPL_DIARIO_CONTB),	 
GPL_D347,	 
GPL_DELEGACION,	 
to_number(GPL_BASE_RETENCION),	 
to_number(GPL_PROCENTAJE_RETEN),	 
to_number(GPL_IMPORTE_RENTE),	 
GPL_APLICAR_RETENCION,	 
to_number(GPL_BASE_IRPF),	 
to_number(GPL_PROCENTAJE_IRPF),	 
to_number(GPL_IMPORTE_IRPF),	 
GPL_CLAVE_IRPF,	 
GPL_SUBCLAVE_IRPF,	 
GPL_CEUTA,	 
GPL_CTA_IVAD,	 
GPL_SCTA_IVAD,	 
GPL_CONDICIONES,	 
GPL_CTA_BANCO,	 
GPL_SCTA_BANCO,	 
GPL_CTA_EFECTOS,	 
GPL_SCTA_EFECTOS, 	
GPL_APUNTE,	 
GPL_CENTRODESTINO,	 
GPL_TIPO_FRA_SII,	 
GPL_CLAVE_RE,	 
GPL_CLAVE_RE_AD1, 	
GPL_CLAVE_RE_AD2, 	
GPL_TIPO_OP_INTRA, 	
GPL_DESC_BIENES,	 
GPL_DESCRIPCION_OP,	 
GPL_SIMPLIFICADA,	 
GPL_FRA_SIMPLI_IDEN,	 
GPL_DIARIO1,	 
to_number(GPL_DIARIO1_BASE),	 
to_number(GPL_DIARIO1_TIPO),	 
to_number(GPL_DIARIO1_CUOTA),	 
GPL_DIARIO2,	 
to_number(GPL_DIARIO2_BASE),	 
to_number(GPL_DIARIO2_TIPO),	 
to_number(GPL_DIARIO2_CUOTA),	 
GPL_TIPO_PARTIDA, 	
GPL_APARTADO,	 
GPL_CAPITULO,	 
GPL_PARTIDA,	 
GPL_CTA_GASTO,	 
GPL_SCTA_GASTO,	 
GPL_REPERCUTIR,	 
GPL_CONCEPTO_FAC,	 
GPL_FECHA_FAC,	 
GPL_COD_COEF,	 
GPL_CODI_DIAR_IVA_V,	 
to_number(GPL_PCTJE_IVA_V),	
GPL_NOMBRE,	 
GPL_CARACTERISTICA,
0,
''REMVIP-5603'',
SYSDATE,
0,
REM01.S_GPL_GASTOS_PRINEX_LBK.NEXTVAL
FROM REM01.AUX_REMVIP_5603 AUX 
JOIN REM01.ACT_ACTIVO ACT ON ACT.ACT_NUM_ACTIVO = AUX.NUM_ACTIVO 
JOIN REM01.GPV_GASTOS_PROVEEDOR GPV ON GPV.GPV_NUM_GASTO_HAYA = AUX.NUM_GASTO
'
;

    --DBMS_OUTPUT.PUT_LINE(V_MSQL);        
    EXECUTE IMMEDIATE V_MSQL;
    
    DBMS_OUTPUT.PUT_LINE('[INFO] '||SQL%ROWCOUNT||' REGISTROS INSERTADOS.');  

    DBMS_OUTPUT.PUT_LINE('[INICIO MERGE]');
    
	V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.GDE_GASTOS_DETALLE_ECONOMICO GDE
				USING (
				   SELECT * FROM (SELECT
				   GPV_ID,
				   GPL_DIARIO1,
				   GPL_DIARIO2,
				   CASE WHEN GPL_DIARIO1 = ''1'' OR GPL_DIARIO1 = ''20'' OR GPL_DIARIO1 = ''2'' THEN NVL(GPL_DIARIO1_BASE,0) ELSE 0 END AS PRINCIPAL_SUJETO,
				   CASE WHEN GPL_DIARIO1 = ''1'' OR GPL_DIARIO1 = ''20'' OR GPL_DIARIO1 = ''2'' AND GPL_DIARIO2 = ''60'' THEN NVL(GPL_DIARIO2_BASE, 0)
				       WHEN GPL_DIARIO1 = ''60'' THEN NVL(GPL_DIARIO1_BASE,0)				       
				       ELSE 0 END AS PRINCIPAL_NO_SUJETO,
				   CASE GPL_DIARIO1 WHEN ''60'' THEN 1 ELSE 0 END AS IMP_IND_EXENTO,
				   NVL(GPL_DIARIO1_TIPO, 0) AS IMP_IND_TIPO_IMPOSITIVO,
				   NVL(GPL_DIARIO1_CUOTA, 0) AS IMP_IND_CUOTA,
				   NVL(GPL_PROCENTAJE_IRPF, 0) AS IRPF_TIPO_IMPOSITIVO,
				   NVL(GPL_IMPORTE_IRPF, 0) AS IRPF_CUOTA,
				   ROW_NUMBER() OVER (PARTITION BY gpv_id ORDER BY act_id ASC) AS RN
				   FROM '||V_ESQUEMA||'.GPL_GASTOS_PRINEX_LBK WHERE GPV_ID in (SELECT GPV_ID FROM '||V_ESQUEMA||'.GPV_GASTOS_PROVEEDOR WHERE GPV_NUM_GASTO_HAYA in (SELECT DISTINCT NUM_GASTO FROM REM01.AUX_REMVIP_5603)) AND GPL_DIARIO1 IS NOT NULL AND BORRADO = 0) WHERE RN = 1) AUX ON (AUX.GPV_ID = GDE.GPV_ID)
				WHEN MATCHED THEN UPDATE SET GDE.GDE_PRINCIPAL_SUJETO = AUX.PRINCIPAL_SUJETO,
				                       GDE.GDE_PRINCIPAL_NO_SUJETO = AUX.PRINCIPAL_NO_SUJETO,
				                       GDE.DD_TIT_ID = 1,
				                       GDE.GDE_IMP_IND_EXENTO = AUX.IMP_IND_EXENTO,
				                       GDE.GDE_IMP_IND_TIPO_IMPOSITIVO = AUX.IMP_IND_TIPO_IMPOSITIVO,
				                       GDE.GDE_IMP_IND_CUOTA = AUX.IMP_IND_CUOTA,
				                       GDE.GDE_IRPF_TIPO_IMPOSITIVO = AUX.IRPF_TIPO_IMPOSITIVO,
				                       GDE.GDE_IRPF_CUOTA = AUX.IRPF_CUOTA,
				                       GDE.GDE_IMPORTE_TOTAL = (SELECT SUM(GPL_IMPORTE_GASTO) FROM '||V_ESQUEMA||'.GPL_GASTOS_PRINEX_LBK WHERE GPV_ID = AUX.GPV_ID),
				                       GDE.USUARIOMODIFICAR = ''REMVIP-5603'',
				                       GDE.FECHAMODIFICAR = SYSDATE';
				                       
	EXECUTE IMMEDIATE V_MSQL;

	DBMS_OUTPUT.PUT_LINE('	[INFO] Se han actualizado '||SQL%ROWCOUNT||' registros');

    DBMS_OUTPUT.PUT_LINE('[FIN]');

  COMMIT;

EXCEPTION

   WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SQLERRM;

        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
        DBMS_OUTPUT.put_line(err_msg);

        ROLLBACK;
        RAISE;          

END;

/

EXIT
