alter table DD_TJ_TIPO_JUICIO  ADD (DD_TPO_ID  NUMBER(16));

ALTER TABLE DD_TJ_TIPO_JUICIO ADD 
CONSTRAINT FK_DD_TJ_TIPO_JUICIO_1
 FOREIGN KEY (DD_TPO_ID)
 REFERENCES DD_TPO_TIPO_PROCEDIMIENTO (DD_TPO_ID)
 ENABLE
 VALIDATE;