
package es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_PERSONAS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsPort", targetNamespace = "http://alamo.haya.es/IntegracionSOA/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsPort {


    /**
     * 
     * @param processEventRequest
     * @return
     *     returns es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_PERSONAS.ProcessEventResponseType
     */
    @WebMethod(action = "http://alamo.haya.es/processEvent")
    @WebResult(name = "processEventResponse", targetNamespace = "http://alamo.haya.es/IntegracionSOA/schemas", partName = "processEventResponse")
    public ProcessEventResponseType processEvent(
        @WebParam(name = "processEventRequest", targetNamespace = "http://alamo.haya.es/IntegracionSOA/schemas", partName = "processEventRequest")
        ProcessEventRequestType processEventRequest);

}
