#!/bin/bash
export NOMBRE_SCRIPT=DML_001_BANKMASTER_DD_TCN_TIPO_CNAE.sql
export ESQUEMA_EJECUCION=BANK01
export VARIABLES_SUSTITUCION='#ESQUEMA#;BANK01,#ESQUEMA_MASTER#;BANKMASTER,#AUTOR#;NOMBRE APELLIDOS,#VARIABLE#;NOSABES'
export AUTOR='LUIS RUIZ'
export ARTEFACTO=batch
export VERSION_ARTEFACTO=2.10.13
export FECHA_CREACION=20150514
export INCIDENCIA_LINK=BCFI-614
export PRODUCTO=SI
