ALTER TABLE DD_INFORMES
ADD (DD_TFA_ID NUMBER(16));

ALTER TABLE DD_INFORMES
   ADD CONSTRAINT FK_DD_INFORMES_FK_TFA FOREIGN KEY (DD_TFA_ID)
      REFERENCES DD_TFA_FICHERO_ADJUNTO (DD_TFA_ID);
      
UPDATE DD_INFORMES SET DD_TFA_ID = 100;
      
ALTER TABLE DD_INFORMES
ADD (DD_INFORME_SUFIJO VARCHAR2(10 BYTE) DEFAULT '.rtf'); 

COMMIT;