SET DEFINE OFF;
Insert into DD_EPF_ESTADO_PROCES_FICH
   (DD_EPF_ID, DD_EPF_CODIGO, DD_EPF_DESCRIPCION, DD_EPF_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR, BORRADO)
 Values
   (S_DD_EPF_ESTADO_PROCES_FICH.NEXTVAL, 'RCH', 'Rechazado', 'Rechazado', 0, 'MOD_PROC', sysdate, 0);
COMMIT;

