
ALTER TABLE BANK01.DD_RMO_RESOL_MORATORIA
 DROP PRIMARY KEY CASCADE;
DROP TABLE BANK01.DD_RMO_RESOL_MORATORIA CASCADE CONSTRAINTS;

CREATE TABLE BANK01.DD_RMO_RESOL_MORATORIA
(
  DD_RMO_ID                 NUMBER(16)          NOT NULL,
  DD_RMO_CODIGO             VARCHAR2(10 CHAR)   NOT NULL,
  DD_RMO_DESCRIPCION        VARCHAR2(50 CHAR)   NOT NULL,
  DD_RMO_DESCRIPCION_LARGA  VARCHAR2(200 CHAR)  NOT NULL,
  VERSION                   INTEGER             DEFAULT 0                     NOT NULL,
  USUARIOCREAR              VARCHAR2(10 CHAR)   NOT NULL,
  FECHACREAR                TIMESTAMP(6)        NOT NULL,
  USUARIOMODIFICAR          VARCHAR2(10 CHAR),
  FECHAMODIFICAR            TIMESTAMP(6),
  USUARIOBORRAR             VARCHAR2(10 CHAR),
  FECHABORRAR               TIMESTAMP(6),
  BORRADO                   NUMBER(1)           DEFAULT 0                     NOT NULL
)
TABLESPACE BANK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK01.PK_DD_RMO_RESOL_MORATORIA ON BANK01.DD_RMO_RESOL_MORATORIA
(DD_RMO_ID)
LOGGING
TABLESPACE BANK01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK01.DD_RMO_RESOL_MORATORIA ADD (
  CONSTRAINT PK_DD_RMO_RESOL_MORATORIA
 PRIMARY KEY
 (DD_RMO_ID)
    USING INDEX 
    TABLESPACE BANK01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
INSERT INTO BANK01.DD_RMO_RESOL_MORATORIA
(
  DD_RMO_ID,
  DD_RMO_CODIGO,
  DD_RMO_DESCRIPCION,
  DD_RMO_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (1,'FAV','FAVORABLE','FAVORABLE','DGG',sysdate,0);


INSERT INTO BANK01.DD_RMO_RESOL_MORATORIA
(
  DD_RMO_ID,
  DD_RMO_CODIGO,
  DD_RMO_DESCRIPCION,
  DD_RMO_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (2,'DES','DESFAVORABLE','DESFAVORABLE','DGG',sysdate,0);

----------------------------------------------------------------

ALTER TABLE BANK01.DD_SIT_SITUACION_TITULO
 DROP PRIMARY KEY CASCADE;
DROP TABLE BANK01.DD_SIT_SITUACION_TITULO CASCADE CONSTRAINTS;

CREATE TABLE BANK01.DD_SIT_SITUACION_TITULO
(
  DD_SIT_ID                 NUMBER(16)          NOT NULL,
  DD_SIT_CODIGO             VARCHAR2(10 CHAR)   NOT NULL,
  DD_SIT_DESCRIPCION        VARCHAR2(50 CHAR)   NOT NULL,
  DD_SIT_DESCRIPCION_LARGA  VARCHAR2(200 CHAR)  NOT NULL,
  VERSION                   INTEGER             DEFAULT 0                     NOT NULL,
  USUARIOCREAR              VARCHAR2(10 CHAR)   NOT NULL,
  FECHACREAR                TIMESTAMP(6)        NOT NULL,
  USUARIOMODIFICAR          VARCHAR2(10 CHAR),
  FECHAMODIFICAR            TIMESTAMP(6),
  USUARIOBORRAR             VARCHAR2(10 CHAR),
  FECHABORRAR               TIMESTAMP(6),
  BORRADO                   NUMBER(1)           DEFAULT 0                     NOT NULL
)
TABLESPACE BANK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK01.PK_DD_SIT_SITUACION_TITULO ON BANK01.DD_SIT_SITUACION_TITULO
(DD_SIT_ID)
LOGGING
TABLESPACE BANK01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK01.DD_SIT_SITUACION_TITULO ADD (
  CONSTRAINT PK_DD_SIT_SITUACION_TITULO
 PRIMARY KEY
 (DD_SIT_ID)
    USING INDEX 
    TABLESPACE BANK01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
INSERT INTO BANK01.DD_SIT_SITUACION_TITULO
(
  DD_SIT_ID,
  DD_SIT_CODIGO,
  DD_SIT_DESCRIPCION,
  DD_SIT_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (1,'INS','INSCRITO','INSCRITO','DGG',sysdate,0);


INSERT INTO BANK01.DD_SIT_SITUACION_TITULO
(
  DD_SIT_ID,
  DD_SIT_CODIGO,
  DD_SIT_DESCRIPCION,
  DD_SIT_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (2,'PEN','PENDIENTE SUBSANACION','PENDIENTE SUBSANACION','DGG',sysdate,0);




ALTER TABLE BANK01.DD_EAD_ENTIDAD_ADJUDICA
 DROP PRIMARY KEY CASCADE;
DROP TABLE BANK01.DD_EAD_ENTIDAD_ADJUDICA CASCADE CONSTRAINTS;

CREATE TABLE BANK01.DD_EAD_ENTIDAD_ADJUDICA
(
  DD_EAD_ID                 NUMBER(16)          NOT NULL,
  DD_EAD_CODIGO             VARCHAR2(10 CHAR)   NOT NULL,
  DD_EAD_DESCRIPCION        VARCHAR2(50 CHAR)   NOT NULL,
  DD_EAD_DESCRIPCION_LARGA  VARCHAR2(200 CHAR)  NOT NULL,
  VERSION                   INTEGER             DEFAULT 0                     NOT NULL,
  USUARIOCREAR              VARCHAR2(10 CHAR)   NOT NULL,
  FECHACREAR                TIMESTAMP(6)        NOT NULL,
  USUARIOMODIFICAR          VARCHAR2(10 CHAR),
  FECHAMODIFICAR            TIMESTAMP(6),
  USUARIOBORRAR             VARCHAR2(10 CHAR),
  FECHABORRAR               TIMESTAMP(6),
  BORRADO                   NUMBER(1)           DEFAULT 0                     NOT NULL
)
TABLESPACE BANK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK01.PK_DD_EAD_ENTIDAD_ADJUDICA ON BANK01.DD_EAD_ENTIDAD_ADJUDICA
(DD_EAD_ID)
LOGGING
TABLESPACE BANK01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK01.DD_EAD_ENTIDAD_ADJUDICA ADD (
  CONSTRAINT PK_DD_EAD_ENTIDAD_ADJUDICA
 PRIMARY KEY
 (DD_EAD_ID)
    USING INDEX 
    TABLESPACE BANK01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
INSERT INTO BANK01.DD_EAD_ENTIDAD_ADJUDICA
(
  DD_EAD_ID,
  DD_EAD_CODIGO,
  DD_EAD_DESCRIPCION,
  DD_EAD_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (1,'FON','FONDO','FONDO','DGG',sysdate,0);


INSERT INTO BANK01.DD_EAD_ENTIDAD_ADJUDICA
(
  DD_EAD_ID,
  DD_EAD_CODIGO,
  DD_EAD_DESCRIPCION,
  DD_EAD_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (2,'BAN','BANKIA','BANKIA','DGG',sysdate,0);


INSERT INTO BANK01.DD_EAD_ENTIDAD_ADJUDICA
(
  DD_EAD_ID,
  DD_EAD_CODIGO,
  DD_EAD_DESCRIPCION,
  DD_EAD_DESCRIPCION_LARGA,
  USUARIOCREAR,
  FECHACREAR,
  BORRADO  
)  VALUES (3,'SAR','SAREB','SAREB','DGG',sysdate,0);


---------------------------------------------------------------------------------

DROP SEQUENCE S_BIE_ADJ_ADJUDICACION;
CREATE SEQUENCE S_BIE_ADJ_ADJUDICACION;


ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION
 DROP PRIMARY KEY CASCADE;
DROP TABLE BANK01.BIE_ADJ_ADJUDICACION CASCADE CONSTRAINTS;


CREATE TABLE BANK01.BIE_ADJ_ADJUDICACION
(
  BIE_ID                       NUMBER(16)       NOT NULL,
  BIE_ADJ_ID                   NUMBER(16)       NOT NULL, 
  BIE_ADJ_F_DECRETO_N_FIRME    DATE,
  BIE_ADJ_F_DECRETO_FIRME      DATE,
  BIE_ADJ_F_ENTREGA_GESTOR     DATE,
  BIE_ADJ_F_PRESEN_HACIENDA    DATE,
  BIE_ADJ_F_SEGUNDA_PRESEN     DATE,
  BIE_ADJ_F_RECPCION_TITULO    DATE,
  BIE_ADJ_F_INSCRIP_TITULO     DATE,
  BIE_ADJ_F_ENVIO_ADICION      DATE,
  BIE_ADJ_F_PRESENT_REGISTRO   DATE,
  BIE_ADJ_F_SOL_POSESION       DATE,
  BIE_ADJ_F_SEN_POSESION       DATE,
  BIE_ADJ_F_REA_POSESION       DATE,
  BIE_ADJ_F_SOL_LANZAMIENTO    DATE,
  BIE_ADJ_F_SEN_LANZAMIENTO    DATE,
  BIE_ADJ_F_REA_LANZAMIENTO    DATE,
  BIE_ADJ_F_SOL_MORATORIA      DATE,
  BIE_ADJ_F_RES_MORATORIA      DATE,
  BIE_ADJ_F_CONTRATO_ARREN     DATE,
  BIE_ADJ_F_CAMBIO_CERRADURA   DATE,
  BIE_ADJ_F_ENVIO_LLAVES       DATE,
  BIE_ADJ_F_RECEP_DEPOSITARIO  DATE,
  BIE_ADJ_F_ENVIO_DEPOSITARIO  DATE,
  BIE_ADJ_OCUPADO              NUMBER(1),
  BIE_ADJ_POSIBLE_POSESION     NUMBER(1),
  BIE_ADJ_OCUPANTES_DILIGENCIA NUMBER(1),
  BIE_ADJ_LANZAMIENTO_NECES    NUMBER(1),
  BIE_ADJ_ENTREGA_VOLUNTARIA   NUMBER(1),
  BIE_ADJ_NECESARIA_FUERA_PUB  NUMBER(1),
  BIE_ADJ_EXISTE_INQUILINO     NUMBER(1),
  BIE_ADJ_LLAVES_NECESARIAS    NUMBER(1),
  BIE_ADJ_GESTORIA_ADJUDIC     NUMBER(16),
  BIE_ADJ_NOMBRE_ARRENDATARIO  VARCHAR2(50 CHAR),
  BIE_ADJ_NOMBRE_DEPOSITARIO   VARCHAR2(50 CHAR),
  BIE_ADJ_NOMBRE_DEPOSITARIO_F VARCHAR2(50 CHAR),
  BIE_ADJ_FONDO                VARCHAR2(50 CHAR),
  DD_EAD_ID                    NUMBER(16),
  DD_SIT_ID                    NUMBER(16),
  DD_RMO_ID                    NUMBER(16),
  VERSION                      INTEGER          DEFAULT 0                     NOT NULL,
  USUARIOCREAR                 VARCHAR2(10 CHAR) NOT NULL,
  FECHACREAR                   TIMESTAMP(6)     NOT NULL,
  USUARIOMODIFICAR             VARCHAR2(10 CHAR),
  FECHAMODIFICAR               TIMESTAMP(6),
  USUARIOBORRAR                VARCHAR2(10 CHAR),
  FECHABORRAR                  TIMESTAMP(6),
  BORRADO                      NUMBER(1)        DEFAULT 0                     NOT NULL

)
TABLESPACE BANK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK01.PK_BIE_ADJ_ADJUDICACION ON BANK01.BIE_ADJ_ADJUDICACION
(BIE_ADJ_ID)
LOGGING
TABLESPACE BANK01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION ADD (
  CONSTRAINT PK_BIE_ADJ_ADJUDICACION
 PRIMARY KEY
 (BIE_ADJ_ID)
    USING INDEX 
    TABLESPACE BANK01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
 
 ALTER TABLE BANK01.BIE_ADJ_ADJUDICACION ADD (
 CONSTRAINT FK_BIE_ADJ 
 FOREIGN KEY (BIE_ID) 
 REFERENCES BANK01.BIE_BIEN (BIE_ID),
 CONSTRAINT FK_BIE_ADJ_EAD 
 FOREIGN KEY (DD_EAD_ID) 
 REFERENCES BANK01.DD_EAD_ENTIDAD_ADJUDICA (DD_EAD_ID),
 CONSTRAINT FK_BIE_ADJ_SIT 
 FOREIGN KEY (DD_SIT_ID) 
 REFERENCES BANK01.DD_SIT_SITUACION_TITULO (DD_SIT_ID),
 CONSTRAINT FK_BIE_ADJ_RMO 
 FOREIGN KEY (DD_RMO_ID) 
 REFERENCES BANK01.DD_RMO_RESOL_MORATORIA (DD_RMO_ID),
 CONSTRAINT FK_BIE_ADJ_PER 
 FOREIGN KEY (BIE_ADJ_GESTORIA_ADJUDIC) 
 REFERENCES BANK01.PER_PERSONAS (PER_ID) 
  );
  
  
  ALTER TABLE BIE_ADJ_ADJUDICACION ADD (
 
    BIE_ADJ_F_RECEP_DEPOSITARIO_F DATE
 

 );



