--/*
--##########################################
--## AUTOR=Guillermo Llidó
--## FECHA_CREACION=20180721
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-1373
--## PRODUCTO=NO
--##
--## Finalidad: 
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

   V_SQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar
   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
   ERR_NUM NUMBER(25); -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(10024 CHAR); -- Vble. auxiliar para registrar errores en el script.
   V_AUX NUMBER(10); -- Variable auxiliar
   USUARIO VARCHAR2(50 CHAR):= 'REMVIP-1373';
   USUARIO_CONSULTA_REM VARCHAR2(50 CHAR):= 'REM_QUERY';
   PL_OUTPUT VARCHAR2(32000 CHAR);

BEGIN

	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK2_ACT_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					DISABLE CONSTRAINT FK2_ACT_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK2_ACT_ID '||CHR(10);
		
	END IF;

	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_CCO_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					DISABLE CONSTRAINT FK_DD_CCO_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_CCO_ID '||CHR(10);
		
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_TBE_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					DISABLE CONSTRAINT FK_DD_TBE_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_TBE_ID '||CHR(10);
		
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_SBE_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					DISABLE CONSTRAINT FK_DD_SBE_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_SBE_ID '||CHR(10);
		
	END IF;

	V_SQL := 'SELECT COUNT(1) from SYS.ALL_TABLES WHERE TABLE_NAME = ''DD_CCO_CATEGORIA_CONTABLE'' AND OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
		
		V_SQL := 'TRUNCATE TABLE '||V_ESQUEMA||'.DD_CCO_CATEGORIA_CONTABLE';
		
		EXECUTE IMMEDIATE V_SQL;
		
		V_SQL := 'ALTER TABLE '||V_ESQUEMA||'.DD_CCO_CATEGORIA_CONTABLE MODIFY DD_CCO_CODIGO VARCHAR2(20 CHAR)' ;
		
		EXECUTE IMMEDIATE V_SQL;

	ELSE
	
		PL_OUTPUT := PL_OUTPUT ||' No existe la tabla DD_CCO_CATEGORIA_CONTABLE '||CHR(10);
	
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM SYS.ALL_TABLES WHERE TABLE_NAME = ''DD_TBE_TIPO_ACTIVO_BDE'' AND OWNER = '''||V_ESQUEMA||'''';

	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
    
        V_SQL := 'TRUNCATE TABLE '||V_ESQUEMA||'.DD_TBE_TIPO_ACTIVO_BDE';
    
        EXECUTE IMMEDIATE V_SQL;
		
		V_SQL := 'ALTER TABLE '||V_ESQUEMA||'.DD_TBE_TIPO_ACTIVO_BDE MODIFY DD_TBE_CODIGO VARCHAR2(20 CHAR)';
        
        EXECUTE IMMEDIATE V_SQL;
		
	ELSE
	
		PL_OUTPUT := PL_OUTPUT ||' No existe la tabla DD_TBE_TIPO_ACTIVO_BDE '||CHR(10);
	
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM SYS.ALL_TABLES WHERE TABLE_NAME = ''DD_SBE_SUBTIPO_ACTIVO_BDE'' AND OWNER = '''||V_ESQUEMA||'''';

	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
    
        V_SQL := 'TRUNCATE TABLE '||V_ESQUEMA||'.DD_SBE_SUBTIPO_ACTIVO_BDE';
    
        EXECUTE IMMEDIATE V_SQL;
	
		V_SQL := 'ALTER TABLE '||V_ESQUEMA||'.DD_SBE_SUBTIPO_ACTIVO_BDE MODIFY DD_SBE_CODIGO VARCHAR2(20 CHAR)';
        
        EXECUTE IMMEDIATE V_SQL;
	
	ELSE
	
		PL_OUTPUT := PL_OUTPUT ||' No existe la tabla DD_SBE_SUBTIPO_ACTIVO_BDE '||CHR(10);
	
	END IF;
	
----- REACTIVAR CONSTRAINT

V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK2_ACT_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					ENABLE CONSTRAINT FK2_ACT_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK2_ACT_ID '||CHR(10);
		
	END IF;

	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_CCO_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					ENABLE CONSTRAINT FK_DD_CCO_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_CCO_ID '||CHR(10);
		
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_TBE_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					ENABLE CONSTRAINT FK_DD_TBE_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_TBE_ID '||CHR(10);
		
	END IF;
	
	V_SQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = ''ACT_ILB_NFO_LIBERBANK'' AND CONSTRAINT_NAME = ''FK_DD_SBE_ID'' AND R_OWNER = '''||V_ESQUEMA||'''';
	
	EXECUTE IMMEDIATE V_SQL INTO V_AUX;
	
	IF V_AUX = 1 THEN
	
		V_SQL := 'ALTER TABLE ACT_ILB_NFO_LIBERBANK
					ENABLE CONSTRAINT FK_DD_SBE_ID';
					
		EXECUTE IMMEDIATE V_SQL;
		
	ELSE
		
		PL_OUTPUT := PL_OUTPUT ||' No existe la CONSTRAINT FK_DD_SBE_ID '||CHR(10);
		
	END IF;		
	
COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ERR_NUM := SQLCODE;
      ERR_MSG := SQLERRM;
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    [ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM);
      PL_OUTPUT := PL_OUTPUT || CHR(10) ||'    '||ERR_MSG;
      ROLLBACK;
      RAISE;
END ;
/
EXIT;
