--/*
--##########################################
--## AUTOR=Teresa Alonso
--## FECHA_CREACION=20161031
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.1
--## INCIDENCIA_LINK=HREOS-1086
--## PRODUCTO=NO
--##
--## Finalidad: Script que añade en DD_SEG_SUBTIPO_ERROR_GASTO los tipos de error definidos en gestorias 
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.  
    V_NUM_TIPO   NUMBER(16); -- Vble. para validar la existencia de la tabla de tipos.    
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
	
    V_TEXT1 VARCHAR2(2400 CHAR); -- Vble. auxiliar
    V_ENTIDAD_ID NUMBER(16);
    V_ID NUMBER(16);
    V_TEG_ID NUMBER(16);

    V_TEXT_TABLA VARCHAR2(40 CHAR) := 'DD_SEG_SUBTIPO_ERROR_GASTO'; -- Vble. auxiliar para almacenar el nombre de la tabla de ref.
    V_TRES_LETRAS_TABLA VARCHAR2(10 CHAR) := 'SEG'; -- Vble. auxiliar para almacenar el sufijo de los campos de la tabla de ref.
    V_TEXT_TABLA_AUX VARCHAR2(40 CHAR) := 'DD_TEG_TIPO_ERROR_GASTO'; -- Vble. auxiliar para almacenar el nombre de la tabla de ref.
    V_TRES_LETRAS_TABLA_AUX VARCHAR2(10 CHAR) := 'TEG'; -- Vble. auxiliar para almacenar el sufijo de los campos de la tabla de ref. aux

    TYPE T_TIPO_DATA IS TABLE OF VARCHAR2(250);
    TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
       T_TIPO_DATA('02' , 'H01' , 'Liq nombre ant titu' , 'Liquidación a nombre de anterior titular' ),
        T_TIPO_DATA('02' , 'H02' , 'Liq pagar nuevo prop' , 'Liquidación a pagar por nuevo propietario (comprador)'),
        T_TIPO_DATA('02' , 'H03' , 'Imp liq no coincide' , 'Importe liquidación no coincide con el tecleado' ),
        T_TIPO_DATA('02' , 'H04' , 'Error de tecleo    ' , 'Error de tecleo' ),
        T_TIPO_DATA('02' , 'H05' , 'Recargo no del propi' , 'El recargo no corresponde al propietario'),
        T_TIPO_DATA('02' , 'H06' , 'No procede pago plus' , 'No procede pago plusvalía'),
        T_TIPO_DATA('02' , 'H07' , 'Abono gasto no exist' , 'Abono de gasto que no existe, está anulado, no está pagado o ya está abonado' ),
        
        T_TIPO_DATA('03' , 'A01' , '% vta no suman 100  ', 'Los porcentajes de la venta conjunta no suman 100' ),
        T_TIPO_DATA('03' , 'A02' , 'Fra Rechaz (ASPRO)  ' , 'Factura Recibida Rechazada por Contabilidad (ASPRO)'  ),
        T_TIPO_DATA('03' , 'A03' , 'Fra sin Inmuebles   ' , 'Factura sin Inmuebles'),
        T_TIPO_DATA('03' , 'A04' , 'Fra sin Detalle(Lín)' , 'Factura sin Detalle (Líneas)'),
        T_TIPO_DATA('03' , 'A05' , 'Cte sin Población   ' , 'Cliente sin Población'  ),
        T_TIPO_DATA('03' , 'A06' , 'Fra Rectifica no inf' , 'Factura Rectificativa que no tiene informado la fac. corregida' ),
        T_TIPO_DATA('03' , 'A07' , 'Imp arras en fra vta' , 'Importe arras incluido en factura de venta'),
        T_TIPO_DATA('03' , 'A08' , 'Forma pago incorrect' , 'Forma de pago incorrecta' ),
        T_TIPO_DATA('03' , 'A09' , 'Dif Imp  KC10-KC11  ' , 'Diferencia de Importes en Facturas Recibidas KC10-KC11' ),
        T_TIPO_DATA('03' , 'A10' , 'Fra mismo prov(ASPRO' , 'Factura ya introducida para el mismo proveedor. (ASPRO)'),
      	T_TIPO_DATA('03' , 'A11' , 'Act no dispo SdadPag' , 'Activo no disponible en la Sociedad Pagadora' ) ,
      	T_TIPO_DATA('03' , 'A12' , 'Sdad Pagad no defini' , 'Sociedad Pagadora no definida' ),
        T_TIPO_DATA('03' , 'A13' , 'Dif Imp  KC10-KC12  ' , 'Diferencia de Importes en Facturas Recibidas KC10-KC12'  ),
        T_TIPO_DATA('03' , 'A14' , 'Faltan datos cliente' , 'Faltan datos de cliente' ),
        
        T_TIPO_DATA('04' , 'B01' , 'Agr no tip ProviFond' , 'Agrupación no es del tipo provisión de fondos' ),
        T_TIPO_DATA('04' , 'B02' , 'Fech anula sin gasto' , 'Llega fecha de anulación y no existe gasto en la tabla' ),
        T_TIPO_DATA('04' , 'B03' , 'Abono gasto NO pagad' ,  'Llega un abono de un gasto que NO está pagado' ),
        T_TIPO_DATA('04' , 'B04' , 'Descto>imp nomi gast' ,  'Descuento mayor que importe nominal del gasto' ),
        T_TIPO_DATA('04' , 'B05' , 'Retorno servidor err' , 'Retorno del servidor erróneo' ),
        T_TIPO_DATA('04' , 'B06' , 'Provisión ya cerrada' , 'La provisión ya está cerrada ' ),
        T_TIPO_DATA('04' , 'B07' , 'Err grupo/tip/subtip' , 'Error en grupo / tipo / subtipo de acción' ),
        T_TIPO_DATA('04' , 'B08' , 'No existe activo    ' , 'No existe el activo en la base corporativa' ),
        T_TIPO_DATA('04' , 'B09' , 'Period sin fecha fin' , 'Periodicidad varios periodos y no hay fecha fin periodo' ),
        T_TIPO_DATA('04' , 'B10' , 'Period <> varios per' , 'Periodicidad <> varios periodos y llega fecha fin periodo' ),
        T_TIPO_DATA('04' , 'B11' , 'Abono gasto<>valores' , 'Llega un abono de un gasto con distintos valores en fichero de entrada y tabla de gastos' ),
        T_TIPO_DATA('04' , 'B12' , 'Abono gasto anulado ' , 'Llega un abono de un gasto que está anulado' ),
        T_TIPO_DATA('04' , 'B13' , 'Abono gasto ya abona' , 'Llega un abono de un gasto que ya está abonado, o bien está en la misma provisión sin anular' ),
        T_TIPO_DATA('04' , 'B14' , 'CONTACTAR CON INFORM' , 'CONTACTAR CON INFORMATICA' ),
        T_TIPO_DATA('04' , 'B15' , 'CONTACTAR CON INFORM' , 'CONTACTAR CON INFORMATICA' ),
        T_TIPO_DATA('04' , 'B16' , 'CONTACTAR CON INFORM' , 'CONTACTAR CON INFORMATICA' ),
        T_TIPO_DATA('04' , 'B17' , 'CONTACTAR CON INFORM' , 'CONTACTAR CON INFORMATICA' ),
        T_TIPO_DATA('04' , 'B18' , 'Gasto provisión exis' , 'Llega un gasto en una provisión y ya existe sin anular en otra provisión.' ),
        T_TIPO_DATA('04' , 'B19' , 'Gasto sin Periodicid' , 'Periodicidad del gasto es cero o espacios' ),
        T_TIPO_DATA('04' , 'B20' , 'Error DB2 tab Activo' , 'Error DB2 en acceso a la tabla de Activos' ),
        T_TIPO_DATA('04' , 'B21' , 'Error DB2 tab Gastos' , 'Error DB2 en acceso a la tabla de Gastos' ),
        T_TIPO_DATA('04' , 'B22' , 'Error DB2 gto/provis' , 'Error DB2 en la tabla de relación gasto / provisión'),
        T_TIPO_DATA('04' , 'B23' , 'Anula gasto YA pagad' , 'Llega anulación de un gasto que YA está pagado'  ),
        T_TIPO_DATA('04' , 'B24' , 'Modif gasto YA pagad' , 'Llega modificación de un gasto que YA está pagado'),
        T_TIPO_DATA('04' , 'B25' , 'Anula dato tab<>fich' , 'Se trata de una anulación y los datos de la tabla son distintos de los datos del fichero de entrada' ),
        T_TIPO_DATA('04' , 'B26' , 'Gto provis tab<>fich' , 'Llega un gasto sin provisión y en la tabla si la tiene' ),
        T_TIPO_DATA('04' , 'B27' , 'Anul GtoProvis no ex' , 'Llega una anulación de un gasto de una provisión y no existe el gasto en dicha provisión' ),
        T_TIPO_DATA('04' , 'B28' , 'Códig moneda invalid' , 'Código de moneda invalido' ),
        T_TIPO_DATA('04' , 'B40' , 'Imp impuesto no váli' , 'El importe del impuesto no se ajusta a ningún tipo de impuesto válido' ),
        T_TIPO_DATA('04' , 'B61' , 'Provision cerrada   ' , 'La provisión ya está cerrada pero se ha actualizado la fecha de pago a proveedor'	),
        T_TIPO_DATA('04' , 'B62' , 'Devoluc imp positivo' , 'Llega una devolución con importe positivo' ),
        T_TIPO_DATA('04' , 'B63' , 'Devoluc sin num prov' , 'Llega una devolución sin número de provisión' ),
        T_TIPO_DATA('04' , 'B64' , 'Faltan datos CONEXIÓ' , 'Faltan datos de la CONEXIÓN' ),
        T_TIPO_DATA('04' , 'B65' , 'Gto CONEX con CódPro' , 'Es un gasto por CONEXIÓN y trae código de provisión' ),
        T_TIPO_DATA('04' , 'B66' , 'Gto Entidad<>Provisi' , 'Gasto de Entidad distinta al resto de la provisión' ),
        T_TIPO_DATA('04' , 'B67' , 'Sdad patrimo no exis' , 'La sociedad patrimonial del Activo no se encuentra en la lista de: sociedades patrimoniales que se pueden facturar'),
        T_TIPO_DATA('04' , 'B68' , 'Gto SdadPatri no Agr' , 'Los gastos de Activos con Sociedad Patrimonial titulizada tienen que ir agrupados en provisiones exclusivas por Sociedad Patrimonial'),
        T_TIPO_DATA('04' , 'B69' , 'Gto FactSareb no Agr' , 'Los gastos de Activos a facturar a Sareb, deben de agruparse a nivel de provisión además de por la entidad por el tipo de Activo, según la clasificación de Arrendados, Suelos y/o obra en curso y Producto acabado'),
        T_TIPO_DATA('04' , 'B70' , '> 500 Gtos ProvFondo' , 'Se ha llegado al limite de 500 gastos para este tipo de Provisión de Fondos'  ),
        T_TIPO_DATA('04' , 'B71' , 'Cod Partida no Valid' , 'Valor no valido codigo tipo partida'),
        T_TIPO_DATA('04' , 'B72' , 'Ident partida obliga' , 'Con tipo partida obligatorio indicar el identificador de la partida' ),
        T_TIPO_DATA('04' , 'B73' , 'Tipo partida obligat' , 'Con identificador de partida obligatorio indicar tipo de partida' ),
        T_TIPO_DATA('04' , 'B74' , 'Gtos LEASING sin agr' , 'Los gastos de Activos de LEASING deben de ir agrupados en provisiones al efecto'),
        T_TIPO_DATA('04' , 'B75' , 'Fech devengo inválid' , 'Fecha de devengo inválida. (no se admiten anteriores a 01.01.1989)	' ),
        T_TIPO_DATA('04' , 'B76' , 'Gto <> Sdad Patrimon' , 'Gasto de Activo con distinta sociedad patrimonial que la  provisión ' ),
        T_TIPO_DATA('04' , 'B77' , 'Fech Devengo <>rango' , 'Fecha de devengo fuera de rango para la sociedad patrimonial' ),
        T_TIPO_DATA('04' , 'B78' , 'Err modif provis Gto' , 'No se puede cambiar de provisión el gasto' ),
        T_TIPO_DATA('04' , 'B79' , 'Sdad Pagad no existe' , 'No encontrada sociedad pagadora' ),
        T_TIPO_DATA('04' , 'B80' , 'Sdad Pagad no valida' , 'Sociedad pagadora no valida' ),
        T_TIPO_DATA('04' , 'B81' , 'Fech Lím Pago errone' , 'Fecha límite del pago (FELIPG) con contenido NO valido'	),
        T_TIPO_DATA('04' , 'B82' , 'PLUSVALIA err AgrPro' , 'Las PLUSVALIAS deben de ir agrupadas en provisiones al efecto' ),
        T_TIPO_DATA('04' , 'B83' , 'Provi solo para PLUS' , 'La provisión solo admite PLUSVALIAS' ),

        T_TIPO_DATA('05' , 'G00' , 'NO ENVIADA A GRM' , 'NO ENVIADA A GRM' ),
        T_TIPO_DATA('05' , 'G01' , 'ENVIADA A GRM' , 'ENVIADA A GRM' ),
        T_TIPO_DATA('05' , 'G02' , '000 FRA ACEPTADA GRM' , '000 FACTURA ACEPTADA POR GRM' ),
        T_TIPO_DATA('05' , 'G03' , '020 SIN PRETO APROBA' , '020 SIN PRESUPUESTO APROBADO' ),
        T_TIPO_DATA('05' , 'G04' , '010 PROVE NO  EN GRM' , '010 PROVEEDOR NO EXISTE EN GRM' ),
        T_TIPO_DATA('05' , 'G05' , '050 ERROR DE FORMATO' , '050 ERROR DE FORMATO' ),
        T_TIPO_DATA('05' , 'G06' , '005 FACTURA DUPLICAD' , '005 FACTURA DUPLICADA' ),
        T_TIPO_DATA('05' , 'G07' , '015 ERROR CONCEPTO' , '015 CONCEPTO NO EXISTE O NO ES VALIDO PARA LA ENTIDAD' ), 
        T_TIPO_DATA('05' , 'G08' , '025 SIN SALDO EJERCI' , '025 SIN SALDO PARA EL EJERCICIO' ),
        T_TIPO_DATA('05' , 'G09' , '030 SIN SALDO ENTIDA' , '030 SIN SALDO PARA LA ENTIDAD' ) ,   
        T_TIPO_DATA('05' , 'G10' , '035 SIN SALDO PRESUP' , '035 SIN SALDO SUFICIENTE EN EL PRESUPUESTO' ), 
        T_TIPO_DATA('05' , 'G11' , '040 PROV IMP NO APRO' , '040 EL PROVEEDOR NO TIENE IMPORTE APROBADO EN LA PETICION'),
        T_TIPO_DATA('05' , 'G12' , '045 PROVEE SIN SALDO' , '045 EL PROVEEDOR NO TIENE SALDO SUFICIENTE EN LA PETICION') ,
    
        T_TIPO_DATA('06' , 'C01' , '000 - OK' , '000 - OK') ,
        T_TIPO_DATA('06' , 'C02' , '1- FICHERO DESORDENADO O SIN CABECERA DE FACTURA' , '1- FICHERO DESORDENADO O SIN CABECERA DE FACTURA'),
	T_TIPO_DATA('06' , 'C03' , '10 - ERROR DE SECUENCIA' , '10 - ERROR DE SECUENCIA' ),
	T_TIPO_DATA('06' , 'C04' , '14 - EL TERCERNO NO EXISTE EN DT20' , '14 - EL TERCERNO NO EXISTE EN DT20' ),
	T_TIPO_DATA('06' , 'C05' , '15 - EL TERCERO NO EXISTE EN LA BD DE PROVEEDORES' , '15 - EL TERCERO NO EXISTE EN LA BD DE PROVEEDORES' ),
	T_TIPO_DATA('06' , 'C06' , '16 - EL REVISOR NO EXISTE EN LA BD O NO TIENE ROL EMPLEADO' , '16 - EL REVISOR NO EXISTE EN LA BD O NO TIENE ROL EMPLEADO' ),
	T_TIPO_DATA('06' , 'C07' , '17 - EL AUTORIZADOR NO EXISTE EN LA BD O NO TIENE ROL EMPLEA' , '17 - EL AUTORIZADOR NO EXISTE EN LA BD O NO TIENE ROL EMPLEA' ),
	T_TIPO_DATA('06' , 'C08' , '19 - LA SOCIEDAD FTA NO EXISTE O ESTÁ DADA DE BAJA' , '19 - LA SOCIEDAD FTA NO EXISTE O ESTÁ DADA DE BAJA' ),
	T_TIPO_DATA('06' , 'C09' , '22 - NO SE ENCUENTRA EL TIPO DE SOCIEDAD PARA ESTE TERCERO' , '22 - NO SE ENCUENTRA EL TIPO DE SOCIEDAD PARA ESTE TERCERO' ),
	T_TIPO_DATA('06' , 'C10' , '30 - EL TERCERO FACTOR NO EXISTE EN LA BD' , '30 - EL TERCERO FACTOR NO EXISTE EN LA BD' ),
	T_TIPO_DATA('06' , 'C11' , '31 - ERROR EN EL PAGO DE FACTURA DE AUTORREPERCUSIÓN' ,  '31 - ERROR EN EL PAGO DE FACTURA DE AUTORREPERCUSIÓN' ),
	T_TIPO_DATA('06' , 'C12' , '32 - NO SE ADMITE FORMA DE PAGO EFECTIVO' , '32 - NO SE ADMITE FORMA DE PAGO EFECTIVO' ),
	T_TIPO_DATA('06' , 'C13' , '41 - LA FECHA DEVENGO NO ES LÓGICA' , '41 - LA FECHA DEVENGO NO ES LÓGICA' ),
	T_TIPO_DATA('06' , 'C14' , '42 - LA FECHA DE PAGO POR CONEXIÓN NO ES LÓGICA' , '42 - LA FECHA DE PAGO POR CONEXIÓN NO ES LÓGICA' ),
	T_TIPO_DATA('06' , 'C15' , '43 - TIPO DE FACTURA ERRÓNEA (E/R)' , '43 - TIPO DE FACTURA ERRÓNEA (E/R)' ),
	T_TIPO_DATA('06' , 'C16' , '47 - LA FECHA DE EMISIÓN NO ES LÓGICA' , '47 - LA FECHA DE EMISIÓN NO ES LÓGICA' ),
	T_TIPO_DATA('06' , 'C17' , '48 - FECHA DE EMISIÓN (FAEMIS) MAYOR QUE FECHA DÍA PROCESO' ,  '48 - FECHA DE EMISIÓN (FAEMIS) MAYOR QUE FECHA DÍA PROCESO' ),
	T_TIPO_DATA('06' , 'C18' , '51 - EN SAREB NO SE PERMITEN FACTURAS DE SUPLIDOS' , '51 - EN SAREB NO SE PERMITEN FACTURAS DE SUPLIDOS' ),
	T_TIPO_DATA('06' , 'C19' , '52 - EN FTA NO SE PERMITEN FACTURAS DE SUPLIDOS' , '52 - EN FTA NO SE PERMITEN FACTURAS DE SUPLIDOS' ),
	T_TIPO_DATA('06' , 'C20' , '54 - SAREB SOLO ADMITE FORMA DE PAGO TRANSFERENCIA O MANUAL' ,  '54 - SAREB SOLO ADMITE FORMA DE PAGO TRANSFERENCIA O MANUAL' ),
	T_TIPO_DATA('06' , 'C21' , '55 - SAREB SOLO ADMITE PROFESIONAL COMO IMPUESTO DIRECTO' ,  '55 - SAREB SOLO ADMITE PROFESIONAL COMO IMPUESTO DIRECTO' ),
	T_TIPO_DATA('06' , 'C22' , '56 - EN SAREB ES OBLIGATORIO EL % DE DEDUCIBILIDAD'  ,  '56 - EN SAREB ES OBLIGATORIO EL % DE DEDUCIBILIDAD' ),
	T_TIPO_DATA('06' , 'C23' , '57 - EL FORMATO DEL % DE DDEDUCIBILIDAD NO ES CORRECTO' ,  '57 - EL FORMATO DEL % DE DDEDUCIBILIDAD NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C24' , '58 - EL % DE DEDUCIBILIDAD ESTÁ FUERA DE RANGO' , '58 - EL % DE DEDUCIBILIDAD ESTÁ FUERA DE RANGO' ),
	T_TIPO_DATA('06' , 'C25' , '60 - EL ROL DE TERCERO NO EXISTE' , '60 - EL ROL DE TERCERO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C26' , '65 - LA MODALIDAD DE PAGO NO EXISTE' , '65 - LA MODALIDAD DE PAGO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C27' , '70 - LA FORMA DE PAGO NO EXISTE' , '70 - LA FORMA DE PAGO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C28' , '85 - INCOHERENCIA ENTRE TERCERO Y ROL DE TERCERO EMPLEADO' , '85 - INCOHERENCIA ENTRE TERCERO Y ROL DE TERCERO EMPLEADO'),
	T_TIPO_DATA('06' , 'C29' , '90 - INCOHERENCIA ENTRE TERCERO Y ROL DE TERCERO FICTICIO' , '90 - INCOHERENCIA ENTRE TERCERO Y ROL DE TERCERO FICTICIO'),
	T_TIPO_DATA('06' , 'C30' , '91 - INCOHERENCIA ENTRE ROL DE TERCERO Y TERCERO FICTICIO' , '91 - INCOHERENCIA ENTRE ROL DE TERCERO Y TERCERO FICTICIO'),
	T_TIPO_DATA('06' , 'C31' , '93 - INCOHERENCI ENTRE TERCERO FACTOR Y FORMA PAGO FACTORING' ,  '93 - INCOHERENCI ENTRE TERCERO FACTOR Y FORMA PAGO FACTORING' ),
	T_TIPO_DATA('06' , 'C32' , '94 - INCOHERENCIA ENTRE TIPO DE OPERACIÓN Y TERCERO' , '94 - INCOHERENCIA ENTRE TIPO DE OPERACIÓN Y TERCERO'),
	T_TIPO_DATA('06' , 'C33' , '95 - EL TIPO DE OPERACIÓN NO EXISTE' , '95 - EL TIPO DE OPERACIÓN NO EXISTE' ),
	T_TIPO_DATA('06' , 'C34' , '97 - TIPO DE OPERACION NO PERMITIDO' , '97 - TIPO DE OPERACION NO PERMITIDO' ),
	T_TIPO_DATA('06' , 'C35' , '100 - TIPO DE OPERACIÓN Y TIPO DE FACTURA INCOMPATIBLES' , '100 - TIPO DE OPERACIÓN Y TIPO DE FACTURA INCOMPATIBLES' ),
	T_TIPO_DATA('06' , 'C36' , '105 - ES OBLIG NÚM FACT PROV A ESTA OPER POR TENER IMPU INDI' ,  '105 - ES OBLIG NÚM FACT PROV A ESTA OPER POR TENER IMPU INDI' ),
	T_TIPO_DATA('06' , 'C37' , '110 - EL TIPO DE OPERACIÓN OBLIGA AL IMPUESTO DIRECTO' , '110 - EL TIPO DE OPERACIÓN OBLIGA AL IMPUESTO DIRECTO' ),
	T_TIPO_DATA('06' , 'C38' , '111 - EL TIPO DE OPERACIÓN NO PERMITE IMPUESTO DIRECTO' , '111 - EL TIPO DE OPERACIÓN NO PERMITE IMPUESTO DIRECTO' ),
	T_TIPO_DATA('06' , 'C39' , '115 - BLOQUE DE DATOS DEL IMPUESTO DIRECTO INCOMPLETO' , '115 - BLOQUE DE DATOS DEL IMPUESTO DIRECTO INCOMPLETO' ),
	T_TIPO_DATA('06' , 'C40' , '116 - BLOQUE DE DATOS DEL IMPUESTO DIRECTO INCOMPLETO' , '116 - BLOQUE DE DATOS DEL IMPUESTO DIRECTO INCOMPLETO' ),
	T_TIPO_DATA('06' , 'C41' , '117 - LA BASE DEL IMPUESTO DIRECTO ES CERO' , '117 - LA BASE DEL IMPUESTO DIRECTO ES CERO'),
	T_TIPO_DATA('06' , 'C42' , '118 - EL CENTRO DE INCORPORACIÓN NO ESTÁ ABIERTO' , '118 - EL CENTRO DE INCORPORACIÓN NO ESTÁ ABIERTO' ),
	T_TIPO_DATA('06' , 'C43' , '120 - BLOQUE DE DATOS DE PAGO POR CONEXIÓN INCOMPLETO' , '120 - BLOQUE DE DATOS DE PAGO POR CONEXIÓN INCOMPLETO' ),
	T_TIPO_DATA('06' , 'C44' , '121 - INCOHERENCIA ENTRE FORMA PAGO Y DATOS PAGO POR CONEXIO' ,  '121 - INCOHERENCIA ENTRE FORMA PAGO Y DATOS PAGO POR CONEXIO' ),
	T_TIPO_DATA('06' , 'C45' , '125 - EL TIPO DE IMPUESTO DIRECTO NO EXISTE' , '125 - EL TIPO DE IMPUESTO DIRECTO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C46' , '130 - EL IMPUESTO DIRECTO NO EXISTE O NO ESTÁ VIGENTE' , '130 - EL IMPUESTO DIRECTO NO EXISTE O NO ESTÁ VIGENTE' ),
	T_TIPO_DATA('06' , 'C47' , '135 - EL PORCENTAJE DEL IMPUESTO DIRECTO NO ES CORRECTO' , '135 - EL PORCENTAJE DEL IMPUESTO DIRECTO NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C48' , '136 - EL PORCENTAJE DEL IMPUESTO DIRECTO ESTÁ FUERA DE RANGO' ,  '136 - EL PORCENTAJE DEL IMPUESTO DIRECTO ESTÁ FUERA DE RANGO' ),
	T_TIPO_DATA('06' , 'C49' , '137 - EL NIF DEL TERCERO NO ADMITE IRPF PROFESIONAL' , '137 - EL NIF DEL TERCERO NO ADMITE IRPF PROFESIONAL'),
	T_TIPO_DATA('06' , 'C50' , '140 - LA MONEDA NO ES CORRECTA' , '140 - LA MONEDA NO ES CORRECTA' ),
	T_TIPO_DATA('06' , 'C51' , '141 - LA CUOTA DE IMPUESTO DIRECTO NO ES CORRECTA' , '141 - LA CUOTA DE IMPUESTO DIRECTO NO ES CORRECTA' ),
	T_TIPO_DATA('06' , 'C52' , '142 - EL CAMBIO DE DIVISA DEBE SER CERO' , '142 - EL CAMBIO DE DIVISA DEBE SER CERO' ),
	T_TIPO_DATA('06' , 'C53' , '145 - ROL DE TERCERO(RECIB EN FICH) NO COINCI CON ROL IM DIR' ,  '145 - ROL DE TERCERO(RECIB EN FICH) NO COINCI CON ROL IM DIR' ),
	T_TIPO_DATA('06' , 'C54' , '146 - ROL DE TERCERO(DE LA BD) NO COINCI CON ROL IMP DIRECTO' ,  '146 - ROL DE TERCERO(DE LA BD) NO COINCI CON ROL IMP DIRECTO' ),
	T_TIPO_DATA('06' , 'C55' , '150 - EL REVISOR NO ES UN EMPLEADO' , '150 - EL REVISOR NO ES UN EMPLEADO' ),
	T_TIPO_DATA('06' , 'C56' , '155 - EL AUTORIZADOR NO ES UN EMPLEADO' , '155 - EL AUTORIZADOR NO ES UN EMPLEADO' ),
	T_TIPO_DATA('06' , 'C57' , '160 - LA SITUACIÓN DE LA FACTURA NO ES CORRECTA' , '160 - LA SITUACIÓN DE LA FACTURA NO ES CORRECTA' ),
	T_TIPO_DATA('06' , 'C58' , '161 - LAS FACTURAS DE INMOVILIZADO DEBEN ESTAR AUTORIZADAS' ,  '161 - LAS FACTURAS DE INMOVILIZADO DEBEN ESTAR AUTORIZADAS' ),
	T_TIPO_DATA('06' , 'C59' , '162 - EL REVISOR ES OBLIGAT EN FACTURAS EMITIDAS O CONFORMAD' ,  '162 - EL REVISOR ES OBLIGAT EN FACTURAS EMITIDAS O CONFORMAD' ),
	T_TIPO_DATA('06' , 'C60' , '163 - ES OBLIGAT REVISOR Y AUTORIZADOR EN FACTURAS AUTORIZAD' ,  '163 - ES OBLIGAT REVISOR Y AUTORIZADOR EN FACTURAS AUTORIZAD' ),
	T_TIPO_DATA('06' , 'C61' , '164 - LA FACTURA DE SUPLIDOS NO TIENE REVISOR NI AUTORIZADOR' ,  '164 - LA FACTURA DE SUPLIDOS NO TIENE REVISOR NI AUTORIZADOR' ),
	T_TIPO_DATA('06' , 'C62' , '170 - FACTU DUPLI: TERCERO, NºFACT PROVEEDOR Y FECHA EMISION' ,  '170 - FACTU DUPLI: TERCERO, NºFACT PROVEEDOR Y FECHA EMISION' ),
	T_TIPO_DATA('06' , 'C63' , '171 - FACT DUPLI EN FICH: TERCERO, Nº FACT PROVEED Y FEC EMI' ,  '171 - FACT DUPLI EN FICH: TERCERO, Nº FACT PROVEED Y FEC EMI' ),
	T_TIPO_DATA('06' , 'C64' , '200 - EL TIPO DE OPERACIÓN OBLIGA AL IMPUESTO INDIRECTO' , '200 - EL TIPO DE OPERACIÓN OBLIGA AL IMPUESTO INDIRECTO' ),
	T_TIPO_DATA('06' , 'C65' , '201 - EL TIPO DE OPERACIÓN NO PERMITE IMPUESTO INDIRECTO' ,  '201 - EL TIPO DE OPERACIÓN NO PERMITE IMPUESTO INDIRECTO' ),
	T_TIPO_DATA('06' , 'C66' , '202 - EL CONCEPTO PAGO SUPLIDO NO LLEVA IMPUESTO INDIRECTO' , '202 - EL CONCEPTO PAGO SUPLIDO NO LLEVA IMPUESTO INDIRECTO' ),
	T_TIPO_DATA('06' , 'C67' , '205 - EL TIPO DE IMPUESTO INDIRECTO NO EXISTE' , '205 - EL TIPO DE IMPUESTO INDIRECTO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C68' , '206 - LA FECHA DE EMISIÓN ES OBLIGATORIA' , '206 - LA FECHA DE EMISIÓN ES OBLIGATORIA' ),
	T_TIPO_DATA('06' , 'C69' , '210 - EL IMPUESTO INDIRECTO NO EXISTE O NO ESTÁ VIGENTE' , '210 - EL IMPUESTO INDIRECTO NO EXISTE O NO ESTÁ VIGENTE' ),
	T_TIPO_DATA('06' , 'C70' , '215 - EL PORCENTAJE DEL IMPUESTO INDIRECTO NO ES CORRECTO' , '215 - EL PORCENTAJE DEL IMPUESTO INDIRECTO NO ES CORRECTO'),
	T_TIPO_DATA('06' , 'C71' , '216 - EL PORCENT DEL IMPUESTO INDIRECTO ESTÁ FUERA DE RANGO' ,  '216 - EL PORCENT DEL IMPUESTO INDIRECTO ESTÁ FUERA DE RANGO' ),
	T_TIPO_DATA('06' , 'C72' , '220 - LA CUOTA DEL IMPUESTO INDIRECTO NO ES CORRECTA' ,  '220 - LA CUOTA DEL IMPUESTO INDIRECTO NO ES CORRECTA' ),
	T_TIPO_DATA('06' , 'C73' , '224 - INDICADOR DE INMOVILIZADO NO VÁLIDO' , '224 - INDICADOR DE INMOVILIZADO NO VÁLIDO' ),
	T_TIPO_DATA('06' , 'C74' , '225 - INDICADOR DE RECLASIFICACIÓN NO VÁLIDO' , '225 - INDICADOR DE RECLASIFICACIÓN NO VÁLIDO' ),
	T_TIPO_DATA('06' , 'C75' , '226 - Incoherencia entre Indicador de Inmovilizado y Concept' ,  '226 - Incoherencia entre Indicador de Inmovilizado y Concept' ),
	T_TIPO_DATA('06' , 'C76' , '227 - INCOHERENCIA ENTRE INDIC DE RECLASIFICACIÓN Y CONCEPTO' ,  '227 - INCOHERENCIA ENTRE INDIC DE RECLASIFICACIÓN Y CONCEPTO' ),
	T_TIPO_DATA('06' , 'C77' , '228 - EL TIPO DE OPERACIÓN NO PERMITE INMOVILIZADO' ,  '228 - EL TIPO DE OPERACIÓN NO PERMITE INMOVILIZADO' ),
	T_TIPO_DATA('06' , 'C78' , '250 - LA FICHA NO EXISTE' , '250 - LA FICHA NO EXISTE' ),
	T_TIPO_DATA('06' , 'C79' , '251 - EL CONCEPTO NO PERMITE LLEVAR FICHA' , '251 - EL CONCEPTO NO PERMITE LLEVAR FICHA' ),
	T_TIPO_DATA('06' , 'C80' , '252 - EL CONCEPTO OBLIGA A LLEVAR FICHA' , '252 - EL CONCEPTO OBLIGA A LLEVAR FICHA' ),
	T_TIPO_DATA('06' , 'C81' , '280 - EL CONCEPTO NO EXISTE' , '280 - EL CONCEPTO NO EXISTE' ),
	T_TIPO_DATA('06' , 'C82' , '281 - INCOHERENCIA ENTRE FACTURA DE FTA Y CONCEPTO DE FTA' , '281 - INCOHERENCIA ENTRE FACTURA DE FTA Y CONCEPTO DE FTA'),
	T_TIPO_DATA('06' , 'C83' , '282 - CPTO PAGO SUPLIDO NO ESTÁ PERMITIDO EN FACT SIN SUPLI' , '282 - CPTO PAGO SUPLIDO NO ESTÁ PERMITIDO EN FACT SIN SUPLI' ),
	T_TIPO_DATA('06' , 'C84' , '283 -  CPTO PAGO SUPLIDO NO ESTÁ PERMITIDO EN  FACT DE SUPLD' ,  '283 -  CPTO PAGO SUPLIDO NO ESTÁ PERMITIDO EN  FACT DE SUPLD' ),
	T_TIPO_DATA('06' , 'C85' , '284 - EL CONCEPTO NO ESTÁ ASOCIADO A LA ENTIDAD' , '284 - EL CONCEPTO NO ESTÁ ASOCIADO A LA ENTIDAD' ),
	T_TIPO_DATA('06' , 'C86' , '285 - CONCEPTO ES DE USO RESTRINGIDO PARA CTRO INCORPORACION' ,  '285 - CONCEPTO ES DE USO RESTRINGIDO PARA CTRO INCORPORACION' ),
	T_TIPO_DATA('06' , 'C87' , '290 - EN SAREB NO SE PERMITE EL IMPUESTO IPSI' , '290 - EN SAREB NO SE PERMITE EL IMPUESTO IPSI' ),
	T_TIPO_DATA('06' , 'C88' , '291 - EN SAREB ES OBLIGATORIO EL CONTRATO' , '291 - EN SAREB ES OBLIGATORIO EL CONTRATO' ),
	T_TIPO_DATA('06' , 'C89' , '292 - EL FORMATO DEL CONTRATO NO ES CORRECTO' , '292 - EL FORMATO DEL CONTRATO NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C90' , '293 - EN FTA OBLIGATORIO CONTRATO PTMO/CTA CDTO/BANCA CORPOR' ,  '293 - EN FTA OBLIGATORIO CONTRATO PTMO/CTA CDTO/BANCA CORPOR' ),
	T_TIPO_DATA('06' , 'C91' , '294 - EL FORMATO DE FICHA/PRÉSTAMO/ACTIVO  NO ES CORRECTO' , '294 - EL FORMATO DE FICHA/PRÉSTAMO/ACTIVO  NO ES CORRECTO'),
	T_TIPO_DATA('06' , 'C92' , '295 - EL CÓDIGO DEL CONTRATO  NO ES CORRECTO' , '295 - EL CÓDIGO DEL CONTRATO  NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C93' , '296 - EL CÓDIGO DE FICHA/PRÉSTAMO/ACTIVO  NO ES CORRECTO' , '296 - EL CÓDIGO DE FICHA/PRÉSTAMO/ACTIVO  NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C94' , '297 - CÓDIGO FICHA/PRÉST/ACT NO VA INFORMADO EN ESTE CONCEPT' ,  '297 - CÓDIGO FICHA/PRÉST/ACT NO VA INFORMADO EN ESTE CONCEPT' ),
	T_TIPO_DATA('06' , 'C95' , '311 - REGISTRO DE RECLASIFICACIÓN SIN REGISTRO DE DETALLE' , '311 - REGISTRO DE RECLASIFICACIÓN SIN REGISTRO DE DETALLE'),
	T_TIPO_DATA('06' , 'C96' , '312 - REG RECLASIFICACIÓN,REG DETALLE NO TIENE ACTDO IN RECL' ,  '312 - REG RECLASIFICACIÓN,REG DETALLE NO TIENE ACTDO IN RECL' ),
	T_TIPO_DATA('06' , 'C97' , '313 - EL CENTRO DE RECLASIFICACIÓN NO ESTÁ ABIERTO' , '313 - EL CENTRO DE RECLASIFICACIÓN NO ESTÁ ABIERTO' ),
	T_TIPO_DATA('06' , 'C98' , '331 - REGISTRO DE INMOVILIZADO SIN REGISTRO DE DETALLE' , '331 - REGISTRO DE INMOVILIZADO SIN REGISTRO DE DETALLE' ),
	T_TIPO_DATA('06' , 'C99' , '332 - REG INMOVILIZADO,REG DE DETALLE NO TIENE ACTDO IND INM' ,  '332 - REG INMOVILIZADO,REG DE DETALLE NO TIENE ACTDO IND INM' ),
	T_TIPO_DATA('06' , 'C100' , '333 - EL NÚMERO DE FICHA DE INMOVILIZADO ES OBLIGATORIO' , '333 - EL NÚMERO DE FICHA DE INMOVILIZADO ES OBLIGATORIO' ),
	T_TIPO_DATA('06' , 'C101' , '334 - EL NÚMERO DE FICHA DE INMOVILIZADO NO ES NUMÉRICO' , '334 - EL NÚMERO DE FICHA DE INMOVILIZADO NO ES NUMÉRICO' ),
	T_TIPO_DATA('06' , 'C102' , '341 - FACTURA RECIBIDA CONTRA FICHA QUE SE QUIERE VENDER' , '341 - FACTURA RECIBIDA CONTRA FICHA QUE SE QUIERE VENDER' ),
	T_TIPO_DATA('06' , 'C103' , '342 - FACT EMITIDA CON PORCENTAJE DE INMOVILIZADO NO NUMÉRIC' ,  '342 - FACT EMITIDA CON PORCENTAJE DE INMOVILIZADO NO NUMÉRIC' ),
	T_TIPO_DATA('06' , 'C104' , '346 - FACTURA EMITIDA CON PORCENTAJE INMOVILIZADO IGUAL A 0' ,  '346 - FACTURA EMITIDA CON PORCENTAJE INMOVILIZADO IGUAL A 0' ),
	T_TIPO_DATA('06' , 'C105' , '347 - EL PORCENTAJE DE INMOVILIZADO ES MAYOR QUE 100%' , '347 - EL PORCENTAJE DE INMOVILIZADO ES MAYOR QUE 100%' ),
	T_TIPO_DATA('06' , 'C106' , '348 - EL PORCENTAJE DE INMOVILIZADO HA DE SER EL 100 %' , '348 - EL PORCENTAJE DE INMOVILIZADO HA DE SER EL 100 %' ),
	T_TIPO_DATA('06' , 'C107' , '351 - NO EXISTE FICHA DE INMOVILIZADO' , '351 - NO EXISTE FICHA DE INMOVILIZADO' ),
	T_TIPO_DATA('06' , 'C108' , '352 - FICHA EN SITUACIÓN VENDIDA' , '352 - FICHA EN SITUACIÓN VENDIDA' ),
	T_TIPO_DATA('06' , 'C109' , '354 - FICHA CON VALOR DE ACTIVO CERO' , '354 - FICHA CON VALOR DE ACTIVO CERO' ),
	T_TIPO_DATA('06' , 'C110' , '355 - FICHA EN SITUACIÓN DIVIDIDA' , '355 - FICHA EN SITUACIÓN DIVIDIDA'),
	T_TIPO_DATA('06' , 'C111' , '360 - LA FICHA NO EXISTE' , '360 - LA FICHA NO EXISTE' ),
	T_TIPO_DATA('06' , 'C112' , '361 - LA FORMA DE PAGO NO PERMITE LLEVAR FICHA' , '361 - LA FORMA DE PAGO NO PERMITE LLEVAR FICHA' ),
	T_TIPO_DATA('06' , 'C113' , '362 - FORMA DE PAGO NO PERMITE LLEVAR CONCEPTO INVENTARIABLE' ,  '362 - FORMA DE PAGO NO PERMITE LLEVAR CONCEPTO INVENTARIABLE' ),
	T_TIPO_DATA('06' , 'C114' , '366 - LA FECHA DE PAGO NO ES LÓGICA' , '366 - LA FECHA DE PAGO NO ES LÓGICA' ),
	T_TIPO_DATA('06' , 'C115' , '367 - FECHA PAGO NO PUEDE SER ANTERIOR A FECH DE EMIS D FACT' ,  '367 - FECHA PAGO NO PUEDE SER ANTERIOR A FECH DE EMIS D FACT' ),
	T_TIPO_DATA('06' , 'C116' , '370 - LA FACTURA DE SUPLIDOS NO PUEDE TENER REGISTRO DE PAGO' ,  '370 - LA FACTURA DE SUPLIDOS NO PUEDE TENER REGISTRO DE PAGO' ),
	T_TIPO_DATA('06' , 'C117' , '371 - INCOHE ENTRE TIPO OPER Y FORMA PAGO EN FACT ACT ADJUDI' ,  '371 - INCOHE ENTRE TIPO OPER Y FORMA PAGO EN FACT ACT ADJUDI' ),
	T_TIPO_DATA('06' , 'C118' , '372 - FACTORING (EN CABECERA) SOLO PERMITE FORMA PAGO TRANSF' ,  '372 - FACTORING (EN CABECERA) SOLO PERMITE FORMA PAGO TRANSF' ),
	T_TIPO_DATA('06' , 'C119' , '373 - EL PAGO POR CHEQUE OBLIGA A INTRODUCIR UN NÚM D CHEQUE' ,  '373 - EL PAGO POR CHEQUE OBLIGA A INTRODUCIR UN NÚM D CHEQUE' ),
	T_TIPO_DATA('06' , 'C120' , '374 - PAGO CONEXION OBLIGA MODALID Y FORM PAGO POR CONEX CAB' ,  '374 - PAGO CONEXION OBLIGA MODALID Y FORM PAGO POR CONEX CAB' ),
	T_TIPO_DATA('06' , 'C121' , '375 - INCHORE ENTRE TIP OPER Y FORMA PAGO EN FACTUR DE M-347' ,  '375 - INCHORE ENTRE TIP OPER Y FORMA PAGO EN FACTUR DE M-347' ),
	T_TIPO_DATA('06' , 'C122' , '376 - INCOHE D FORM PAG ANTICI/PROVI/RETE Y MODAL CONTR ANTI' ,  '376 - INCOHE D FORM PAG ANTICI/PROVI/RETE Y MODAL CONTR ANTI' ),
	T_TIPO_DATA('06' , 'C123' , '385 - EL TERCERO NO TIENE ASOCIADA ESTA CUENTA BANCARIA' , '385 - EL TERCERO NO TIENE ASOCIADA ESTA CUENTA BANCARIA' ),
	T_TIPO_DATA('06' , 'C124' , '386 - TERCERO NO TIENE ASOCIADA ESA CTA BANC (SIN DIG CONTR)' ,  '386 - TERCERO NO TIENE ASOCIADA ESA CTA BANC (SIN DIG CONTR)' ),
	T_TIPO_DATA('06' , 'C125' , '387 - TERCERO NO TIENE ASOCIADA CTA BANCARIA PREFERENCIAL' , '387 - TERCERO NO TIENE ASOCIADA CTA BANCARIA PREFERENCIAL'),
	T_TIPO_DATA('06' , 'C126' , '388 - ENT BANCARIA NO CORRECT EN CTA CORRI RECIBIDA EN BATCH' ,  '388 - ENT BANCARIA NO CORRECT EN CTA CORRI RECIBIDA EN BATCH' ),
	T_TIPO_DATA('06' , 'C127' , '389 - OFI BANCARIA NO CORRECT EN CTA CORRI RECIBIDA EN BATCH' ,  '389 - OFI BANCARIA NO CORRECT EN CTA CORRI RECIBIDA EN BATCH' ),
	T_TIPO_DATA('06' , 'C128' , '390 - DIG CONTROL NO CORRECTO EN CTA CORRI RECIBIDA EN BATCH' ,  '390 - DIG CONTROL NO CORRECTO EN CTA CORRI RECIBIDA EN BATCH' ),
	T_TIPO_DATA('06' , 'C129' , '390 - DIGS CONTR NO CORRECTOS EN CTA CORRI RECIBIDA EN BATCH' ,  '390 - DIGS CONTR NO CORRECTOS EN CTA CORRI RECIBIDA EN BATCH' ),
	T_TIPO_DATA('06' , 'C130' , '410 - FACTURA SIN MOVIMIENTOS DE DETALLE' , '410 - FACTURA SIN MOVIMIENTOS DE DETALLE' ),
	T_TIPO_DATA('06' , 'C131' , '412 - FACTURA PRINCIPAL DEBE TENER UN CONCEPTO PAGO SUPLIDO' , '412 - FACTURA PRINCIPAL DEBE TENER UN CONCEPTO PAGO SUPLIDO' ),
	T_TIPO_DATA('06' , 'C132' , '413 - FACT PPAL SOLO PUEDE TENER UN CONCEPTO DE PAGO SUPLIDO' ,  '413 - FACT PPAL SOLO PUEDE TENER UN CONCEPTO DE PAGO SUPLIDO' ),
	T_TIPO_DATA('06' , 'C133' , '414 - LA FACT PPAL DEBE TENER AL MENOS UN CONCEPTO DE GASTO' , '414 - LA FACT PPAL DEBE TENER AL MENOS UN CONCEPTO DE GASTO' ),
	T_TIPO_DATA('06' , 'C134' , '415 - LA SUM D IMPORT DE REG DE DETAL NO CUADRA CON TOT FACT' ,  '415 - LA SUM D IMPORT DE REG DE DETAL NO CUADRA CON TOT FACT' ),
	T_TIPO_DATA('06' , 'C135' , '420 - FACTURA SIN MOVIMIENTOS DE PAGO' , '420 - FACTURA SIN MOVIMIENTOS DE PAGO' ),
	T_TIPO_DATA('06' , 'C136' , '422 - LA FACTURA DE SUPLIDOS NO PUEDE TENER REGISTRO DE PAGO' ,  '422 - LA FACTURA DE SUPLIDOS NO PUEDE TENER REGISTRO DE PAGO' ),
	T_TIPO_DATA('06' , 'C137' , '425 - SUM D IMP D REG DE PAGO NO CUADRA CON TOT A PAGAR FACT' ,  '425 - SUM D IMP D REG DE PAGO NO CUADRA CON TOT A PAGAR FACT' ),
	T_TIPO_DATA('06' , 'C138' , '430 - FACTURA DE ABONO DE FTA SIN RELACIÓN DE SU FACT CARGO' , '430 - FACTURA DE ABONO DE FTA SIN RELACIÓN DE SU FACT CARGO' ),
	T_TIPO_DATA('06' , 'C139' , '440 - REGISTROS DE INMOVILIZADO SIN REGISTRO DE DETALLE' , '440 - REGISTROS DE INMOVILIZADO SIN REGISTRO DE DETALLE' ),
	T_TIPO_DATA('06' , 'C140' , '441 - IND INMOVILIZADO ESTÁ ACTIVO Y NO EXISTEN REG DE INMOV' ,  '441 - IND INMOVILIZADO ESTÁ ACTIVO Y NO EXISTEN REG DE INMOV' ),
	T_TIPO_DATA('06' , 'C141' , '442 - NO EXISTEN REG INMOVILIZADO Y EL IND INMOV ESTÁ ACTIVO' ,  '442 - NO EXISTEN REG INMOVILIZADO Y EL IND INMOV ESTÁ ACTIVO' ),
	T_TIPO_DATA('06' , 'C142' , '443 - SUMA IMP D REG INMOV NO CUADRA CON IMP TOT DEL MOV DET' ,  '443 - SUMA IMP D REG INMOV NO CUADRA CON IMP TOT DEL MOV DET' ),
	T_TIPO_DATA('06' , 'C143' , '444 - SUMA IMP D REG INMOV NO CUADRA CON IMP BAS DEL MOV DET' ,  '444 - SUMA IMP D REG INMOV NO CUADRA CON IMP BAS DEL MOV DET' ),
	T_TIPO_DATA('06' , 'C144' , '450 - REGISTROS DE RECLASIFACIÓN SIN REGISTRO DE DETALLE' , '450 - REGISTROS DE RECLASIFACIÓN SIN REGISTRO DE DETALLE' ),
	T_TIPO_DATA('06' , 'C145' , '451 - IND RECLASI ESTÁ ACTIVO Y NO EXISTEN REG RECLASI' , '451 - IND RECLASI ESTÁ ACTIVO Y NO EXISTEN REG RECLASI' ),
	T_TIPO_DATA('06' , 'C146' , '452 - NO EXISTEN REG RECLASI Y EL IND RECLASI ESTA ACTIVO' , '452 - NO EXISTEN REG RECLASI Y EL IND RECLASI ESTA ACTIVO'),
	T_TIPO_DATA('06' , 'C147' , '453 - SUM IMP REG RECLASI NO CUADRA CON IMP TOT DEL MOV DETA' ,  '453 - SUM IMP REG RECLASI NO CUADRA CON IMP TOT DEL MOV DETA' ),
	T_TIPO_DATA('06' , 'C148' , '454 - SUM IMP REG RECLASI NO CUADRA CON IMP BAS DEL MOV DETA' ,  '454 - SUM IMP REG RECLASI NO CUADRA CON IMP BAS DEL MOV DETA' ),
	T_TIPO_DATA('06' , 'C149' , '470 - EL TIPO DE RELACIÓN NO ES VÁLIDO' , '470 - EL TIPO DE RELACIÓN NO ES VÁLIDO' ),
	T_TIPO_DATA('06' , 'C150' , '471 - FACTURAS DE SUPLIDOS NO PUEDEN TENER FACT RELACIONADAS' ,  '471 - FACTURAS DE SUPLIDOS NO PUEDEN TENER FACT RELACIONADAS' ),
	T_TIPO_DATA('06' , 'C151' , '472 - FACT RECIBIDAS DE CARGO NO PUEDEN TENER FACT RELACIONA' ,  '472 - FACT RECIBIDAS DE CARGO NO PUEDEN TENER FACT RELACIONA' ),
	T_TIPO_DATA('06' , 'C152' , '473 - FACT EMITIDAS DE ABONO NO PUEDEN TENER FACT RELACIONA' , '473 - FACT EMITIDAS DE ABONO NO PUEDEN TENER FACT RELACIONA' ),
	T_TIPO_DATA('06' , 'C153' , '474 - NO SE ENCUENTRA LA FACTURA RELACIONADA' , '474 - NO SE ENCUENTRA LA FACTURA RELACIONADA' ),
	T_TIPO_DATA('06' , 'C154' , '475 - LA FACTURA RELACIONADA NO PUEDE SER UNA ANULACIÓN' , '475 - LA FACTURA RELACIONADA NO PUEDE SER UNA ANULACIÓN' ),
	T_TIPO_DATA('06' , 'C155' , '476 - LA FACTURA RELACIONADA NO PUEDE ESTAR ANULADA' , '476 - LA FACTURA RELACIONADA NO PUEDE ESTAR ANULADA'),
	T_TIPO_DATA('06' , 'C156' , '477 - LA FACTURA RELACIONADA NO ESTÁ CONTABILIZADA' , '477 - LA FACTURA RELACIONADA NO ESTÁ CONTABILIZADA' ),
	T_TIPO_DATA('06' , 'C157' , '478 - FACT RELACIONADA DEBE SER MISMO TIPO (EMITIDA/RECIBID)' ,  '478 - FACT RELACIONADA DEBE SER MISMO TIPO (EMITIDA/RECIBID)' ),
	T_TIPO_DATA('06' , 'C158' , '479 - EL TIPO DE OPERACIÓN DE LA FACT RELACIONADA NO EXISTE' , '479 - EL TIPO DE OPERACIÓN DE LA FACT RELACIONADA NO EXISTE' ),
	T_TIPO_DATA('06' , 'C159' , '480 - FACT RELACIONADA NO PUEDE TENER MISMA NATURAL(CAR/ABO)' ,  '480 - FACT RELACIONADA NO PUEDE TENER MISMA NATURAL(CAR/ABO)' ),
	T_TIPO_DATA('06' , 'C160' , '492 - ENTI CONTABILIZ POR CENTROS Y CENTRO ESTÁ SIN INFORMAR' ,  '492 - ENTI CONTABILIZ POR CENTROS Y CENTRO ESTÁ SIN INFORMAR' ),
	T_TIPO_DATA('06' , 'C161' , '501 - FACT PPAL CON SUPLIDOS DEBE SER RECIBIDA, NO EMITIDA' , '501 - FACT PPAL CON SUPLIDOS DEBE SER RECIBIDA, NO EMITIDA' ),
	T_TIPO_DATA('06' , 'C162' , '502 - FACTURA DE SUPLIDOS TIENE QUE SER RECIBIDA, NO EMITIDA' ,  '502 - FACTURA DE SUPLIDOS TIENE QUE SER RECIBIDA, NO EMITIDA' ),
	T_TIPO_DATA('06' , 'C163' , '503 - FACTURA DE SUPLIDO QUE NO TIENE FACTURA PRINCIPAL' , '503 - FACTURA DE SUPLIDO QUE NO TIENE FACTURA PRINCIPAL' ),
	T_TIPO_DATA('06' , 'C164' , '504 - FACT PRINCIPAL CON SUPLIDOS Y NO TIENE FACT D SUPLIDOS' ,  '504 - FACT PRINCIPAL CON SUPLIDOS Y NO TIENE FACT D SUPLIDOS' ),
	T_TIPO_DATA('06' , 'C165' , '505 - FACT PPAL CON SUPLIDOS NO TIENE CONCEPTO PAGO SUPLIDO' , '505 - FACT PPAL CON SUPLIDOS NO TIENE CONCEPTO PAGO SUPLIDO' ),
	T_TIPO_DATA('06' , 'C166' , '506 - INCOHE ENTRE FACT PPAL CON SUPLIDOS Y CONCEPT PAG SUPL' ,  '506 - INCOHE ENTRE FACT PPAL CON SUPLIDOS Y CONCEPT PAG SUPL' ),
	T_TIPO_DATA('06' , 'C167' , '510 - IMP CONCEPTO PAG SUPLI NO = CON SUM IMP TOT FACT SUPLI' ,  '510 - IMP CONCEPTO PAG SUPLI NO = CON SUM IMP TOT FACT SUPLI' ),
	T_TIPO_DATA('06' , 'C168' , '511 - NO SE ENCUENTRAN FACT SUPLIDO PARA CONCEPTO PAG SUPLID' ,  '511 - NO SE ENCUENTRAN FACT SUPLIDO PARA CONCEPTO PAG SUPLID' ),
	T_TIPO_DATA('06' , 'C169' , '512 - FACT PPAL CON SUPLIDOS NO TIENE EL CONCEPTO PAGO SUPLI' ,  '512 - FACT PPAL CON SUPLIDOS NO TIENE EL CONCEPTO PAGO SUPLI' ),
	T_TIPO_DATA('06' , 'C170' , '513 - FORMATO DE IMPUESTO INDIR NO ES CORRECTO IMBIMP,IMTIMP' ,  '513 - FORMATO DE IMPUESTO INDIR NO ES CORRECTO IMBIMP,IMTIMP' ),
	T_TIPO_DATA('06' , 'C171' , '601 - EL FORMATO DEL CONCEPTO NO ES CORRECTO CLCONC' , '601 - EL FORMATO DEL CONCEPTO NO ES CORRECTO CLCONC'),
	T_TIPO_DATA('06' , 'C172' , '602 - EL CONCEPTO NO PUEDE SER CERO O NEGATIVO CLCONC' , '602 - EL CONCEPTO NO PUEDE SER CERO O NEGATIVO CLCONC' ),
	T_TIPO_DATA('06' , 'C173' , '603 - FORMATO DEL TIPO IMPUESTO INDIR NO ES CORRECTO CLTIMP' , '603 - FORMATO DEL TIPO IMPUESTO INDIR NO ES CORRECTO CLTIMP' ),
	T_TIPO_DATA('06' , 'C174' , '604 - TIPO DE IMPUESTO INDIRECTO NO PUEDE SER NEGATIV CLTIMP' ,  '604 - TIPO DE IMPUESTO INDIRECTO NO PUEDE SER NEGATIV CLTIMP' ),
	T_TIPO_DATA('06' , 'C175' , '605 - FORMATO D BASE DEL IMPUESTO INDIR NO ES CORRECT IMBIMP' ,  '605 - FORMATO D BASE DEL IMPUESTO INDIR NO ES CORRECT IMBIMP' ),
	T_TIPO_DATA('06' , 'C176' , '606 - BASE D IMPUESTO INDIR NO PUEDE SER 0 O NEGATIVO IMBIMP' ,  '606 - BASE D IMPUESTO INDIR NO PUEDE SER 0 O NEGATIVO IMBIMP' ),
	T_TIPO_DATA('06' , 'C177' , '607 - FORMATO D CUOTA D IMPUESTO INDIR NO ES CORRECTO IMTIMP' ,  '607 - FORMATO D CUOTA D IMPUESTO INDIR NO ES CORRECTO IMTIMP' ),
	T_TIPO_DATA('06' , 'C178' , '608 - LA CUOTA D IMPUESTO INDIR NO PUEDE SER NEGATIVO IMTIMP' ,  '608 - LA CUOTA D IMPUESTO INDIR NO PUEDE SER NEGATIVO IMTIMP' ),
	T_TIPO_DATA('06' , 'C179' , '609 - FORMATO PORCENT D IMPUESTO INDIR NO ES CORRECTO POIMAP' ,  '609 - FORMATO PORCENT D IMPUESTO INDIR NO ES CORRECTO POIMAP' ),
	T_TIPO_DATA('06' , 'C180' , '610 - PORCENTAJE D IMPUEST INDIR NO PUEDE SER NEGATIV POIMAP' ,  '610 - PORCENTAJE D IMPUEST INDIR NO PUEDE SER NEGATIV POIMAP' ),
	T_TIPO_DATA('06' , 'C181' , '611 - EL INDICADOR DE INMOVILIZADO ES OBLIGATORIO' , '611 - EL INDICADOR DE INMOVILIZADO ES OBLIGATORIO'),
	T_TIPO_DATA('06' , 'C182' , '612 - EL INDICADOR DE RECLASIFICACIÓN ES OBLIGATORIO' , '612 - EL INDICADOR DE RECLASIFICACIÓN ES OBLIGATORIO' ),
	T_TIPO_DATA('06' , 'C183' , '613 - EL FORMATO DEL NÚMERO DE FICHA NO ES CORRECTO NUORFI' , '613 - EL FORMATO DEL NÚMERO DE FICHA NO ES CORRECTO NUORFI' ),
	T_TIPO_DATA('06' , 'C184' , '614 - EL NÚMERO DE FICHA NO PUEDE SER NEGATIVO NUORFI' , '614 - EL NÚMERO DE FICHA NO PUEDE SER NEGATIVO NUORFI' ),
	T_TIPO_DATA('06' , 'C185' , '621 - EL FORMATO DEL IMPORTE DE PAGO NO ES CORRECTO IMPAGF' , '621 - EL FORMATO DEL IMPORTE DE PAGO NO ES CORRECTO IMPAGF' ),
	T_TIPO_DATA('06' , 'C186' , '622 - EL IMPORTE DE PAGO NO PUEDE SER CERO O NEGATIVO IMPAGF' ,  '622 - EL IMPORTE DE PAGO NO PUEDE SER CERO O NEGATIVO IMPAGF' ),
	T_TIPO_DATA('06' , 'C187' , '623 - LA FORMA DE PAGO ES OBLIGATORIA' , '623 - LA FORMA DE PAGO ES OBLIGATORIA' ),
	T_TIPO_DATA('06' , 'C188' , '624 - LA FECHA DE PAGO ES OBLIGATORIA' , '624 - LA FECHA DE PAGO ES OBLIGATORIA' ),
	T_TIPO_DATA('06' , 'C189' , '625 - FORMATO D CONCEPTO INVENTARIABLE NO ES CORRECTO CLCONH' ,  '625 - FORMATO D CONCEPTO INVENTARIABLE NO ES CORRECTO CLCONH' ),
	T_TIPO_DATA('06' , 'C190' , '626 - CONCEPTO INVENTARIABLE NO PUEDE SER 0 O NEGATIV CLCONH' ,  '626 - CONCEPTO INVENTARIABLE NO PUEDE SER 0 O NEGATIV CLCONH' ),
	T_TIPO_DATA('06' , 'C191' , '627 - EL FORMATO DEL NÚMERO DE FICHA NO ES CORRECTO NUORFI' , '627 - EL FORMATO DEL NÚMERO DE FICHA NO ES CORRECTO NUORFI' ),
	T_TIPO_DATA('06' , 'C192' , '628 - EL NÚMERO DE FICHA NO PUEDE SER CERO O NEGATIVO NUORFI' ,  '628 - EL NÚMERO DE FICHA NO PUEDE SER CERO O NEGATIVO NUORFI' ),
	T_TIPO_DATA('06' , 'C193' , '631 - EL FORMATO DEL TIPO DE RELACIÓN NO ES CORRECTO COTRFF' , '631 - EL FORMATO DEL TIPO DE RELACIÓN NO ES CORRECTO COTRFF' ),
	T_TIPO_DATA('06' , 'C194' , '632 - EL TIPO DE RELACIÓN NO PUEDE SER 0 O NEGATIVO COTRFF' , '632 - EL TIPO DE RELACIÓN NO PUEDE SER 0 O NEGATIVO COTRFF' ),
	T_TIPO_DATA('06' , 'C195' , '633 - FORMATO D EJER D FACT RELACIONADA NO ES CORRECT COANOB' ,  '633 - FORMATO D EJER D FACT RELACIONADA NO ES CORRECT COANOB' ),
	T_TIPO_DATA('06' , 'C196' , '634 - EJER D FACT RELACIONADA NO PUEDE SER 0 O NEGATI COANOB' ,  '634 - EJER D FACT RELACIONADA NO PUEDE SER 0 O NEGATI COANOB' ),
	T_TIPO_DATA('06' , 'C197' , '635 - FORMATO D NÚM D FACT RELACIONADA NO ES CORRECTO COAFRB' ,  '635 - FORMATO D NÚM D FACT RELACIONADA NO ES CORRECTO COAFRB' ),
	T_TIPO_DATA('06' , 'C198' , '636 - NÚM D FACT RELACIONADA NO PUEDE SER 0 O NEGATIV COAFRB' ,  '636 - NÚM D FACT RELACIONADA NO PUEDE SER 0 O NEGATIV COAFRB' ),
	T_TIPO_DATA('06' , 'C199' , '637 - LA SERIE DE LA FACT RELACIONADA ES OBLIGATORIA COSERB' , '637 - LA SERIE DE LA FACT RELACIONADA ES OBLIGATORIA COSERB' ),
	T_TIPO_DATA('06' , 'C200' , '641 - EL NÚMERO DE RECLASIFICACIÓN NO ES NUMÉRICO COMOVR' , '641 - EL NÚMERO DE RECLASIFICACIÓN NO ES NUMÉRICO COMOVR' ),
	T_TIPO_DATA('06' , 'C201' , '642 - NÚM D RECLASIFICACIÓN NO PUEDE SER 0 O NEGATIVO COMOVR' ,  '642 - NÚM D RECLASIFICACIÓN NO PUEDE SER 0 O NEGATIVO COMOVR' ),
	T_TIPO_DATA('06' , 'C202' , '643 - FORMATO D CENTRO D RECLASIFICACIÓN NO ES CORREC CLCENF' ,  '643 - FORMATO D CENTRO D RECLASIFICACIÓN NO ES CORREC CLCENF' ),
	T_TIPO_DATA('06' , 'C203' , '644 - CENTRO DE RECLASIFICACIÓN NO PUEDE SER NEGATIVO CLCENF' ,  '644 - CENTRO DE RECLASIFICACIÓN NO PUEDE SER NEGATIVO CLCENF' ),
	T_TIPO_DATA('06' , 'C204' , '645 - FORMATO DEL IMP D RECLASIFICACIÓN NO ES CORRECT IMRCLA' ,  '645 - FORMATO DEL IMP D RECLASIFICACIÓN NO ES CORRECT IMRCLA' ),
	T_TIPO_DATA('06' , 'C205' , '646 - IMP D RECLASIFICACIÓN NO PUEDE SER 0 O NEGATIVO IMRCLA' ,  '646 - IMP D RECLASIFICACIÓN NO PUEDE SER 0 O NEGATIVO IMRCLA' ),
	T_TIPO_DATA('06' , 'C206' , '651 - FORMATO D LA ENTIDAD DE INMOVILIZ NO ES NUMÉRIC COENIV' ,  '651 - FORMATO D LA ENTIDAD DE INMOVILIZ NO ES NUMÉRIC COENIV' ),
	T_TIPO_DATA('06' , 'C207' , '652 - ENTIDAD D INMOVILIZADO NO PUEDE SER 0 O NEGATIV COENIV' ,  '652 - ENTIDAD D INMOVILIZADO NO PUEDE SER 0 O NEGATIV COENIV' ),
	T_TIPO_DATA('06' , 'C208' , '653 - FORMATO D IMPORTE D INMOVILIZADO NO ES CORRECTO IMINMO' ,  '653 - FORMATO D IMPORTE D INMOVILIZADO NO ES CORRECTO IMINMO' ),
	T_TIPO_DATA('06' , 'C209' , '654 - IMPORTE D INMOVILIZADO NO PUEDE SER 0 O NEGATIV IMINMO' ,  '654 - IMPORTE D INMOVILIZADO NO PUEDE SER 0 O NEGATIV IMINMO' ),
	T_TIPO_DATA('06' , 'C210' , '655 - FORMATO D PORCENTAJ D INMOVILIZADO NO ES CORREC POINMO' ,  '655 - FORMATO D PORCENTAJ D INMOVILIZADO NO ES CORREC POINMO' ),
	T_TIPO_DATA('06' , 'C211' , '656 - PORCENTAJE D INMOVILIZADO NO PUEDE SER NEGATIVO POINMO' ,  '656 - PORCENTAJE D INMOVILIZADO NO PUEDE SER NEGATIVO POINMO' ),
	T_TIPO_DATA('06' , 'C212' , '661 - FORMATO D CENTRO D INCORPORACIÓN NO ES CORRECTO CLCENT' ,  '661 - FORMATO D CENTRO D INCORPORACIÓN NO ES CORRECTO CLCENT' ),
	T_TIPO_DATA('06' , 'C213' , '662 - EL CENTRO D INCORPORACIÓN NO PUEDE SER NEGATIVO CLCENT' ,  '662 - EL CENTRO D INCORPORACIÓN NO PUEDE SER NEGATIVO CLCENT' ),
	T_TIPO_DATA('06' , 'C214' , '663 - EL FORMATO DEL ROL DE TERCERO NO ES CORRECTO CLROLT' , '663 - EL FORMATO DEL ROL DE TERCERO NO ES CORRECTO CLROLT'),
	T_TIPO_DATA('06' , 'C215' , '664 - EL ROL DE TERCERO NO PUEDE SER CERO O NEGATIVO CLROLT' , '664 - EL ROL DE TERCERO NO PUEDE SER CERO O NEGATIVO CLROLT' ),
	T_TIPO_DATA('06' , 'C216' , '665 - EL FORMATO D LA MODALIDAD D PAGO NO ES CORRECTO CLMOPA' ,  '665 - EL FORMATO D LA MODALIDAD D PAGO NO ES CORRECTO CLMOPA' ),
	T_TIPO_DATA('06' , 'C217' , '666 - LA MODALIDAD D PAGO NO PUEDE SER CERO O NEGATIV CLMOPA' ,  '666 - LA MODALIDAD D PAGO NO PUEDE SER CERO O NEGATIV CLMOPA' ),
	T_TIPO_DATA('06' , 'C218' , '667 - EL FORMATO DEL TIPO DE OPERACIÓN NO ES CORRECTO CLTOPE' ,  '667 - EL FORMATO DEL TIPO DE OPERACIÓN NO ES CORRECTO CLTOPE' ),
	T_TIPO_DATA('06' , 'C219' , '668 - EL TIPO D OPERACIÓN NO PUEDE SER CERO O NEGATIV CLTOPE' ,  '668 - EL TIPO D OPERACIÓN NO PUEDE SER CERO O NEGATIV CLTOPE' ),
	T_TIPO_DATA('06' , 'C220' , '669 - EL FORMATO DE LA MONEDA NO ES CORRECTO COMONE' , '669 - EL FORMATO DE LA MONEDA NO ES CORRECTO COMONE'),
	T_TIPO_DATA('06' , 'C221' , '670 - LA MONEDA NO PUEDE SER CERO O NEGATIVO COMONE' , '670 - LA MONEDA NO PUEDE SER CERO O NEGATIVO COMONE'),
	T_TIPO_DATA('06' , 'C222' , '671 - FORMATO D TIPO D IMPUESTO DIRECTO NO ES CORRECT CLTIMP' ,  '671 - FORMATO D TIPO D IMPUESTO DIRECTO NO ES CORRECT CLTIMP' ),
	T_TIPO_DATA('06' , 'C223' , '672 - EL TIPO D IMPUESTO DIRECTO NO PUEDE SER NEGATIV CLTIMP' ,  '672 - EL TIPO D IMPUESTO DIRECTO NO PUEDE SER NEGATIV CLTIMP' ),
	T_TIPO_DATA('06' , 'C224' ,  '673 - EL FORMATO DEL CAMBIO DE DIVISA NO ES CORRECTO POCVAL' , '673 - EL FORMATO DEL CAMBIO DE DIVISA NO ES CORRECTO POCVAL' ),
	T_TIPO_DATA('06' , 'C225' , '674 - EL CAMBIO DE DIVISA NO PUEDE SER NEGATIVO POCVAL' , '674 - EL CAMBIO DE DIVISA NO PUEDE SER NEGATIVO POCVAL' ),
	T_TIPO_DATA('06' , 'C226' , '675 - FORMATO D PORCEN DE IMPUESTO DIREC NO ES CORREC POIMAP' ,  '675 - FORMATO D PORCEN DE IMPUESTO DIREC NO ES CORREC POIMAP' ),
	T_TIPO_DATA('06' , 'C227' , '676 - PORCENTAJE D IMPUESTO DIREC NO PUEDE SER NEGATI POIMAP' ,  '676 - PORCENTAJE D IMPUESTO DIREC NO PUEDE SER NEGATI POIMAP' ),
	T_TIPO_DATA('06' , 'C228' , '677 - EL FORMATO DEL TOTAL A PAGAR NO ES CORRECTO IMNFAC' , '677 - EL FORMATO DEL TOTAL A PAGAR NO ES CORRECTO IMNFAC' ),
	T_TIPO_DATA('06' , 'C229' , '678 - EL TOTAL A PAGAR NO PUEDE SER NEGATIVO IMNFAC' , '678 - EL TOTAL A PAGAR NO PUEDE SER NEGATIVO IMNFAC'),
	T_TIPO_DATA('06' , 'C230' , '679 - EL FORMATO DEL TOTAL FACTURA NO ES CORRECTO IMBFAC' , '679 - EL FORMATO DEL TOTAL FACTURA NO ES CORRECTO IMBFAC' ),
	T_TIPO_DATA('06' , 'C231' , '680 - EL TOTAL FACTURA NO PUEDE SER CERO O NEGATIVO IMBFAC' , '680 - EL TOTAL FACTURA NO PUEDE SER CERO O NEGATIVO IMBFAC' ),
	T_TIPO_DATA('06' , 'C232' , '681 - FORMATO D LA BASE D IMPUESTO DIREC NO ES CORREC IMBIMP' ,  '681 - FORMATO D LA BASE D IMPUESTO DIREC NO ES CORREC IMBIMP' ),
	T_TIPO_DATA('06' , 'C233' , '682 - LA BASE D IMPUESTO DIRECTO NO PUEDE SER NEGATIV IMBIMP' ,  '682 - LA BASE D IMPUESTO DIRECTO NO PUEDE SER NEGATIV IMBIMP' ),
	T_TIPO_DATA('06' , 'C234' , '683 - FORMATO D CUOTA D IMPUESTO DIRECTO NO ES CORREC IMTIMP' ,  '683 - FORMATO D CUOTA D IMPUESTO DIRECTO NO ES CORREC IMTIMP' ),
	T_TIPO_DATA('06' , 'C235' , '684 - CUOTA DE IMPUESTO DIRECTO NO PUEDE SER NEGATIVO IMTIMP' ,  '684 - CUOTA DE IMPUESTO DIRECTO NO PUEDE SER NEGATIVO IMTIMP' ),
	T_TIPO_DATA('06' , 'C236' , '700 - ERROR EN ACCESO A TABLAS DB2' , '700 - ERROR EN ACCESO A TABLAS DB2' ),
	T_TIPO_DATA('06' , 'C237' , '701 - EL NÚMERO DE FACTURA NO ES NUMÉRICO COAFRA' , '701 - EL NÚMERO DE FACTURA NO ES NUMÉRICO COAFRA' ),
	T_TIPO_DATA('06' , 'C238' , '702 - EL NÚMERO DE FACTURA NO PUEDE SER CERO COAFRA' , '702 - EL NÚMERO DE FACTURA NO PUEDE SER CERO COAFRA'),
	T_TIPO_DATA('06' , 'C239' , '703 - LA SERIE DE LA FACTURA ES OBLIGATORIA' , '703 - LA SERIE DE LA FACTURA ES OBLIGATORIA' ),
	T_TIPO_DATA('06' , 'C240' , '704 - NO EXISTE LA FORMA DE PAGO' , '704 - NO EXISTE LA FORMA DE PAGO' ),
	T_TIPO_DATA('06' , 'C241' , '705 - EL FORMATO DE LA FECHA DE EMISIÓN NO ES CORRECTO' , '705 - EL FORMATO DE LA FECHA DE EMISIÓN NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C242' , '706 - EL VALOR DE LA FECHA DE EMISIÓN NO ES CORRECTO' , '706 - EL VALOR DE LA FECHA DE EMISIÓN NO ES CORRECTO' ),
	T_TIPO_DATA('06' , 'C243' , '707 - LA FECHA DE EMISIÓN NO ES COHERENTE' , '707 - LA FECHA DE EMISIÓN NO ES COHERENTE' ),
	T_TIPO_DATA('06' , 'C244' , '710 - LA FACTURA NO EXISTE' , '710 - LA FACTURA NO EXISTE' ),
	T_TIPO_DATA('06' , 'C245' , '711 - LA FACTURA YA ESTÁ ANULADA. NO SE PUEDE ANULAR' , '711 - LA FACTURA YA ESTÁ ANULADA. NO SE PUEDE ANULAR' ),
	T_TIPO_DATA('06' , 'C246' , '712 - LA FACTURA ES DE ANULACIÓN. NO SE PUEDE ANULAR' , '712 - LA FACTURA ES DE ANULACIÓN. NO SE PUEDE ANULAR' ),
	T_TIPO_DATA('06' , 'C247' , '713 - NO ES FACT PPAL. NO SE ANULAN FACT D ANULA O D SUPLIDO' ,  '713 - NO ES FACT PPAL. NO SE ANULAN FACT D ANULA O D SUPLIDO' ),
	T_TIPO_DATA('06' , 'C248' , '714 - FACTURA CON IRPF. NO SE PERMITE ANULA EN DISTINTO EJER' ,  '714 - FACTURA CON IRPF. NO SE PERMITE ANULA EN DISTINTO EJER' ),
	T_TIPO_DATA('06' , 'C249' , '715 - EL ESTADO DE LA FACTURA NO PERMITE LA ANULACIÓN' , '715 - EL ESTADO DE LA FACTURA NO PERMITE LA ANULACIÓN' ),
	T_TIPO_DATA('06' , 'C250' , '716 - NO SE ENCUENTRA EL TERCERO DE LA FACTURA' , '716 - NO SE ENCUENTRA EL TERCERO DE LA FACTURA' ),
	T_TIPO_DATA('06' , 'C251' , '717 - TIPO D IDENTIFICACIÓN FISCAL NO = QUE EL DE LA FACTURA' ,  '717 - TIPO D IDENTIFICACIÓN FISCAL NO = QUE EL DE LA FACTURA' ),
	T_TIPO_DATA('06' , 'C252' , '718 - NÚM D IDENTIFICACIÓN FISCAL NO = QUE EL DE LA FACTURA' , '718 - NÚM D IDENTIFICACIÓN FISCAL NO = QUE EL DE LA FACTURA' ),
	T_TIPO_DATA('06' , 'C253' , '719 - NÚM D FACT DEL PROVEEDOR NO COINCIDE CON EL DE LA FACT' ,  '719 - NÚM D FACT DEL PROVEEDOR NO COINCIDE CON EL DE LA FACT' ),
	T_TIPO_DATA('06' , 'C254' , '720 - LA FECHA DE EMISIÓN NO COINCIDE CON LA DE LA FACTURA' , '720 - LA FECHA DE EMISIÓN NO COINCIDE CON LA DE LA FACTURA' ),
	T_TIPO_DATA('06' , 'C255' , '721 - FACT ES EMITIDA D AUTORREPERCUSIÓN. NO SE PUEDE ANULAR' ,  '721 - FACT ES EMITIDA D AUTORREPERCUSIÓN. NO SE PUEDE ANULAR' ),
	T_TIPO_DATA('06' , 'C256' , '722 - NO EXISTE EL CONCEPTO' , '722 - NO EXISTE EL CONCEPTO' ),
	T_TIPO_DATA('06' , 'C257' , '723 - FACT TIENE UN CONCEPTO INVENTARIABLE. NO SE PUEDE ANUL' ,  '723 - FACT TIENE UN CONCEPTO INVENTARIABLE. NO SE PUEDE ANUL' ),
	T_TIPO_DATA('06' , 'C258' , '724 - IMPUESTO INDIRE NO ESTÁ VIGENTE EN FECH D EMISIÓN FACT' ,  '724 - IMPUESTO INDIRE NO ESTÁ VIGENTE EN FECH D EMISIÓN FACT' ),
	T_TIPO_DATA('06' , 'C259' , '725 - NO SE ANUL FACT EMI CON IVA CONTAB ANTES 2011 CAMB POR' ,  '725 - NO SE ANUL FACT EMI CON IVA CONTAB ANTES 2011 CAMB POR' ),
	T_TIPO_DATA('06' , 'C260' , '726 - LA FACT NO ES DEL SISTEMA INDICADO. NO SE PUEDE ANULAR' ,  '726 - LA FACT NO ES DEL SISTEMA INDICADO. NO SE PUEDE ANULAR' ),
	T_TIPO_DATA('06' , 'C261' , '810 - ERROR GENERAL ACTIVO ADJUDICADO' , '810 - ERROR GENERAL ACTIVO ADJUDICADO' ),
	T_TIPO_DATA('06' , 'C262' , '811 - TIPO DE CAMBIO A CEROS POCVAL' , '811 - TIPO DE CAMBIO A CEROS POCVAL' ),
	T_TIPO_DATA('06' , 'C263' , '812 - FICHA INFORMADA EN REGIDE DATOS D INCREMENTO DE ACTIVO' ,  '812 - FICHA INFORMADA EN REGIDE DATOS D INCREMENTO DE ACTIVO' ),
	T_TIPO_DATA('06' , 'C264' , '813 - NO EXISTE NÚMERO DE FICHA COINMO' , '813 - NO EXISTE NÚMERO DE FICHA COINMO' ),
	T_TIPO_DATA('06' , 'C265' , '814 - ERROR EN ACCESO TABLA DE ADICIONES' , '814 - ERROR EN ACCESO TABLA DE ADICIONES' ),
	T_TIPO_DATA('06' , 'C266' , '815 - LA FICHA NO ESTA EN ESTADO DE ALTA' , '815 - LA FICHA NO ESTA EN ESTADO DE ALTA' ),
	T_TIPO_DATA('06' , 'C267' , '816 - NO EXISTE LA ADICIÓN PARA LA FICHA' , '816 - NO EXISTE LA ADICIÓN PARA LA FICHA' ),
	T_TIPO_DATA('06' , 'C268' , '817 - ADICIÓN EN ESTADO VENDIDA' , '817 - ADICIÓN EN ESTADO VENDIDA' ),
	T_TIPO_DATA('06' , 'C269' , '818 - CLAVE DETALLE DE FACTURA ERRONEO' , '818 - CLAVE DETALLE DE FACTURA ERRONEO' ),
	T_TIPO_DATA('06' , 'C270' , '819 - TERCERO NO ENCONTRADO' , '819 - TERCERO NO ENCONTRADO' ),
	T_TIPO_DATA('06' , 'C271' , '820 - PROPUESTA NO INFORMADA' , '820 - PROPUESTA NO INFORMADA' ),
	T_TIPO_DATA('06' , 'C272' , '980 - NO EXISTE EL REGISTRO DE CABECERA DE FACTURA' , '980 - NO EXISTE EL REGISTRO DE CABECERA DE FACTURA' ),
	T_TIPO_DATA('06' , 'C273' , '981 - EL CÓDIGO DE REGISTRO NO ES VÁLIDO CODREG' , '981 - EL CÓDIGO DE REGISTRO NO ES VÁLIDO CODREG' ),
	T_TIPO_DATA('06' , 'C274' , '982 - EL CÓDIGO DE ENTIDAD NO ES NUMÉRICO COENTV' , '982 - EL CÓDIGO DE ENTIDAD NO ES NUMÉRICO COENTV' ),
	T_TIPO_DATA('06' , 'C275' , '983 - EL CÓDIGO DE ENTIDAD NO PUEDE SER CERO COENTV' , '983 - EL CÓDIGO DE ENTIDAD NO PUEDE SER CERO COENTV'),
	T_TIPO_DATA('06' , 'C276' , '984 - EL NÚMERO DE OPERACIÓN NO ES NUMÉRICO IDNOPE' , '984 - EL NÚMERO DE OPERACIÓN NO ES NUMÉRICO IDNOPE' ),
	T_TIPO_DATA('06' , 'C277' , '985 - EL NÚMERO DE OPERACIÓN NO PUEDE SER CERO IDNOPE' , '985 - EL NÚMERO DE OPERACIÓN NO PUEDE SER CERO IDNOPE' ),
	T_TIPO_DATA('06' , 'C278' , '986 - EL EJERCICIO NO ES NUMÉRICO COANOF' , '986 - EL EJERCICIO NO ES NUMÉRICO COANOF' ),
	T_TIPO_DATA('06' , 'C279' , '987 - EL EJERCICIO NO PUEDE SER CERO COANOF' , '987 - EL EJERCICIO NO PUEDE SER CERO COANOF' ),
	T_TIPO_DATA('06' , 'C280' , '988 - EL NÚMERO DE MOVIMIENTO NO ES NUMÉRICO COMOVT / COMOVP' ,  '988 - EL NÚMERO DE MOVIMIENTO NO ES NUMÉRICO COMOVT / COMOVP' ),
	T_TIPO_DATA('06' , 'C281' , '989 - EL NÚM DE MOVIMIENTO NO PUEDE SER CERO COMOVT / COMOVP' ,  '989 - EL NÚM DE MOVIMIENTO NO PUEDE SER CERO COMOVT / COMOVP' ),
	T_TIPO_DATA('06' , 'C282' , '990 - EL NÚMERO DE FACTURA PRINCIPAL NO ES NUMÉRICO IDNOP1' , '990 - EL NÚMERO DE FACTURA PRINCIPAL NO ES NUMÉRICO IDNOP1' ),
	T_TIPO_DATA('06' , 'C283' , '991 - EL NÚM DE FACTURA PRINCIPAL NO PUEDE SER CERO IDNOP1' , '991 - EL NÚM DE FACTURA PRINCIPAL NO PUEDE SER CERO IDNOP1' )

		); 
    V_TMP_TIPO_DATA T_TIPO_DATA;
    
BEGIN	
	
	DBMS_OUTPUT.PUT_LINE('[INICIO] ');

	-- LOOP para insertar los valores en la tabla indicada
    	DBMS_OUTPUT.PUT_LINE('[INFO]: INSERCION EN '||V_TEXT_TABLA||'] ');
    	FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
      	LOOP
             	V_TMP_TIPO_DATA := V_TIPO_DATA(I);

--              Buscar el campo DD_TEG_ID a partir del campo DD_TEG_CODIGO en la tabla DD_TEG_TIPO_ERROR_GASTO. 
--              Identificar si existe el tipo de error en la tabla DD_TEG_TIPO_ERROR_GASTO.
                V_MSQL := 'SELECT COUNT(1) FROM '|| V_ESQUEMA ||'.'|| V_TEXT_TABLA_AUX || ' WHERE DD_TEG_CODIGO = '''|| TRIM(V_TMP_TIPO_DATA(1)) ||'''';
                EXECUTE IMMEDIATE V_MSQL INTO V_NUM_TIPO;

                IF V_NUM_TIPO  > 0 THEN				

                   V_MSQL := 'SELECT DD_'||V_TRES_LETRAS_TABLA_AUX||'_ID FROM '|| V_ESQUEMA ||'.'|| V_TEXT_TABLA_AUX || ' WHERE DD_'||V_TRES_LETRAS_TABLA_AUX||'_CODIGO = '''|| TRIM(V_TMP_TIPO_DATA(1)) ||'''';
                   EXECUTE IMMEDIATE V_MSQL INTO V_TEG_ID;
--                 DBMS_OUTPUT.PUT_LINE(V_MSQL);  
--                 DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.'|| V_TEXT_TABLA_AUX || '.DD_'||V_TRES_LETRAS_TABLA_AUX||'_ID =' || V_TEG_ID ||'');
   
                ELSE		

                   DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.'|| V_TEXT_TABLA_AUX || '. No existe el tipo error '|| TRIM(V_TMP_TIPO_DATA(1)) ||'');
                END IF;
      

	        --Recuperamos el id del tipo de error a insertar
--        	V_SQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.'||V_TEXT_TABLA||' WHERE DD_'||V_TRES_LETRAS_TABLA||'_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(2))||'''';
--        	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
   
	        --Comprobamos el dato a insertar
        	V_SQL := 'SELECT COUNT(1) FROM '||V_ESQUEMA||'.'||V_TEXT_TABLA||' WHERE DD_'||V_TRES_LETRAS_TABLA||'_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(2))||'''';
        	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
        
	        --Si existe lo modificamos
        	IF V_NUM_TABLAS > 0 THEN				
			DBMS_OUTPUT.PUT_LINE('[INFO]: MODIFICAMOS EL REGISTRO '''|| TRIM(V_TMP_TIPO_DATA(2)) ||'''');

	       	  	V_MSQL := 'UPDATE '|| V_ESQUEMA ||'.'||V_TEXT_TABLA||' '||
		        		'SET DD_'||V_TRES_LETRAS_TABLA_AUX||'_ID = '''||TRIM( V_TEG_ID )||''''|| 
					', DD_'||V_TRES_LETRAS_TABLA||'_DESCRIPCION = SUBSTR('''||TRIM(V_TMP_TIPO_DATA(3))||'''1, 20)'|| 
					', DD_'||V_TRES_LETRAS_TABLA||'_DESCRIPCION_LARGA = '''||TRIM(V_TMP_TIPO_DATA(4))||''''||
					', USUARIOMODIFICAR = ''DML'' , FECHAMODIFICAR = SYSDATE '||
					'WHERE DD_'||V_TRES_LETRAS_TABLA||'_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(2))||'''';
		  	EXECUTE IMMEDIATE V_MSQL;

		  	DBMS_OUTPUT.PUT_LINE('[INFO]: REGISTRO MODIFICADO CORRECTAMENTE');

          	--Si no existe, lo insertamos   
       		ELSE
       			DBMS_OUTPUT.PUT_LINE('[INFO]: INSERTAMOS EL REGISTRO '''|| TRIM(V_TMP_TIPO_DATA(2)) ||'''');   

          		V_MSQL := 'SELECT '|| V_ESQUEMA ||'.S_'||V_TEXT_TABLA||'.NEXTVAL FROM DUAL';
	       		EXECUTE IMMEDIATE V_MSQL INTO V_ID;
	
          		V_MSQL := 'INSERT INTO '|| V_ESQUEMA ||'.'||V_TEXT_TABLA||' (' ||
                      		     'DD_'||V_TRES_LETRAS_TABLA||'_ID, DD_'||V_TRES_LETRAS_TABLA_AUX||'_ID, DD_'||V_TRES_LETRAS_TABLA||'_CODIGO, DD_'||V_TRES_LETRAS_TABLA||'_DESCRIPCION, DD_'||V_TRES_LETRAS_TABLA||'_DESCRIPCION_LARGA,' ||
  				     'VERSION, USUARIOCREAR, FECHACREAR, BORRADO) ' ||
                      		'SELECT ' || V_ID || ',' || V_TEG_ID || ','''||TRIM(V_TMP_TIPO_DATA(2))||''',SUBSTR('''||TRIM(V_TMP_TIPO_DATA(3))||''', 1, 20) ,'''||TRIM(V_TMP_TIPO_DATA(4))||''',' ||
                    		'0, ''DML'',SYSDATE,0 FROM DUAL';
        		EXECUTE IMMEDIATE V_MSQL;
          		DBMS_OUTPUT.PUT_LINE('[INFO]: REGISTRO INSERTADO CORRECTAMENTE');

        	END IF;
      	END LOOP;
    	
	COMMIT;
	
	DBMS_OUTPUT.PUT_LINE('[FIN]: DICCIONARIO '||V_TEXT_TABLA||' ACTUALIZADO CORRECTAMENTE ');
   
EXCEPTION
     WHEN OTHERS THEN
          err_num := SQLCODE;
          err_msg := SQLERRM;

          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(err_msg);

          ROLLBACK;
          RAISE;          

END;

/

EXIT

