--/*
--##########################################
--## AUTOR=Pablo Meseguer
--## FECHA_CREACION=20180608
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-1005
--## PRODUCTO=NO
--##
--## Finalidad: Actualizar campos en ACT_ACTIVO
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE

    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar    
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_EXISTS NUMBER(10);


BEGIN
	DBMS_OUTPUT.PUT_LINE('[INICIO] ACTUALIZACION DE CARTERA JAIPUR-INMOBILIARIO');
	--ACTULIZAMOS LOS PROPIETARIOS
    V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_PAC_PROPIETARIO_ACTIVO PAC
	SET 
	  PAC.PRO_ID = (SELECT PRO.PRO_ID FROM '||V_ESQUEMA||'.ACT_PRO_PROPIETARIO PRO 
					INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = PRO.DD_CRA_ID
					WHERE CRA.DD_CRA_CODIGO=''07'' AND PRO.PRO_DOCIDENTIF=''B86053394'' AND PRO_CODIGO_UVEM = 7038),
	  PAC.USUARIOMODIFICAR = ''REMVIP-1005'',
	  PAC.FECHAMODIFICAR = SYSDATE 
	WHERE PAC.PAC_ID IN (SELECT PAC.PAC_ID
						  FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
						  INNER JOIN '||V_ESQUEMA||'.ACT_PAC_PROPIETARIO_ACTIVO PAC ON PAC.ACT_ID = ACT.ACT_ID
						  INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
						  INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = ACT.DD_SCR_ID
						  WHERE CRA.DD_CRA_CODIGO IN (''09'', ''07'')--JAIPUR/CERBERUS
						  AND SCR.DD_SCR_CODIGO IN (''21'', ''22'', ''17'') --INMOBILIARIO/FINANCIERO/INMOBILIARIO
						  AND PAC.PRO_ID <> (SELECT PRO.PRO_ID FROM '||V_ESQUEMA||'.ACT_PRO_PROPIETARIO PRO 
											INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = PRO.DD_CRA_ID
											WHERE CRA.DD_CRA_CODIGO=''07'' AND PRO.PRO_DOCIDENTIF=''B86053394'' AND PRO_CODIGO_UVEM = 7038))';
        EXECUTE IMMEDIATE V_MSQL;       
        DBMS_OUTPUT.PUT_LINE('[INFO] Se actualizan '||SQL%ROWCOUNT||' registros en ACT_PAC_PROPIETARIO_ACTIVO para asignar el propietario ''CERBERUS IBERIA ADVISORS''');    
    
    DBMS_OUTPUT.PUT_LINE('[INICIO] ACTUALIZACION DE CARTERA JAIPUR-INMOBILIARIO');
    --COMPROBAMOS EXISTENCIA DATOS
    V_MSQL := 'SELECT COUNT(1)
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
				INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = ACT.DD_SCR_ID
				WHERE CRA.DD_CRA_CODIGO = ''09''--JAIPUR
				AND SCR.DD_SCR_CODIGO = ''22'' --INMOBILIARIO';
    EXECUTE IMMEDIATE V_MSQL INTO V_EXISTS;
    
    IF V_EXISTS > 1 THEN
        --UPDATEAMOS CARTERA Y SUBCARTERA       
        V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_ACTIVO ACT
					SET
					  ACT.DD_CRA_ID = (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = ''07''),
					  ACT.DD_SCR_ID = (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = ''37''),
					  ACT.USUARIOMODIFICAR = ''REMVIP-1005'',
					  ACT.FECHAMODIFICAR = SYSDATE
					WHERE ACT.DD_CRA_ID = (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = ''09'')
					AND  ACT.DD_SCR_ID = (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = ''22'')';
        EXECUTE IMMEDIATE V_MSQL;       
        DBMS_OUTPUT.PUT_LINE('[INFO] Se actualizan '||SQL%ROWCOUNT||' registros en ACT_ACTIVO para Jaipur - Inmobiliario');    
    ELSE
        DBMS_OUTPUT.PUT_LINE('[INFO] No existen activo de Jaipur - Inmobiliario en la tabla ACT_ACTIVO');
    END IF;
    
    
        DBMS_OUTPUT.PUT_LINE('[INICIO] ACTUALIZACION DE CARTERA JAIPUR-FINANCIERO');
    --COMPROBAMOS EXISTENCIA DATOS
    V_MSQL := 'SELECT COUNT(1)
				FROM '||V_ESQUEMA||'.ACT_ACTIVO ACT
				INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
				INNER JOIN '||V_ESQUEMA||'.DD_SCR_SUBCARTERA SCR ON SCR.DD_SCR_ID = ACT.DD_SCR_ID
				WHERE CRA.DD_CRA_CODIGO = ''09''--JAIPUR
				AND SCR.DD_SCR_CODIGO = ''21'' --FINANCIERO';
    EXECUTE IMMEDIATE V_MSQL INTO V_EXISTS;
    
    IF V_EXISTS > 1 THEN
        --UPDATEAMOS CARTERA Y SUBCARTERA       
        V_MSQL := 'UPDATE '||V_ESQUEMA||'.ACT_ACTIVO ACT
					SET
					  ACT.DD_CRA_ID = (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = ''07''),
					  ACT.DD_SCR_ID = (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = ''38''),
					  ACT.USUARIOMODIFICAR = ''REMVIP-1005'',
					  ACT.FECHAMODIFICAR = SYSDATE
					WHERE ACT.DD_CRA_ID = (SELECT DD_CRA_ID FROM '||V_ESQUEMA||'.DD_CRA_CARTERA WHERE DD_CRA_CODIGO = ''09'')
					AND  ACT.DD_SCR_ID = (SELECT DD_SCR_ID FROM '||V_ESQUEMA||'.DD_SCR_SUBCARTERA WHERE DD_SCR_CODIGO = ''21'')';
        EXECUTE IMMEDIATE V_MSQL;       
        DBMS_OUTPUT.PUT_LINE('[INFO] Se actualizan '||SQL%ROWCOUNT||' registros en ACT_ACTIVO para Jaipur - Financiero');    
    ELSE
        DBMS_OUTPUT.PUT_LINE('[INFO] No existen activo de Jaipur - Financiero en la tabla ACT_ACTIVO');
    END IF;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SQLERRM;
        DBMS_OUTPUT.PUT_LINE('KO no modificada');
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
        DBMS_OUTPUT.put_line(err_msg);
        ROLLBACK;
        RAISE;          
END;
/
EXIT
