
package org.cajamar.ws.S_C_RECOVERY_CUENTA_DAT_CF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "S_C_RECOVERY_CUENTA_DAT_CFType", targetNamespace = "http://cajamar.org/webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SCRECOVERYCUENTADATCFType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.cajamar.ws.S_C_RECOVERY_CUENTA_DAT_CF.OUTPUT
     */
    @WebMethod(operationName = "S_C_RECOVERY_CUENTA_DAT_CF")
    @WebResult(name = "OUTPUT", targetNamespace = "http://cajamar.org/webservice", partName = "parameters")
    public OUTPUT sCRECOVERYCUENTADATCF(
        @WebParam(name = "INPUT", targetNamespace = "http://cajamar.org/webservice", partName = "parameters")
        INPUT parameters);

}
