WHENEVER SQLERROR EXIT SQL.SQLCODE;

UPDATE REMMASTER.ENTIDADCONFIG SET DATAVALUE='/ora11g/instantclient/sqlldr' WHERE DATAKEY='pathToSqlLoader' AND ENTIDAD_ID=1;
UPDATE REMMASTER.ENTIDADCONFIG SET DATAVALUE='jdbc:oracle:thin:REM01/j0b3d2CHe3I=04045316@//rem-db:1521/orcl' WHERE DATAKEY='url' AND ENTIDAD_ID=1;
UPDATE REMMASTER.ENTIDADCONFIG SET DATAVALUE='REM01' WHERE DATAKEY='username' AND ENTIDAD_ID=1;
UPDATE REMMASTER.ENTIDADCONFIG SET DATAVALUE='j0b3d2CHe3I=04045316' WHERE DATAKEY='password' AND ENTIDAD_ID=1;
UPDATE REMMASTER.ENTIDADCONFIG SET DATAVALUE='REM01/j0b3d2CHe3I=04045316@//rem-db:1521/orcl' WHERE DATAKEY='connectionInfo' AND ENTIDAD_ID=1;

exit;
