--/*
--##########################################
--## AUTOR=Guillermo Llidó Parra
--## FECHA_CREACION=20190531
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=HREOS-5932
--## PRODUCTO=NO
--## Finalidad: Rollback Ofertas , Expedientes y Tramites.
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 

DECLARE
    err_num NUMBER; -- Numero de error.
    err_msg VARCHAR2(2048); -- Mensaje de error.
    V_ESQUEMA VARCHAR2(25 CHAR):= 'REM01'; -- Configuracion Esquemas.
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= 'REMMASTER'; -- Configuracion Esquemas.
    V_USUARIOMODIFICAR VARCHAR(100 CHAR):= '';
    V_MSQL VARCHAR2(4000 CHAR);
    
	V_TABLA_BACKUP VARCHAR2(100 CHAR);
	V_ESQUEMA_BACKUP VARCHAR2(100 CHAR);
	
BEGIN

  DBMS_OUTPUT.put_line('[INICIO] Ejecutando [ROLLBACK OFERTAS , EXPEDIENTES , TRAMITES ]  ...........');

/**
 ROLLBACK ACTIVOS
**/

		DBMS_OUTPUT.put_line('	[INFO] Se realiza rollback sobre tabla OFR_OFERTAS ');
		
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''ACT_ACTIVO'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_ACTIVO ACT USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (ACT.ACT_ID =  AUX.ACT_ID)
					WHEN MATCHED THEN UPDATE SET 
						ACT.DD_TCO_ID = AUX.DD_TCO_ID
					,	ACT.DD_TAL_ID = AUX.DD_TAL_ID
					,	ACT.USUARIOMODIFICAR = AUX.USUARIOMODIFICAR
					,	ACT.fechamodificar = AUX.fechamodificar
					,	ACT.USUARIOBORRAR = AUX.USUARIOBORRAR
					,	ACT.FECHABORRAR = AUX.FECHABORRAR
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' activos.'); 
  		

/**
 ROLLBACK OFERTAS
**/

		DBMS_OUTPUT.put_line('	[INFO] Se realiza rollback sobre tabla OFR_OFERTAS ');
		
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''OFR_OFERTAS'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.OFR_OFERTAS OFR USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (OFR.OFR_ID =  AUX.OFR_ID)
					WHEN MATCHED THEN UPDATE SET 
						OFR.DD_EOF_ID = AUX.DD_EOF_ID
					,	OFR.USUARIOMODIFICAR = AUX.USUARIOMODIFICAR
					,	OFR.FECHAMODIFICAR = AUX.FECHAMODIFICAR
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' ofertas.'); 
  		
  		
/**
 ROLLBACK EXPEDIENTES
**/ 		
		
		DBMS_OUTPUT.put_line('	[INFO] Se realiza rollback sobre tabla ECO_EXPEDIENTE_COMERCIAL ');
		
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''ECO_EXPEDIENTE_COMERCIAL'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (ECO.ECO_ID =  AUX.ECO_ID)
					WHEN MATCHED THEN UPDATE SET 
						ECO.DD_EEC_ID 			= AUX.DD_EEC_ID
					,	ECO.ECO_FECHA_ANULACION = AUX.ECO_FECHA_ANULACION
					,	ECO.USUARIOMODIFICAR 	= AUX.USUARIOMODIFICAR
					,	ECO.FECHAMODIFICAR 		= AUX.FECHAMODIFICAR
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' expedientes.'); 
  		
/**
 ROLLBACK TRAMITES (ACT_TRA_TRAMITE)
**/ 		
		
		DBMS_OUTPUT.put_line('	[INFO] Se realiza rollback sobre tabla ACT_TRA_TRAMITE ');
		
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''ACT_TRA_TRAMITE'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (TRA.TRA_ID =  AUX.TRA_ID)
					WHEN MATCHED THEN UPDATE SET 
						TRA.TRA_FECHA_FIN 		= AUX.TRA_FECHA_FIN
					,	TRA.USUARIOMODIFICAR 	= AUX.USUARIOMODIFICAR
					,	TRA.FECHAMODIFICAR 		= AUX.FECHAMODIFICAR
					,	TRA.USUARIOBORRAR 		= AUX.USUARIOBORRAR
					,	TRA.FECHABORRAR 		= AUX.FECHABORRAR
					,	TRA.BORRADO 			= AUX.BORRADO			
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' ACT_TRA_TRAMITE.'); 	

		DBMS_OUTPUT.put_line('	[INFO] Se realiza rollback sobre tabla ACT_TRA_TRAMITE ');
		
/**
 ROLLBACK TRAMITES (TAR_TAREAS_NOTIFICACIONES)
**/ 		
				
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''TAR_TAREAS_NOTIFICACIONES'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR_ID USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (TAR.TAR_ID =  AUX.TAR_ID)
					WHEN MATCHED THEN UPDATE SET 
						TAR_ID.TAR_FECHA_FIN 			= AUX.TAR_FECHA_FIN
					,	TAR_ID.TAR_TAREA_FINALIZADA		= AUX.TAR_TAREA_FINALIZADA
					,	TAR_ID.USUARIOMODIFICAR 		= AUX.USUARIOMODIFICAR
					,	TAR_ID.FECHAMODIFICAR 			= AUX.FECHAMODIFICAR
					,	TAR_ID.USUARIOBORRAR 			= AUX.USUARIOBORRAR
					,	TAR_ID.FECHABORRAR 				= AUX.FECHABORRAR
					,	TAR_ID.BORRADO 					= AUX.BORRADO
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' TEX_TAREA_EXTERNA.'); 	
  		
/**
 ROLLBACK TRAMITES (TEX_TAREA_EXTERNA)
**/ 		
				
		-- OBTENEMOS LA TABLA BACKUP
		V_MSQL := 'SELECT TABLA_BACKUP FROM '||V_ESQUEMA||'.AUX_MIG_ALQUILERES_TAB_AFEC  WHERE TABLA = ''TEX_TAREA_EXTERNA'' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_TABLA_BACKUP;
		-- OBTENEMOS EL ESQUEMA TABLA BACKUP
		V_MSQL := 'SELECT TABLESPACE_NAME FROM SYS.ALL_TABLES WHERE TABLE_NAME = '''||V_TABLA_BACKUP||''' ';
		EXECUTE IMMEDIATE V_MSQL INTO V_ESQUEMA_BACKUP;
		
		V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TEX USING '||V_ESQUEMA_BACKUP||'.'||V_TABLA_BACKUP||' AUX 
					ON (TEX.TEX_ID =  AUX.TEX_ID)
					WHEN MATCHED THEN UPDATE SET 
						TEX.USUARIOMODIFICAR 		= AUX.USUARIOMODIFICAR
					,	TEX.FECHAMODIFICAR 			= AUX.FECHAMODIFICAR
					,	TEX.USUARIOBORRAR 			= AUX.USUARIOBORRAR
					,	TEX.FECHABORRAR 			= AUX.FECHABORRAR
					,	TEX.BORRADO 				= AUX.BORRADO
					';
									
		EXECUTE IMMEDIATE V_MSQL;
  		
  		DBMS_OUTPUT.PUT_LINE('	[INFO] Se ha hecho rollback de  '||SQL%ROWCOUNT||' TEX_TAREA_EXTERNA.'); 		
  		
  		
COMMIT;
  
 DBMS_OUTPUT.put_line('[FIN] Ejecutando [ROLLBACK OFERTAS , EXPEDIENTES , TRAMITES ]  ...........');

EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(ERR_MSG);
          ROLLBACK;
          RAISE;   
END;
/
EXIT;
