export ESQUEMA_EJECUCION=REM01
export VARIABLES_SUSTITUCION='#ESQUEMA#;REM01,#ESQUEMA_MASTER#;REMMASTER,#TABLESPACE_INDEX#;REM_IDX'
export MULTIENTIDAD='SAREB'
export SAREB='REM01'

export GENERATE_BAT='false'

export UNIFIED_PACKAGE='true'
