-- INSERT DEL DICCIONARIO DE TIPOS DE EXPEDIENTE

INSERT INTO DD_TPX_TIPO_EXPEDIENTE 
(DD_TPX_ID, DD_TPX_CODIGO, DD_TPX_DESCRIPCION, DD_TPX_DESCRIPCION_LARGA, USUARIOCREAR, FECHACREAR) VALUES
(S_DD_TPX_TIPO_EXPEDIENTE.NEXTVAL,'INT','Expediente interno','Expediente interno','SAG',sysdate);

INSERT INTO DD_TPX_TIPO_EXPEDIENTE 
(DD_TPX_ID, DD_TPX_CODIGO, DD_TPX_DESCRIPCION, DD_TPX_DESCRIPCION_LARGA, USUARIOCREAR, FECHACREAR) VALUES
(S_DD_TPX_TIPO_EXPEDIENTE.NEXTVAL,'REC','Expediente de recobro','Expediente de recobro','SAG',sysdate);

commit;
