set verify off;

-- borrar la estructura

DROP TABLE CRC_CICLO_RECOBRO_CNT;

DROP TABLE  CRP_CICLO_RECOBRO_PER;

DROP TABLE CRE_CICLO_RECOBRO_EXP;

DROP TABLE EXR_EXPEDIENTE_RECOBRO;

DROP SEQUENCE S_CRE_CICLO_RECOBRO_EXP;

DROP SEQUENCE S_CRC_CICLO_RECOBRO_CNT;

DROP SEQUENCE S_CRP_CICLO_RECOBRO_PER;
