OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_2681
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ID_ACTIVO			NULLIF(ID_ACTIVO=BLANKS)						"TRIM(:ID_ACTIVO)",
	TIPO_PUBLICACION		NULLIF(TIPO_PUBLICACION=BLANKS)						"TRIM(:TIPO_PUBLICACION)",
	FECHA_INI			NULLIF(FECHA_INI=BLANKS)						"TRIM(:FECHA_INI)"
	
)
