--/*
--##########################################
--## AUTOR=Alberto S
--## FECHA_CREACION=20160323
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=PRODUCTO-897
--## PRODUCTO=NO
--## Finalidad: DML para crear nuevos tipos de despacho y grupo, sta, usd... de Haya-Sareb
--##           
--## INSTRUCCIONES: Configurar las variables necesarias en el principio del DECLARE
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
set linesize 2000
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

   V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
   V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master

   V_NUM_REGS NUMBER(16); -- Vble. para validar la existencia de un registro   
   ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
   ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.

    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.
    V_TMP NUMBER(16); -- Vble. para validar la existencia de una tabla.      
    V_TMP_2 NUMBER(16); -- Vble. para validar la existencia de una tabla.

    V_DDNAME VARCHAR2(30):='USU_USUARIOS';
    V_DDNAME_STA VARCHAR2(30):='DD_STA_SUBTIPO_TAREA_BASE';
    V_DDNAME_TGP VARCHAR2(30):= 'TGP_TIPO_GESTOR_PROPIEDAD';
    V_DDNAME_USD VARCHAR2(30):= 'USD_USUARIOS_DESPACHOS';
    V_DD_TDE_ID_OFI NUMBER(16); -- Vble. para almacenar el DD_TDE_ID del tipo despacho oficina.

BEGIN
-------Gestor de Deuda
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor de Deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGDEU''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Gestor de deuda');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo gestor de deuda');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Gestor de deuda'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo gestor de deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GGDEU''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
		V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
		|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GGDEU'',''1234'',''Grupo - Gestor de deuda'', ''PRODUCTO-897'', sysdate, 1)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''803''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GDEU''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''803'',''Tarea del Gestor deuda'',''Tarea del Gestor deuda'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GDEU''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''UNIGES'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GGDEU''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGDEU'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Gestor Auditoria
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Gestor auditoria');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Gestor auditoria');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Gestor Auditoria'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GGAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GGAUD'',''1234'',''Grupo - Gestor Auditoria'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TGAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TGAUD'',''Tarea del Gestor de auditoria'',''Tarea del Gestor de auditoria'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''GAUD'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GGAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGAUD'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Supervisor auditoría
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Supervisor auditoria');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Supervisor auditoria');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Supervisor Auditoria'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo gestor de deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GSAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GSAUD'',''1234'',''Grupo - Supervisor Auditoria'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TSAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TSAUD'',''Tarea del Supervisor de auditoria'',''Tarea del Supervisor de auditoria'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''SAUD'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GSAUD''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSAUD'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Asesoría jurídica
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DAJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Asesoría jurídica'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo gestor de deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GAJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GAJUR'',''1234'',''Grupo - Asesoria Juridica'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TAJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''AJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TAJUR'',''Tarea del Gestor de asesoria juridica'',''Tarea del Gestor de asesoria juridica'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''AJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''AJUR'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GAJUR''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DAJUR'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Gestor soporte deuda
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Gestor soporte deuda');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Gestor soporte deuda'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo gestor de deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GGSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GGSDE'',''1234'',''Grupo - Gestor soporte deuda'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''805''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''805'',''Tarea del Gestor soporte deuda'',''Tarea del Gestor soporte deuda'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''UNISOP'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GGSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGSDE'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Supervisor soporte deuda
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor Auditoria');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Gestor soporte deuda');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Supervisor soporte deuda'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo gestor de deuda');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GSSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - gestor de deuda');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GSSDE'',''1234'',''Grupo - Supervisor soporte deuda'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''806''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''806'',''Tarea del Supervisor soporte deuda'',''Tarea del Supervisor soporte deuda'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''UNISOP'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GSSDE''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSSDE'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Equipo Adquisiciones
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Equipo Adquisiciones');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DEADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Equipo Adquisiciones');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Equipo Adquisiciones'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo Equipo Adquisiciones');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GEADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - Equipo Adquisiciones');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GEADQ'',''1234'',''Grupo - Equipo Adquisiciones'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TGEA''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''EADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TGEA'',''Tarea del Gestor Equipo Adquisiciones'',''Tarea del Gestor Equipo Adquisiciones'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''EADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''EADQ'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GEADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DEADQ'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Supervisor Equipo Adquisiciones
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Supervisor Equipo Adquisiciones');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Equipo Adquisiciones');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Supervisor Equipo Adquisiciones'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo Supervisor Equipo Adquisiciones');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GSADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - Supervisor Equipo Adquisiciones');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GSADQ'',''1234'',''Grupo - Supervisor Equipo Adquisiciones'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TSEA''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TSEA'',''Tarea del Supervisor Adquisiciones'',''Tarea del SupervisorAdquisiciones'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''SADQ'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GSADQ''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSADQ'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Gestor de CN
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor de CN');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Gestor de CN');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Gestor de CN'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo Gestor de CN');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GGCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - Gestor de CN');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GGCN'',''1234'',''Grupo - Gestor de CN'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TGCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TGCN'',''Tarea del Gestor de CN'',''Tarea del Gestor de CN'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''GCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''GCN'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GGCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DGCN'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------
-------Supervisor de CN
   DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo despacho Gestor de CN');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_DD_TDE_ID_OFI;

	DBMS_OUTPUT.PUT_LINE('[INFO] Se consulta si existe un DES_DESPACHO_EXTERNO con tipo Supervisor de CN');

	V_SQL := 'SELECT COUNT(1) FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = ' || V_DD_TDE_ID_OFI;
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO DES_DESPACHO_EXTERNO con tipo Asesoría jurídica');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO (DES_ID, DES_DESPACHO, VERSION, USUARIOCREAR, FECHACREAR, DD_TDE_ID) VALUES (' 
		||V_ESQUEMA ||'.S_DES_DESPACHO_EXTERNO.NEXTVAL, ''Supervisor de CN'', 0, ''PRODUCTO-897'', sysdate, ' || V_DD_TDE_ID_OFI || ')'; 
		EXECUTE IMMEDIATE V_MSQL;
	END IF;


	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nuevo usuario Grupo Supervisor de CN');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME || ' WHERE USU_USERNAME = ''GSCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en usu_usuarios grupo - Supervisor de CN');
	V_MSQL := 'INSERT INTO '|| V_ESQUEMA_M || '.USU_USUARIOS (usu_id, entidad_id, usu_username, usu_password, usu_nombre, usuariocrear,fechacrear, usu_grupo)  values  ('
	|| V_ESQUEMA_M ||'.s_usu_usuarios.nextval, ''1'',''GSCN'',''1234'',''Grupo - Supervisor de CN'', ''PRODUCTO-897'', sysdate, 1)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada DD_STA_SUBTIPO_TAREA_BASE');
	V_NUM_TABLAS := 0;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA_M || '.' || V_DDNAME_STA || ' WHERE DD_STA_CODIGO = ''TSCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN DD_STA_ID ES: ' || V_TMP);
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en DD_STA_SUBTIPO_TAREA_BASE');
		V_MSQL := 'INSERT INTO ' || V_ESQUEMA_M ||'.DD_STA_SUBTIPO_TAREA_BASE (DD_STA_ID,DD_TAR_ID, DD_STA_CODIGO,DD_STA_DESCRIPCION,DD_STA_DESCRIPCION_LARGA,DD_TGE_ID,USUARIOCREAR,FECHACREAR) 
		VALUES ('||V_ESQUEMA_M ||'.S_DD_STA_SUBTIPO_TAREA_BASE.NEXTVAL,1,''TSCN'',''Tarea del Supervisor de CN'',''Tarea del Supervisor de CN'','|| V_TMP ||',''PRODUCTO-897'',sysdate)';
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
		EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada TGP_TIPO_GESTOR_PROPIEDAD');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_SQL := 'SELECT DD_TGE_ID FROM ' || V_ESQUEMA_M || '.DD_TGE_TIPO_GESTOR WHERE DD_TGE_CODIGO = ''SCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	DBMS_OUTPUT.PUT_LINE('[INFO] EL ID DE TGE A INSERTAR EN TGP_TIPO_GESTOR_PROPIEDAD ES: ' || V_TMP);
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_TGP || ' WHERE DD_TGE_ID = '|| V_TMP ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en TGP_TIPO_GESTOR_PROPIEDAD');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA ||'.TGP_TIPO_GESTOR_PROPIEDAD  (TGP_ID, dd_tge_id, tgp_clave, tgp_valor, usuariocrear, fechacrear)
	values (' || V_ESQUEMA || '.S_TGP_TIPO_GESTOR_PROPIEDAD.nextval, '|| V_TMP ||', ''DES_VALIDOS'', ''SCN'', ''PRODUCTO-897'', sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;

	DBMS_OUTPUT.PUT_LINE('[INFO] Insertar nueva entrada USD_USUARIOS_DESPACHOS');
	V_NUM_TABLAS := 0;
	V_TMP := 0;
	V_TMP_2 := 0;
	V_SQL := 'SELECT USU_ID FROM ' || V_ESQUEMA_M || '.USU_USUARIOS WHERE USU_USERNAME = ''GSCN''';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP;
	V_SQL := 'SELECT DES_ID FROM ' || V_ESQUEMA || '.DES_DESPACHO_EXTERNO WHERE DD_TDE_ID = (SELECT DD_TDE_ID FROM ' || V_ESQUEMA_M || '.DD_TDE_TIPO_DESPACHO WHERE DD_TDE_CODIGO = ''DSCN'')';
	EXECUTE IMMEDIATE V_SQL INTO V_TMP_2;
	V_SQL := 'SELECT COUNT(*) FROM ' || V_ESQUEMA || '.' || V_DDNAME_USD || ' WHERE USU_ID = '|| V_TMP ||' AND DES_ID = '|| V_TMP_2 ||'';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;

	IF V_NUM_TABLAS = 0 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO en USD_USUARIOS_DESPACHOS');
	V_MSQL := 'INSERT INTO ' || V_ESQUEMA || '.' || V_DDNAME_USD || '(USD_ID,USU_ID,DES_ID,USD_GESTOR_DEFECTO,USD_SUPERVISOR,USUARIOCREAR,FECHACREAR) VALUES('|| V_ESQUEMA ||'.s_usd_usuarios_despachos.nextval,'|| V_TMP ||','|| V_TMP_2 ||',1,0,''PRODUCTO-897'',sysdate)';
	DBMS_OUTPUT.PUT_LINE('[INFO] INSERTANDO esta query: ' || V_MSQL);
	EXECUTE IMMEDIATE V_MSQL;
	END IF;	
--------------------------------


  COMMIT;

EXCEPTION
     WHEN OTHERS THEN
          err_num := SQLCODE;
          err_msg := SQLERRM;

          DBMS_OUTPUT.PUT_LINE('KO no modificado');
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(err_num));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(err_msg);

          ROLLBACK;
          RAISE;          

END;

/

EXIT