--/*
--##########################################
--## AUTOR=Carlos Gil Gimeno
--## FECHA_CREACION=20160329
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2.1
--## INCIDENCIA_LINK= PRODUCTO-1074
--## PRODUCTO=NO
--##
--## Finalidad:
--## INSTRUCCIONES: 
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;
DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquemas  
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquemas  
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    V_SQL_REG_EXT VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.  
    V_NUM_TABLAS NUMBER(16); -- Vble. para validar la existencia de una tabla.     
    V_NUM_TABLAS2 NUMBER(16); -- Vble. para validar la existencia de una tabla.
    V_NUM_TABLAS3 NUMBER(16); -- Vble. para validar la existencia de una tabla.
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
BEGIN	

    
	
	V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	IF V_NUM_TABLAS > 0 THEN
	
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''VER-POLITICA''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''VER-POLITICA'' AND PEF.PEF_CODIGO =''GESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''VER-POLITICA'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS'' AND PEF.PEF_CODIGO =''GESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP'' AND PEF.PEF_CODIGO =''GESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP'' AND PEF.PEF_CODIGO =''GESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_COMITE''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ROLE_COMITE'' AND PEF.PEF_CODIGO =''GESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_COMITE'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''GESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
	
	ELSE
	
		DBMS_OUTPUT.PUT_LINE('NO EXISTE EL PERFIL GESTDEUDA');
	
	END IF;
	
	
	
	V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA''';
	EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS;
	
	IF V_NUM_TABLAS > 0 THEN
	
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''VER-POLITICA''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''VER-POLITICA'' AND PEF.PEF_CODIGO =''SUPGESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''VER-POLITICA'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS'' AND PEF.PEF_CODIGO =''SUPGESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_PUEDE_VER_TAB_EXP_PROPUESTAS'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP'' AND PEF.PEF_CODIGO =''SUPGESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''TAB_COBROS_PAGOS_EXP'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP'' AND PEF.PEF_CODIGO =''SUPGESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ACTUACIONES_EXPLORAR_GESTANA_EXP'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
		
		
		V_SQL := 'SELECT COUNT (1) FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_COMITE''';
		EXECUTE IMMEDIATE V_SQL INTO V_NUM_TABLAS2;
		
		V_SQL_REG_EXT := 'SELECT COUNT (1) FROM '||V_ESQUEMA||'.FUN_PEF FUNPEF INNER JOIN '||V_ESQUEMA||'.PEF_PERFILES PEF ON PEF.PEF_ID = FUNPEF.PEF_ID INNER JOIN '||V_ESQUEMA_M||'.FUN_FUNCIONES FUNFUN ON FUNFUN.FUN_ID = FUNPEF.FUN_ID WHERE FUNFUN.FUN_DESCRIPCION = ''ROLE_COMITE'' AND PEF.PEF_CODIGO =''SUPGESTDEUDA'' ';
		EXECUTE IMMEDIATE V_SQL_REG_EXT INTO V_NUM_TABLAS3;
		
		IF V_NUM_TABLAS2 > 0 AND V_NUM_TABLAS3 < 1 THEN
			V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.FUN_PEF (FUN_ID,PEF_ID,FP_ID,USUARIOCREAR,FECHACREAR,BORRADO)(SELECT(SELECT FUN_ID FROM '||V_ESQUEMA_M||'.FUN_FUNCIONES WHERE FUN_DESCRIPCION = ''ROLE_COMITE'') AS FUN_ID, PEF_ID, '||V_ESQUEMA||'.S_FUN_PEF.NEXTVAL AS PF_ID, ''PRODUCTO-1074'',SYSDATE,''0'' FROM '||V_ESQUEMA||'.PEF_PERFILES WHERE PEF_CODIGO = ''SUPGESTDEUDA'')';
			EXECUTE IMMEDIATE V_MSQL;
			DBMS_OUTPUT.PUT_LINE('OK INSERTADO');
		ELSE
		 	DBMS_OUTPUT.PUT_LINE('NO EXISTE LA FUNCION');		
		END IF;
	
	ELSE
	
		DBMS_OUTPUT.PUT_LINE('NO EXISTE EL PERFIL SUPGESTDEUDA');
	
	END IF;
	
	
	COMMIT;
	    
    
	DBMS_OUTPUT.PUT_LINE('[INFO] Fin.');


EXCEPTION
  WHEN OTHERS THEN
    ERR_NUM := SQLCODE;
    ERR_MSG := SQLERRM;
    DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
    DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
    DBMS_OUTPUT.put_line(ERR_MSG);
    ROLLBACK;
    RAISE;   
    
END;
/

EXIT;
  	