OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_5052
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ACT_NUM_ACTIVO					NULLIF(ACT_NUM_ACTIVO=BLANKS)				"TRIM(:ACT_NUM_ACTIVO)",
	DD_PRV_CODIGO					NULLIF(DD_PRV_CODIGO=BLANKS)				"TRIM(:DD_PRV_CODIGO)",
	DD_LOC_CODIGO					NULLIF(DD_LOC_CODIGO=BLANKS)				"TRIM(:DD_LOC_CODIGO)",
	DD_UPO_CODIGO					NULLIF(DD_UPO_CODIGO=BLANKS)				"TRIM(:DD_UPO_CODIGO)"
)
