OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
TRUNCATE INTO TABLE AUX_UPDATE_GESTORES_ACTIVOS
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'          
TRAILING NULLCOLS
 ( 
	NUM_ACTIVO
	, USERNAME_GESTOR
	, TIPO_GESTOR
 )