-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

DROP PROCEDURE IF EXISTS `Crear_Dim_Asunto` $$

-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

SET NAMES UTF8 $$

CREATE DEFINER=`bi_cdd`@`62.15.160.14` PROCEDURE `Crear_Dim_Asunto`(OUT o_error_status varchar(500))
MY_BLOCK_DIM_ASU: BEGIN
	

-- ===============================================================================================
-- Autor: Gonzalo Martín, PFS Group
-- Fecha creación: Julio 2012
-- Responsable última modificación:
-- Fecha última modificación:Procedures
-- Motivos del cambio:
-- Cliente: Recovery BI UGAS 
--
-- Descripción: Procedimiento almancenado que crea las tablas de la dimensión Asunto.
-- ===============================================================================================
	
	-- --------------------------------------------------------------------------------
	-- DEFINICIÓN DE LOS HANDLER DE ERROR
	-- --------------------------------------------------------------------------------
	DECLARE EXIT handler for 1062 set o_error_status := 'Error 1062: La tabla ya existe';
	DECLARE EXIT handler for 1048 set o_error_status := 'Error 1048: Has intentado insertar un valor nulo'; 
	DECLARE EXIT handler for 1318 set o_error_status := 'Error 1318: Número de parámetros incorrecto'; 


	-- --------------------------------------------------------------------------------
	-- DEFINICIÓN DEL HANDLER GENÉRICO DE ERROR
	-- --------------------------------------------------------------------------------
	DECLARE EXIT handler for sqlexception set o_error_status:= 'Se ha producido un error en el proceso';
	
	DROP TABLE D_ENTIDAD_CEDENTE;
	CREATE TABLE IF NOT EXISTS D_ENTIDAD_CEDENTE(
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		`ENTIDAD_CEDENTE_DESC` VARCHAR(50) NULL ,
		`ENTIDAD_CEDENTE_DESC_ALT` VARCHAR(250) NULL ,
		PRIMARY KEY (`ENTIDAD_CEDENTE_ID`)
	);

	DROP TABLE D_ASU_ESTADO;
	CREATE TABLE IF NOT EXISTS D_ASU_ESTADO(
		`ESTADO_ASUNTO_ID` DECIMAL(16,0) NOT NULL ,
		`ESTADO_ASUNTO_DESC` VARCHAR(50) NULL ,
		`ESTADO_ASUNTO_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`ESTADO_ASUNTO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	
	DROP TABLE D_ASU_DESPACHO;	
	CREATE TABLE IF NOT EXISTS D_ASU_DESPACHO (
		`DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`DESPACHO_DESC` VARCHAR(250) NULL ,
		`TIPO_DESPACHO_ID` DECIMAL(16,0) NULL ,
		`ZONA_DESPACHO_ID` DECIMAL(16,0) NULL ,  
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_TIPO_DESPACHO;		  
	CREATE TABLE IF NOT EXISTS D_ASU_TIPO_DESPACHO(
		`TIPO_DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`TIPO_DESPACHO_DESC` VARCHAR(50) NULL ,
		`TIPO_DESPACHO_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`TIPO_DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_DESPACHO_GESTOR;
	CREATE TABLE IF NOT EXISTS D_ASU_DESPACHO_GESTOR (
		`DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`DESPACHO_GESTOR_DESC` VARCHAR(250) NULL ,
		`TIPO_DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,
		`ZONA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,  
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
	PRIMARY KEY (`DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_TIPO_DESPACHO_GESTOR;	  
	CREATE TABLE IF NOT EXISTS D_ASU_TIPO_DESPACHO_GESTOR(
		`TIPO_DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`TIPO_DESPACHO_GESTOR_DESC` VARCHAR(50) NULL ,
		`TIPO_DESPACHO_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`TIPO_DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_GESTOR;
	CREATE TABLE IF NOT EXISTS D_ASU_GESTOR (
		`GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`GESTOR_NOMBRE` VARCHAR(250) NULL ,
		`GESTOR_APELLIDO1` VARCHAR(250) NULL ,
		`GESTOR_APELLIDO2` VARCHAR(250) NULL ,
		`ENTIDAD_GESTOR_ID` DECIMAL(16,0) NULL , 
		`DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,  
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_ENTIDAD_GESTOR;
	CREATE TABLE IF NOT EXISTS D_ASU_ENTIDAD_GESTOR(
		`ENTIDAD_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`ENTIDAD_GESTOR_DESC` VARCHAR(255) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`ENTIDAD_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_ROL_GESTOR;	
	CREATE TABLE IF NOT EXISTS D_ASU_ROL_GESTOR(
		`ROL_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`ROL_GESTOR_DESC` VARCHAR(50) NULL ,
		`ROL_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`ROL_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_NVL_DESPACHO;		  
	CREATE TABLE IF NOT EXISTS D_ASU_NVL_DESPACHO( 
		`NIVEL_DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`NIVEL_DESPACHO_DESC` VARCHAR(50) NULL ,
		`NIVEL_DESPACHO_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`NIVEL_DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_OFI_DESPACHO;
	CREATE TABLE IF NOT EXISTS D_ASU_OFI_DESPACHO( 
		`OFICINA_DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`OFICINA_DESPACHO_DESC` VARCHAR(50) NULL ,
		`OFICINA_DESPACHO_DESC_ALT` VARCHAR(250) NULL ,
		`PROVINCIA_DESPACHO_ID` DECIMAL(16,0) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`OFICINA_DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_PROV_DESPACHO;
	CREATE TABLE IF NOT EXISTS D_ASU_PROV_DESPACHO( 
		`PROVINCIA_DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`PROVINCIA_DESPACHO_DESC` VARCHAR(50) NULL ,
		`PROVINCIA_DESPACHO_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`PROVINCIA_DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_ZONA_DESPACHO;
	CREATE TABLE IF NOT EXISTS D_ASU_ZONA_DESPACHO( 
		`ZONA_DESPACHO_ID` DECIMAL(16,0) NOT NULL ,
		`ZONA_DESPACHO_DESC` VARCHAR(50) NULL ,
		`ZONA_DESPACHO_DESC_ALT` VARCHAR(250) NULL ,
		`NIVEL_DESPACHO_ID` DECIMAL(16,0) NULL ,
		`OFICINA_DESPACHO_ID` DECIMAL(16,0) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`ZONA_DESPACHO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	
	DROP TABLE D_ASU_NVL_DESPACHO_GESTOR;
	CREATE TABLE IF NOT EXISTS D_ASU_NVL_DESPACHO_GESTOR( 
		`NIVEL_DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`NIVEL_DESPACHO_GESTOR_DESC` VARCHAR(50) NULL ,
		`NIVEL_DESPACHO_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`NIVEL_DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_OFI_DESPACHO_GESTOR;	  
	CREATE TABLE IF NOT EXISTS D_ASU_OFI_DESPACHO_GESTOR( 
		`OFICINA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`OFICINA_DESPACHO_GESTOR_DESC` VARCHAR(50) NULL ,
		`OFICINA_DESPACHO_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`PROVINCIA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`OFICINA_DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_PROV_DESPACHO_GESTOR;	
	CREATE TABLE IF NOT EXISTS D_ASU_PROV_DESPACHO_GESTOR( 
		`PROVINCIA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`PROVINCIA_DESPACHO_GESTOR_DESC` VARCHAR(50) NULL ,
		`PROVINCIA_DESPACHO_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`PROVINCIA_DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	  
	DROP TABLE D_ASU_ZONA_DESPACHO_GESTOR;		
	CREATE TABLE IF NOT EXISTS D_ASU_ZONA_DESPACHO_GESTOR( 
		`ZONA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NOT NULL ,
		`ZONA_DESPACHO_GESTOR_DESC` VARCHAR(50) NULL ,
		`ZONA_DESPACHO_GESTOR_DESC_ALT` VARCHAR(250) NULL ,
		`NIVEL_DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,
		`OFICINA_DESPACHO_GESTOR_ID` DECIMAL(16,0) NULL ,
		`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
		PRIMARY KEY (`ZONA_DESPACHO_GESTOR_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	
	DROP TABLE D_ASU;	
	CREATE TABLE IF NOT EXISTS D_ASU( 
	  `ASUNTO_ID` DECIMAL(16,0) NOT NULL ,
	  `NOMBRE_ASUNTO` VARCHAR(310) NULL ,
	  `ESTADO_ASUNTO_ID` DECIMAL(16,0) NULL,
	  `EXPEDIENTE_ID` DECIMAL(16,0) NULL ,
	  `DESPACHO_ID` DECIMAL(16,0) NULL ,
	  `ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL ,
	  PRIMARY KEY (`ASUNTO_ID`,`ENTIDAD_CEDENTE_ID`)
	);
	
	DROP TABLE TEMP_DESPACHO_ASUNTO;		
	CREATE TABLE IF NOT EXISTS TEMP_DESPACHO_ASUNTO( 
	`ASUNTO_ID` DECIMAL(16,0) NULL, 
	`DESPACHO_ID` DECIMAL(16,0) NOT NULL,
	`ENTIDAD_CEDENTE_ID` DECIMAL(16,0) NOT NULL
	);
	
END MY_BLOCK_DIM_ASU
