
package org.cajamar.ws.S_C_RECOVERY_DAT_PR;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "S_C_RECOVERY_DAT_PR", targetNamespace = "http://cajamar.org/webservice", wsdlLocation = "https://multidesa.larural.es:515/RECOVERY/services/S_C_RECOVERY_DAT_PR?wsdl")
public class SCRECOVERYDATPR
    extends Service
{

    private final static URL SCRECOVERYDATPR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.cajamar.ws.S_C_RECOVERY_DAT_PR.SCRECOVERYDATPR.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.cajamar.ws.S_C_RECOVERY_DAT_PR.SCRECOVERYDATPR.class.getResource(".");
            url = new URL(baseUrl, "https://multidesa.larural.es:515/RECOVERY/services/S_C_RECOVERY_DAT_PR?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://multidesa.larural.es:515/RECOVERY/services/S_C_RECOVERY_DAT_PR?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SCRECOVERYDATPR_WSDL_LOCATION = url;
    }

    public SCRECOVERYDATPR(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCRECOVERYDATPR() {
        super(SCRECOVERYDATPR_WSDL_LOCATION, new QName("http://cajamar.org/webservice", "S_C_RECOVERY_DAT_PR"));
    }

    /**
     * 
     * @return
     *     returns SCRECOVERYDATPRType
     */
    @WebEndpoint(name = "S_C_RECOVERY_DAT_PRPort")
    public SCRECOVERYDATPRType getSCRECOVERYDATPRPort() {
        return super.getPort(new QName("http://cajamar.org/webservice", "S_C_RECOVERY_DAT_PRPort"), SCRECOVERYDATPRType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCRECOVERYDATPRType
     */
    @WebEndpoint(name = "S_C_RECOVERY_DAT_PRPort")
    public SCRECOVERYDATPRType getSCRECOVERYDATPRPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cajamar.org/webservice", "S_C_RECOVERY_DAT_PRPort"), SCRECOVERYDATPRType.class, features);
    }

}
