--/*
--##########################################
--## AUTOR=DANIEL GUTIERREZ
--## FECHA_CREACION=20150622
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.1.0-X
--## INCIDENCIA_LINK=MITCDD-2068
--## PRODUCTO=SI
--##
--## Finalidad: Nuevo campo en RES_RESOLUCIONES_MASIVO
--## INSTRUCCIONES: 
--## VERSIONES:
--##        0.1 Version inicial
--##########################################
--*/

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;
DECLARE
    V_MSQL VARCHAR2(4000 CHAR);
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    seq_count number(3); -- Vble. para validar la existencia de las Secuencias.
    table_count number(3); -- Vble. para validar la existencia de las Tablas.
    v_column_count number(3); -- Vble. para validar la existencia de las Columnas.
    v_constraint_count number(3); -- Vble. para validar la existencia de las Constraints.
    err_num NUMBER; -- Numero de errores
    err_msg VARCHAR2(2048); -- Mensaje de error
    
BEGIN

	DBMS_OUTPUT.PUT_LINE('******** RES_RESOLUCIONES_MASIVO ********'); 
	DBMS_OUTPUT.PUT_LINE('[INFO] '||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO... Comprobaciones previas');

	-- Comprobamos si ya existe la columna
	V_MSQL := 'SELECT COUNT(1) FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME= ''RES_ADA_ID'' and TABLE_NAME=''RES_RESOLUCIONES_MASIVO'' and owner = '''||V_ESQUEMA||'''';
	EXECUTE IMMEDIATE V_MSQL INTO table_count;
	
	IF table_count = 1 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO.RES_ADA_ID... Ya existe');
	ELSE
		EXECUTE IMMEDIATE 'ALTER TABLE ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO ADD 
			(RES_ADA_ID NUMBER(16))';
		
		DBMS_OUTPUT.PUT_LINE('ALTER TABLE '|| V_ESQUEMA ||'.RES_RESOLUCIONES_MASIVO ADD RES_ADA_ID ... OK');
		
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_PPR_PROCURADOR... Creando FK');
		V_MSQL := 'ALTER TABLE '||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO ADD (
						CONSTRAINT FK_RES_ADA_ID FOREIGN KEY (RES_ADA_ID) REFERENCES ADA_ADJUNTOS_ASUNTOS (ADA_ID)
						)';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_PPR_PROCEDIMIENTO... Creando FK');
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO.RES_ADA_ID ... OK');
	END IF;
	
	-- Comprobamos si ya existe la columna
	V_MSQL := 'SELECT COUNT(1) FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME= ''RES_TAR_ID'' and TABLE_NAME=''RES_RESOLUCIONES_MASIVO'' and owner = '''||V_ESQUEMA||'''';
	EXECUTE IMMEDIATE V_MSQL INTO table_count;
	
	IF table_count = 1 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO.RES_TAR_ID... Ya existe');
	ELSE
		EXECUTE IMMEDIATE 'ALTER TABLE ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO ADD 
			(RES_TAR_ID NUMBER(16))';
		
		DBMS_OUTPUT.PUT_LINE('ALTER TABLE '|| V_ESQUEMA ||'.RES_RESOLUCIONES_MASIVO ADD RES_TAR_ID ... OK');
		
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_RES_TAR_ID... Creando FK');
		V_MSQL := 'ALTER TABLE '||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO ADD (
						CONSTRAINT FK_RES_TAR_ID FOREIGN KEY (RES_TAR_ID) REFERENCES TAR_TAREAS_NOTIFICACIONES (TAR_ID)
						)';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_RES_TAR_ID... Creando FK');
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO.RES_TAR_ID... OK');
	END IF;
	
	-- Comprobamos si ya existe la columna
	V_MSQL := 'SELECT COUNT(1) FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME= ''RES_CAT_ID'' and TABLE_NAME=''RES_RESOLUCIONES_MASIVO'' and owner = '''||V_ESQUEMA||'''';
	EXECUTE IMMEDIATE V_MSQL INTO table_count;
	
	IF table_count = 1 THEN
		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO.RES_CAT_ID... Ya existe');
	ELSE
		EXECUTE IMMEDIATE 'ALTER TABLE ' || V_ESQUEMA || '.RES_RESOLUCIONES_MASIVO ADD 
			(RES_CAT_ID NUMBER(16))';
		
		DBMS_OUTPUT.PUT_LINE('ALTER TABLE '|| V_ESQUEMA ||'.RES_RESOLUCIONES_MASIVO ADD RES_CAT_ID ... OK');
		
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_RES_CAT_ID... Creando FK');
		V_MSQL := 'ALTER TABLE '||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO ADD (
						CONSTRAINT FK_RES_CAT_ID FOREIGN KEY (RES_CAT_ID) REFERENCES CAT_CATEGORIAS (CAT_ID)
						)';
		EXECUTE IMMEDIATE V_MSQL;
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.FK_RES_CAT_ID... Creando FK');
		DBMS_OUTPUT.PUT_LINE('[INFO] ' ||V_ESQUEMA||'.RES_RESOLUCIONES_MASIVO.RES_CAT_ID... OK');
	END IF;


EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Código de error obtenido:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
          


END;
/

EXIT