  drop sequence BANK01.S_PRB_PRC_BIE;
  drop table "BANK01"."PRB_PRC_BIE";
  
  
  CREATE SEQUENCE BANK01.S_PRB_PRC_BIE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  NOORDER;

  CREATE TABLE "BANK01"."PRB_PRC_BIE" (	
  	"PRB_ID" NUMBER(16,0),
   	"PRC_ID" NUMBER(16,0), 
	"BIE_ID" NUMBER(16,0),
	"DD_SGB_ID" NUMBER(16,0),
	"VERSION" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"USUARIOCREAR" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"FECHACREAR" TIMESTAMP (6) NOT NULL ENABLE, 
	"USUARIOMODIFICAR" VARCHAR2(10 CHAR), 
	"FECHAMODIFICAR" TIMESTAMP (6), 
	"USUARIOBORRAR" VARCHAR2(10 CHAR), 
	"FECHABORRAR" TIMESTAMP (6), 
	"BORRADO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRB_PRC_BIE" PRIMARY KEY ("PRB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANK01"  ENABLE, 
	 CONSTRAINT "FK_DD_PRC_BIE_SGB" FOREIGN KEY ("DD_SGB_ID")
	  REFERENCES "BANKMASTER"."DD_SGB_SOLVENCIA_GARANTIA_BIEN" ("DD_SGB_ID") ENABLE,
	  CONSTRAINT "FK_PRC_BIE_REFERENCE_BIE_BIEN" FOREIGN KEY ("BIE_ID")
	  REFERENCES "BANK01"."BIE_BIEN" ("BIE_ID") ENABLE,
	 CONSTRAINT "FK_PRC_BIE_REFERENCE_PRC_PROC" FOREIGN KEY ("PRC_ID")
	  REFERENCES "BANK01"."PRC_PROCEDIMIENTOS" ("PRC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANK01" ;
 

  CREATE INDEX "BANK01"."PRB_PRC_BIE_PRC_ID" ON "BANK01"."PRB_PRC_BIE" ("PRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANK01" ;
  
  CREATE INDEX "BANK01"."PRB_PRC_BIE_BIE_ID" ON "BANK01"."PRB_PRC_BIE" ("BIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANK01" ;