
package es.pfsgroup.plugin.gestorDocumental.ws.MAESTRO_INTEGRACION;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsWS", targetNamespace = "http://alamo.haya.es/IntegracionSOA/schemas", wsdlLocation = "http://10.10.25.196:8080/WSIntegracionSOA/wsdl/ws.wsdl?wsdl")
public class WsWS
    extends Service
{

    private final static URL WSWS_WSDL_LOCATION;
    private final static WebServiceException WSWS_EXCEPTION;
    private final static QName WSWS_QNAME = new QName("http://alamo.haya.es/IntegracionSOA/schemas", "wsWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.10.25.196:8080/WSIntegracionSOA/wsdl/ws.wsdl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSWS_WSDL_LOCATION = url;
        WSWS_EXCEPTION = e;
    }

    public WsWS() {
        super(__getWsdlLocation(), WSWS_QNAME);
    }

    public WsWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WsPort
     */
    @WebEndpoint(name = "ws")
    public WsPort getWs() {
        return super.getPort(new QName("http://alamo.haya.es/IntegracionSOA/schemas", "ws"), WsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPort
     */
    @WebEndpoint(name = "ws")
    public WsPort getWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://alamo.haya.es/IntegracionSOA/schemas", "ws"), WsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSWS_EXCEPTION!= null) {
            throw WSWS_EXCEPTION;
        }
        return WSWS_WSDL_LOCATION;
    }

}
