whenever sqlerror exit sql.sqlcode;

set linesize 200
SET FEEDBACK OFF;
SET VERIFY OFF;

DECLARE
  v_RSR_NOMBRE_SCRIPT VARCHAR2(200 CHAR);
  v_RSR_ESQUEMA_EJECUCION VARCHAR2(200 CHAR);
  v_RSR_AUTOR VARCHAR2(200 CHAR);
  v_RSR_ARTEFACTO VARCHAR2(200 CHAR);
  v_RSR_VERSION_ARTEFACTO VARCHAR2(200 CHAR);
  v_RSR_FECHACREACION VARCHAR2(200 CHAR);
  v_RSR_INCIDENCIA_LINK VARCHAR2(200 CHAR);
  v_RSR_PRODUCTO VARCHAR2(200 CHAR); 

BEGIN

  v_RSR_NOMBRE_SCRIPT := '&&1';
  v_RSR_ESQUEMA_EJECUCION := '&&2';
  v_RSR_AUTOR := '&&3';
  v_RSR_ARTEFACTO := '&&4';
  v_RSR_VERSION_ARTEFACTO := '&&5';
  v_RSR_FECHACREACION := '&&6';
  v_RSR_INCIDENCIA_LINK := '&&7';
  v_RSR_PRODUCTO := '&&8';

  #ESQUEMA#.RSR_PASO3(
    v_RSR_NOMBRE_SCRIPT => v_RSR_NOMBRE_SCRIPT,
    v_RSR_ESQUEMA_EJECUCION => v_RSR_ESQUEMA_EJECUCION,
    v_RSR_AUTOR => v_RSR_AUTOR,
    v_RSR_ARTEFACTO => v_RSR_ARTEFACTO,
    v_RSR_VERSION_ARTEFACTO => v_RSR_VERSION_ARTEFACTO,
    v_RSR_FECHACREACION => v_RSR_FECHACREACION,
    v_RSR_INCIDENCIA_LINK => v_RSR_INCIDENCIA_LINK,
    v_RSR_PRODUCTO => v_RSR_PRODUCTO
  );


EXCEPTION
     WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución: '||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
        DBMS_OUTPUT.put_line(SQLERRM);
        
        ROLLBACK;
        RAISE;

END;
/

exit
