OPTIONS (DIRECT=TRUE, BINDSIZE=1024000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET AL32UTF8
INTO TABLE REM01.AUX_REMVIP_8912
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	TIPO				NULLIF(TIPO=BLANKS)			"TRIM(:TIPO)",
	ACTIVO				NULLIF(ACTIVO=BLANKS)			"TRIM(:ACTIVO)"
)
