CREATE SEQUENCE S_ITA_INPUTS_TAREAS
  START WITH 1
  MAXVALUE 999999999999999999999999999;

ALTER TABLE LIN001.ITA_INPUTS_TAREAS
 DROP PRIMARY KEY CASCADE;
DROP TABLE LIN001.ITA_INPUTS_TAREAS CASCADE CONSTRAINTS;

CREATE TABLE LIN001.ITA_INPUTS_TAREAS
(
  ITA_ID      NUMBER(19)                        NOT NULL,
  BPM_IPT_ID  NUMBER(19)                        NOT NULL,
  TEX_ID      NUMBER(19)                        NOT NULL
)
TABLESPACE LIN001
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIN001.ITA_INPUTS_TAREAS_PK ON LIN001.ITA_INPUTS_TAREAS
(ITA_ID)
LOGGING
TABLESPACE LIN001
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE LIN001.ITA_INPUTS_TAREAS ADD (
  CONSTRAINT ITA_INPUTS_TAREAS_PK
 PRIMARY KEY
 (ITA_ID)
    USING INDEX 
    TABLESPACE LIN001
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE LIN001.ITA_INPUTS_TAREAS ADD (
  CONSTRAINT FK_ITA_BPM_IPT 
 FOREIGN KEY (BPM_IPT_ID) 
 REFERENCES LIN001.BPM_IPT_INPUT (BPM_IPT_ID),
  CONSTRAINT FK_ITA_TEX 
 FOREIGN KEY (TEX_ID) 
 REFERENCES LIN001.TEX_TAREA_EXTERNA (TEX_ID));