--/*
--##########################################
--## AUTOR=VIOREL REMUS OVIDIU
--## FECHA_CREACION=20190129
--## ARTEFACTO=online
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-3176
--## PRODUCTO=NO
--##
--## Finalidad: Crear tabla histórica para proceso SP_CAMBIO_ESTADO_PUBLICACION, con nombre H_CAMBIO_ESTADO_PUBLICACION
--## INSTRUCCIONES:
--## VERSIONES:
--##        0.1 Versión inicial
--##########################################
--*/
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

  V_SQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar         
  V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
  V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
  V_COUNT NUMBER(16); -- Vble. para contar.
  ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
  ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
  TYPE T_TABLA IS TABLE OF VARCHAR2(30 CHAR);
  V_TABLA VARCHAR2(32 CHAR) := 'H_CAMBIO_ESTADO_PUBLICACION';
  V_USUARIO VARCHAR2(32 CHAR) := 'REMVIP-3176';
  ITABLE_SPACE VARCHAR(25 CHAR) :='#TABLESPACE_INDEX#';
  V_HIST VARCHAR2(30 CHAR);
  V_EXISTE NUMBER (1);
  V_MSQL VARCHAR2(4000 CHAR);
    
BEGIN

  DBMS_OUTPUT.PUT_LINE('[INICIO]');

    V_SQL := 'SELECT COUNT(1) FROM ALL_TABLES WHERE OWNER = '''||V_ESQUEMA||''' AND TABLE_NAME = '''||V_TABLA||'''';
    EXECUTE IMMEDIATE V_SQL INTO V_EXISTE;

    IF V_EXISTE = 1 THEN
	    V_MSQL := 'DROP TABLE '||V_TABLA||' PURGE';
	    EXECUTE IMMEDIATE V_MSQL;
	    DBMS_OUTPUT.PUT_LINE('TABLA '||V_TABLA||' BORRADA.');
    END IF;

    V_MSQL := 'CREATE TABLE '||V_ESQUEMA||'.'||V_TABLA||' 
    (   "ID"  NUMBER(16,0) NOT NULL,
	"FASE_SP"  VARCHAR2(20 CHAR) NOT NULL, 
	"FECHACREAR" TIMESTAMP(6)   NOT NULL,
	"USUARIOCREAR"  VARCHAR2(50 CHAR),
	"FECHACREAR_APU" 	TIMESTAMP(6),
	"DD_EPV_ID" 	NUMBER(16,0),
	"ACT_NUM_ACTIVO" 	NUMBER(16,0),
	"APU_CHECK_PUB_SIN_PRECIO_V" 	NUMBER(1,0),
	"APU_CHECK_OCULTAR_PRECIO_V" 	NUMBER(1,0),
	"APU_CHECK_PUB_SIN_PRECIO_A" 	NUMBER(1,0),
	"FECHACREAR_PAC" 	TIMESTAMP(6),
	"USUARIOCREAR_PAC" 	VARCHAR2(50 CHAR),
	"APU_CHECK_OCULTAR_PRECIO_A" 	NUMBER(1,0),
	"APU_CHECK_OCULTAR_A" 	NUMBER(1,0),
	"APU_CHECK_PUBLICAR_A"	 NUMBER(1,0),
	"APU_CHECK_OCULTAR_V" 	NUMBER(1,0),
	"APU_CHECK_PUBLICAR_V" 	NUMBER(1,0),
	"PAC_INCLUIDO" 	NUMBER(1,0),
	"DD_EPA_ID" 	NUMBER(16,0),
	"USUARIOCREAR_APU" 	VARCHAR2(50 CHAR),
	"PAC_CHECK_GESTIONAR" 	NUMBER(1,0),
	"PAC_FECHA_GESTIONAR" 	DATE,
	"PAC_MOTIVO_GESTIONAR"	 VARCHAR2(255 CHAR),
	"PAC_CHECK_ASIGNAR_MEDIADOR" 	NUMBER(1,0),
	"PAC_FECHA_ASIGNAR_MEDIADOR" 	DATE,
	"PAC_MOTIVO_ASIGNAR_MEDIADOR" 	VARCHAR2(255 CHAR),
	"PAC_CHECK_COMERCIALIZAR" 	NUMBER(1,0),
	"PAC_FECHA_COMERCIALIZAR" 	DATE,
	"DD_MCO_ID" 	NUMBER(16,0),
	"PAC_CHECK_FORMALIZAR"	 NUMBER(1,0),
	"PAC_FECHA_FORMALIZAR" 	DATE,
	"PAC_MOTIVO_FORMALIZAR" 	VARCHAR2(255 CHAR),
	"PAC_MOT_EXCL_COMERCIALIZAR" 	VARCHAR2(256 CHAR),
	"PAC_CHECK_PUBLICAR" 	NUMBER(1,0),
	"PAC_FECHA_PUBLICAR" 	DATE,
	"PAC_MOTIVO_PUBLICAR" 	VARCHAR2(255 CHAR),
	"USUARIOMODIFICAR_PAC" 	VARCHAR2(50 CHAR),
	"FECHAMODIFICAR_PAC" 	TIMESTAMP(6),
	"USUARIOBORRAR_PAC" 	VARCHAR2(50 CHAR),
	"FECHABORRAR_PAC" 	TIMESTAMP(6),
	"PAC_MOTIVO_TRA_ADMISION" 	VARCHAR2(255 CHAR),
	"PAC_FECHA_TRA_ADMISION" 	DATE,
	"PAC_CHECK_TRA_ADMISION" 	NUMBER(1,0),
	"FECHAMODIFICAR_APU" 	TIMESTAMP(6),
	"USUARIOMODIFICAR_APU" 	VARCHAR2(50 CHAR),
	"APU_MOTIVO_PUBLICACION" 	VARCHAR2(1500 CHAR),
	"DD_TPU_A_ID" 	NUMBER(16,0),
	"APU_FECHA_INI_ALQUILER" 	DATE,
	"APU_MOT_OCULTACION_MANUAL_A" 	VARCHAR2(250 CHAR),
	"DD_MTO_A_ID" 	NUMBER(16,0),
	"DD_TPU_V_ID" 	NUMBER(16,0),
	"APU_FECHA_INI_VENTA" 	DATE,
	"APU_MOT_OCULTACION_MANUAL_V" 	VARCHAR2(250 CHAR),
	"DD_MTO_V_ID" 	NUMBER(16,0),
	"DD_TPU_ID" 	NUMBER(16,0),
	"DD_TCO_ID" 	NUMBER(16,0) 
     ) TABLESPACE '||ITABLE_SPACE||' ';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('TABLA '||V_TABLA||' CREADA.');

  --DAMOS GRANTS

  V_MSQL := 'SELECT COUNT(1) FROM ALL_USERS WHERE USERNAME = ''REM01'' ';
  EXECUTE IMMEDIATE V_MSQL INTO V_EXISTE;
  IF V_EXISTE = 1 THEN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON '||V_TABLA||' TO REM01';
  END IF;

  V_MSQL := 'SELECT COUNT(1) FROM ALL_USERS WHERE USERNAME = ''REM_QUERY'' ';
  EXECUTE IMMEDIATE V_MSQL INTO V_EXISTE;
  IF V_EXISTE = 1 THEN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON '||V_TABLA||' TO REM_QUERY';
  END IF;
  
  V_MSQL := 'SELECT COUNT(1) FROM ALL_USERS WHERE USERNAME = ''PFSREM'' ';
  EXECUTE IMMEDIATE V_MSQL INTO V_EXISTE;
  IF V_EXISTE = 1 THEN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON '||V_TABLA||' TO PFSREM';
  END IF;
  
  --SECUENCIA TABLA ACTIVOS_A_BORRAR
  V_TABLA := 'S_H_CAMBIO_ESTADO_PUBLICACION';
  V_MSQL := 'SELECT COUNT(1) FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = '''||V_TABLA||''' ';
  EXECUTE IMMEDIATE V_MSQL INTO V_EXISTE;

  IF V_EXISTE = 1 THEN
    V_MSQL := 'DROP SEQUENCE '||V_TABLA;
    EXECUTE IMMEDIATE V_MSQL;
    DBMS_OUTPUT.PUT_LINE('SECUENCIA '||V_TABLA||' BORRADA.');
  END IF;

  V_MSQL := 'CREATE SEQUENCE '||V_ESQUEMA||'.'||V_TABLA||' MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ';
  EXECUTE IMMEDIATE V_MSQL;
  DBMS_OUTPUT.PUT_LINE('SECUENCIA '||V_TABLA||' CREADA.');

  DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
  WHEN OTHERS THEN
    ERR_NUM := SQLCODE;
    ERR_MSG := SQLERRM;
    DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
    DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
    DBMS_OUTPUT.put_line(ERR_MSG);
    ROLLBACK;
    RAISE;   
END;
/
EXIT;
