--/*
--#########################################
--## AUTOR=SIMEON SHOPOV
--## FECHA_CREACION=20180313
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=2.0.15
--## INCIDENCIA_LINK=REMVIP-???
--## PRODUCTO=NO
--## 
--## Finalidad: 
--##            
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/
--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE
WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
    V_SQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar         
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_TABLA VARCHAR2(25 CHAR):= 'ACT_VAL_VALORACIONES';
    --V_COUNT NUMBER(16); -- Vble. para contar.
    --V_COUNT_INSERT NUMBER(16):= 0; -- Vble. para contar inserts
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
	V_USUARIO VARCHAR2(32 CHAR):= 'REMVIP-201';
	
BEGIN

EXECUTE IMMEDIATE 'MERGE INTO '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES T1
USING (SELECT DISTINCT TAR.TAR_ID
    FROM '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC
    JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON TAC.ACT_ID = ACT.ACT_ID
    JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TRA_ID = TAC.TRA_ID
    JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
    JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.TBJ_ID = TRA.TBJ_ID
    JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR ON OFR.OFR_ID = ECO.OFR_ID
    JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_CODIGO = ''02''
    JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_CODIGO = ''02''
    JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_CODIGO = ''05''
    WHERE ECO.ECO_NUM_EXPEDIENTE = 83818) T2
ON (T1.TAR_ID = T2.TAR_ID)
WHEN MATCHED THEN UPDATE SET
    T1.TAR_TAREA_FINALIZADA = 1, T1.TAR_FECHA_FIN = SYSDATE, T1.BORRADO = 1
    , T1.USUARIOMODIFICAR = ''REMVIP-???'', T1.FECHAMODIFICAR = SYSDATE
    ';
    
EXECUTE IMMEDIATE 'MERGE INTO '||V_ESQUEMA||'.ACT_TRA_TRAMITE T1
USING (SELECT DISTINCT TRA.TRA_ID, EPR.DD_EPR_ID
    FROM '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC
    JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON TAC.ACT_ID = ACT.ACT_ID
    JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE TRA ON TRA.TRA_ID = TAC.TRA_ID
    JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
    JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON ECO.TBJ_ID = TRA.TBJ_ID
    JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR ON OFR.OFR_ID = ECO.OFR_ID
    JOIN '||V_ESQUEMA||'.DD_EOF_ESTADOS_OFERTA EOF ON EOF.DD_EOF_CODIGO = ''02''
    JOIN '||V_ESQUEMA||'.DD_EEC_EST_EXP_COMERCIAL EEC ON EEC.DD_EEC_CODIGO = ''02''
    JOIN '||V_ESQUEMA_M||'.DD_EPR_ESTADO_PROCEDIMIENTO EPR ON EPR.DD_EPR_CODIGO = ''05''
    WHERE ECO.ECO_NUM_EXPEDIENTE = 83818) T2
ON (T1.TRA_ID = T2.TRA_ID)
WHEN MATCHED THEN UPDATE SET
    T1.TRA_FECHA_FIN = SYSDATE, T1.DD_EPR_ID = T2.DD_EPR_ID
    , T1.USUARIOMODIFICAR = ''REMVIP-???'', T1.FECHAMODIFICAR = SYSDATE
    ';
    
	COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(SQLCODE));
      DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------');
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
      ROLLBACK;
      RAISE;
END;
/
EXIT;
