--/*
--###########################################
--## AUTOR=Vicente Martinez
--## FECHA_CREACION=20180703
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=9.2
--## INCIDENCIA_LINK=REMVIP-1212
--## PRODUCTO=NO
--## 
--## Finalidad: Re-asignar activos, tareas y eco's
--##            
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--###########################################
----*/


WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON; 
SET DEFINE OFF;


DECLARE
    V_MSQL VARCHAR2(32000 CHAR); -- Sentencia a ejecutar     
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
    V_ESQUEMA_MASTER VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master
    V_SQL VARCHAR2(4000 CHAR); -- Vble. para consulta que valida la existencia de una tabla.
    ERR_NUM NUMBER(25);  -- Vble. auxiliar para registrar errores en el script.
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.
    V_USUARIO VARCHAR2(200 CHAR):= 'REMVIP-1212';
    TYPE T_TIPO_DATA IS TABLE OF VARCHAR2(250);
    TYPE T_ARRAY_DATA IS TABLE OF T_TIPO_DATA;
    V_TIPO_DATA T_ARRAY_DATA := T_ARRAY_DATA(
        T_TIPO_DATA('uniges01' , 'garsa01', 'IN', 'GGADM')
       ,T_TIPO_DATA('uniges02' , 'garsa02', 'IN', 'GIAADMT')
       ,T_TIPO_DATA('uniges01' , 'montalvo01', 'NOT IN', 'GGADM')
       ,T_TIPO_DATA('uniges02' , 'montalvo02', 'NOT IN', 'GIAADMT')
        ); 
    V_TMP_TIPO_DATA T_TIPO_DATA;
    
    TYPE T_ARRAY_FORM IS TABLE OF T_TIPO_DATA;
    V_TIPO_FORM T_ARRAY_FORM := T_ARRAY_FORM(
        T_TIPO_DATA('uniges03' , 'garsa03', 'IN', 'GIAFORM')    
        ,T_TIPO_DATA('uniges03' , 'montalvo03', 'NOT IN', 'GIAFORM')
    );

BEGIN
    FOR I IN V_TIPO_DATA.FIRST .. V_TIPO_DATA.LAST
      LOOP
      V_TMP_TIPO_DATA := V_TIPO_DATA(I);
        --ACTUALIZACION GEE
        
        --QUERY PARA ACTUALIZAR LOS GEE
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD T1
        USING (
            SELECT GEE.GEE_ID FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
            JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC ON GEE.GEE_ID = GAC.GEE_ID
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON GAC.ACT_ID = ACT.ACT_ID
            JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEE.USU_ID = USU.USU_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE ON GEE.DD_TGE_ID = TGE.DD_TGE_ID AND TGE.DD_TGE_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(4))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'') 
            AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
        ) T2
        ON (T1.GEE_ID = T2.GEE_ID)
        WHEN MATCHED THEN UPDATE SET
            T1.USU_ID = (SELECT USU_ID FROM '||V_ESQUEMA_MASTER||'.USU_USUARIOS WHERE USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||''')';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');

            --QUERY PARA ACTUALIZAR LOS GEH
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST T1
        USING (
            SELECT GEH_ID, RN
            FROM (
                SELECT 
                    DISTINCT GEH.GEH_ID, ACT.ACT_ID, ROW_NUMBER() OVER(PARTITION BY ACT.ACT_ID ORDER BY GEH.GEH_FECHA_HASTA DESC NULLS FIRST) RN 
                FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
                JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH ON GEH.GEH_ID = GAH.GEH_ID
                JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON GAH.ACT_ID = ACT.ACT_ID
                JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
                JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
                JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
                JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEH.USU_ID = USU.USU_ID
                WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
                AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
                AND GEH.GEH_FECHA_HASTA IS NULL
                )
            WHERE RN = 1) T2
            ON (T1.GEH_ID = T2.GEH_ID)
            WHEN MATCHED THEN UPDATE SET
                T1.GEH_FECHA_HASTA = SYSDATE,
                T1.USUARIOMODIFICAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''),
                T1.FECHAMODIFICAR = SYSDATE';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
    
        --QUERY PARA INSERTAR NUEVOS VALORES EN LA GEH
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (GEH_ID, USU_ID, DD_TGE_ID, GEH_FECHA_DESDE, USUARIOCREAR, FECHACREAR, USUARIOMODIFICAR)
        (SELECT '||V_ESQUEMA||'.S_GEH_GESTOR_ENTIDAD_HIST.NEXTVAL, USU_ID, DD_TGE_ID, SYSDATE, TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''), SYSDATE, ACT_ID
        FROM (
            SELECT
                DISTINCT GEH.GEH_ID, USU2.USU_ID, GEH.DD_TGE_ID, ACT.ACT_ID, ROW_NUMBER() OVER(PARTITION BY ACT.ACT_ID ORDER BY GEH.GEH_FECHA_HASTA DESC NULLS FIRST) RN, GEH.USUARIOMODIFICAR
            FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
            JOIN '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO GAH ON GEH.GEH_ID = GAH.GEH_ID
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON GAH.ACT_ID = ACT.ACT_ID
            JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEH.USU_ID = USU.USU_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU2 ON USU2.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||'''
            JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE ON GEH.DD_TGE_ID = TGE.DD_TGE_ID AND TGE.DD_TGE_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(4))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
            AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
            )
        WHERE RN = 1
        AND USUARIOMODIFICAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''))';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han insertado en la GEH '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
        
        --QUERY PARA INSERTAR NUEVOS VALORES EN LA GAH
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GAH_GESTOR_ACTIVO_HISTORICO (GEH_ID, ACT_ID) 
        (SELECT GEH_ID, USUARIOMODIFICAR FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST
        WHERE USUARIOCREAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||''') 
        AND USUARIOMODIFICAR IS NOT NULL
        AND FECHAMODIFICAR IS NULL)';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han insertado en la GAH '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
        
        --REASIGNACION TAREAS
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS T1
        USING (
            SELECT TAC.TAR_ID, TAC.ACT_ID, USU2.USU_ID
            FROM '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC
            JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAC.TAR_ID = TAR.TAR_ID AND TAR.BORRADO = 0
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON TAC.USU_ID = USU.USU_ID AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON TAC.ACT_ID = ACT.ACT_ID  AND ACT.BORRADO = 0
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON ACT.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU2 ON USU2.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
        ) T2
        ON (T1.TAR_ID = T2.TAR_ID AND T1.ACT_ID = T2.ACT_ID)
        WHEN MATCHED THEN UPDATE SET
            T1.USU_ID = T2.USU_ID';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
            
    END LOOP;
    
    FOR I IN V_TIPO_FORM.FIRST .. V_TIPO_FORM.LAST
      LOOP
       V_TMP_TIPO_DATA := V_TIPO_FORM(I);
        --ACTUALIZACION GEE
        
        --QUERY PARA ACTUALIZAR LOS GEE
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD T1
        USING (
            SELECT GEE.GEE_ID FROM '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE
            JOIN '||V_ESQUEMA||'.GAC_GESTOR_ADD_ACTIVO GAC ON GEE.GEE_ID = GAC.GEE_ID
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON GAC.ACT_ID = ACT.ACT_ID
            JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEE.USU_ID = USU.USU_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE ON GEE.DD_TGE_ID = TGE.DD_TGE_ID AND TGE.DD_TGE_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(4))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'') 
            AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
        ) T2
        ON (T1.GEE_ID = T2.GEE_ID)
        WHEN MATCHED THEN UPDATE SET
            T1.USU_ID = (SELECT USU_ID FROM '||V_ESQUEMA_MASTER||'.USU_USUARIOS WHERE USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||''')'
        ;

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
        --QUERY PARA ACTUALIZAR LOS GEH
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST T1
        USING (
            SELECT GEH_ID, RN
            FROM (
                SELECT 
                    DISTINCT GEH.GEH_ID, ECO.ECO_ID, ROW_NUMBER() OVER(PARTITION BY ECO.ECO_ID ORDER BY GEH.GEH_FECHA_HASTA DESC NULLS FIRST) RN 
                FROM GEH_GESTOR_ENTIDAD_HIST GEH
                JOIN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO GCH ON GEH.GEH_ID = GCH.GEH_ID
                JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON GCH.ECO_ID = ECO.ECO_ID
                JOIN '||V_ESQUEMA||'.ACT_OFR OFR ON ECO.OFR_ID = OFR.OFR_ID
                JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON OFR.ACT_ID = ACT.ACT_ID
                JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
                JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
                JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
                JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEH.USU_ID = USU.USU_ID
                WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
                AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
                AND GEH.GEH_FECHA_HASTA IS NULL
                )
            WHERE RN = 1) T2
            ON (T1.GEH_ID = T2.GEH_ID)
            WHEN MATCHED THEN UPDATE SET
                T1.GEH_FECHA_HASTA = SYSDATE,
                T1.USUARIOMODIFICAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''),
                T1.FECHAMODIFICAR = SYSDATE';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');
    
        --QUERY PARA INSERTAR NUEVOS VALORES EN LA GEH
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST (GEH_ID, USU_ID, DD_TGE_ID, GEH_FECHA_DESDE, USUARIOCREAR, FECHACREAR, USUARIOMODIFICAR)
        (SELECT '||V_ESQUEMA||'.S_GEH_GESTOR_ENTIDAD_HIST.NEXTVAL, USU_ID, DD_TGE_ID, SYSDATE, TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''), SYSDATE, ECO_ID
        FROM (
            SELECT
                DISTINCT GEH.GEH_ID, USU2.USU_ID, GEH.DD_TGE_ID, ECO.ECO_ID, ROW_NUMBER() OVER(PARTITION BY ECO.ECO_ID ORDER BY GEH.GEH_FECHA_HASTA DESC NULLS FIRST) RN, GEH.USUARIOMODIFICAR
            FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST GEH
            JOIN '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO GCH ON GEH.GEH_ID = GCH.GEH_ID
            JOIN '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO ON GCH.ECO_ID = ECO.ECO_ID
            JOIN '||V_ESQUEMA||'.ACT_OFR OFR ON ECO.OFR_ID = OFR.OFR_ID
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON OFR.ACT_ID = ACT.ACT_ID
            JOIN '||V_ESQUEMA||'.BIE_BIEN BIE ON ACT.BIE_ID = BIE.BIE_ID
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON BIE.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON GEH.USU_ID = USU.USU_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU2 ON USU2.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||'''
            JOIN '||V_ESQUEMA_MASTER||'.DD_TGE_TIPO_GESTOR TGE ON GEH.DD_TGE_ID = TGE.DD_TGE_ID AND TGE.DD_TGE_CODIGO = '''||TRIM(V_TMP_TIPO_DATA(4))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
            AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
            )
        WHERE RN = 1
        AND USUARIOMODIFICAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||'''))';

        EXECUTE IMMEDIATE V_MSQL;
        
        DBMS_OUTPUT.PUT_LINE('Se han insertado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');

        --QUERY PARA INSERTAR NUEVOS VALORES EN LA GCH
        V_MSQL := 'INSERT INTO '||V_ESQUEMA||'.GCH_GESTOR_ECO_HISTORICO (GEH_ID, ECO_ID) 
        (SELECT GEH_ID, USUARIOMODIFICAR FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST
        WHERE USUARIOCREAR = TRIM('''||V_USUARIO||'_'||TRIM(V_TMP_TIPO_DATA(4))||'_'||I||''')
        AND USUARIOMODIFICAR IS NOT NULL
        AND FECHAMODIFICAR IS NULL)';

        EXECUTE IMMEDIATE V_MSQL;

        DBMS_OUTPUT.PUT_LINE('Se han insertado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');

        
        --REASIGNACION TAREAS
        V_MSQL := 'MERGE INTO '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS T1
        USING (
            SELECT TAC.TAR_ID, TAC.ACT_ID, USU2.USU_ID
            FROM '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC
            JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAC.TAR_ID = TAR.TAR_ID AND TAR.BORRADO = 0
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU ON TAC.USU_ID = USU.USU_ID AND USU.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(1))||'''
            JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON TAC.ACT_ID = ACT.ACT_ID  AND ACT.BORRADO = 0
            JOIN '||V_ESQUEMA||'.BIE_LOCALIZACION LOC ON ACT.BIE_ID = LOC.BIE_ID
            JOIN '||V_ESQUEMA_MASTER||'.DD_PRV_PROVINCIA PRV ON LOC.DD_PRV_ID = PRV.DD_PRV_ID
            JOIN '||V_ESQUEMA_MASTER||'.USU_USUARIOS USU2 ON USU2.USU_USERNAME = '''||TRIM(V_TMP_TIPO_DATA(2))||'''
            WHERE PRV.DD_PRV_CODIGO '||TRIM(V_TMP_TIPO_DATA(3))||' (''7'',''35'',''38'')
        ) T2
        ON (T1.TAR_ID = T2.TAR_ID AND T1.ACT_ID = T2.ACT_ID)
        WHEN MATCHED THEN UPDATE SET
            T1.USU_ID = T2.USU_ID';

        EXECUTE IMMEDIATE V_MSQL;
        
        DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros para el cambio de '||TRIM(V_TMP_TIPO_DATA(1))||' a '||TRIM(V_TMP_TIPO_DATA(2))||'');

    END LOOP;
    
    --QUERY PARA QUITAR EL USUARIOMODIFICAR DE LA GEH
    V_MSQL := 'UPDATE '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST SET 
    USUARIOMODIFICAR = NULL
    WHERE GEH_ID IN (SELECT GEH_ID FROM '||V_ESQUEMA||'.GEH_GESTOR_ENTIDAD_HIST WHERE USUARIOMODIFICAR IS NOT NULL AND FECHAMODIFICAR IS NULL AND BORRADO = 0)';

    EXECUTE IMMEDIATE V_MSQL;

    DBMS_OUTPUT.PUT_LINE('Se han actualizado '||SQL%ROWCOUNT||' registros');

    COMMIT;

EXCEPTION
     WHEN OTHERS THEN
          ERR_NUM := SQLCODE;
          ERR_MSG := SQLERRM;
          DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecución:'||TO_CHAR(ERR_NUM));
          DBMS_OUTPUT.put_line('-----------------------------------------------------------'); 
          DBMS_OUTPUT.put_line(ERR_MSG);
          DBMS_OUTPUT.put_line(V_MSQL);
          ROLLBACK;
          RAISE;   
END;
/
EXIT;