--/*
--#########################################
--## AUTOR=PIER GOTTA
--## FECHA_CREACION=20181129
--## ARTEFACTO=batch
--## VERSION_ARTEFACTO=2.0.20
--## INCIDENCIA_LINK=REMVIP-2567
--## PRODUCTO=NO
--## 
--## Finalidad: Cambiar usuario de tramite
--##			
--## INSTRUCCIONES:  
--## VERSIONES:
--##        0.1 Versión inicial
--#########################################
--*/

--Para permitir la visualización de texto en un bloque PL/SQL utilizando DBMS_OUTPUT.PUT_LINE

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
TABLE_COUNT NUMBER(1,0) := 0;
V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; -- Configuracion Esquema
V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; -- Configuracion Esquema Master

BEGIN			
			
	DBMS_OUTPUT.PUT_LINE('[INICIO]'); 

	EXECUTE IMMEDIATE 'MERGE INTO '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS T1 USING (
		SELECT DISTINCT ECO.ECO_NUM_EXPEDIENTE,TAC.TAR_ID, TAC.TRA_ID, GEE.USU_ID 
		FROM '||V_ESQUEMA||'.ECO_EXPEDIENTE_COMERCIAL ECO
                INNER JOIN '||V_ESQUEMA||'.OFR_OFERTAS OFR ON ECO.OFR_ID = OFR.OFR_ID
                INNER JOIN '||V_ESQUEMA||'.ACT_OFR ACO ON ACO.OFR_ID = OFR.OFR_ID
                INNER JOIN '||V_ESQUEMA||'.ACT_ACTIVO ACT ON ACT.ACT_ID = ACO.ACT_ID
                INNER JOIN '||V_ESQUEMA||'.DD_CRA_CARTERA CRA ON CRA.DD_CRA_ID = ACT.DD_CRA_ID
                INNER JOIN '||V_ESQUEMA||'.GCO_GESTOR_ADD_ECO GCO ON GCO.ECO_ID = ECO.ECO_ID
                INNER JOIN '||V_ESQUEMA||'.GEE_GESTOR_ENTIDAD GEE ON GEE.GEE_ID = GCO.GEE_ID
                INNER JOIN '||V_ESQUEMA_M||'.USU_USUARIOS USU ON USU.USU_ID = GEE.USU_ID
                INNER JOIN '||V_ESQUEMA_M||'.DD_TGE_TIPO_GESTOR TGE ON TGE.DD_TGE_ID = GEE.DD_TGE_ID
		INNER JOIN '||V_ESQUEMA||'.ACT_TBJ_TRABAJO TRA ON ECO.TBJ_ID = TRA.TBJ_ID 
		INNER JOIN '||V_ESQUEMA||'.ACT_TRA_TRAMITE ATR ON ATR.TBJ_ID = TRA.TBJ_ID
		INNER JOIN '||V_ESQUEMA||'.TAC_TAREAS_ACTIVOS TAC ON ATR.TRA_ID = TAC.TRA_ID
		INNER JOIN '||V_ESQUEMA||'.TAR_TAREAS_NOTIFICACIONES TAR ON TAR.TAR_ID = TAC.TAR_ID
                INNER JOIN '||V_ESQUEMA||'.TEX_TAREA_EXTERNA TXT ON TXT.TAR_ID = TAR.TAR_ID
                INNER JOIN '||V_ESQUEMA||'.TAP_TAREA_PROCEDIMIENTO TAP ON TXT.TAP_ID = TAP.TAP_ID
		WHERE TAP.TAP_CODIGO IN (''T013_InformeJuridico'', ''T013_PosicionamientoYFirma'',''T013_DocumentosPostVenta'')
                AND TAR.TAR_TAREA_FINALIZADA = 0 AND TGE.DD_TGE_CODIGO = ''GIAFORM''AND CRA.DD_CRA_DESCRIPCION = ''Cajamar'' AND ECO.BORRADO = 0 AND ECO.ECO_NUM_EXPEDIENTE NOT IN(14311, 15172, 15906, 16469, 16533,
		16557,16821,17003,17019,17097,17145,17157,17207,17209,17285,17286,17337,17338,17369,17389,17428,17454,17455,17476,17483,17552)
		) T2
			ON (T1.TAR_ID = T2.TAR_ID AND T1.TRA_ID = T2.TRA_ID)
		WHEN MATCHED THEN UPDATE
               		SET T1.USU_ID = T2.USU_ID, T1.USUARIOMODIFICAR = ''REMVIP-2597'', T1.FECHAMODIFICAR = SYSDATE
		';

	DBMS_OUTPUT.PUT_LINE('	[INFO] '||SQL%ROWCOUNT||' expedientes anulados.');  

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('[FIN]');

EXCEPTION

    WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('[ERROR] Se ha producido un error en la ejecucion:'||TO_CHAR(SQLCODE));
        DBMS_OUTPUT.put_line('-----------------------------------------------------------');
        DBMS_OUTPUT.put_line(SQLERRM);
        ROLLBACK;
        RAISE;
END;

/

EXIT
