/*
--##########################################
--## AUTOR=Alejandro I�igo
--## FECHA_CREACION=20151030
--## ARTEFACTO=ETL
--## VERSION_ARTEFACTO=1.0
--## INCIDENCIA_LINK=BKREC-706
--## PRODUCTO=NO
--##########################################
--*/




WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE

    V_MSQL VARCHAR2(32000 CHAR); /* Sentencia a ejecutar    */
    V_ESQUEMA VARCHAR2(25 CHAR):= '#ESQUEMA#'; /* Configuracion Esquema*/
    V_ESQUEMA_M VARCHAR2(25 CHAR):= '#ESQUEMA_MASTER#'; /* Configuracion Esquema Master*/
    V_TS_INDEX VARCHAR2(25 CHAR):= '#TABLESPACE_INDEX#'; /* Configuracion Indice*/
    V_SQL VARCHAR2(4000 CHAR); /* Vble. para consulta que valida la existencia de una tabla.*/
    V_NUM_TABLAS NUMBER(16); /* Vble. para validar la existencia de una tabla.  */
    ERR_NUM NUMBER(25);  /* Vble. auxiliar para registrar errores en el script.*/
    ERR_MSG VARCHAR2(1024 CHAR); -- Vble. auxiliar para registrar errores en el script.*/

    V_TEXT1 VARCHAR2(2400 CHAR); /* Vble. auxiliar*/
    
    V_ESQUEMA_MIN VARCHAR2(25 CHAR):= '#ESQUEMA_MINIREC#'; /* Configuracion Esquema minirec*/
    V_ESQUEMA_DWH VARCHAR2(25 CHAR):= '#ESQUEMA_DWH#'; /* Configuracion Esquema recovery_bankia_dwh*/
    V_ESQUEMA_STG VARCHAR2(25 CHAR):= '#ESQUEMA_STG#'; /* Configuracion Esquema recovery_bankia_datastage*/
	
BEGIN


    /*  tabla DEF_DOCUMENTOS_EFECTOS_LIQ <-- ELIMINAR*/

    DBMS_OUTPUT.PUT_LINE('[START] DROP TABLE tabla DEF_DOCUMENTOS_EFECTOS_LIQ');

    select count(1) into V_NUM_TABLAS from ALL_TABLES where table_name = 'DEF_DOCUMENTOS_EFECTOS_LIQ';
    if V_NUM_TABLAS > 0 then
        EXECUTE IMMEDIATE ' DROP TABLE '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ CASCADE CONSTRAINTS';
            DBMS_OUTPUT.PUT_LINE('DROP TABLE '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ... Tabla borrada OK');
    end if;
            
    EXECUTE IMMEDIATE '    
    CREATE TABLE '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ
      (
	    DEF_PCO_LIQ_ID      NUMBER(16)   ,   
	    DEF_XCOEMP VARCHAR2(5),
		DEF_COPSER VARCHAR2(5),
		DEF_IDPRIG VARCHAR2(17),
		DEF_IDCOEC VARCHAR2(15),
		DEF_FEVACM DATE,
		DEF_FEPEAU DATE,
		DEF_FFVPMA DATE,                 
		DEF_CLLIQ1 VARCHAR2(1),          
		DEF_CDIGMO VARCHAR2(1),          
		DEF_FILLR1 VARCHAR2(32),         
		DEF_IDRECV VARCHAR2(23),         
		DEF_TIPOEF VARCHAR2(20),         
		DEF_FEVCTR DATE,                 
		DEF_FEREAM DATE,                 
		DEF_IMCPRC NUMBER(15,2),         
		DEF_IDEGPR NUMBER(15,2),         
		DEF_IDEOTG NUMBER(15,2),         
		DEF_CDINTS NUMBER(3,6),          
		DEF_IMPRTV NUMBER(15,2),         
		DEF_IMDEUD NUMBER(15,2),         
		DEF_NOLIB9 VARCHAR2(35),         
		DEF_COTIVT VARCHAR2(1),          
		DEF_NUFA34 VARCHAR2(34),         
		DEF_FILLR2 VARCHAR2(360),
        USUARIOCREAR        VARCHAR2(10 CHAR) not null,
        FECHACREAR          TIMESTAMP(6) not null,
        USUARIOMODIFICAR    VARCHAR2(10 CHAR),
        FECHAMODIFICAR      TIMESTAMP(6)	,		
		VERSION                   	INTEGER DEFAULT 0  NOT NULL,
		USUARIOBORRAR             	VARCHAR2(50)         ,
		FECHABORRAR               	TIMESTAMP(6)         ,
		BORRADO                  	NUMBER(1) DEFAULT 0  NOT NULL,			    
		CONSTRAINT DEF_UNIQUE_LIQ_EXTERN_ID UNIQUE (DEF_XCOEMP,DEF_COPSER,DEF_IDPRIG,DEF_IDCOEC,DEF_FEVACM,DEF_FEPEAU,DEF_CLLIQ1)					   ) ' ; 
		
		EXECUTE IMMEDIATE 'CREATE INDEX ' || V_ESQUEMA || '.IDX_DEF_PCO_LIQ_ID ON ' || V_ESQUEMA || '.DEF_DOCUMENTOS_EFECTOS_LIQ (DEF_PCO_LIQ_ID) ' ||
		'  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 ' ||
  		'  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE ' || V_TS_INDEX;
  		
  		DBMS_OUTPUT.PUT_LINE('[INFO] ' || V_ESQUEMA || '.DEF_PCO_LIQ_ID... Indice creado');				
		
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_XCOEMP        is ''EMPRESA CONTRATO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_COPSER        is ''TIPO PRODUCTO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IDPRIG        is ''NUMERO CONTRATO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IDCOEC        is ''ID. CONDICION ESPECIAL CONTRATO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FEVACM        is ''FECHA LIQUIDACION''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FEPEAU        is ''FECHA PETICION''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FFVPMA        is ''FECHA VENCIMIENTO MAS ANTIGUO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_CLLIQ1        is ''TIPO DE LIQUIDACION''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_CDIGMO        is ''MONEDA SOLICTADA''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FILLR1        is ''FILLER''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IDRECV        is ''NUMERO LETRA (DOCUMENTO)''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_TIPOEF        is ''TIPO DE EFECTO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FEVCTR        is ''FECHA VENCIMIENTO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FEREAM        is ''FECHA VALOR (APLICACIÓN INTERESES)''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IMCPRC        is ''NOMINAL''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IDEGPR        is ''GASTOS PROT.''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IDEOTG        is ''GASTOS''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_CDINTS        is ''TIPO INTERES''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IMPRTV        is ''INTERES''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_IMDEUD        is ''TOTAL DOCUMENTO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_NOLIB9        is ''NOMBRE LIBRADO(TIT FACTURA) ''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_COTIVT        is ''IMPAGADO/EN CURSO''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_NUFA34        is ''FACTURA (CONFIRMING)''  ';
EXECUTE IMMEDIATE  'comment on column '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ.DEF_FILLR2        is ''FILLER''  ';

		

DBMS_OUTPUT.PUT_LINE('TABLE '|| V_ESQUEMA ||'.DEF_DOCUMENTOS_EFECTOS_LIQ... Tabla CREADA OK');
    
DBMS_OUTPUT.PUT_LINE('[END] Tabla DEF_DOCUMENTOS_EFECTOS_LIQ');
    
DBMS_OUTPUT.PUT_LINE('[INFO] EJECUCION TERMINADA CON EXITO');

EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('[ERROR] Se ha producido un error en la ejecución: '|| TO_CHAR(SQLCODE) || ' ' || SQLERRM );
    RAISE;
END;
/
exit		
