INSERT INTO CM01.MIG_MAESTRA_HITOS
SELECT
CD_PROCEDIMIENTO,
CM01.S_PRC_PROCEDIMIENTOS.NEXTVAL,
PRC_ID,
ORDEN+1,
'HCJ001',
'T. declaración IVA/IGIC - HCJ',
'HCJ001_DeclararIVAIGIC',
CM01.S_TAR_TAREAS_NOTIFICACIONES.NEXTVAL,
'Declarar IVA/IGIC',
NULL,
0,
CD_BIEN,
COD_HITO_ACTUAL,
ULTIMO_HITO
FROM CM01.MIG_MAESTRA_HITOS
WHERE TAP_CODIGO = 'H005_DeclaracionIVAIGIC'
AND TAR_TAREA_FINALIZADA = 0;

INSERT INTO CM01.MIG_MAESTRA_HITOS
SELECT
CD_PROCEDIMIENTO,
CM01.S_PRC_PROCEDIMIENTOS.NEXTVAL,
PRC_ID,
ORDEN+1,
'HCJ001',
'T. declaración IVA/IGIC - HCJ',
'HCJ001_DeclararIVAIGIC',
CM01.S_TAR_TAREAS_NOTIFICACIONES.NEXTVAL,
'Declarar IVA/IGIC',
NULL,
1,
CD_BIEN,
COD_HITO_ACTUAL,
ULTIMO_HITO
FROM CM01.MIG_MAESTRA_HITOS
WHERE TAP_CODIGO = 'H005_DeclaracionIVAIGIC'
AND TAR_TAREA_FINALIZADA = 1;

COMMIT;

EXIT;
/
