OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_9269_NOJUDICIAL_3
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ADN_ID				NULLIF(ADN_ID=BLANKS)		"TRIM(:ADN_ID)",
	ADN_NUM_REFERENCIA 			NULLIF(ADN_NUM_REFERENCIA=BLANKS)		"TRIM(:ADN_NUM_REFERENCIA)"
)
