Insert into UGASMASTER.DD_STA_SUBTIPO_TAREA_BASE
   (DD_STA_ID, DD_TAR_ID, DD_STA_CODIGO, DD_STA_DESCRIPCION, DD_STA_DESCRIPCION_LARGA, DD_STA_GESTOR, VERSION, USUARIOCREAR, FECHACREAR, USUARIOMODIFICAR, FECHAMODIFICAR, USUARIOBORRAR, FECHABORRAR, BORRADO, DD_TGE_ID, DTYPE)
 Values
   (700, 1, '700', 'Anotacion', 
    'Anotacion', NULL, 0, 'DD', TO_TIMESTAMP('21/05/2012 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 
    NULL, NULL, NULL, NULL, 0, 
    NULL, 'EXTSubtipoTarea');
Insert into UGASMASTER.DD_STA_SUBTIPO_TAREA_BASE
   (DD_STA_ID, DD_TAR_ID, DD_STA_CODIGO, DD_STA_DESCRIPCION, DD_STA_DESCRIPCION_LARGA, DD_STA_GESTOR, VERSION, USUARIOCREAR, FECHACREAR, USUARIOMODIFICAR, FECHAMODIFICAR, USUARIOBORRAR, FECHABORRAR, BORRADO, DD_TGE_ID, DTYPE)
 Values
   (701, 3, '701', 'Anotacion', 
    'Anotacion', NULL, 0, 'DD', TO_TIMESTAMP('23/05/2012 0:00:00.000000','DD/MM/YYYY fmHH24fm:MI:SS.FF'), 
    NULL, NULL, NULL, NULL, 0, 
    NULL, 'EXTSubtipoTarea');
COMMIT;