--Si no existe como es el caso de PFS01 (en producción)
ALTER TABLE PRC_CEX ADD (
  CONSTRAINT FK_PRC_CEX_REFERENCE_PRC_PROC 
 FOREIGN KEY (PRC_ID) 
 REFERENCES PRC_PROCEDIMIENTOS (PRC_ID));

ALTER TABLE PRC_CEX ADD (
  CONSTRAINT FK_PRC_CEX_REFERENCE_CEX_CON 
 FOREIGN KEY (CEX_ID) 
 REFERENCES CEX_CONTRATOS_EXPEDIENTE (CEX_ID));

ALTER TABLE PRC_PER
 ADD (VERSION  INTEGER);
 
update prc_per set version = 0;

ALTER TABLE PRC_PER
MODIFY(VERSION NOT NULL); 
------------------------------------

INSERT INTO PLA_PLAZOS_DEFAULT(PLA_ID, DD_STA_ID, PLA_PLAZO, PLA_CODIGO, PLA_DESCRIPCION, USUARIOCREAR, FECHACREAR)
VALUES (11, (select dd_sta_id from pfsmaster.DD_STA_SUBTIPO_TAREA_BASE where dd_sta_codigo = '53'), 1*24*60*60*1000, '11', 'Plazo comprobación umbral', 'DD', SYSDATE);


INSERT INTO PLA_PLAZOS_DEFAULT(PLA_ID, DD_STA_ID, PLA_PLAZO, PLA_CODIGO, PLA_DESCRIPCION, USUARIOCREAR, FECHACREAR)
VALUES (12, (select dd_sta_id from pfsmaster.DD_STA_SUBTIPO_TAREA_BASE where dd_sta_codigo = '55'), 365*24*60*60*1000, '12', 'Plazo prorroga en DC', 'DD', SYSDATE);



CREATE SEQUENCE S_ADP_ADJUNTOS_PERSONAS START WITH 1 NOCYCLE CACHE 100;

CREATE SEQUENCE S_ADC_ADJUNTOS_CONTRATOS START WITH 1 NOCYCLE CACHE 100;

CREATE SEQUENCE S_HTC_HIST_TRASP_COMITE START WITH 1 NOCYCLE CACHE 100;


ALTER TABLE OBA_OBSERVACION_ACEPTACION
MODIFY(OBA_DETALLE NULL);


ALTER TABLE AAA_ACTITUD_APTITUD_ACTUACION
 ADD (AAA_REVISION  VARCHAR2(1024));


ALTER TABLE CLI_CLIENTES
 ADD (CLI_FECHA_GV	DATE);


CREATE TABLE ADP_ADJUNTOS_PERSONAS (
   ADP_ID               NUMBER(16)                    NOT NULL,
   PER_ID               NUMBER(16)                    NOT NULL,
   ADP_NOMBRE           VARCHAR2(255)                 NOT NULL,
   ADP_CONTENT_TYPE     VARCHAR2(50)                  NOT NULL,
   ADP_LENGTH           NUMBER(16)                    NOT NULL,
   ADP_DESCRIPCION      VARCHAR2(1024),
   ADJ_ID               NUMBER(16)                    NOT NULL,
   VERSION              INTEGER                       DEFAULT 0 NOT NULL,
   USUARIOCREAR         VARCHAR2(10)                  NOT NULL,
   FECHACREAR           TIMESTAMP                     NOT NULL,
   USUARIOMODIFICAR     VARCHAR2(10),
   FECHAMODIFICAR       TIMESTAMP,
   USUARIOBORRAR        VARCHAR2(10),
   FECHABORRAR          TIMESTAMP,
   BORRADO              NUMBER(1,0)                   DEFAULT 0 NOT NULL,
   CONSTRAINT PK_ADP_ADJUNTOS_PERSONAS PRIMARY KEY (ADP_ID)
);

ALTER TABLE ADP_ADJUNTOS_PERSONAS
   ADD CONSTRAINT FK_FK_PER_ADJ FOREIGN KEY (PER_ID)
      REFERENCES PER_PERSONAS (PER_ID);

ALTER TABLE ADP_ADJUNTOS_PERSONAS
   ADD CONSTRAINT FK_FK_ADP_ADJ FOREIGN KEY (ADJ_ID)
      REFERENCES ADJ_ADJUNTOS (ADJ_ID);


CREATE TABLE ADC_ADJUNTOS_CONTRATOS (
   ADC_ID               NUMBER(16)                    NOT NULL,
   CNT_ID               NUMBER(16)                    NOT NULL,
   ADC_NOMBRE           VARCHAR2(255)                 NOT NULL,
   ADC_CONTENT_TYPE     VARCHAR2(50)                  NOT NULL,
   ADC_LENGTH           NUMBER(16)                    NOT NULL,
   ADC_DESCRIPCION      VARCHAR2(1024),
   ADJ_ID               NUMBER(16)                    NOT NULL,
   VERSION              INTEGER                       DEFAULT 0 NOT NULL,
   USUARIOCREAR         VARCHAR2(10)                  NOT NULL,
   FECHACREAR           TIMESTAMP                     NOT NULL,
   USUARIOMODIFICAR     VARCHAR2(10),
   FECHAMODIFICAR       TIMESTAMP,
   USUARIOBORRAR        VARCHAR2(10),
   FECHABORRAR          TIMESTAMP,
   BORRADO              NUMBER(1,0)                   DEFAULT 0 NOT NULL,
   CONSTRAINT PK_ADC_ADJUNTOS_CONTRATOS PRIMARY KEY (ADC_ID)
);


ALTER TABLE ADC_ADJUNTOS_CONTRATOS
   ADD CONSTRAINT FK_FK_CNT_ADJ FOREIGN KEY (CNT_ID)
      REFERENCES CNT_CONTRATOS (CNT_ID);

ALTER TABLE ADC_ADJUNTOS_CONTRATOS
   ADD CONSTRAINT FK_FK_ADC_ADJ FOREIGN KEY (ADJ_ID)
      REFERENCES ADJ_ADJUNTOS (ADJ_ID);


CREATE TABLE HTC_HIST_TRASP_COMITE(
	HTC_ID				 NUMBER(16)		NOT NULL,
	EXP_ID				 NUMBER(16)		NOT NULL,
	COM_ID_ORIGEN		 NUMBER(16)		NOT NULL,
	COM_ID_DESTINO	     NUMBER(16)		NOT NULL,
	HTC_FECHA			 TIMESTAMP		NOT NULL,
	VERSION              INTEGER        DEFAULT 0 NOT NULL,
  	USUARIOCREAR         VARCHAR2(10)   NOT NULL,
  	FECHACREAR           TIMESTAMP      NOT NULL,
  	USUARIOMODIFICAR     VARCHAR2(10),
  	FECHAMODIFICAR       TIMESTAMP,
  	USUARIOBORRAR        VARCHAR2(10),
  	FECHABORRAR          TIMESTAMP,
  	BORRADO              NUMBER(1,0)    DEFAULT 0 NOT NULL,
  	CONSTRAINT PK_HTC_ID PRIMARY KEY (HTC_ID)
);

ALTER TABLE HTC_HIST_TRASP_COMITE
   ADD CONSTRAINT FK_HTC_EXP FOREIGN KEY (EXP_ID)
      REFERENCES EXP_EXPEDIENTES (EXP_ID);

ALTER TABLE HTC_HIST_TRASP_COMITE
   ADD CONSTRAINT FK_HTC_COM_OR FOREIGN KEY (COM_ID_ORIGEN)
      REFERENCES COM_COMITES (COM_ID);

ALTER TABLE HTC_HIST_TRASP_COMITE
   ADD CONSTRAINT FK_HTC_COM_DEST FOREIGN KEY (COM_ID_DESTINO)
      REFERENCES COM_COMITES (COM_ID);


commit;	  