WHENEVER SQLERROR EXIT SQL.SQLCODE;

UPDATE MY_EXAMPLEMASTER.ENTIDADCONFIG SET DATAVALUE='/ora11g/instantclient/sqlldr' WHERE DATAKEY='pathToSqlLoader' AND ENTIDAD_ID=1;
UPDATE MY_EXAMPLEMASTER.ENTIDADCONFIG SET DATAVALUE='jdbc:oracle:thin:MY_EXAMPLE/j0b3d2CHe3I=04045316@//example-db:1521/orcl' WHERE DATAKEY='url' AND ENTIDAD_ID=1;
UPDATE MY_EXAMPLEMASTER.ENTIDADCONFIG SET DATAVALUE='MY_EXAMPLE' WHERE DATAKEY='username' AND ENTIDAD_ID=1;
UPDATE MY_EXAMPLEMASTER.ENTIDADCONFIG SET DATAVALUE='j0b3d2CHe3I=04045316' WHERE DATAKEY='password' AND ENTIDAD_ID=1;
UPDATE MY_EXAMPLEMASTER.ENTIDADCONFIG SET DATAVALUE='MY_EXAMPLE/j0b3d2CHe3I=04045316@//example-db:1521/orcl' WHERE DATAKEY='connectionInfo' AND ENTIDAD_ID=1;

exit;
