delete from rem01.ACT_ADM_INF_ADMINISTRATIVA where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_ADN_ADJNOJUDICIAL where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_AGO_AGRUPACION_OBS where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_AJD_ADJJUDICIAL where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_BNY_BANYO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_CAT_CATASTRO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_COC_COCINA where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_CPR_COM_PROPIETARIOS where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_CRE_CARPINTERIA_EXT where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_CRG_CARGAS where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_CRI_CARPINTERIA_INT where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_DIS_DISTRIBUCION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_EDI_EDIFICIO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_INF_INFRAESTRUCTURA where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_INS_INSTALACION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_LLV_LLAVE where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_LOC_LOCALIZACION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_MLV_MOVIMIENTO_LLAVE where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_PDV_PLAN_DIN_VENTAS where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_PRO_PROPIETARIO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_PRT_PRESUPUESTO_TRABAJO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_PRV_PARAMENTO_VERTICAL where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_PVC_PROVEEDOR_CONTACTO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_PAC_PROPIETARIO_ACTIVO where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_ETP_ENTIDAD_PROVEEDOR ETP where EXISTS (SELECT 1 FROM REM01.ACT_PVE_PROVEEDOR PVE WHERE PVE.PVE_ID = ETP.PVE_ID AND PVE.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_PVE_PROVEEDOR where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_REG_INFO_REGISTRAL where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_ONV_OBRA_NUEVA ONV where EXISTS (SELECT 1 FROM REM01.ACT_AGR_AGRUPACION AGR WHERE AGR.AGR_ID = ONV.AGR_ID AND AGR.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_RES_RESTRINGIDA RES where EXISTS (SELECT 1 FROM REM01.ACT_AGR_AGRUPACION AGR WHERE AGR.AGR_ID = RES.AGR_ID AND AGR.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_AGA_AGRUPACION_ACTIVO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_AGR_AGRUPACION where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_SDV_SUBDIVISION_ACTIVO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_SOL_SOLADO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_SPS_SIT_POSESORIA where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_TAS_TASACION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_TBJ TBJ where EXISTS (SELECT 1 FROM rem01.ACT_TBJ_TRABAJO TBJT WHERE TBJT.TBJ_ID = TBJ.TBJ_ID AND TBJT.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_TBJ_TRABAJO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_TIT_TITULO where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.ACT_VAL_VALORACIONES where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_LCO_LOCAL_COMERCIAL LCO WHERE EXISTS (SELECT 1 FROM rem01.ACT_ICO_INFO_COMERCIAL ICO WHERE LCO.ICO_ID = ICO.ICO_ID AND ICO.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_APR_PLAZA_APARCAMIENTO APR WHERE EXISTS (SELECT 1 FROM rem01.ACT_ICO_INFO_COMERCIAL ICO WHERE APR.ICO_ID = ICO.ICO_ID AND ICO.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_VIV_VIVIENDA VIV where EXISTS (SELECT 1 FROM rem01.ACT_ICO_INFO_COMERCIAL ICO WHERE VIV.ICO_ID = ICO.ICO_ID AND ICO.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_ZCO_ZONA_COMUN where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_ICO_INFO_COMERCIAL where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.BIE_ADJ_ADJUDICACION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.lob_lote_bien lob1 where exists (select 1 from rem01.BIE_BIEN bie where bie.BIE_ID = lob1.bie_id and BIE.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.BIE_CAR_CARGAS where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.BIE_DATOS_REGISTRALES where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.BIE_LOCALIZACION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.BIE_VALORACIONES where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_GES_DISTRIBUCION where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.ACT_ADA_ADJUNTO_ACTIVO where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.GEE_GESTOR_ENTIDAD where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.GEH_GESTOR_ENTIDAD_HIST where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.BIE_BIEN where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.bie_adicional where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.bie_anc_analisis_contratos where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.bie_bien_entidad where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.bie_sui_subasta_instrucciones where usuariocrear= 'MIGRAREM01BNK';
delete from rem01.emp_nmbembargos_procedimientos where usuariocrear= 'MIGRAREM01BNK';
commit;
delete from rem01.GAH_GESTOR_ACTIVO_HISTORICO GAH where EXISTS (SELECT 1 FROM rem01.ACT_ACTIVO ACT WHERE ACT.ACT_ID = GAH.ACT_ID AND ACT.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.GAC_GESTOR_ADD_ACTIVO GAC where EXISTS (SELECT 1 FROM rem01.ACT_ACTIVO ACT WHERE ACT.ACT_ID = GAC.ACT_ID AND ACT.usuariocrear= 'MIGRAREM01BNK');
delete from rem01.ACT_ACTIVO where usuariocrear= 'MIGRAREM01BNK';
commit;
