wc -l ACTIVO_CABECERA.dat
wc -l ACTIVO_DATOSADICIONALES.dat
wc -l ACTIVO_TITULO.dat
wc -l ACTIVO_PLANDINVENTAS.dat
wc -l ACTIVO_ADJ_JUDICIAL.dat
wc -l ACTIVO_ADJ_NO_JUDICIAL.dat
wc -l COM_PROPIETARIOS_CABECERA.dat
wc -l PROPIETARIOS_ACTIVO.dat
wc -l CARGAS_ACTIVO.dat
wc -l LLAVES_ACTIVO.dat
wc -l TASACIONES_ACTIVO.dat
wc -l INFOCOMERCIAL_ACTIVO.dat
wc -l CALIDADES_ACTIVO.dat
wc -l AGRUPACIONES_ACTIVO.dat
wc -l AGRUPACIONES.dat
wc -l ACTIVO_PRECIO.dat
wc -l CATASTRO_ACTIVO.dat
wc -l INFOCOMERCIAL_DISTRIBUCION.dat
wc -l OBSERVACIONES_AGRUPACION.dat
wc -l PRESUPUESTO_TRABAJO.dat
wc -l SUBDIVISIONES_AGRUPACION.dat
wc -l MOVIMIENTOS_LLAVE.dat
wc -l PROPIETARIOS_CABECERA.dat
wc -l PROVEEDOR_CONTACTO.dat
wc -l ACTIVO_PROVEEDORES.dat
wc -l TRABAJO.dat


/****INICIO******/
SELECT 
  (SELECT 'ACTIVO_ADJ_JUDICIAL' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ADJ_JUDICIAL_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_ADJ_NO_JUDICIAL' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ADJ_NO_JUDICIAL_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_CABECERA' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ACA_CABECERA_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_DATOSADICIONALES' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ADA_DATOS_ADI_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_PLANDINVENTAS' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APL_PLANDINVENTAS_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_PRECIO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APC_PRECIO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_PROVEEDORES' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APR_PROVEEDORES_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ACTIVO_TITULO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ATI_TITULO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ADMISION_DOCUMENTOS' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ADD_ADMISION_DOC_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'AGRUPACIONES' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AAG_AGRUPACIONES_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'AGRUPACIONES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AAA_AGRUPACION_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'CALIDADES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ACA_CALIDADES_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'CARGAS_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ACA_CARGAS_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'CATASTRO_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ACA_CATASTRO_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'COM_PROPIETARIOS_CABECERA' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_CPC_PROP_CABECERA_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'COM_PROPIETARIOS_CUOTA' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_CPC_PROP_CUOTAS_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'DOCUMENTOS_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ADA_DOCUMENTOS_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'ENTIDAD_PROVEEDOR' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AEP_ENTIDAD_PROVEEDOR_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'IMAGENES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AIA_IMAGENES_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'IMAGENES_AGRUPACION' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AIA_IMAGEN_AGRUPACION_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'IMAGENES_CABECERA' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AIC_IMAGENES_CABECERA_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'IMAGENES_SUBDIVISION' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AIS_IMAGEN_SUBDIVISION_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'INFOCOMERCIAL_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AIA_INFCOMERCIAL_ACT_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'INFOCOMERCIAL_DISTRIBUCCION' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AID_INFCOMERCIAL_DISTR_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'LLAVES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ALA_LLAVES_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'MOVIMIENTOS_LLAVE' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AML_MOVIMIENTOS_LLAVE_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'OBSERVACIONES_ACTIVOS' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AOA_OBSERVACIONES_ACT_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'OBSERVACIONES_AGRUPACION' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AOA_OBSERVACION_AGRUP_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'OCUPANTES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_AOA_OCUPANTES_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PRESUPUESTO-ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_PRESUPUESTO_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PRESUPUESTO_TRABAJO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APT_PRESUPUESTO_TRABAJ_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PROPIETARIOS_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APA_PROP_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PROPIETARIOS_CABECERA' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APC_PROP_CABECERA_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PROVEEDOR_CONTACTO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APC_PROVEEDOR_CONTACTO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'PROVISION_SUPLIDO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_APS_PROVISION_SUPLIDO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'SUBDIVIONES_AGRUPACION' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ASA_SUBDIVISION_AGRUP_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'TASACIONES_ACTIVO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ATA_TASACIONES_ACTIVO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL
UNION ALL
SELECT 
  (SELECT 'TRABAJO' FROM DUAL) AS INTERFAZ,
  TO_NUMBER('') AS "VOLUMETRIA FICHERO",
  (SELECT COUNT(1) FROM MIG_ATR_TRABAJO_BNK) AS "VOLUMETRIA TABLAS MIG2"
FROM DUAL;

/**/
  SELECT * FROM MIG_ADJ_JUDICIAL_BNK;
  SELECT * FROM MIG_ADJ_NO_JUDICIAL_BNK;
  SELECT * FROM MIG_ACA_CABECERA_BNK;
  SELECT * FROM MIG_ADA_DATOS_ADI_BNK;
  SELECT * FROM MIG_APL_PLANDINVENTAS_BNK;
  SELECT * FROM MIG_APC_PRECIO_BNK;
  SELECT * FROM MIG_APR_PROVEEDORES_BNK;
  SELECT * FROM MIG_ATI_TITULO_BNK;
  SELECT * FROM MIG_ADD_ADMISION_DOC_BNK;
  SELECT * FROM MIG_AAG_AGRUPACIONES_BNK;
  SELECT * FROM MIG_AAA_AGRUPACION_ACTIVO_BNK;
  SELECT * FROM MIG_ACA_CALIDADES_ACTIVO_BNK;
  SELECT * FROM MIG_ACA_CARGAS_ACTIVO_BNK;
  SELECT * FROM MIG_ACA_CATASTRO_ACTIVO_BNK;
  SELECT * FROM MIG_CPC_PROP_CABECERA_BNK;
  SELECT * FROM MIG_CPC_PROP_CUOTAS_BNK;
  SELECT * FROM MIG_ADA_DOCUMENTOS_ACTIVO_BNK;
  SELECT * FROM MIG_AEP_ENTIDAD_PROVEEDOR_BNK;
  SELECT * FROM MIG_AIA_IMAGENES_ACTIVO_BNK;
  SELECT * FROM MIG_AIA_IMAGEN_AGRUPACION_BNK;
  SELECT * FROM MIG_AIC_IMAGENES_CABECERA_BNK;
  SELECT * FROM MIG_AIS_IMAGEN_SUBDIVISION_BNK;
  SELECT * FROM MIG_AIA_INFCOMERCIAL_ACT_BNK;
  SELECT * FROM MIG_AID_INFCOMERCIAL_DISTR_BNK;
  SELECT * FROM MIG_ALA_LLAVES_ACTIVO_BNK;
  SELECT * FROM MIG_AML_MOVIMIENTOS_LLAVE_BNK;
  SELECT * FROM MIG_AOA_OBSERVACIONES_ACT_BNK;
  SELECT * FROM MIG_AOA_OBSERVACION_AGRUP_BNK;
  SELECT * FROM MIG_AOA_OCUPANTES_ACTIVO_BNK;
  SELECT * FROM MIG_PRESUPUESTO_ACTIVO_BNK;
  SELECT * FROM MIG_APT_PRESUPUESTO_TRABAJ_BNK;
  SELECT * FROM MIG_APA_PROP_ACTIVO_BNK;
  SELECT * FROM MIG_APC_PROP_CABECERA_BNK;
  SELECT * FROM MIG_APC_PROVEEDOR_CONTACTO_BNK;
  SELECT * FROM MIG_APS_PROVISION_SUPLIDO_BNK;
  SELECT * FROM MIG_ASA_SUBDIVISION_AGRUP_BNK;
  SELECT * FROM MIG_ATA_TASACIONES_ACTIVO_BNK;
  SELECT * FROM MIG_ATR_TRABAJO_BNK;
/**/




