OPTIONS (DIRECT=TRUE, BINDSIZE=512000, ROWS=10000, ERRORS=999999)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE REM01.AUX_REMVIP_5062
TRUNCATE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	ID_OFERTA_REM					NULLIF(ID_OFERTA_REM=BLANKS)				"TRIM(:ID_OFERTA_REM)",
        NUM_EXPEDIENTE					NULLIF(NUM_EXPEDIENTE=BLANKS)				"TRIM(:NUM_EXPEDIENTE)",
	IMP_FINANCIACION_VENTA			        NULLIF(IMP_FINANCIACION_VENTA=BLANKS)			"TRIM(:IMP_FINANCIACION_VENTA)"
)
