/*==============================================================*/
/* Table: 	DiccionariosEDitables DIC_DICCIONARIOS_EDITABLES    */
/* Listadod de diccionarios que pueden ser editados por medio	*/
/* Del módulo de parametrización y administración				*/
/*==============================================================*/
-- USUARIO MASTER

CREATE SEQUENCE PFSMASTER.S_DIC_DICCIONARIOS_EDIT_MAEST;

CREATE TABLE PFSMASTER.DIC_DICCIONARIOS_EDIT_MAEST  (
   DIC_ID		 			NUMBER(16)			NOT NULL,
   DIC_NBTABLA				VARCHAR2(100)		NOT NULL,
   DIC_CODIGO           	VARCHAR2(50 BYTE)   NOT NULL,
   DIC_DESCRIPCION			VARCHAR2(100)		NOT NULL,
   DIC_DESCRIPCION_LARGA	VARCHAR2(250),
   DIC_EDICION				NUMBER(1)       DEFAULT 0		NOT NULL,
   DIC_ADD					NUMBER(1)       DEFAULT 0		NOT NULL,
   VERSION                  INTEGER         DEFAULT 0  	NOT NULL,
   USUARIOCREAR             VARCHAR2(10 BYTE)   				NOT NULL,
   FECHACREAR               TIMESTAMP(6)        				NOT NULL,
   USUARIOMODIFICAR         VARCHAR2(10 BYTE),
   FECHAMODIFICAR           TIMESTAMP(6),
   USUARIOBORRAR            VARCHAR2(10 BYTE),
   FECHABORRAR              TIMESTAMP(6),
   BORRADO                  NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_DIC_DICCIONARIOS_EDIT_MAEST PRIMARY KEY (DIC_ID)
);	

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ACC_CAPACIDAD_PAGO', '01', 'Estados para un análisis de capacidad de pago', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ACS_CAMBIO_SOLVENCIA', '02', 'Estados para un acuerdo de cambio de solvencia', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ACT_ACTOR', '03', 'Estados para actores', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ACT_CONCLUSION_TITULO', '04', 'Estados conclusion de acuerdo de titulo', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_AEX_AMBITOS_EXPEDIENTE', '05', 'Estados de ambitos de expedientes', '', 1, 1, 1,'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_APE_PERIODICIDAD_ACUERDO', '06', 'Estados de periodicidad de acuerdos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ATA_TIP_ACTUA_ACUE', '07', 'Estados de tipos de actuaciones de acuerdos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ATP_ACUERDO_TIPO_PAGO', '08', 'Tipos de acuerdos de pago', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ECP_ESTADO_COBRO_PAGO', '16', 'Diccionario de estados de cobros y pagos', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CDE_CAUSAS_DECISION', '10', 'Posibles causas de decision', '', 1, 1, 1,'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CIC_CODIGO_ISO_CIRBE', '50', 'Diccionario de datos de paises', '', 1, 1, 1,'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CIM_CAUSAS_IMPAGO', '09', 'Posibles causas de impago', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_COC_COD_OPERAC_CIRBE', '51', 'Diccionario de datos de codigos de operacion', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_COM_COMPLETITUD', '52', 'Diccionario de datos de completitud', '', 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_COR_CORRECTO', '53', 'Diccionario de datos de correctitud', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CPR_CAUSA_PRORROGA', '11', 'Posibles causas de prorroga', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CRA_CRITERIO_ANALISIS', '12', 'Estados de criterios de analisis', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CRC_CLASE_RIESGO_CIRBE', '54', 'Diccionario de datos clases de riesgo', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CRE_CAUSA_RECURSO', '55', 'Posibles causas de recurso', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_DCA_DEMANDANTES_CARGAS', '13', 'Estados de demandantes de cargas', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_DRR_RESULTADO_RESOL', '56', 'Posibles resultados de la resolucion', '', 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_DTR_TIPO_RECURSO', '57', 'Posibles tipos de recursos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EAC_ESTADO_ACUERDO', '14', 'Diccionario de estados de acuerdos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EAS_ESTADO_ASUNTOS', '58', 'Posibles estados del asunto', '', 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ECL_ESTADO_CLIENTE', '15', 'Diccionario de estados de clientes', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD,  VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EDE_ESTADOS_DECISION', '17', 'Diccionario de estados de decision', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EEX_ESTADO_EXPEDIENTE', '18', 'Diccionario de estados del expediente', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EFC_ESTADO_FINAN_CNT', '19', 'Diccionario de estados financieros', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EIN_ENTIDAD_INFORMACION', '59', 'Diccionario de datos de entidades de informacion', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EPI_EST_POL_ITINERARIO', '20', 'Diccionario de estados de itinerarios', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EPR_ESTADO_PROCEDIMIENTO', '60', 'Posibles estados del procedimiento', '', 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ESC_ESTADO_CNT', '21', 'Diccionario de estados de contratos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ESC_ESTADO_CUMPLIMIENTO', '61', 'Posibles estados del cumplimiento', '', 1, 1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ESO_ESTADO_OBJETIVO', '62', 'Posibles estados del objetivo', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ESP_ESTADO_POLITICA', '63', 'Posibles estados de politica', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_EST_ESTADOS_ITINERARIOS', '22', 'Diccionario de estados de itinerarios', '', 1, 1, 1, 'DD', SYSDATE);

--INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
--VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_FCN_FINALIDAD_CONTRATO', '65', 'Diccionario de datos de finalidades de contrato', '', 1, 1, 1, 'DD', SYSDATE);

/*INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_FMG_FASES_MAPA_GLOBAL', '23', 'Diccionario de datos de fases del mapa global', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_FNO_FINALIDAD_OFICIAL', '66', 'Diccionario de datos de finalidades oficiales', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_GCN_GARANTIA_CONTRATO', '67', 'Tipos de garantias de un contrato', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_GGE_GRUPO_GESTOR', '68', 'Posibles grupos de un gestor', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_IM1_IMPUGNACION1', '69', 'Diccionario de datos de tipos de impugnacion', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_IM2_IMPUGNACION2', '70', 'Diccionario de datos de tipos de impugnacion 2', '', 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_IMP_IMPACTO', '71', 'Diccionario de datos de tipos de impacto', '', 1, 1, 1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_INS_INSTRUCCIONES', '72', 'Diccionario de datos instrucciones', '', 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_MET_MOT_EXC_TELECOBRO', '24', 'Posibles motivos de exclusion de Telecobro', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_MEX_MOTIVOS_EXP_MANUAL', '25', 'Posibles motivos de expediente manual', '', 1, 1, 1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_MON_MONEDAS', '26', 'Diccionario de datos de tipos de monedas', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_MX3_MOVIMIENTO_EXTRA_3', '73', 'Diccionario de datos de movimientos extraordinarios', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_MX4_MOVIMIENTO_EXTRA_4', '74', 'Diccionario de datos de movimientos extraordinarios 4', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_POL_POLITICAS', '75', 'Diccionario de datos de tipos de politica', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_POS_POSITIVO_NEGATIVO', '76', 'Diccionario de datos de positivo-negativo', '', 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PRA_PROPUESTA_AAA', '27', 'Diccionario de datos de propuestas de actuacion', '', 1,1,1, 'DD', SYSDATE);

/*INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PRV_PROVINCIA', '28', 'Diccionario de datos de provincias', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PS1_POSTORES1', '77', 'Diccionario de datos de postores', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PS2_POSTORES2', '78', 'Diccionario de datos de postores 2', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PX3_PERSONA_EXTRA_3', '79', 'Diccionario de datos de personas', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_PX4_PERSONA_EXTRA_4', '80', 'Diccionario de datos de personas4', '', 1, 1, 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_RAA_RESULTADO_ACUERDO', '29', 'Posibles resultados de acuerdos de actuacion', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_RAX_RATING_AUXILIAR', '81', 'Diccionario de datos de rating auxiliar', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_REX_RATING_EXTERNO', '82', 'Diccionario de datos de rating externo', '', 1,1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_RPR_RAZON_PRORROGA', '30', 'Posibles respuestas de prorroga', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_SCP_SUBTIPO_COBRO_PAGO', '31', 'Opciones de cobro y pago', '', 1, 1, 1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_SEX_SEXOS', '83', 'Diccionario de datos de sexos', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_SIN_SINO', '84', 'Diccionario de datos de si no', '', 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_SMG_SUBFASES_MAPA_GLOBAL', '32', 'Subfases del mapa global', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_SOL_SOLICITANTE', '33', 'Diccionario de datos de solicitantes', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_STA_SUBTIPO_TAREA_BASE', '34', 'Diccionario de datos de subtipos de tareas', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_STI_SITUACION', '35', 'Diccionario de datos de tipos de situacion', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TAA_TIPO_AYUDA_ACTUACION', '36', 'Diccionario de datos de tipos de ayuda', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TAC_TIPO_ACTUACION', '37', 'Diccionario de datos de tipos de actuacion', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TAN_TIPO_ANALISIS', '85', 'Diccionario de datos de tipos de analisis', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TAR_TIPO_TAREA_BASE', '86', 'Diccionario de datos de tipos tareas base', '', 1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TAY_TIPO_AYUDA_ACUERDO', '38', 'Acuerdos de tipos de ayuda', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TBI_TIPO_BIEN', '39', 'Diccionario de datos de tipos de bienes', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TCA_TIPOS_CARGAS', '40', 'Diccionario de datos de tipos de cargas', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TCP_TIPO_COBRO_PAGO', '87', 'Tipos de cobro pago', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TDI_TIPO_DOCUMENTO_ID', '88', 'Diccionario de datos de tipos de documentos', '', 1, 1, 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TFI_TIPO_FICHERO', '89', 'Diccionario de datos de tipos de fichero', '', 1,1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TGC_TIPO_GARANTIA_CIRBE', '90', 'Diccionario de datos de tipos de garantia', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TGL_TIPO_GRUPO_CLIENTE', '91', 'Diccionario de datos de tipos de cliente', '', 1,1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TIT_TIPO_ITINERARIOS', '92', 'Diccionario de datos de tipos de itinerarios', '', 1,'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TMC_TIPO_MONEDA_CIRBE', '41', 'Diccionario de datos de tipos de moneda cirbe', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TOP_TIPO_OPERADOR', '93', 'Diccionario de datos de tipos de operador', '', 1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TPA_TIPO_ACUERDO', '42', 'Diccionario de datos de tipos de acuerdos', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TPE_TIPO_PERSONA', '43', 'Diccionario de datos de tipos de personas', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TPR_TIPO_PRORROGA', '94', 'Diccionario de datos de tipos de prorroga', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TRC_TERCEROS', '95', 'Diccionario de datos de tipo de terceros', '', 1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TRE_TIPO_RECLAMACION', '44', 'Diccionario de datos de tipos de reclamacion', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TSC_TIPO_SITUAC_CIRBE', '97', 'Diccionario de datos de tipos de situacion cirbe', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TTE_TIPO_TELEFONO', '98', 'Diccionario de datos de tipos telefono', '', 1,1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TTG_TIPO_TIT_GEN', '45', 'Diccionario de datos de tipos de titulos generales', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TTI_TIPO_TITULO', '46', 'Diccionario de datos de tipos de titulo', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TVC_TIPO_VENC_CIRBE', '99', 'Diccionario de datos de tipos de vencimiento cirbe', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TVI_TIPO_VIA', '100', 'Diccionario de datos de tipos de vía', '', 1,1,1, 'DD', SYSDATE);
*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_VAA_VALORA_ACTU_AMIST', '47', 'Tipos de valoracion de actuaciones amistosas', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_VAL_VALORACION', '101', 'Diccionario de datos de tipos de valoracion', '', 1,1,1, 'DD', SYSDATE);
/*
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_ACA_ACCION_AUTO', '48', 'Tipos autos de accion', '', 1,1,1, 'DD', SYSDATE);

INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA,DIC_EDICION,DIC_ADD, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_CCO_CORRECTO_COBROS', '49', 'Tipos correctos de cobro', '', 1,1,1, 'DD', SYSDATE);



INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_FAV_FAVORABLE', '64', 'Diccionario de datos de resultado', '', 1, 'DD', SYSDATE);

*/
INSERT INTO DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID, DIC_NBTABLA, DIC_CODIGO, DIC_DESCRIPCION, DIC_DESCRIPCION_LARGA, VERSION, USUARIOCREAR, FECHACREAR)
VALUES (S_DIC_DICCIONARIOS_EDIT_MAEST.nextVal, 'DD_TRE_TIPO_REGLAS_ELEVACION', '96', 'Diccionario de datos de reglas de elevacion', '', 1, 'DD', SYSDATE);



/*==============================================================*/
/* Para dar permisos de lectura, escritura, ejecucion de        */
/* las tablas del master desde el entity añadir las 			*/ 
/* siguientes líneas											*/
/*                                                     			*/
/*==============================================================*/
  
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_EDIT_MAEST TO PFS01;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_EDIT_MAEST TO PFS02;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_EDIT_MAEST TO PFS03;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_EDIT_MAEST TO PFS04;

/*==============================================================*/
/* Table: 	DiccionariosEDitables DIC_DICCIONARIOS_EDITABLES    */
/* Historico de cambios realizados sobre los distintos			*/ 
/* diccionarios													*/
/* Del módulo de parametrización y administración				*/
/*==============================================================*/

CREATE SEQUENCE S_DIC_DICCIONARIOS_LOG_MAEST;

CREATE TABLE DIC_DICCIONARIOS_LOG_MAEST (
   DIL_ID		 			NUMBER(16)						NOT NULL,
   DIL_DICCIONARIO_ID		NUMBER(16)						NOT NULL,
   DIL_USUARIO           	VARCHAR2(50 BYTE)   			NOT NULL,
   DIL_ACCION				VARCHAR2(100)					NOT NULL,
   DIL_FECHA				TIMESTAMP(6)					NOT NULL,
   DIL_VALOR_ANTERIOR		VARCHAR2(250)					,
   DIL_VALOR_NUEVO			VARCHAR2(250)					NOT NULL,
   VERSION                  INTEGER       		DEFAULT 0  	NOT NULL,
   USUARIOCREAR             VARCHAR2(10 BYTE)   			NOT NULL,
   FECHACREAR               TIMESTAMP(6)        			NOT NULL,
   USUARIOMODIFICAR         VARCHAR2(10 BYTE),
   FECHAMODIFICAR           TIMESTAMP(6),
   USUARIOBORRAR            VARCHAR2(10 BYTE),
   FECHABORRAR              TIMESTAMP(6),
   BORRADO                  NUMBER(1)       DEFAULT 0		NOT NULL,   
   CONSTRAINT PK_DIC_DICCIONARIOS_LOG_MAEST PRIMARY KEY (DIL_ID)
);	

ALTER TABLE DIC_DICCIONARIOS_LOG_MAEST
   ADD CONSTRAINT FK_DILOG_FK_DIC FOREIGN KEY (DIL_DICCIONARIO_ID)
      REFERENCES DIC_DICCIONARIOS_EDIT_MAEST (DIC_ID);
/*==============================================================*/
/* Para dar permisos de lectura, escritura, ejecucion de        */
/* las tablas del master desde el entity añadir las 			*/ 
/* siguientes líneas											*/
/*                                                     			*/
/*==============================================================*/
  
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_LOG_MAEST TO PFS01;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_LOG_MAEST TO PFS02;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_LOG_MAEST TO PFS03;
GRANT SELECT,INSERT,UPDATE,DELETE ON PFSMASTER.DIC_DICCIONARIOS_LOG_MAEST TO PFS04;

 