-- *************************************************************************** --
-- **  Se actualiza el campo DD_FAP_ID de la tabla TAP_TAREA_PROCEDIMIENTO  * -- 
-- *************************************************************************** --

-- Tramite de posesión
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_regPorcentajePropiedadAdjudicada';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_regSolicitudPosesion';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_solicitarLanzamiento';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_confirmarAdmisionLanzamiento';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_notificarAOcupantes';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarVista';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarResolucion';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarPosesion';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarLanzamientoEfectivo';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarCambioCerradura';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P54_registrarPersonaDepLlaves';


-- Tramite de registro   
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P42_PagoDeImpuestos';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P42_InscribirEnRegistroPropiedad';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P42_RegistrarEnCatastro';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P42_CambiarNombre';
UPDATE TAP_TAREA_PROCEDIMIENTO SET DD_FAP_ID = (select DD_FAP_ID from DD_FAP_FASE_PROCESAL where DD_FAP_CODIGO='01') 
WHERE  TAP_CODIGO='P42_InformarCambioPropiedad';
